### ISSUE TITLE
Управление Sonoff GK-200mp2-B.

### ISSUE THREAD

**Issue by OldFedor** [JurajNyiri/HomeAssistant-Tapo-Control#1]
Будьте любезны, приведите пример как вывести на панель видео с кнопками управления камерой Sonoff GK-200mp2-B. 
Мы с внуком уже запутались. 
Учу я его, а вот камеру не могу. Поток rstp вывели. А управление камерой нет. 
С уважением, OldFedor.

**Comment by JurajNyiri** [comment]
I do not speak Russian, I used translation so some information could have been lost in translation.

I understand that you would like to display video feed with controls in one panel for Sonoff camera.

This component is for Tapo camera from TP-Link. I am not sure if it works on that camera too as I do not own it.
There is a[ topic for your camera here](https://community.home-assistant.io/t/sonoff-gk-200mp2-b-ip-camera/157400), from a quick Google search. There seems to be a lot of information for it available on Google.

This component only provides you controls of the Tapo camera and does not provide video feed. 

That being said, in general; For video feed, you can use [generic ip camera](https://www.home-assistant.io/integrations/generic_ip_camera/), [onvif](https://www.home-assistant.io/integrations/onvif/) or [many other components for cameras](https://www.home-assistant.io/integrations/#camera) documented on Home Assistant documentation. You can combine that, with for example [picture-glance](https://www.home-assistant.io/lovelace/picture-glance/) card where you would put your own entities (scripts for example) which trigger services, like rotating, turning on alarm etc.

Closing this issue as it is not related to this component.

**Comment by OldFedor** [comment]
Благодарю за ответ.

**Comment by JurajNyiri** [comment]
рада помочь
