### ISSUE TITLE
Bug: Camera entity not support requesting width and height

### ISSUE THREAD

**Issue by migromao** [JurajNyiri/HomeAssistant-Tapo-Control#101]
Starting (?) on core-2021.9 , Camera entity not support requesting width and height
**Expected behavior**
It would be expectable to:
 camera images can now be scaled to a resolution that fits the device/screen you are looking at; Additionally, they only update when visible. This makes cameras usable in any bandwidth situation.

**Log**
Just warnings, asking to contact the author of integration

WARNING (MainThread) [homeassistant.components.camera] The camera entity camera.tvcam_sd does not support requesting width and height, please open an issue with the integration author

 - Device Model:  C200

**Using stream component**
Yes

**Comment by JurajNyiri** [comment]
Is this still happening on https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/3.4.1?

**Comment by migromao** [comment]
It's working fine. I'm embarrassed for not to fully test previously.
I can only say you are great !

**Comment by JurajNyiri** [comment]
No worries, I asked you to create issue before it was fixed and then fixed it a bit later when I had time!
