### ISSUE TITLE
Feature Request:How to flip a picture

### ISSUE THREAD

**Issue by Ponyru** [JurajNyiri/HomeAssistant-Tapo-Control#102]
Hello.
How to flip a picture 90, 180% ?

**Comment by JurajNyiri** [comment]
Disable stream in options, then put in extra arguments for ffmpeg:

https://community.home-assistant.io/t/rotate-a-camera-image-90-degrees/14539/5?u=jurajnyiri

**Comment by Ponyru** [comment]
Thanks
