### ISSUE TITLE
Motion detection

### ISSUE THREAD

**Issue by jeremypsl** [JurajNyiri/HomeAssistant-Tapo-Control#107]
Hello

I was wondering if the motion detection work with all detections in Tapo settings (cross a line, intrusion, etc...) or just the regular motion ?

Thanks for your hard work.

**Comment by JurajNyiri** [comment]
Hello, it uses onvif to get motion events. Whatever tapo send there is caught. As for today, it is sending only regular motion afaik. There is no other way currently to get different types of movement.

**Comment by JurajNyiri** [comment]
https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/105
