### ISSUE TITLE
FFMpeg Extra Arguments Only Rotate Preview And Not Stream

### ISSUE THREAD

**Issue by danieljgmaclean** [JurajNyiri/HomeAssistant-Tapo-Control#108]
Hi,

I noticed you added extra arguments for ffmpeg which is great because I was trying to figure out how to rotate a camera without physically rotating it. However, it appears to only rotate the preview image and not the actual stream. Is this intended behaviour or have I configured this incorrectly?

Screenshot attached.

Thanks

<img width="496" alt="Screenshot 2021-09-23 at 11 43 28" src="https://user-images.githubusercontent.com/985467/134494184-6e16d24d-bed5-4eb4-b098-66f02574ebc1.png">

**Comment by JurajNyiri** [comment]
Turn off stream for camera and restart, it will rotate also stream if you are not using [stream](https://www.home-assistant.io/integrations/stream/). 

It has some disadvantages and advantages, depending on your environment nad HW. https://github.com/JurajNyiri/HomeAssistant-Tapo-Control#troubleshooting--faq
