### ISSUE TITLE
Bug: Motion Detection Stops working unless restart home assistant and camera

### ISSUE THREAD

**Issue by raigeiki55** [JurajNyiri/HomeAssistant-Tapo-Control#109]
**Describe the bug**
Motion Detection reporting only works before the server reaches a day, then stops reporting. If its not reporting, it won't trigger the wifi bulb.

**Expected behavior**
 n/a
**Log**
No logs
```

**Using stream component**
yes
**Camera works through onvif component OR different cameras work in general**
yes - rtsp
**Camera has all attributes filled out properly in developer tools**
yes
**HASS Environment**
Raspberry pi 4

**Comment by JurajNyiri** [comment]
Duplicate of  https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/84 .
