### ISSUE TITLE
Trying to record from camera

### ISSUE THREAD

**Issue by epjdeheer** [JurajNyiri/HomeAssistant-Tapo-Control#111]
Hi Juraj,

My name is Eric, relatively new to HomeAssistant 2021.9.7, and installed your integration to view the streams of my TAPO c200 camera's. Everything works fine, and the streams display great, I enabled the preload function so they also load very quickly.

Now I want to record the stream of the Camera to a file with the Camera.record function.
For this I created a script, I used the visual editor, but this is how it looks in yaml:

service: camera.record
target:
  entity_id: camera.bedroom_hd
data:
  filename: /share/motioneye/Camera2/test.mp4

However, if I run the script I get an failed to call the service error: Can't write /share/morioneye/Camera2/test.mp4, no access to path! The path exists, no typos in the fiename, and I can create the file manually with touch.

The path exists (it is where my motioneye addon also stores the files), I chmod the rights to 747 to ensure the rights are ok.
But the problem persists, I tried putting ' and " around the filename, but keep getting the same error.
Any suggestion what might be causing this, could it be that I have to add specific mpeg parameters in the TAPO configuration?
Any other hint to what might be the reason?

Thanks for your help.
Kind regards,
Eric

![Screenshot 2021-09-30 214349](https://user-images.githubusercontent.com/74110109/135520498-2d727f9d-2978-46e6-8ac5-b6b27425fe1f.png)

**Comment by JurajNyiri** [comment]
Hello, you should ask this question in https://community.home-assistant.io/c/configuration/11 . It heavily depends on your environment, for example if you are running Home Assistant in docker, your paths will not be the same and you need to passthrough a directory to docker etc.

Not related to integration, closing.
