### ISSUE TITLE
Bug: HA throwing warnings on requests for unsupported image sizes...

### ISSUE THREAD

**Issue by tescophil** [JurajNyiri/HomeAssistant-Tapo-Control#112]
**Describe the bug**
Warnings are generated when viewing camera feeds (see log output)

**To Reproduce**
Look at a camera feed

**Expected behavior**
I expect this not to throw warnings...

**Log**
```
Logger: homeassistant.components.camera
Source: components/camera/__init__.py:465
Integration: Camera (documentation, issues)
First occurred: 14:52:13 (2 occurrences)
Last logged: 14:52:14

The camera entity camera.utility_camera_hd does not support requesting width and height, please open an issue with the integration author
The camera entity camera.garage_camera_hd does not support requesting width and height, please open an issue with the integration author
```

**Camera (please complete the following information):**
 - Device Model: C200
 - FW: 1.1.11 Build 210625 Rel.56514n(4555)

**Using stream component**
Yes

**Camera works through onvif component OR different cameras work in general**
Yes

**Camera has all attributes filled out properly in developer tools**
Yes

**HASS Environment**
Pi3B+ Home Assistant OS

**Additional context**
Everything looks to be working OK, just throwing these warnings

**Comment by JurajNyiri** [comment]
Update to latest version.

https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/101
