### ISSUE TITLE
Bug: no video showing

### ISSUE THREAD

**Issue by ady-crow** [JurajNyiri/HomeAssistant-Tapo-Control#113]
**Describe the bug**

I installed Tapo through HAC’s as recommended. Restarted HS. Added the integration, specified the IP, added the username and password and completed the install. Camera (C100) shows as configured and all added. added both SD and HD to Lovelace but no image is shown. 

Firewalls turned off to make sure its not the ports. Log just says Camera is Idle

**Log**
If applicable, add error logs.

```
Logger: homeassistant.setup
Source: custom_components/tapo_control/init.py:341
First occurred: 18:08:58 (1 occurrences)
Last logged: 18:08:58

Error during setup of component tapo_control
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
result = await task
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/tapo_control/init.py", line 341, in setup
tapoConnector = Tapo(host, username, password)
File "/usr/local/lib/python3.8/site-packages/pytapo/init.py", line 29, in init
self.presets = self.getPresets()
File "/usr/local/lib/python3.8/site-packages/pytapo/init.py", line 430, in getPresets
return self.getPresets(True)
File "/usr/local/lib/python3.8/site-packages/pytapo/init.py", line 427, in getPresets
raise Exception("Error: "+self.getErrorMessage(data['error_code'])+" Response:" + json.dumps(data))
Exception: Error: -1337 Response:{"error": "Not enough pixels!!", "error_code": -1337}
```

**Camera (please complete the following information):**
 - Device Model: [e.g. C200]
 - FW: [e.g. 1.0.14 Build 200720 Rel.38552n(4555)]

**Using stream component**
[yes/no]

**Camera works through onvif component OR different cameras work in general**
[yes/no]

**Camera has all attributes filled out properly in developer tools**
[yes/no - provide more info]

**HASS Environment**
[Describe the environment where you are running camera in, for example: Docker on Synology NAS]

**Additional context**

**Comment by JurajNyiri** [comment]
You are asking for help yet you did not take the time to fill out the template. I spent 15 minutes investigating the log you copy pasted, which is an example, until I noticed.

Fill out the template properly. Integration does work with C100.
