### ISSUE TITLE
Feature Request: service to manually sync camera date & time

### ISSUE THREAD

**Issue by Toukite** [JurajNyiri/HomeAssistant-Tapo-Control#119]
**Is your feature request related to a problem? Please describe.**
When camera reboots, date and time are completely off. 
However, when this integration starts when HA starts, date and time are fixed.
Unfortunaltely, reloading this integration is not working (I'm loosing camera connection and getting 'invalid credential'), a full HA restart is required to realign everything

**Describe the solution you'd like**
I would like to be able to manually call a service that would resync date and time of the camera (exactly the same thing that is done automatically when HA restarts.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by JurajNyiri** [comment]
Date and time is automatically synced every few hours. I can add the manual service though.
