### ISSUE TITLE
Feature Request: status + sensors

### ISSUE THREAD

**Issue by chaimt** [JurajNyiri/HomeAssistant-Tapo-Control#12]
hi,
  i am working on a lovelace for the camera calls.
it would be nice to have sensors for the current state of the camera

**Comment by JurajNyiri** [comment]
What current status would you like to have available?

Could you please list all the things you would like to have available?

**Comment by mikesrus** [comment]
Hi!
here is attributes XML of tapo c200 cam

```
access_token: a07......
model_name: C200
brand: TP-Link
motion_detection: 'on'
device_type: SMART.IPCAMERA
device_model: C200
device_name: C200 1.0
device_info: C200 1.0
hw_version: '1.0'
sw_version: 1.0.10 Build 200520 Rel.45325n(4555)
device_alias: камера в зале
features: '3'
barcode: ''
mac: B0-95-....
dev_id: 802145C74AA....
oem_id: 8902D2F34FC....
hw_desc: '485744455....'
motion_detection_sensitivity: normal
privacy_mode: 'off'
alarm: 'off'
alarm_mode:
  - sound
  - sound
led: 'off'
auto_track: 'off'
presets:
  '1': по умолчанию
  '2': зона 1
  '3': Отмеченная зона 1
friendly_name: камера в зале - HD
icon: 'mdi:cctv'
entity_picture: >-
  /api/camera_proxy/camera.kamera_v_zale_hd?token=
supported_features: 3

```

it will be wery cool if

motion_detection: 'on' - as sensor on device card in HA
privacy_mode: 'off' - as switch on device card in HA
alarm: 'off' - as switch on device card in HA
alarm_mode:  - as sensor on device card in HA
led: 'off' - as switch on device card in HA

And current binary sensor for motionsensor creates not in device card. it's bug or not?

**Comment by JurajNyiri** [comment]
Hello,

You can do all of these via template switches / sensor in hass. I will eventually add some examples in here.

I am not a fan of the idea of having it in the integration as that is more things that would need to be maintained, could introduce bugs in the future etc. If things can be done via hass, let's do them via hass.
