### ISSUE TITLE
Feature Request: Low delayed live view

### ISSUE THREAD

**Issue by wrobi** [JurajNyiri/HomeAssistant-Tapo-Control#121]
Hi!
I appreciate your work with Tapo-Control.
I'd like to view live stream without 10 seconds of delay. I tried to untick "Use Stream from Home Assistant [requires restart]" option, but it doesn't help. After some research, found AlexxIT/WebRTC custom component for HA, and it works with 0.5 sec lag, 10-15 fps @1080p and 25-30% CPU usage. (15-20% CPU @720p)
Is it possible to implement to your project?
Thank you

**Comment by JurajNyiri** [comment]
Added instructions to readme.


**Another possibility is using [WebRTC Camera by AlexxIT](https://github.com/AlexxIT/WebRTC).**

Example working configuration:

```
type: custom:webrtc-camera
entity: camera.bedroom_hd
```
