### ISSUE TITLE
Bug: Motion Sensor on C200 not detected or unavailable

### ISSUE THREAD

**Issue by jorgelaranjo** [JurajNyiri/HomeAssistant-Tapo-Control#122]
**Describe the bug**
C200 no longer gets motion detection (entity) detected thus cannot be used.
Works fine on APP.

**To Reproduce**
1. Upgrade to 1.1.15 Build 211111 Rel. 34670n(4555)
2. Add to Home Assistant
3. Check Entities Detected.

**Expected behavior**
Motion Detector would be available.
![image](https://user-images.githubusercontent.com/1196202/143278605-2536556d-b0c4-44bd-8636-15412ab6c12d.png)

ONVIF
![image](https://user-images.githubusercontent.com/1196202/143285850-b585fae5-d593-4d1e-a656-33efd9cfd0b8.png)

**Log**
If applicable, add error logs.

**Camera (please complete the following information):**
 - Device Model: C200
 - FW: 1.1.15 Build 211111 Rel.34670n(4555)

**Using stream component**
yes

**Camera works through onvif component OR different cameras work in general**
yes

**Camera has all attributes filled out properly in developer tools**
Yes

```
model_name: C200
brand: TP-Link
motion_detection: 'on'
device_type: SMART.IPCAMERA
device_model: C200
device_name: C200 1.0
device_info: C200 1.0 IPC
hw_version: '1.0'
sw_version: 1.1.15 Build 211111 Rel.34670n(4555)
device_alias: Tapo_Camera_E999
features: '3'
barcode: ''
motion_detection_sensitivity: normal
privacy_mode: 'off'
alarm: 'off'
alarm_mode:
  - sound
led: 'on'
day_night_mode: auto
auto_track: 'off'
presets: {}
```

**HASS Environment**
Docker on Unraid (Home-Assistant-Core) with HACS added.

**Comment by JurajNyiri** [comment]
Read readme troubleshooting section.

Also, if motion sensor is not available also inside onvif, it is not an issue of this integration.

**Comment by jorgelaranjo** [comment]
> Read readme troubleshooting section.
> 
> Also, if motion sensor is not available also inside onvif, it is not an issue of this integration.

It was available before the update as far as I could see it, then it went to _Unavailable_.

It was available for sometime then gone. Not sure why.
Do you have a C200 with motion sensor working with HA?

**Comment by JurajNyiri** [comment]
What is written in troubleshooting section in readme?

All that you are asking is written in readme.

**Comment by jorgelaranjo** [comment]
> What is written in troubleshooting section in readme?
> 
> All that you are asking is written in readme.

Not sure why it went AWOL but after triggering a new detection it does show up again, on the new firmware.

![image](https://user-images.githubusercontent.com/1196202/143304226-0868251b-90e8-4349-8d28-eb9ac7f6f5b9.png)

**Comment by JurajNyiri** [comment]
If you read the readme like I told you 3 times now you what know 🤷

**Comment by jorgelaranjo** [comment]
> If you read the readme like I told you 3 times now you would know shrug
Sure. Thanks
