### ISSUE TITLE
Feature Request: AI Detection/ person detection

### ISSUE THREAD

**Issue by retoziegler** [JurajNyiri/HomeAssistant-Tapo-Control#126]
In the latest iOS tapo app in Detection & Alerts of my C310 cameras there is a setting for AI Detection > Person detection.
It would be great if the results of that detection could be accessed from Home Assistant as well, similar to the binary sensor for Motion Detection.

**Comment by JurajNyiri** [comment]
There is currently no known way how to access this data. 
First it needs to be available in [pytapo ](https://github.com/JurajNyiri/pytapo/issues?q=is%3Aopen+is%3Aissue)lib and someone needs to discover a way to get these data. It is not exposed via onvif.
