### ISSUE TITLE
TAPO INTEGRATION HA 2021.12

### ISSUE THREAD

**Issue by morenonew2** [JurajNyiri/HomeAssistant-Tapo-Control#128]
Logger: homeassistant.util.package
Source: util/package.py:100
First occurred: 10:29:20 (3 occurrences)
Last logged: 10:29:33

Unable to install package onvif-zeep-async==1.0.0: ERROR: Cannot install onvif-zeep-async==1.0.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

Tapo doesn't work. Thanks

**Comment by JurajNyiri** [comment]
This integration works in 2021.12.
