### ISSUE TITLE
Time autosync

### ISSUE THREAD

**Issue by va77** [JurajNyiri/HomeAssistant-Tapo-Control#129]
Hi.

Sometimes I turned off my camera by unpluging power, when I turned it on again, time doesn't sync, or doesn't sync everytime (I blocked in firewall access to internet from camera).
Restart HA helps me.

Can you add autosync every 15-30 minutes, or add scheduled interval time as a parameter? Or at least or a button to force sync time or restart whole integration in settings?

HA 2021.12.4 Core
RPi 4
Tapo C200

**Comment by JurajNyiri** [comment]
Hello,

Autosync is already in place, it needs to be enabled in integration options. Manual sync has Feature request opened.
