### ISSUE TITLE
Bug: HA logs flooded with messages when the camera is shutdown

### ISSUE THREAD

**Issue by sgurgul** [JurajNyiri/HomeAssistant-Tapo-Control#130]
**Describe the bug**
Appeared with C100 camera. The camera is (intentionally) periodically OFF by cutting the power supply off.
The result is 1000+ entries reported within few hours of unavailability into the HA log.

**To Reproduce**
1. Integration enabled
2. Turn off camera completely
4. Wait 15 minutes and check HA logs to see the entries

**Expected behavior**
It's not bad that the entry appears in the log. The best would be if it appears once or at least less frequent than it it is reported now.

**Log**
Two types of errors are log - both have plenty of occurences

```
Logger: custom_components.tapo_control
Source: custom_components/tapo_control/__init__.py:209
Integration: Tapo: Cameras Control (documentation, issues)
First occurred: 22 December 2021, 20:00:38 (989 occurrences)
Last logged: 00:20:00
    HTTPSConnectionPool(host='192.168.1.132', port=443): Max retries exceeded with url: /stok=a940aff39125472596fefa890e9be7b4/ds (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff922bb460>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
```

```
Logger: homeassistant.components.onvif
Source: components/onvif/event.py:134
Integration: onvif (documentation, issues)
First occurred: 22 December 2021, 20:01:13 (247 occurrences)
Last logged: 00:19:31
Failed to restart ONVIF PullPoint subscription for 'f9c87025f66da34b6556440af7772a8b_tapo_events'. Retrying
```

**Camera (please complete the following information):**
 - Device Model: C100
 - FW: 1.1.15 Build 211130 Rel.15378n(4555)

**Using stream component**
yes

**Camera works through onvif component OR different cameras work in general**
yes

**Camera has all attributes filled out properly in developer tools**
yes

**HASS Environment**
HASSIO

**Comment by JurajNyiri** [comment]
This is expected. I am not sure how other integrations are handling this? If there are some guidelines about this I can update the code to follow it.

**Comment by sgurgul** [comment]
Hard to say it is expected by users :) Turning off camera e.g. for the day is quite common use-case. Flooding the log by a certain entity affects not only this integration but overall readability of the log.
Maybe it should be logged in Debug mode only ?
I am using Hikvision and Dahua integrations as well. None of them is using that aggressive logging.
When Hikvision is turned off similar error log entry appears but once per hour only. This is acceptable.
Dahua does not repeat log about camera unavailability at all unless debug mode is enabled.
