### ISSUE TITLE
Bug: integration not found on 2021.12.5

### ISSUE THREAD

**Issue by tco69** [JurajNyiri/HomeAssistant-Tapo-Control#131]
**Describe the bug**
The integration doesn't appears on integration section (ha docker 2021.12.5).

**To Reproduce**
try to add the integration

**Log**
No error logs, no help

Any idea? Regards

**Comment by tco69** [comment]
Installing by hacs it's working.

No problem 👍

**Comment by Bodge-IT** [comment]
I have the same issue on 2021.12.8.
Installed through HACS and integration shows there.
Tapo not showing in Integration list.
![image](https://user-images.githubusercontent.com/1881642/148366848-8ad5e9a9-d7a2-45f0-a82e-e1a68c943598.png)

![image](https://user-images.githubusercontent.com/1881642/148366766-adc787c6-a53b-40da-befb-b4a8e198cf9f.png)

**Comment by Bodge-IT** [comment]
OK, a little weird but after install, hacs requires system restart.  After reboot, Integration doesn't show in list.
Reloaded HAC integration and restarted again, still no integration in list.
Refreshed browser and it shows up.  Must be some caching for that integration list in UI.
