### ISSUE TITLE
Bug:Cannot add Tapo Integration

### ISSUE THREAD

**Issue by montolino** [JurajNyiri/HomeAssistant-Tapo-Control#133]
After installing Tapo from HACS, when I try to add the integration the error 
"Failed to load configuration flow"
(in italian "Impossibile caricare il flusso di configurazione" )

**Comment by JurajNyiri** [comment]
Hello, check your logs, try restarting home assistant and clear your cache. 
This is most probably related to your environment or setup and not an integration bug.

**Comment by montolino** [comment]
iI'm quite new on HA. I've checked the supervisor log but there are no errors. Could you kindly tell me where I can find other logs? Thanks

**Comment by JurajNyiri** [comment]
Hello

Configuration, settings, log
