### ISSUE TITLE
Bug: C200 motion sensor state

### ISSUE THREAD

**Issue by amitkeret** [JurajNyiri/HomeAssistant-Tapo-Control#136]
**Describe the bug**

I'm not exactly sure how to define this...
I noticed that I'm not getting motion updates from the camera. when I checked the entity state through the UI, it was shown as "Unavailable" - definitely explains the lack of updates.
However, at the same time, under Developer tools > States and Template, the state is still being reported as "on" (the last state reported before the entity became unavailable.

See below, "native" (and correct) representation:
![image](https://user-images.githubusercontent.com/1258597/150293541-c48d3240-8d8a-4742-ab17-3002a8da95f2.png)

...and is Developer Tools:
![image](https://user-images.githubusercontent.com/1258597/150293339-eb52e8ae-9a5c-442a-b605-9de2fed2b60a.png)
![image](https://user-images.githubusercontent.com/1258597/150293677-ef729bf7-3002-4ffa-8a6d-f59c4ff8f186.png)

This creates a problem when relying on the reported state in templates and automations.
Below is a sensor card using a template:
![image](https://user-images.githubusercontent.com/1258597/150293588-2c8d93f3-1f4d-49cc-b27f-4a7403011d82.png)

**Expected behavior**
The reported state should be consistent between "native" UI and `states` object.

**Log**
I'm not sure if this relevant, but it's the only Tapo-related log entries,

```
2022-01-20 12:37:40 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: 'bool' object is not subscriptable
2022-01-20 12:37:40 WARNING (MainThread) [homeassistant.config_entries] Config entry 'C200' for tapo_control integration not ready yet: None; Retrying in background
```

**Camera (please complete the following information):**
 - Device Model: C200
 - FW: 1.1.15 Build 211112 Rel.10589n(4555)

**Using stream component**
no

**Camera works through onvif component OR different cameras work in general**
no

**Camera has all attributes filled out properly in developer tools**
no - only have `icon` and `friendly_name`

**HASS Environment**
Home Assistant OS 7.1
core-2021.12.10
supervisor-2021.12.2

**Comment by amitkeret** [comment]
@JurajNyiri apologies for opening this bug... I misread the entities.
Now back to my original problem - figuring out why the motion sensor is unavailable :)

**Comment by JurajNyiri** [comment]
Hey, there is a section in [FAQ](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control#troubleshooting--faq) talking about why it might be unavailable and what to do to fix it.
