### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by acs-lux** [JurajNyiri/HomeAssistant-Tapo-Control#139]
Implement Tapo Care features.

Tapo Care is a paid subscription service that reinstates auto tracking controllable in home assistant and also provides AI for person detection.

A binary sensor for person detection would be a very useful thing in home assistant. For example, this would mean there really is someone at the door.

Maybe there are other sensors too if you have Tapo Care.

**Comment by JurajNyiri** [comment]
Duplicate of https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/126 .
