### ISSUE TITLE
Feature Request: Toggle privacy mode

### ISSUE THREAD

**Issue by kankadev** [JurajNyiri/HomeAssistant-Tapo-Control#140]
**Describe the solution you'd like**
![2022-02-08 06_51_55-Window](https://user-images.githubusercontent.com/84390410/152915136-3d3c4c07-cb5e-410f-aa30-76720297dcb6.png)
Would be nice to click on this camera card on the dashboard to toggle the privacy mode. I couldn't find a solution to configure this within the dashboard configuration.

**Describe alternatives you've considered**
Maybe it's possible but I don't know. So sorry, but please tell me how to solve this.

**Comment by JurajNyiri** [comment]
This is not possible in default lovelace cards. 

See [examples for lovelace cards](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/blob/main/examples/EXAMPLES_LOVELACE.md) or [examples for template entities](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/blob/main/examples/EXAMPLES_ENTITIES.md).

For any other lovelace related questions please ask in community forums instead.
