### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by sharpmindstudio** [JurajNyiri/HomeAssistant-Tapo-Control#144]
**Describe the bug**
After last update my L530 lost the ability to chage color

**To Reproduce**
The temperature still woks fine but the color selection failswit error: Failed to call service light/turn_on.'result'

**Expected behavior**
To work asin the previous version :)

**Comment by JurajNyiri** [comment]
This integration does not expose light entity. This integration only has camera and binary sensor entities.
