### ISSUE TITLE
Bug: tapo_control & Home Assistant 2022.3.0

### ISSUE THREAD

**Issue by andrewbpowers** [JurajNyiri/HomeAssistant-Tapo-Control#149]
Hello!

After updating to the new version (2022.3.0) of Home Assistant, I get the following message after restarting the server:

> Invalid config
> The following integrations and platforms could not be set up:
> 
> [tapo_control](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control)
> Please check your config and [logs](http://homeassistant.local:8123/config/logs).

Thanks for any help!
:-)

**Comment by JurajNyiri** [comment]
Use the latest version.
