### ISSUE TITLE
Bug: Tapo Control stopped working.

### ISSUE THREAD

**Issue by aspades** [JurajNyiri/HomeAssistant-Tapo-Control#150]
**Describe the bug**
Tapo Control stopped working after update the core.

**To Reproduce**
Update the core to 2022.3 from 2022.2

**Log**
Logger: homeassistant.setup
Source: setup.py:155
First occurred: 09:21:40 (1 occurrences)
Last logged: 09:21:40

Setup failed for tapo_control: Requirements for tapo_control not found: ['onvif-zeep-async==1.0.0'].

**Comment by JurajNyiri** [comment]
This has been fixed for [7 days now](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/3.4.5). Please refrain from reporting issues if you are using outdated versions. 

There are also 2 already:

https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/149
https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/148

**Comment by aspades** [comment]
Thank you for your response.
