### ISSUE TITLE
C200 binary sensor for motion not available

### ISSUE THREAD

**Issue by millenniumy2k** [JurajNyiri/HomeAssistant-Tapo-Control#160]
### Description

Hi, I don't have the binery sensor ..
TAPO CAMERA CONTROLLER 3.4.7

<img width="1024" alt="Schermata 2022-03-11 alle 12 48 45" src="https://user-images.githubusercontent.com/8614031/157861804-936af1e8-00b6-4b90-b9ac-97573375d0cc.png">

### Reproduction Steps

not error....

### Expected behavior

not error....

### Device Firmware

Firmware: 1.1.16 Build 211209 Rel.37726n(4555)

### Using stream component

No

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

No

### HASS Environment

Docker > Windows

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Hello, read FAQ in readme.
