### ISSUE TITLE
Package Conflict since last Hassio Update

### ISSUE THREAD

**Issue by kaQn4p** [JurajNyiri/HomeAssistant-Tapo-Control#162]
### Description

Heyho,

the Tapo integration has a dependency conflict since the last Hassio Update.
It does not b00t anymore and cannot be reinstalled.

### Reproduction Steps

Remove Tapo integration. Try to install it.

### Expected behavior

Integration starts

### If applicable, add error logs.

Logger: homeassistant.util.package
Source: util/package.py:99
First occurred: 11:20:42 (3 occurrences)
Last logged: 11:21:15

Unable to install package onvif-zeep-async==1.0.0: ERROR: Cannot install onvif-zeep-async==1.0.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.

### Device Firmware

latest

### Using stream component

No

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Raspbi with Hassio latest Version

### Search for similar issues

No

## System Health

version | core-2022.3.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.92-v7
arch | armv7l
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4981
Installed Version | 1.18.0
Stage | running
Available Repositories | 1008
Installed Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.5
-- | --
update_channel | stable
supervisor_version | supervisor-2022.03.5
docker_version | 20.10.9
disk_total | 116.5 GB
disk_used | 7.5 GB
healthy | true
supported | true
board | rpi3
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), Terminal & SSH (9.3.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 4
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by JurajNyiri** [comment]
Try searching for similar issues, thats why the question is in the template. 🤦‍♀️
