### ISSUE TITLE
Feature Request: Expose noise detection as binary_sensor

### ISSUE THREAD

**Issue by TitanNano** [JurajNyiri/HomeAssistant-Tapo-Control#167]
**Is your feature request related to a problem? Please describe.**
To properly work with the `noise_detected` attribute, it has to be converted into a sensor. I'm pretty everyone that does anything with it does that via a template sensor or anything similar.

**Describe the solution you'd like**
Remove the overhead of having to define a template sensor and define the attribute as a binary_sensor of class sound directly inside the integration.

**Describe alternatives you've considered**
Everyone keeps defining their own template sensors.

**Comment by JurajNyiri** [comment]
As you said, you can define a template sensor. Having binary sensor means more maintenance and more possible bugs in the future.
