### ISSUE TITLE
binary_sensor and update entities are never unloaded

### ISSUE THREAD

**Issue by TitanNano** [JurajNyiri/HomeAssistant-Tapo-Control#169]
### Description

Both the binary_sensor entity and the update entity are never unloaded. This causes exceptions when the integration is being reloaded or deactivated and then reactivated. 
https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/blob/6dda7b15fd305f103f1ca4cbaf16d67ee497f840/custom_components/tapo_control/__init__.py#L121-L127

HASS core will throw an exception that these entities are still loaded and won't load them again. This in turn puts the integration into a somewhat broken state.

### Reproduction Steps

1. go to `/config/integrations`
2. reload "Tapo: Camera Control"

### Expected behavior

The extension is being reloaded

### If applicable, add error logs.

I already patched my local integration so I do not have the exact exception at hand, but I can revert my changes if neccessary.

### Device Firmware

1.1.16 Build 211209 Rel.37726n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HASS OS on raspberry pi

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Hey! Could you please open pr with the patch?
