### ISSUE TITLE
Feature Request: specify mac address in device_info.connections

### ISSUE THREAD

**Issue by TitanNano** [JurajNyiri/HomeAssistant-Tapo-Control#170]
**Is your feature request related to a problem? Please describe.**
My HASS instance is unable to understand that the Tapo camera device defined by this integration and the Tapo camera defined by my router are the same device.

**Describe the solution you'd like**
the mac address of the camera should be added to the `connections` list of the `device_info`. This will allow HASS to merge the device into other devices with the same mac address.

**Describe alternatives you've considered**
Creating a MQTT device that has both the mac address and the identifier of this integration. It didn't work.

**Additional context**
Final result with the mac address added to the `device_info`:
![image](https://user-images.githubusercontent.com/4500858/162813546-87e35ae7-29f3-40f5-a7f9-d22ef2d030ec.png)

**Comment by JurajNyiri** [comment]
Hey, this is a great enhancement.
It looks like you already modified the code. Would you consider opening a PR?
