### ISSUE TITLE
Tapo c210 motion detection issues

### ISSUE THREAD

**Issue by RestOp** [JurajNyiri/HomeAssistant-Tapo-Control#174]
### Description

Hello,

I have problems with motion detection on my C210
Firmware V1.1.16 build 220119 tel 41999 (4555)
Last Home Assistant and addon.

Thanks a lot.

### Reproduction Steps

After restart of Home Assistant motion detection works some time (maybe hour maybe 3) then it stops to report any motions. When i restart home assistant one more time, i got the same behavior.

I have also c200 and c100, they works with no issues on this system

If i restart camera itself, then motion detection still not work.

### Expected behavior

Motion detection
.

### Device Firmware

1.1.16 build 220119 tel 41999 (4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HassOS, problem stays on at least on last 3-4 version, maybe more.

### Search for similar issues

Yes

**Comment by RestOp** [comment]
> ### Description
> Hello,
> 
> I have problems with motion detection on my C210 Firmware V1.1.16 build 220119 tel 41999 (4555) Last Home Assistant and addon.
> 
> Thanks a lot.
> 
> ### Reproduction Steps
> After restart of Home Assistant motion detection works some time (maybe hour maybe 3) then it stops to report any motions. When i restart home assistant one more time, i got the same behavior.
> 
> I have also c200 and c100, they works with no issues on this system
> 
> If i restart camera itself, then motion detection still not work.
> 
> ### Expected behavior
> Motion detection .
> 
> ### If applicable, add error logs.
> _No response_
> 
> ### Device Firmware
> 1.1.16 build 220119 tel 41999 (4555)
> 
> ### Using stream component
> Yes
> 
> ### Does camera work via official integrations?
> Yes
> 
> ### Camera has all attributes filled out in developer tools
> Yes
> 
> ### HASS Environment
> HassOS, problem stays on at least last 3-4 versions, maybe more.
> 
> ### Search for similar issues
> Yes
> 
> ### Additional information
> _No response_

**Comment by JurajNyiri** [comment]
Can you test with [onvif](https://www.home-assistant.io/integrations/onvif/) integration if it behaves correctly or if you can observe the same error there?

**Comment by RestOp** [comment]
Of course.  Do i need to remove camera from you integration to the time of this test or the can work together?

**Comment by RestOp** [comment]
> Of course. Do i need to remove camera from you integration to the time of this test or they can work together?

**Comment by JurajNyiri** [comment]
I recommend removing it, to make sure camera is not overloaded.

**Comment by marcoahp** [comment]
I have the same problem with tapo c210. Have you solved?

**Comment by RestOp** [comment]
> I have the same problem with tapo c210. Have you solved?

No, i was not at Home Assistant server all this time to check what [JurajNyiri](https://github.com/JurajNyiri) mentioned https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/174#issuecomment-1114625192

**Comment by peslung** [comment]
I have the same problem with my Tapo C210, firmware 1.1.16
Usually there is several days between each time this happens, restart of HA fixes the problem.

Motion from my Tapo C310 is functional all the time.
Motion in the Tapo app is functional on both all the time.

**Comment by marcoahp** [comment]
c200 the same

**Comment by peslung** [comment]
Been stable last 5 days

**Comment by RestOp** [comment]
Me not

**Comment by JurajNyiri** [comment]
Closing in favor of https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/84 . Please follow instructions I posted there and continue conversation in there.
