### ISSUE TITLE
! Retry configuration: None

### ISSUE THREAD

**Issue by Matt7C2** [JurajNyiri/HomeAssistant-Tapo-Control#179]
### Description

Hi.. With the last update of core, the tapo camera integration stopped work.
From the menù device->integration i have this error:
Retry configuration: None
How can i resolve it?

Camera model: c100
Camera firmware: 1.1.15
Integration: v3.6.0
supervisor-2022.05.3
Home Assistant OS 8.1
core-2022.6.2

### Reproduction Steps

I can't reproduce it

### Expected behavior

That the integration runs

### Device Firmware

1.1.15

### Using stream component

No

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Hassio

### Search for similar issues

Yes

### Additional information

I looked for the same error... i found to upgrade at v3.4.5 of the integration but min is the latest version

**Comment by JurajNyiri** [comment]
It still works. Try reinstalling.

**Comment by Matt7C2** [comment]
Thank.. i reinstalled it and now works
