### ISSUE TITLE
Tapo c200 no motion detection attribute

### ISSUE THREAD

**Issue by marcoahp** [JurajNyiri/HomeAssistant-Tapo-Control#181]
### Description

Previously I had motion sensor, but I removed integration and added it again and motion detection attribute is not added.
I rebooted camera and HA but do not work

### Reproduction Steps

1 Add Integration
2 Only 2 attributes installed SD and HD camera but motion detection not installed

### Expected behavior

Install Motion Sensor

### If applicable, add error logs.

Logger: custom_components.tapo_control
Source: custom_components/tapo_control/__init__.py:227
Integration: Tapo: Cameras Control ([documentation](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control), [issues](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues))
First occurred: 10:09:55 (2 occurrences)
Last logged: 10:16:16

HTTPSConnectionPool(host='192.168.1.171', port=443): Max retries exceeded with url: /stok=2a018d3d71193e1f669cd03145734732/ds (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff6249b190>: Failed to establish a new connection: [Errno 110] Operation timed out'))
HTTPSConnectionPool(host='192.168.1.171', port=443): Max retries exceeded with url: /stok=2a018d3d71193e1f669cd03145734732/ds (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff5fd6af40>: Failed to establish a new connection: [Errno 110] Operation timed out'))

### Device Firmware

1.1.16 Build 211209 Rel.37726n(4555)

### Using stream component

No

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HA Supervised on Amlogic S905X

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Read faq.

**Comment by marcoahp** [comment]
I had read, and I checked all but didn’t work

 

De: Juraj Nyíri ***@***.***> 
Enviado el: jueves, 16 de junio de 2022 10:44
Para: JurajNyiri/HomeAssistant-Tapo-Control ***@***.***>
CC: marcoahp ***@***.***>; Author ***@***.***>
Asunto: Re: [JurajNyiri/HomeAssistant-Tapo-Control] Tapo c200 no motion detection attribute (Issue #181)

 

Read faq.

**Comment by JurajNyiri** [comment]
Make sure to go through all the steps, maybe multiple times.
If it still doesn't work, you can try with [onvif](https://www.home-assistant.io/integrations/onvif/) integration instead. That will also probably not work, but if it does, test with this integration afterwards and if it still doesn't work, please reopen this issue.
