### ISSUE TITLE
Feature Request: Trigger alarm from outside?

### ISSUE THREAD

**Issue by anoff** [JurajNyiri/HomeAssistant-Tapo-Control#182]
**Is your feature request related to a problem? Please describe.**
This is more a request for your expert knowledge than an actual feature.
Does the API you use expose any way of triggering the alarm (noise / light) from the outside?
If it does, would you be willing to take a PR for that?

**Describe the solution you'd like**
Potentially add an actor for each camera to trigger the siren / light.

Thanks Juraj for maintaining this vital component for the HA ecosystem :)

**Comment by JurajNyiri** [comment]
This was just [added](https://github.com/JurajNyiri/pytapo/pull/35) to pytapo, so we can add it to Home Assistant integration as well.

We can add it as a new service exposed on the tapo_control domain. PRs are welcomed, if noone creates a PR I will try to find some time.

**Comment by JurajNyiri** [comment]
Now available in [3.7.0](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/3.7.0).

**Comment by Bastiencc** [comment]
Hi,
thanks for this new feature.
is there an attribut (or an other way ?) that says the alarm is triggered ?

thanks for your great work !!

**Comment by JurajNyiri** [comment]
For the one from camera yes it's the alarm one. For this manual not that I know of as it is not supported in the app. You could make a switch that turns on/off the alarm as the service and this integration is the only way to trigger it.
