### ISSUE TITLE
Feature Request: AI Mode

### ISSUE THREAD

**Issue by lawi75** [JurajNyiri/HomeAssistant-Tapo-Control#184]
**Is your feature request related to a problem? Please describe.**
No issue
**Describe the solution you'd like**
My TP-Link C310 now have something called AI-mode (or something like that, doesn't have the app in english) with the feature of detecting persons... Would be nice to be able to use this feature from HA as well as I only like to be notified if the camera sees a person

**Describe alternatives you've considered**
Just use it as of today with notifications for all movements

**Additional context**

**Comment by fanuch** [comment]
Isn't this request identical to this issue that was closed?

https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/126

**Comment by JurajNyiri** [comment]
@fanuch yes that is correct, thank you.

**Comment by lawi75** [comment]
Yes, my bad… Missed that inte
