### ISSUE TITLE
Feature Request: Add C210 to list of supported models

### ISSUE THREAD

**Issue by pascal-puetz** [JurajNyiri/HomeAssistant-Tapo-Control#185]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The C210 does work with this integration, so it should be added to the list of supported cameras.

**Describe alternatives you've considered**
-

**Additional context**
Confirmed working.

**Comment by JurajNyiri** [comment]
C210 is in the list.
