### ISSUE TITLE
Camera not connecting after update

### ISSUE THREAD

**Issue by dineshkathir** [JurajNyiri/HomeAssistant-Tapo-Control#188]
### Description

Lost connection after the update.

I have tried reconfiguring. I can able to stream rtsp in the VLC player. But HA integration says below error.

"Invalid authentication data. Make sure you have created your 3rd party account via Tapo app. You can also test if these credentials work via rtsp stream, for example VLC using link rtsp://username:password@IP Address:554/stream1"

<img width="455" alt="image" src="https://user-images.githubusercontent.com/69247666/177210041-0f2e358f-5814-4e6d-ac70-8e3cc0fb9d85.png">

### Reproduction Steps

1. Added Tapo camera integration via HACS
2. Tried configuring it in HA
3. Provided the ip address
4. It asked for credentials
5. But credentials did not work (but same credentials worked in VLC)

### Expected behavior

Lost connection after the update.

I have tried reconfiguring. I can able to stream rtsp in the VLC player. But HA integration says below error.

"Invalid authentication data. Make sure you have created your 3rd party account via Tapo app. You can also test if these credentials work via rtsp stream, for example VLC using link rtsp://username:password@IP Address:554/stream1"

<img width="455" alt="image" src="https://user-images.githubusercontent.com/69247666/177210041-0f2e358f-5814-4e6d-ac70-8e3cc0fb9d85.png">

### Device Firmware

latest

### Using stream component

Yes

### Does camera work via official integrations?

No

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Laptop hard disk

### Search for similar issues

Yes

**Comment by abdelrahman-osama** [comment]
What was the solution for this problem?

**Comment by JurajNyiri** [comment]
Update was not an issue. Restart camera, restart hass, make sure camera is accessible and you are entering correct information etc.

**Comment by dineshkathir** [comment]
I am able to connect the camera after restarting the camera and reinstalling Tapo camera in HA
