### ISSUE TITLE
Motion Detected Binary Sensors

### ISSUE THREAD

**Issue by krasatos** [JurajNyiri/HomeAssistant-Tapo-Control#19]
Hey therer @JurajNyiri, Great work! i was waiting for this a long time.

The question / feature request is as stated in the title, **will the cameras be able to inform HA when they detect motion?**
Through a dedicated binary sensor created for each camera, i'm guessing.

I wish i was able to contribute code-wise but i'm afraid i have no idea how to.
Please let me know if i could provide you with debug logs or something to help you out 💯

**Comment by JurajNyiri** [comment]
Hello,

PR is opened here and I am currently working on it.

https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/11
