### ISSUE TITLE
There is no possibility to select a camera when calling the service "Tapo:..."

### ISSUE THREAD

**Issue by Anton-Ka** [JurajNyiri/HomeAssistant-Tapo-Control#195]
### Description

There is no possibility to select a camera when calling the service "Tapo:..."
![image](https://user-images.githubusercontent.com/74901464/185418473-341afc5f-aad8-4103-9233-8fd57f75678d.png)

### Reproduction Steps

1. Enter the Developer Panel, 
2. Select the Services tab, 
3. Select any service "Tapo:..."

### Expected behavior

You should be able to select a cameras.
![image](https://user-images.githubusercontent.com/74901464/185419558-2b5061dd-343a-4f16-b133-03663ca1ce71.png)

### Device Firmware

C200 TP-Link sw_version: 1.1.16 Build 211209 Rel.37726n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Home Assistant 2022.8.4 / Supervisor 2022.08.3 / Debian

### Search for similar issues

Yes

**Comment by Hjord** [comment]
I have the same problem. Also doesn't come up when creating an automation etc.
Additional  info:

**Device Firmware**
C200 TP-Link sw_version: 1.1.17  hw version: 2
C200 TP-Link sw version 1.1.18 hw version: 1

**Using stream component**
No

**HASS Environment**
Home Assistant 2022.8.6 (Container)

**Comment by Anton-Ka** [comment]
When I try to start the service 
![Screenshot_2022-08-22-23-18-41-87_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/74901464/186011987-5a0452ba-43c0-4a1e-930f-5ae5f7d6b54b.jpg)
I get an error
![Screenshot_2022-08-22-23-22-35-90_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/74901464/186012028-91c95869-2231-4baf-9fcf-fd4abc41a242.jpg)
Perhaps this is because the camera was added somehow wrong ...
![IMG_20220822_232647](https://user-images.githubusercontent.com/74901464/186012624-09aca560-c749-4f71-8943-8cb4ebc32831.jpg)

**Comment by JurajNyiri** [comment]
This is a known bug.

For now you need to put entity_id manually under data. See [examples](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/blob/main/examples/EXAMPLES_ENTITIES.md) .

**Comment by vsimanin** [comment]
this is not an integration error, but a home assistant error.  It has already been fixed, but still not merged into the release.

**Comment by JurajNyiri** [comment]
> I trying use this service:
> 
> ```
>       service: tapo_control.ptz
>       service_data:
>         entity_id: camera.tapo_camera_3_sd
>         pan: RIGHT
> ```
> 
> But, I see error again.

You are using service_data. The error is surely also different, read it along with the link I sent before.

**Comment by Anton-Ka** [comment]
Now I tried to make `privacy_mode` on your link.  it works. 
In my call, I changed `service_data` to just `data`.  And it worked. 
I just was not careful and wrote extra `data` in my code.
Right code (for other people):
```
service: tapo_control.ptz
data:
  entity_id: camera.tapo_camera_3_sd
  preset: 1
```

**Comment by JurajNyiri** [comment]
Is this still an issue as per Sep release of Home Assistant?
