### ISSUE TITLE
HD Stream not available

### ISSUE THREAD

**Issue by nurimoca** [JurajNyiri/HomeAssistant-Tapo-Control#196]
### Description

I have 4 Tapo cameras, same configuration for all of them, no wifi issues, for some the HD stream is available and others it is not.
The SD stream works fine.

### Reproduction Steps

.

### Expected behavior

HD stream should be available

### If applicable, add error logs.

.

### Device Firmware

1.1.21

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

proxmox

### Search for similar issues

Yes

### Additional information

.

**Comment by JurajNyiri** [comment]
Not a integration issue. Make sure you are not overloading the camera.
