### ISSUE TITLE
Camera Control not showing in intergrations

### ISSUE THREAD

**Issue by FauxHobo** [JurajNyiri/HomeAssistant-Tapo-Control#200]
### Description

When i install Camera Control through HACS, I'm not able to add the integration in the HA UI. 

HACS confirms it is installed. A restart is done but then I can't get it to appear in HA UI. I tried v3.7.1 and 3.7.2. 

Running:
Home Assistant 2022.8.6
Supervisor 2022.08.3
Operating System 8.4
Frontend 20220802.0 - latest.

I also tried a fresh older build of my HA. Running on an RPi3. 

### Reproduction Steps

Go to HACS
Download Tapo Camera Control.
Restart HA.
Confirm in HACS that camera control is shown as installed.
Go to HA integration
Add integration 
Search for Tapo
Nothing found. 

### Expected behavior

Expect. to see Tapo camera contro integration to use. 

### Device Firmware

Tapo C210 1.1.21

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

No

### HASS Environment

RPi3

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
It is there. Make sure you installed it and you are looking at a correct place. Try also incognito mode or different browser.

**Comment by FauxHobo** [comment]
Damn, that was fast! And thank you, that worked.

 I'd tried in my browser and on the app, so assumed caching wasn't the issue. I was clearly wrong. I really appreciate you taking the time to respond.
