### ISSUE TITLE
Feature Request: Be able to change username/password for the camera in the integration page

### ISSUE THREAD

**Issue by GSzabados** [JurajNyiri/HomeAssistant-Tapo-Control#21]
**Is your feature request related to a problem? Please describe.**
Changed stream username and password on the camera, I want to update it for the integration.

**Describe the solution you'd like**
Option to change the username and password for the camera in the integration page as well.

**Describe alternatives you've considered**
Delete and add again the integration of the camera. A bit cumbersome. (Or change in the core.config_entities)

**Additional context**
N/A

**Comment by JurajNyiri** [comment]
Could you provide an example of some other integration on hass that is allowing this? AFAIK it is not something that is currently supported?

**Comment by GSzabados** [comment]
If that is the case, then it is another WTH, but I will have a look.

**Comment by GSzabados** [comment]
Ok, MQTT has a Configuration button and there it allows yo change username and password from the Integration panel. Is it close enough?

**Comment by JurajNyiri** [comment]
Thank you, I will take a look when I get to it, currently all my work is focused on [2.1 milestone](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/milestone/1)

**Comment by GSzabados** [comment]
No worries. Actually this feature should be there for many integrations, but it is not currently. And it is cumbersome to get around. Any how, it is not urgent.
