### ISSUE TITLE
Wrong MDI-icon for privacy switch (disabled)

### ISSUE THREAD

**Issue by Eyco1981** [JurajNyiri/HomeAssistant-Tapo-Control#211]
### Description

If the privacy switch ist turned off, it gets the MDI-icon mdi:eye-outline-off and no icon will be shown. It needs to be mdi:eye-off-outline to be shown.

### Reproduction Steps

1. Turn off privacy switch
2. Check MDI-Icon in Devtools

### Expected behavior

Showing icon mdi:eye-off-outline when switched off.

### Device Firmware

1.1.21 Build 220511 Re. 29067n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HA OS

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Fixed in [4.0.2](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/4.0.2). Thank you!

**Comment by kamil5771** [comment]
It should be: **mdi:eye-off-outline**

**Comment by Eyco1981** [comment]
It is mdi:eye-off-outline in 4.0.2. Have you cleared your browser's cache?

**Comment by JurajNyiri** [comment]
It should be working in 4.0.2. Make sure to clear cache, restart home assistant and/or try in incognito.

![image](https://user-images.githubusercontent.com/5785999/196533119-6a1c35aa-dc6a-4109-a6bd-375af41f0fb0.png)

**Comment by kamil5771** [comment]
Ok, I deleted integration and files and install again. It is working now. 

BTW. Integration frozing my HA. After reinstalation everthing is ok beyong logs:

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:515
First occurred: 21:57:16 (2 occurrences)
Last logged: 21:57:16

Update of camera.kuchnia_sd is taking over 10 seconds
Update of camera.hall_hd is taking over 10 seconds

**Comment by JurajNyiri** [comment]
That is expected, camera can sometimes take a long time to respond.
