### ISSUE TITLE
Error adding entities for domain select and switch

### ISSUE THREAD

**Issue by gateriderz** [JurajNyiri/HomeAssistant-Tapo-Control#213]
### Description

When installing the new version 4.0.2, I received 2 errors in the logs

```
Error adding entities for domain select with platform tapo_control
Error while setting up tapo_control platform for select
ValueError: Entity cannot be None

Error adding entities for domain switch with platform tapo_control
Error while setting up tapo_control platform for switch
ValueError: Entity cannot be None

```

### Reproduction Steps

1. Update to 4.0.2
2. Reboot Home Assistant (2022.10.04)
3. Validate Logs

### Expected behavior

No errors

### If applicable, add error logs.

```
Logger: homeassistant.components.select
Source: helpers/entity_platform.py:482
Integration: Select ([documentation](https://www.home-assistant.io/integrations/select), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+select%22))

Error adding entities for domain select with platform tapo_control
Error while setting up tapo_control platform for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 482, in _async_add_entity
    raise ValueError("Entity cannot be None")
ValueError: Entity cannot be None


Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:482
Integration: Switch ([documentation](https://www.home-assistant.io/integrations/switch), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+switch%22))

Error adding entities for domain switch with platform tapo_control
Error while setting up tapo_control platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 482, in _async_add_entity
    raise ValueError("Entity cannot be None")
ValueError: Entity cannot be None

```

### Device Firmware

1.1.15 Build 211130 Rel.15378n(5553)

### Using stream component

Yes

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HassOS 9.2

### Search for similar issues

Yes

### Additional information

I tried removing all the entities and the same issue occurs when using 4.0.2.

When rolling back to 3.7.2, no issues.

**Comment by JurajNyiri** [comment]
Hello,

what camera do you have?

**Comment by gateriderz** [comment]
@JurajNyiri ,

Camera: Tapo C100
On my Tapo app or in Home Assistant Options ?

**Comment by JurajNyiri** [comment]
In Home Assistant by going to Devices, searching for Tapo, selecting your camera and clicking on **1 Device**.

![image](https://user-images.githubusercontent.com/5785999/196543418-5d115fa9-01b8-4989-99ee-54071d24db4b.png)

**Comment by JurajNyiri** [comment]
I probably found the bug, working on a fix.

**Comment by gateriderz** [comment]
![image](https://user-images.githubusercontent.com/69553040/196544235-8503dddc-61bc-4ba0-a3a3-f50c0b6f71ca.png)

**Comment by JurajNyiri** [comment]
Should be fixed in [4.0.3](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/4.0.3).

Please let me know if it is.

**Comment by JurajNyiri** [comment]
Thank you! One more fix incoming for buttons for movement, if camera does not support them they will not be created.

**Comment by gateriderz** [comment]
Yes I saw that and they are now greyed out.

Thanks
