### ISSUE TITLE
Feature Request: add a way to check if alarm is running

### ISSUE THREAD

**Issue by Bastiencc** [JurajNyiri/HomeAssistant-Tapo-Control#214]
**Is your feature request related to a problem? Please describe.**
With news version, thete is no more way to cjeck if alarm is running

**Describe the solution you'd like**
Add a sensor or an attribut (like in the previous version)

**Additional context**
thanks for the great work !

**Comment by JurajNyiri** [comment]
Fixed in [4.0.5](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/4.0.5).
