### ISSUE TITLE
Tapo C320SW Motion Detection

### ISSUE THREAD

**Issue by abernas** [JurajNyiri/HomeAssistant-Tapo-Control#216]
**Is your feature request related to a problem? Please describe.**
the Tapo C320SW camera does not have an entity to change the motion detection mode

**Describe the solution you'd like**
option to switch motion detection mode (OFF, low, normal, high)

**Describe alternatives you've considered**

**Additional context**
I have two Tapo cameras. The Tapo C210 has a switch between the entities to select the Motion Detection mode. The Tapo C320WS camera does not have this switch. Although the camera supports changing modes and can be used in the default application. Please add. Thank you

**Comment by JurajNyiri** [comment]
Fixed in [4.0.7](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/4.0.7).
