### ISSUE TITLE
Feature Request: Sound Detection Entity

### ISSUE THREAD

**Issue by CFenner** [JurajNyiri/HomeAssistant-Tapo-Control#219]
**Is your feature request related to a problem? Please describe.**

I would like to detect if my baby is crying on the upper floor where my camera is positioned.

**Describe the solution you'd like**

I would like the camera to provide me with a sound detected binary sensor.

**Describe alternatives you've considered**

Alternative would be to create a template sensor using the attribute stored on the stream entity.

**Additional context**

**Comment by JurajNyiri** [comment]
Released in [4.1.0](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/4.1.0).
