### ISSUE TITLE
the entity of "move to  preset" is with unknown status

### ISSUE THREAD

**Issue by DZ8888** [JurajNyiri/HomeAssistant-Tapo-Control#220]
### Description

I followed the camera control example which is with webrtc and scripts using stack-in-car to make the card in Lovelace.
PTZ function is OK, but there is aways an error message show up after I pressed either Home or palm tree button.
It said "**Fail to call service script/set_outdoor_camera_home. Option Privacy not valid for outdoor_C200 move to preset**" for home button and said "**Fail to call service script/set_outdoor_camera_away. Option Room not valid for outdoor_C200 move to preset**" for palm tree. I checked the content in script and didn't find the error wording. then I get into developer tool to check the entities and found the entity status of "**outdoor_C200 move to preset**" is unknow. Is it the problem? May I have your help to guide me for the debuging! Thanks!
BTW, my camera is Tapo C200 and C210. both are with same problem as above!

### Reproduction Steps

Please refere to description.

### Expected behavior

The function of Home and palm tree button work well!

### Device Firmware

Tapo C210 : 1.3.0 Build 220830 Rel.69909n(4555) ; Tapo C200 : 1.1.19 Build 220627 Rel.33188n(5553)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Raspberry Pi 4B

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
You need to change the values of the example. Replace value of `option` with your preset name and `entity_id` with your entity id.

You can find preset names by checking the select via Settings -> Devices & Services -> Search for Tapo -> Click 1 device -> Scroll down to Configuration or checking attribute "presets" of the camera entity in development tools.

**Comment by DZ8888** [comment]
Thanks for prompt answer! 
As I mentioned in

**Comment by DZ8888** [comment]
As I mentioned in desscription, I did check the preset in development tool but the status is unknow without any option as below.
<img width="574" alt="屏幕截图 2022-10-20 165947" src="https://user-images.githubusercontent.com/59321522/196944649-d70eba7e-4fba-4199-9dd4-9f10b9ff7182.png">

I also checked the configuration, there is no any option in preset as below.
<img width="191" alt="屏幕截图 2022-10-20 202851" src="https://user-images.githubusercontent.com/59321522/196949829-af5a0899-aff0-4418-ae3b-e893f7823b48.png">

It seems something wrong there, do you have the idea for what's the problem? 

Sorry for the trouble and Thanks!

**Comment by JurajNyiri** [comment]
If the preset is empty, you probably have no presets configured.

Re-read my message above:

You can find preset names by checking the select via Settings -> Devices & Services -> Search for Tapo -> Click 1 device -> Scroll down to Configuration or checking attribute "presets" **_of the camera entity_** in development tools.

**Comment by DZ8888** [comment]
Sorry for one more question!
Following is all of my Tapo camera's attributes of preset. I can not see the preset name there. Doeas that mean I didn't configure the preset? but I do set the preset in Tapo app. Is there anything else I can check it furtherly. 
Thanks!

<img width="596" alt="屏幕截图 2022-10-21 085553" src="https://user-images.githubusercontent.com/59321522/197087167-b23264c3-398a-4015-afad-47ee71e4a62b.png">
