### ISSUE TITLE
with the latest upgrade 4.0.8 I'not able to turn the tapo c200 any more

### ISSUE THREAD

**Issue by KonTiki1957** [JurajNyiri/HomeAssistant-Tapo-Control#222]
### Description

After a couple of months I decided to upgrade the tapo component which has been working very well since the beginning, but now with the version 4.0.8 whenever I try to move the camera, on the UI or through a script an error comes out stating: Unable to find service tapo_control.ptz. No problem with the Tapo app. I would even very like to downgrade to an earlier version because I need this function but I don't know how to do it.

### Reproduction Steps

1 goto webUI
2 push a button to move the camera in any direction

### Expected behavior

expect ameramovement

### If applicable, add error logs.

2022-10-20 17:51:11.075 ERROR (MainThread) [homeassistant.components.script.camera_esterno_su_scrivania] camera esterno su scrivania: Error executing script. Service not found for call_service at pos 1: Unable to find service tapo_control.ptz
2022-10-20 17:51:11.093 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved

### Device Firmware

1.1.15 Build 211111 Rel.34670n(4555)

### Using stream component

No

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

supervisor installation on debian 11/rasi4 64 bit

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Read release notes when updating. Especially breaking changes.

**Comment by KonTiki1957** [comment]
yes sir thanks for the fast response, I was just seeing the breaking changes of version 4.0.0 when I received your reply. Sorry I was a little bit panicking because I just updated after a couple of months of not attending at this server and I was lost when I saw that it didn't seem to work any more. For the time being I fixed the controls but I don't find a way to use this new way in the scripts or automations ... I don't have to call a service, am I correct?

**Comment by JurajNyiri** [comment]
You need to look up documentation on the new entities. 
https://www.home-assistant.io/integrations/switch/
https://www.home-assistant.io/integrations/select/
https://www.home-assistant.io/integrations/button/

There are also [lovelace examples](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/blob/main/examples/EXAMPLES_LOVELACE.md) in this repo.

**Comment by KonTiki1957** [comment]
okay thank you again
