### ISSUE TITLE
'TapoMotionDetectionSelect' object has no attribute with version 4.1.3

### ISSUE THREAD

**Issue by masiko-jh** [JurajNyiri/HomeAssistant-Tapo-Control#233]
### Description

I have two cameras, C200 and C310.
After updated to version 4.1.3, HA logs plenty attributeError related to 'TapoMotionDetectionSelect'

### Reproduction Steps

updated version to 4.1.3

### Expected behavior

no error logged

### If applicable, add error logs.

2022-10-21 20:46:04.490 ERROR (MainThread) [custom_components.tapo_control] Unexpected error fetching Tapo resource status data: 'TapoMotionDetectionSelect' object has no attribute '_enabled'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/tapo_control/__init__.py", line 234, in async_update_data
    if entity._enabled:
AttributeError: 'TapoMotionDetectionSelect' object has no attribute '_enabled'

### Device Firmware

C200: 1.1.18 Build 220518 Rel.61472n(4555) - C310: v1.3.1 Build 220713 Rel.42087n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker on NUC with Debian11

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
That doesn't make much sense, it should be there and I cannot replicate it.

What version did you upgrade from?

Try restarting Home Assistant and let me know if the issue persists.

**Comment by masiko-jh** [comment]
Hi.. I upgraded from v 4.1.2 to 4.1.3.. 
home assistant restarted as yoou requested, same error on log, restarted even NUC, error still show up on log
updated to 4.1.4, same error .. 

removed integration and reinstalled 4.1.4 from scratch
added camera C200.. no error on log
added camera C310  and error come up again.. 

I dont know, if I'm the only one with this problem maybe could be something related to my configuration..  I'll investigate more.. if I find something I'll let you know!

Thanks

**Comment by JurajNyiri** [comment]
I do not own C310 so I cannot test for it. 4.1.3 introduced a new way to get updates, so it might be possible it doesnt work properly on C310. Could you come to discord to debug?

**Comment by JurajNyiri** [comment]
Is there anything else in the logs? Try enabling debug logs and post everything up until that error.

**Comment by JurajNyiri** [comment]
Also please confirm the error goes away if you move back to 4.1.2, you can do this easily by HACS.

**Comment by masiko-jh** [comment]
v4.1.4 -- Removed camera C200 and configured only C310, debug enabled and restarted HA

[debug__log_4.1.4.txt](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/files/9842709/debug__log_4.1.4.txt)
i'm trying to move back to 4.1.2..

**Comment by JurajNyiri** [comment]
This was helpful, I can see that for some reason the TapoMotionDetectionSelect does not finish initialization, even though there is no error which is very weird.

I have pushed a new version into the github, please [download](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/archive/refs/heads/main.zip) it and overwrite files manually. Then send debug logs again.

**Comment by masiko-jh** [comment]
done.. here is the full log.. 
[debug__log_main.txt](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/files/9842925/debug__log_main.txt)

**Comment by JurajNyiri** [comment]
I see the issue, the `'motion_detection_sensitivity': None`. That should never happen.

I added one more log could you download again and run?

**Comment by JurajNyiri** [comment]
The latest version I just pushed to github (not yet released) has a fix for this. But please do still post the full debug log with it, I need to know how your camera got into that state it should never be in so that I can fix it better.

**Comment by masiko-jh** [comment]
now seem fixed..  error is gone

[debug__log_last.txt](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/files/9843011/debug__log_last.txt)

**Comment by vingerha** [comment]
Have had the same TapoMotionDetectionSelect issue with a C310 after/with recent many updates (I was on 3.72 recently)
Just installed 'main' and the error no longer shows.

**Comment by JurajNyiri** [comment]
Fixed for 4.1.5 I will fix it better in next version. Thank you for the logs!
