### ISSUE TITLE
Lost services of Ptz control and Privacy

### ISSUE THREAD

**Issue by antstyl** [JurajNyiri/HomeAssistant-Tapo-Control#234]
### Description

Suddenly after an update (not the last one but the previous I think) I lost all services regarding camera Ptz control and enabling disabling Privacy mode.

### Reproduction Steps

![Screenshot_20221022-150902_Home Assistant](https://user-images.githubusercontent.com/6030798/197338392-5f0d8a5e-adc6-4e5a-9898-a0028dd29d6f.jpg)

### Expected behavior

Should be able to control Camera PTZ and Privacy mode as previously.

![Screenshot_20221022-150913_Home Assistant](https://user-images.githubusercontent.com/6030798/197338426-61d427ce-f751-487e-bb29-57695007c189.jpg)

### Device Firmware

1.1.18

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Raspberry 

### Search for similar issues

Yes

**Comment by andrewigali** [comment]
I confirm the problem/shortcoming.
Previously, there were many more call service options, for example:
 tapo_control.ptz
 and
 tapo_control.set_privacy_mode

Currently, only the following can be selected:
tapo_control.delete_preset
tapo_control.save_preset

Can it be solved so that all options can also be selected as call services, not just as devices?

**Comment by JurajNyiri** [comment]
Go read release notes.

**Comment by andrewigali** [comment]
It's great that there are entities, but only for those who set up automation as a device.
 In my opinion, it would be very important if it could also be set up as a call service (in some ways it is safer, better, more stable).
Please help us by giving us this option.  Ok can be a device-entity but we also want it as a call service.

**Comment by JurajNyiri** [comment]
It is in no way more safer, better or stable. Entities are user friendly and intuitive and the way everything in Home Assistant should be. 
You can call a proper service with the entity achieving everything you could before. Go read documentation.

**Comment by andrewigali** [comment]
The Call Service is better than the Device method, because if the device is deleted, the automatism does not fall apart, it remains formally, at most it cannot find where the task should be performed.
With the Device method, the data is lost, and if another device is added again, the automation must be completely rebuilt.  In the case of Call Service, a maximum of the name must be rewritten.
Please try it to understand.
Sorry, I'm not good at English.  :(

**Comment by JurajNyiri** [comment]
You can call service on any entities.
You are simply objectively not correct. Go read documentation and educate yourself.

**Comment by robkarpati** [comment]
Hi All,
I miss tapo_control.ptz and tapo_control.set_privacy_mode too.
I have a few automatisations with these services and now I am unable to use them. And I cant find a way how to rewrite them without these services. 
The new entities are very nice and useful, but services are more useful for me.

**Comment by JurajNyiri** [comment]
**Individual services are not coming back.**

**Stop being lazy and go learn how to do the most basic things in Home Assistant or read through numerous examples.**

Moving to preset [example](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/blob/main/examples/EXAMPLES_LOVELACE.md) via **_calling service_** [select.select_option](https://www.home-assistant.io/integrations/select/) :

```
      service: select.select_option
      data:
        option: Privacy
      target:
        entity_id: select.bedroom_move_to_preset
```

Switching privacy mode [example](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/blob/main/examples/EXAMPLES_LOVELACE.md) via **_calling service_** [switch.turn_on](https://www.home-assistant.io/integrations/select/) :

```
      service: switch.turn_on
      data: {}
      target:
        entity_id: switch.bedroom_privacy
```

I am not going to provide any more examples and or answers here. If you are too lazy to search for most basic things in home assistant, uninstall it, and get something simple.

Next person asking for getting back services gets banned & muted for wasting my time by being completely and utterly lazy and silly.
