### ISSUE TITLE
Privacy switch disappear

### ISSUE THREAD

**Issue by pinkfloydFR** [JurajNyiri/HomeAssistant-Tapo-Control#235]
### Description

Hi,

On my TAPO C200 i used to switch privacy mode by a button or nod-red, but since last update this option disappear...

- entity: camera.tapo_camera_hd_stream
    icon: mdi:eye-off-outline
    tap_action:
      action: call-service
      service: tapo_control.set_privacy_mode
      service_data:
        entity_id: camera.tapo_camera_hd_stream
        privacy_mode: 'on'

service tapo_control.set_privacy_mode doesn't exist anympore :(

Thanks !

### Reproduction Steps

search for service tapo_control.set_privacy_mode

doesn't exist anymore

### Expected behavior

Possibility to switch privacy mode ON/OFF

### Device Firmware

1.1.18

### Using stream component

No

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker on RASPERRY PI ( HA OS )

### Search for similar issues

Yes

### Additional information

Just find this in the forum : 

service: select.select_option
data:
  option: Privacy
target:
  entity_id: select.bedroom_move_to_preset

but got unknown error. Will be grateful for help or link to documentation, thanks.

EDIT : 

find 
https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/blob/main/examples/EXAMPLES_LOVELACE.md

but i dont have privacy switch...

![image](https://user-images.githubusercontent.com/49475899/197340935-bc66174a-0a88-4632-8730-d3defd107fb9.png)

**Comment by JurajNyiri** [comment]
Go read release notes.
