### ISSUE TITLE
Camera removal fails, entity still exists in config\.storage

### ISSUE THREAD

**Issue by Fettkeewl** [JurajNyiri/HomeAssistant-Tapo-Control#237]
### Description

Device entity persists after removal from integration via UI.
Blocks re-adding device via UI.
Manual delete is required from config \ .storage \ core.config_entires
![devicepersist](https://user-images.githubusercontent.com/25577040/197478495-61aed363-c381-4073-bd03-039c89463bfe.png)

### Reproduction Steps

1. Remove device from UI
2. Add new device with same IP 

### Expected behavior

The old device should have been removed entirely

### Device Firmware

1.1.18 Build 220518 Rel.61472n(4555)

### Using stream component

No

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Hassio on Oracle VM 

### Search for similar issues

No

**Comment by tekgamerpt** [comment]
same problem here

**Comment by alexanderznamensky** [comment]
same with me.
solution: deactivate camera nd delete after that

**Comment by JurajNyiri** [comment]
Could you please test with the latest beta release? I wasn't able to replicate it anymore.
