### ISSUE TITLE
The image does not load

### ISSUE THREAD

**Issue by abernas** [JurajNyiri/HomeAssistant-Tapo-Control#238]
### Description

After updating to the latest version, the image from the C210 and C320SW cameras stopped loading. HD stream and SD stream is Idle

### Reproduction Steps

Settings - Add-ons - Tapo: Cameras Control - Canera

### Expected behavior

Loaded image from camera

### Device Firmware

C210 - 1,3,0  C320SW 1.1.21

### Using stream component

No

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Rpi4

### Search for similar issues

No

### Additional information

Everything was working before the update, now it's broken

**Comment by JurajNyiri** [comment]
There were no changes with stream, restart camera, fix the environment and make sure it works with https://www.home-assistant.io/integrations/onvif/ for example.
