### ISSUE TITLE
Failed to call service tapo_control/xxx_xxxxxxxx_xxxx. Service not found.

### ISSUE THREAD

**Issue by andrewbpowers** [JurajNyiri/HomeAssistant-Tapo-Control#239]
### Description

Since the last updates of HA (Home Assistant 2022.10.5, Supervisor 2022.10.0, Operating System 9.2, Frontend 20221010.0 - latest) and Tapo-Control, I get the following error messages when I click on the privacy mode button. 

`Failed to call service tapo_control/set_privacy_mode. Service not found.`

The camera is a C210 with firmware 1.3.0.

### Reproduction Steps

See above!

### Expected behavior

The cameras should be able to be controlled in the same way as before.

### Device Firmware

1.3.0.

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Raspberry Pi

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
> Search for similar issues
> Yes

Try again.

**Comment by JurajNyiri** [comment]
Happy to help! Thanks for wasting my team by being lazy to do 5 second search!

**Comment by andrewbpowers** [comment]
You wasted most of your time with your infantile answers ;-) Therefore, thank you again, I was very amused. :-)
