### ISSUE TITLE
Camera move to preset not working via service call

### ISSUE THREAD

**Issue by Chrisiesmit93** [JurajNyiri/HomeAssistant-Tapo-Control#240]
### Description

The TP-Link Tapo C200 camera creates an 'select' entity for PTZ presets (with the coorect/know presets) , but this cannot be called from a service call or automation.

If I choose an PTZ preset from the created 'select' entity, the camera goes to the right preset (this is working correctly)
But if I want to call the service call with the following command: 
`service: select.woonkamer_move_to_preset
data:
  option: Keuken`
I got the following error: `Kan service select.woonkamer_move_to_preset niet aanroepen. Unable to find service select.woonkamer_move_to_preset`

If I go to developer tools -> Services, the service 'select.woonkamer_move_to_preset' is also not known (but is does exist at developer tools -> states).

Furthermore, the entity 'select.woonkamer_move_to_preset' has always state 'Unknown', even after changing PTZ position via the dropdown menu within the states input entity.

Extra info: the old 'tapo_control.ptz' service worked fine without any problems (which now isn't available anymore with the updated component).

### Reproduction Steps

Go to developer tools -> Services
Fill in the following:
`service: select.woonkamer_move_to_preset
data:
  option: Keuken`
An error apears

OR

Go to developer tools -> States
Search for 'select.woonkamer_move_to_preset'
State is: unknown
Click on the entity -> choose a PTZ preset -> this works correctly.

### Expected behavior

Camera goes to the PTZ preset/postition from an service call (/automation), just like when you manually select the ptz preset from the 'select entity'.

### If applicable, add error logs.

`Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:140
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 19:15:33 (3 occurrences)
Last logged: 19:30:37

[140153828655456] Error handling message: Unable to find service select.woonkamer_move_to_preset (unknown_error)`

`Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:409
First occurred: 19:15:33 (3 occurrences)
Last logged: 19:30:37

websocket_api script: Error executing script. Service not found for call_service at pos 1: Unable to find service select.woonkamer_move_to_preset`

### Device Firmware

Firmware: 1.1.19 Build 220627 Rel.33188n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Home Assistant Operating System

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
There is no service `select.woonkamer_move_to_preset` that is your entity name.

Moving to preset [example](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/blob/main/examples/EXAMPLES_LOVELACE.md) via **_calling service_** [select.select_option](https://www.home-assistant.io/integrations/select/) :

```
      service: select.select_option
      data:
        option: Privacy
      target:
        entity_id: select.bedroom_move_to_preset
```
