### ISSUE TITLE
Sudden errors with tapo_control.set_privacy_mode

### ISSUE THREAD

**Issue by ryanmaule** [JurajNyiri/HomeAssistant-Tapo-Control#241]
### Description

I had an automation enable privacy mode when I arrived home on my indoor cameras, but HA is now reporting that this service doesn't exist and I cannot find it in my system.  Was it recently removed?

### Reproduction Steps

Attempt to call tapo_control.set_privacy_mode.

### Expected behavior

tapo_control.set_privacy_mode can be utilized

### If applicable, add error logs.

Logger: homeassistant.components.automation.heating_disengage
Source: helpers/script.py:409
Integration: Automation (documentation, issues)
First occurred: 2:22:47 PM (1 occurrences)
Last logged: 2:22:47 PM

At Cottage - leave: Error executing script. Service not found for call_service at pos 2: Unable to find service tapo_control.set_privacy_mode

### Device Firmware

1.1.15 Build 211130 Rel.15378n(5553)

### Using stream component

No

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker

### Search for similar issues

Yes

### Additional information

Here's what I see in States:

auto_update: false
installed_version: 1.1.15 Build 211130 Rel.15378n(5553)
in_progress: false
latest_version: 1.1.15 Build 211130 Rel.15378n(5553)
release_summary: null
release_url: null
skipped_version: null
title: 'Tapo Camera: Basement'
entity_picture: https://brands.home-assistant.io/_/tapo_control/icon.png
friendly_name: Camera - Basement
supported_features: 17

**Comment by JurajNyiri** [comment]
Did you search for similar issues?
