### ISSUE TITLE
Says update is available when not

### ISSUE THREAD

**Issue by SVH-Powel** [JurajNyiri/HomeAssistant-Tapo-Control#242]
### Description

As the image below show. The update sensor is "on" and the installed version is newer than what is "latest version"

![image](https://user-images.githubusercontent.com/64255194/197988338-a6803fc9-06a2-4235-b85d-3d8706e6b0e4.png)

### Reproduction Steps

Dont know how to reproduce this

### Expected behavior

The update sensor should be "off"

### Device Firmware

1.3.1

### Using stream component

Yes

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HA OS

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Update sensor shows as on when the version as latest reported is different to the currently installed version. I am not sure how this could happen. Maybe they rolled back the released version?

Could your try to reboot home assistant to see if it resolves?

**Comment by SVH-Powel** [comment]
A reboot solved it
