### ISSUE TITLE
Feature request: Camera availability sensor

### ISSUE THREAD

**Issue by Fettkeewl** [JurajNyiri/HomeAssistant-Tapo-Control#248]
**Is your feature request related to a problem? Please describe.**
I currently have all my cameras blocked from the internet through my router.
The only way I can communicate with my cameras outside of my home is through Home Assistant
and this is the way I want it to be. However since I'm not constantly looking at the feeds I currently
have no way of knowing should a camera be taken offline or be defective until I actually look for it.

**Describe the solution you'd like**
A sensor from the Tapo Integration that checks if the camera is available/online
with regular intervals (30/60s) ... perhaps even configurable.  

**Describe alternatives you've considered**
I could make my own ping sensors for sure but I'd rather it be implementet from
the tapo integration

**Additional context**
<none>

**Comment by JurajNyiri** [comment]
What exactly is the request here? It is not clear to me. Is the request to have a sensor for camera having or not having internet connection?

**Comment by Fettkeewl** [comment]
A sensor that tracks the cameras connection to the Tapo Integration. 
If the tapo integration cant communicate with the camera (because its turned off or rebooting or disconnected from the network) the sensor should reflect that state.

A simple "is the connection available" sensor that checks every 30 s or so

**Comment by JurajNyiri** [comment]
It is already there, if the camera is powered off, all the sensors will eventually switch to unavailable.
