### ISSUE TITLE
ERROR: Support only RTSP-stream 

### ISSUE THREAD

**Issue by ahaverty** [JurajNyiri/HomeAssistant-Tapo-Control#249]
### Description

Following the recommendation of using WebRTC, I get the error:
`ERROR: Support only RTSP-stream`

for my Tapo C310

My configuration:
```yaml
type: custom:webrtc-camera
url: camera.front_camera_hd_stream
```

I get the same for sd_stream too.

<img width="501" alt="image" src="https://user-images.githubusercontent.com/2920947/200281422-61bf93f0-20f8-4213-8302-c08803a33d34.png">

<img width="827" alt="image" src="https://user-images.githubusercontent.com/2920947/200282044-3dd23afd-7af9-4a11-bc07-ddbb8a7b7e37.png">

_I know WebRTC is more of a suggestion on the readme, but perhaps someone could help me understand why RTSP is not found for my camera here?_

### Reproduction Steps

Setup C310
Setup WebRTC
Reboot
Add camera via WebRTC card

### Expected behavior

Camera displayed via WebRTC card

### Device Firmware

Firmware: 1.3.0 Build 220830 Rel.72368n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Home Assistant Blue - Supervised - 2022.10.5

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Make sure that your stream works. If it works via Home Assistant, and not webrtc, open issue with webrtc.

**Comment by zenitraM** [comment]
@ahaverty just also fell on this, in case you haven't noticed yet -- you have to set in the WebRTC component
```yaml
entity: camera.front_camera_hd_stream
```
instead of
```yaml
url: camera.front_camera_hd_stream
```
for it to work.
