### ISSUE TITLE
C310: motion detection loop

### ISSUE THREAD

**Issue by vingerha** [JurajNyiri/HomeAssistant-Tapo-Control#250]
### Description

Recently (1-2 weeks) I am seeing that the motion sensor, provided by this integration, triggers about every minute. Camera reboot does not help, only HA reboot seems to do the trick. The senor then first turns up as 'unavailable' but with the first detection it is working fine....and without the loop.
Below a screenshot of the log, the detection loop started 09:52 and went on till HA restart (~2 hours)
At 09:52 there was indeed an actual detection (email notification received)

![image](https://user-images.githubusercontent.com/44190435/200540301-82f4ec68-40e8-4512-b92b-e9c05441a2a2.png)

### Reproduction Steps

Use of C310 with motion detection and latest HACS version 4.1.6

### Expected behavior

Only throw detected when actually detected

### Device Firmware

1.3.0 / 220830

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker on NUC 2022.11.1

### Search for similar issues

Yes

### Additional information

Might be related to other open topic on C310 unavailable state?

**Comment by vingerha** [comment]
I downgraded to 4.1.2 to see if this makes a change, keep you posted

**Comment by JurajNyiri** [comment]
Please verify the behaviour happening / not happening with the official onvif integration.

**Comment by vingerha** [comment]
Thanks for getting back, should I then temporarily undo your integration or should this run in parallel?

**Comment by vingerha** [comment]
Findings: 
Main system 2022.11.1 / tapo 4.1.2 + onvif
Tapo integration sensor just went in a loop again at 17:11 after reall motion was detected...and then continued, the onvif only shows the actual last motion at 17:11 and then remains clear

Dev system 2022.11.1 / ONLY onvif
onvif only shows the actual last motion at 17:11 and then clear

**Comment by vingerha** [comment]
New findings
Main system tapo sensor started minute-loop again (loop now for 2 hours)
Main system onvif behaving 'normal'
Dev system: onvif lost connection to the motion detection re-install did not help.

**Comment by vingerha** [comment]
@JurajNyiri  ?your view? 
The onvif motion detector may be a workaround but it behaves really odd, it now all-of-a-sudden available in my dev instance and no longer available in main...possibly it does not work across multiple instance...Anyhow, this I cannot use as unreliable. If you require more details then I am of course happy to supply where I can...just give me some pointers then :)

**Comment by JurajNyiri** [comment]
Camera has limited resources. It is possible you are overloading it. Make sure to access camera only via one connection and not multiple.
The code for onvif (motion events) in this integration is pretty much identical to official onvif integration.

**Comment by vingerha** [comment]
Thanks and with onvif/tapo on Main... a careful conclusion is that the tapo integration starts looping (as onvif sensor does not). Could this be related to a cooldown? Any other tips to analyse as the loop is annoying as you can imagine :)

**Comment by JurajNyiri** [comment]
Try enabling debug logs and post them here.

As a workaround, you can disable motion sensor in this integration and use the one from onvif (disable camera entities there.

**Comment by vingerha** [comment]
I will give it a go first without the tapo md but I am not sure if disabling it will posisbly reduce/remove the logging of errors for it?
So, I will first disable and then see what happens. Sadly I also seem to be the only one having this issue so that does make it not very urgent for you :)

**Comment by JurajNyiri** [comment]
To debug the issue do not disable it, just enable debug logging and do not use the camera with any other integration / application including the official phone app.

>  I also seem to be the only one having this issue so that does make it not very urgent for you :)

I would love to help you and fix this but its really hard if I cannot replicate it, so we need to figure it out on your machine.

**Comment by vingerha** [comment]
Hmm...not sure how to bring this message. I switched off Tapo in favor of onvif
Aside the motion part, I had increasing more issues with my image_processing (deepstack) being unable to process the image. Furhermore it took many seonds to display the camera feed on my tablet, showing cam feed after motion.
So, today I removed all of tapo just to see if onvif all-by-itself would be fine too, do note that I only need cam and motion, no fancy other stuff.
Motion is more responsive although arguably not that much but the main diff is with the cam feed, deepstack works now even with 3 times bigger file size and when my tablet wants to display the feed-after-motion, it shows <1 instead of >2
About 1 year ago, when I bought the tapo, onvif was not good at all or so it seemed, and though 1 day is very little to judge from ... it seems to fit my needs better.
You can close the thread or leave it open...if the latter then I will continue to feed when I re on tapo

**Comment by JurajNyiri** [comment]
There is no difference in stream between onvif and this integration. Both just expose rtsp link to Home Assistant.
Your issues were most probably caused by overloading the camera (see tapo faq).

**Comment by vingerha** [comment]
That would also be my understanding but I have not changed anything on the camera side whilst verifying onvif. 
This camera is (!) connexted to my Syno surveillance station and that does affect things, e.g. it was one of the reasons to move HA from the same Syno to a NUC. 
However, I just tested it again with Tapo (and without onvif) the feed is quite a bit slower in response and deeptstack image_processing fails on the HD setting (I guess this is because of the slow response but no log whatsoever). 
What I continue to see as odd too is that (so-far) only I have this issue, or?
