### ISSUE TITLE
Some C200 are only creating stream entity

### ISSUE THREAD

**Issue by Tugado** [JurajNyiri/HomeAssistant-Tapo-Control#251]
### Description

I have 2 C200. When I add the integration, one is creating all the entities related to control the camera but the other creates only the stream entities. I’ve been comparing them and the second camera shows HW version 2.0 while the first one shows 1.0. 
Also their firmware have different versions.

Both are C200 but one of them doesn’t seem to be compatible.

### Reproduction Steps

Add new Tapo Integration with a HW 2.0 C200

### Expected behavior

It should be creating the entities related to movement, privacy mode, etc…

### Device Firmware

1.0.19

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

No

### HASS Environment

Docker on raspberry pi 4

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Is there any errors in the logs?

This is not very probable, some control entities are always created. Try restarting cameras and Home Assistant. If that doesnt work, try removing the devices, restarting, removing the integration and reinstalling and adding.

**Comment by Tugado** [comment]
I restarted HA and cameras several times but didn't work but removing, restart and reinstalling did the trick. Thanks!
