### ISSUE TITLE
Feature Request: AI baby camera support

### ISSUE THREAD

**Issue by anshul10s** [JurajNyiri/HomeAssistant-Tapo-Control#252]
**Is your feature request related to a problem? Please describe.**
Tapo camera android app supports AI baby cry detection, same is not supported as binary sensor via this integration. Use-case for me is to notify people at home via google home speaker if babies are crying but there is no one present around them (via presence sensor).

**Describe the solution you'd like**
I would like AI baby cry detection to be supported as a binary sensor via this integration in HA.

**Describe alternatives you've considered**
I have considered noise detection supported by this integration and tweaked a lot of configs but either it leads to false detection or no detection. 

**Additional context**

Attaching the baby AI detection feature screenshots
![Screenshot_20221114-211050](https://user-images.githubusercontent.com/1374902/201704570-c70bd7f3-5181-467d-a3a3-6b1b804c88e7.png)
![Screenshot_20221114-211005](https://user-images.githubusercontent.com/1374902/201704577-f54925f5-05a5-46c6-b617-70e089f980ba.png)
![Screenshot_20221114-211036](https://user-images.githubusercontent.com/1374902/201704580-d4411bca-83f4-42ec-8865-b7b5e6f6629d.png)

**Comment by JurajNyiri** [comment]
If possible, this will first need to be discovered and added to https://github.com/JurajNyiri/pytapo library.

Until that happens, this is impossible to implement here.

**Comment by anshul10s** [comment]
how can i help?

**Comment by CFenner** [comment]
Is this a feature of the camera itself or the cloud service? Could this work without a subscription?

**Comment by anshul10s** [comment]
This feature should work on the camera itself, as i have monitored the network usage of the camera in idle state it in few bytes/secs and when the notification is sent to the app there is no spike in network usage

This does not require any cloud subscription to work

**Comment by JurajNyiri** [comment]
This might work similarly like how auto-tracking works - it can be switched on/off but doesn't work without the subscription.

We will need someone to discover and publicly document a correct network call / subscription to get the state of this as it is not something that is reported via onvif events. After that is available I will be able to add it to pytapo and then here.

**Comment by fredrikhaggbom** [comment]
@anshul10s Are you familiar with using Burp Suite as a proxy for a smartphone? I just used that to discover the calls made  for controlling the "person detection AI feature" available for outdoor cameras. Unfortunately I do not have an indoor camera with the baby cry detection feature (which i guess is located in the "AI detection" category?) and cannot discover the calls made for that feature myself.
FYI, the person detection AI feature works for me without a subscription.

**Comment by anshul10s** [comment]
Thanks @fredrikhaggbom let me Google burpsuite and try it and reference on how to use this tool will be appreciated!

**Comment by fredrikhaggbom** [comment]
@anshul10s Download Burp Suite Community Edition (free) and follow the guide on Portswiggers website:
for Android: https://portswigger.net/burp/documentation/desktop/mobile/config-android-device
for iOS: https://portswigger.net/burp/documentation/desktop/mobile/config-ios-device

Not sure you need to perform the CA certificate step, depends if the mobile app uses https to communicate with the camera. It's a bit easier to do that on an iOS device since Android requires the device to be rooted to install CA certificates.

**Comment by JurajNyiri** [comment]
It is now possible to configure baby crying detection in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.1.0.beta.1 (still no binary sensor).
