### ISSUE TITLE
Feature Request: Set Camera Control Entities to "Hidden" by Default

### ISSUE THREAD

**Issue by david-kalbermatten** [JurajNyiri/HomeAssistant-Tapo-Control#255]
**Is your feature request related to a problem? Please describe.**
Not really a problem, more of a quality of life improvement. Auto-generated dashboards list all the camera controls which is not really sensible.

**Describe the solution you'd like**
Setting an entity to "hidden" excludes it from auto-generated dashboards and from being exposed to stuff like Google Home. My motivation for this request is to remove unwanted entities from the HA App on my smartwatch. Having all the camera control entities associated with a room exposed on the auto-generated dashboards doesn't make a whole lot of sense in my eyes.

**Describe alternatives you've considered**
Setting all unwanted entities to "hidden" by hand.

**Additional context**
[Advanced Properties](https://developers.home-assistant.io/docs/core/entity#advanced-properties)

**Screenshots**
![image](https://user-images.githubusercontent.com/45201085/202902153-e19f50ec-a1c8-4a8a-b0a7-5028be2e8f30.png)
![IMG20221120132337_2](https://user-images.githubusercontent.com/45201085/202901954-5041aa4f-93f4-419a-8c49-76b3bb3b8f2b.jpg)

**Comment by JurajNyiri** [comment]
The question here is what are the unwanted entities? Someone might want to have control for example exposed for PTZ. It can be helpful for new users to see everything in autogenerated dashboard, and advanced users usually do not use autogenerated dashboards.
