### ISSUE TITLE
After upgrade to Firmware: 1.1.22 Build 220725 Rel.60466n(4555), no control or configuration entities work

### ISSUE THREAD

**Issue by LiquidArtist** [JurajNyiri/HomeAssistant-Tapo-Control#256]
### Description

After upgrading to Firmware: 1.1.22 Build 220725 Rel.60466n(4555), all control and configuration entitys are unavailable.

### Reproduction Steps

Go to Settings / Devices & Services / Integrations / Tapo: Camerac control / some ip / 1 device
Controls: 
Press +9 entities not shown
Choose something.
And I get "This entity is unavailable."

Configuration:
Press +12 entities not shown
Choose something.
And I get "This entity is unavailable."

### Expected behavior

I expect to be able to change controls and configuration. Especially "Privacy mode", just like before.

### Device Firmware

1.1.22 Build 220725 Rel.60466n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

No

### HASS Environment

Raspberry 4

### Search for similar issues

Yes

### Additional information

All controls and configurations is like this:
![image](https://user-images.githubusercontent.com/77017773/204089521-a2eaa576-7795-4bd7-a849-afd1fac038f8.png)

**Comment by JurajNyiri** [comment]
What is in the logs?

**Comment by JurajNyiri** [comment]
Did you try restarting?

**Comment by LiquidArtist** [comment]
There was a lot in logs. Once I found the right place. 
After deleting the camera, and adding it again, it started working. 
I apologize for the incorrect problem report.
