### ISSUE TITLE
Bug: Motion Detection is always ON

### ISSUE THREAD

**Issue by RestOp** [JurajNyiri/HomeAssistant-Tapo-Control#26]
C200 cam.
Motion detections sensor goes never OFF.
![image](https://user-images.githubusercontent.com/46259141/95513066-03f6b900-09ba-11eb-8f94-b7d915890f65.png)

Tried to follow https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/20#issuecomment-705798647

**Comment by JurajNyiri** [comment]
Try adding the camera via onvif (port 2020) and see if its sensor work as expected.

For faster debugging join [Discord](https://discord.gg/pa54QyK).

**Comment by RestOp** [comment]
I remember that via ONVIF was the same behaviour! What does it mean for me? 
If we have the same cams, why does they work not the same? )))
I have deleted addon and reinstalled it.
TH motion sensor was not created, i made some movements, the tapo-app showed me that the motion was detected. But the sensor was not created, I restarted HA, but no sensor.

**Comment by JurajNyiri** [comment]
That means that the camera keeps reporting motion via ONVIF even if there is none.

I have 3 C200s and all work well.

As to why, I am not sure. 
- Are you on the latest fw?
- Is there REALLY no movement? Try turning on the lights if its dark and then move around, go away and watch stream.
- Try setting sensitivity to low

Regarding the missing sensor, you just have to give it some time or do what I described [here](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/20#issuecomment-705798647). The more you restart stuff the higher chance the camera will get bugged and will take a while to recover (the process I linked resurrects it).

If it is an option for you, come to discord I linked and I can do some debugging with you.

**Comment by RestOp** [comment]
Sensor has come a little later

FW 1.0.14
HW 1.0
I have no SD card if its matters
Motion detection and notification are turned on
Set sensivity to low, will look, but it doe not matter i think because i get new notifications in app, it means that before to send new one, cam must send off signal

I can discord a little later.

**Comment by RestOp** [comment]
i have pud SD in. Will look.

**Comment by JurajNyiri** [comment]
I am also not using notifications on movement, shouldn't make a difference but worth a try maybe...

**Comment by RestOp** [comment]
> I am also not using notifications on movement, shouldn't make a difference but worth a try maybe...

tried to turn off...

**Comment by JurajNyiri** [comment]
I am closing this as it is not related to this component (behaves the same on onvif).

If you would like help trying to figure this out I can try and help you with app / camera settings on discord.

**Comment by krasatos** [comment]
@RestOp Did you find a solution? I'm having the same issue. 
Both onvif's and Tapo's component sensors are either unavailable or stuck on "detected"

**Comment by RestOp** [comment]
> Both onvif's and Tapo's component sensors are either unavailable or stuck on "detected"

More to say - i have got one c100 and behaviour is the same.
