### ISSUE TITLE
HA 2022.12.2 causes high CPU load

### ISSUE THREAD

**Issue by amaximus** [JurajNyiri/HomeAssistant-Tapo-Control#260]
### Description

On HA 2022.12.2 it causes high CPU load and ffmpeg processes running all the time even if the view for cameras is not the active one. This wasn't the case in 2022.11.x versions.

Cameras: Tapo C310.

### Reproduction Steps

1. Install HA Core 2022.12.1
2. On the dashboard select a view that has no Tapo cameras
3. check the list of processes: the ffmpeg processes associated with the Tapo cameras keep running and consuming a significant amount of CPU.

### Expected behavior

No ffmpeg processes when the active view has no Tapo camera entities.

### Device Firmware

1.3.0 Build 220830 Rel.72368n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HASS Core 2022.12.1

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Make sure to remove stream from your configuration and try to see how the official onvif integration behaves.

**Comment by JurajNyiri** [comment]
https://github.com/home-assistant/core/pull/83795
