### ISSUE TITLE
Noise sensor triggers when privacy mode is activated

### ISSUE THREAD

**Issue by CFenner** [JurajNyiri/HomeAssistant-Tapo-Control#262]
### Description

If I enable the privacy mode, the noise sensor changes to "detected".

### Reproduction Steps

1. wait till no noise is detected.
2. activate privacy mode
3. noise sensor changes to "detected"
4. 

### Expected behavior

noise sensor stays "normal"

### Device Firmware

latest

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HA OS

### Search for similar issues

No

**Comment by JurajNyiri** [comment]
Now fixed in [5.3.0.beta.9.4](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.3.0.beta.9.4).

**Comment by JurajNyiri** [comment]
Fixed in [5.3.0](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.3.0).
