### ISSUE TITLE
Feature Request:  Security level - on Providing password / account

### ISSUE THREAD

**Issue by frank777777** [JurajNyiri/HomeAssistant-Tapo-Control#264]
**Is your feature request related to a problem? Please describe.**

I'm feeling a bit nervous every time i have to share the tapo account password.   ( even if I'm using HA internally - not with remote access  to HA) 

**Describe the solution you'd like**
a  clear description / information explanation on why it is safe - as password are (?) stored ..  and not sent to the developer 

**Describe alternatives you've considered**
none

**Additional context**

**Comment by JurajNyiri** [comment]
The explanation is there, the camera requires it for control, even if it is fully local. Thats how it works.

**Comment by frank777777** [comment]
i really thank you for your reply.  and of course congratulate for this massive works. BTW , it is working 100%
