### ISSUE TITLE
Feature Request: Sensor for Night Vision

### ISSUE THREAD

**Issue by joaopedros2** [JurajNyiri/HomeAssistant-Tapo-Control#266]
Is your feature request related to a problem? Please describe.
No.

Describe the solution you'd like
Creat a sensor to tell when night vision it turns on or off when is in automatic mode.

Additional context
For automations it would be very useful.  For example, when the baby is sleeping the lights are off and the camera switches to night vision on, and at that moment I want to receive notifications if he wakes up in his sleep.  when night vision is off I don't want any notifications.

**Comment by JurajNyiri** [comment]
This is not exposed by the camera.

**Comment by joaopedros2** [comment]
i tried with the frigate integration but there is nothing that evaluates the image is in black and white or in color.  Don't know of anything that can do this?

**Comment by JurajNyiri** [comment]
You could write a python script that opens the image and looks at one specific pixel, which always has color in color mode. If it has rgb values only between black and white, you know its on or not. See https://stackoverflow.com/questions/138250/how-to-read-the-rgb-value-of-a-given-pixel-in-python for example.

**Comment by fanuch** [comment]
This is a problem I'm trying to solve for too.

My case is that my cameras float between "night mode" and not every two second in some cases.
The loud clicking is very very annoying, so I wanted to "check" if it is floating and turn off "auto" for a while as a cool down.

I found this one-liner using `imagemagick` to test if a picture is "colourful" or not:
```
convert $file -colorspace HSL -channel H -separate -unique-colors -format %w info:
````

This has returned `1` on multiple images that are taken from my C210 in night mode, and in random test images it returns anywhere from 91 to over 9000. 

I think it will be safe to turn this into some kind of "command line sensor" to test the cameras.
