### ISSUE TITLE
Unable to connect to Tapo

### ISSUE THREAD

**Issue by migromao** [JurajNyiri/HomeAssistant-Tapo-Control#270]
### Description

After upgrading to the recent Home Assistant Core 2023.1 .there are several occurrences of error:

Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.68.126', port=443): Max retries exceeded

### Reproduction Steps

there are no actions that I'm taking to reproduce the error as I've already updated the custom_component and start fresh and after a while, the error is being shown once again.
if Home assistant is restarted , the error is still be shown and I need to reboot the cameras.
the rtsp stream is still working via webrtc-camera component

### Expected behavior

I would expect no error and te service calls would be working

### If applicable, add error logs.

First occurred: 20:29:52 (230 occurrences)
Last logged: 22:55:42

Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.68.126', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f75d489d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.68.126', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f71809450>: Failed to establish a new connection: [Errno 111] Connection refused')) ... 

### Device Firmware

1.0.17 Build 201111 Rel.74534n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

No

### HASS Environment

HA Core instalation

### Search for similar issues

Yes

### Additional information

I'm able to see the stream (via rtsp) but not able to do any other service call ( move, pan, alarm , motion sensor , etc ...)

**Comment by JurajNyiri** [comment]
Your cameras are overloaded or your network is not stable.

**Comment by migromao** [comment]
thank you for your fantastic work on this

**Comment by JurajNyiri** [comment]
Camera is refusing the connection 

```
Failed to establish a new connection: [Errno 111] Connection refused
```

I can't see a way how HA could affect it.

**Comment by eprompc** [comment]
Any update?
