### ISSUE TITLE
No motion sensor as an entity for Tapo 420

### ISSUE THREAD

**Issue by Pippo1989** [JurajNyiri/HomeAssistant-Tapo-Control#271]
### Description

Hi,

Thanks in advance for your work.

I do not really know if this can be defined as a bug or considered as a feature request, but I am using Tapo 420(S2) cameras in HA and the MOTION SENSOR entity is missing.

Thus, you cannot create any automation using the values of that entity (on/off). Considered that the motion sensor entity is likely the most important one for a camera and its integrability, I think it should be considered as a big issue!

I really hope you can do something for that.

### Reproduction Steps

Simply, motion sensor entity and its attributes won't show in Home Assistant for Tapo 420(S2) camera.

### Expected behavior

Motion sensor entity and its attributes should appear with the camera device when integrated in Home Assistant.

### Device Firmware

1.2.4 Build 20221208 rel.73688

### Using stream component

No

### Does camera work via official integrations?

No

### Camera has all attributes filled out in developer tools

No

### HASS Environment

Raspberry Pi4 + HASSIO

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Not discovered yet.

**Comment by Pippo1989** [comment]
Hi,

Thanks for the quick answer. Do you mean that you have not figured out how
to solve the issue, or else?

Thanks again.


Filippo

Il lun 9 gen 2023, 20:29 Juraj Nyíri ***@***.***> ha scritto:
