### ISSUE TITLE
Feature Request: setting values of MOTION DETECTION entity

### ISSUE THREAD

**Issue by Pippo1989** [JurajNyiri/HomeAssistant-Tapo-Control#274]
**Is your feature request related to a problem? Please describe.**
In Tapo C420 cameras (integrated in Home Assistant), the selectable settings of motion detection entity (high, medium, low, off) won't let you actually choose the correct sensitivity from 0 to 10. I.E., setting "high" in Home Assistant will result in a value of 8 on the Tapo app, and you can't set it higher (as desired).

**Describe the solution you'd like**
The integration should allow you to decide the correct value of motion detection entity (sensitivity) from 0 to 10, in order to properly set an automation.

**Describe alternatives you've considered**
Nothing.

**Additional context**

**Comment by JurajNyiri** [comment]
Now available in [5.3.0.beta.9.5](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.3.0.beta.9.5).

**Comment by JurajNyiri** [comment]
Available in [5.3.0](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.3.0).
