### ISSUE TITLE
Motion Sensor Entity Unavailable 

### ISSUE THREAD

**Issue by GRClark** [JurajNyiri/HomeAssistant-Tapo-Control#277]
### Description

The motion sensor entity is now unavailable saying:  “ This entity is no longer being provided by the tapo_control integration. If the entity is no longer in use, delete it in settings.” but didn’t see anything in the release notes (maybe I missed it) and unsure if it’s just me, my camera model or whether it’s something that can be implemented again as it worked flawlessly up until the latest update.  

### Reproduction Steps

Went to integration, device and listed entities.   

### Expected behavior

Motion sensor entity should be available. 

### Device Firmware

Firmware: 1.3.0 Build 220830 Rel.69880n(5553)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker on Raspberry Pi OS

### Search for similar issues

Yes

### Additional information

Here’s a screenshot of states under developer tools:

![](https://i.imgur.com/VEWWj0V.png)

Here’s under entity info:

![](https://i.imgur.com/2lgQFq7.png)

**Comment by JurajNyiri** [comment]
Hello, Read faq
