### ISSUE TITLE
TAPO C320WS - IP address is not a supported Tapo device

### ISSUE THREAD

**Issue by frank777777** [JurajNyiri/HomeAssistant-Tapo-Control#280]
### Description

Hi, 
Just installed a C320WS - and update latest software . 
on the tapo cameras control  - when inserting the IP , I got the "  IP address is not a supported Tapo device" 
I've already created camera account , and obtained the IP from the TAPO APP - Setting > General IP Address

thanks for help

### Reproduction Steps

go to integration 
select Tapo cameral controls. 
screen : Insert Ip .
Inserting the IP .. 192.xxxx
error
 IP address is not a supported Tapo device!

### Expected behavior

expected that works, as TAPO C320 WS is in the compatible list 

### Device Firmware

1.0.4 Build 221031 Rel 40874n

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

difficult for me . HA -.. and others C100 are working fine

### Search for similar issues

Yes

### Additional information

Other mine  Tapo C100 works fine.

**Comment by JurajNyiri** [comment]
Hello make sure to update to the latest version and restart the camera, it will work.

**Comment by frank777777** [comment]
Thx . I can confirm works now. ( with the latest version of the HACS Tapo camera Controls)

**Comment by jesusperulima** [comment]
Alguien tiene firmware c320v2?

**Comment by jesusperulima** [comment]
Does anyone have c320v2 firmware?
