### ISSUE TITLE
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) 

### ISSUE THREAD

**Issue by Casadomoticap** [JurajNyiri/HomeAssistant-Tapo-Control#281]
### Description

Hi, with the new Home assistant core I have this error in my log page: 

Este error se originó a partir de una integración personalizada.

Logger: custom_components.tapo_control
Source: custom_components/tapo_control/__init__.py:285
Integration: Tapo: Cameras Control (documentation, issues)
First occurred: 11:10:41 (1 occurrences)
Last logged: 11:10:41

('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

### Reproduction Steps

Go to Settings -> Logs 
See the error with title: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) 

### Expected behavior

No error logs for this integration

### Device Firmware

Firmware: 1.3.2 Build 220901

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

OS System

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Nothing that can be done from integration. Go read duplicate issues, basically try to restart camera and limit the amount of sources hitting it.
