### ISSUE TITLE
No person detection enity

### ISSUE THREAD

**Issue by panoskpv** [JurajNyiri/HomeAssistant-Tapo-Control#283]
### Description

I have two cameras, C210 and C310. I have enabled relevant options in app, but no person detection entity is available in HA. Person detection sensitivity is available in HA. Please note that access to internet for both cameras is restricted (if this have anything to do with this problem)

### Reproduction Steps

Have tapo cameras added before latest updates 

### Expected behavior

I guess having one entity for person detection

### Device Firmware

1.3.0 Build 220830 

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

VM in Proxmox server

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Person detection entity is not available.

**Comment by panoskpv** [comment]
So how should I be informed in case a person is detected?

**Comment by JurajNyiri** [comment]
Not through this integration. You could use something like frigate or other NVR with ai detection.

**Comment by panoskpv** [comment]
Excuse me, but I don't really get if. As per  #269 this integration has person detection like move detection, right? Do I miss something?

**Comment by JurajNyiri** [comment]
#269 provided a select entity, a way how to set sensitivity for it
