### ISSUE TITLE
Feature Request: siren entity

### ISSUE THREAD

**Issue by ldotlopez** [JurajNyiri/HomeAssistant-Tapo-Control#284]
**Is your feature request related to a problem? Please describe.**

Implement support for  [siren entity](https://developers.home-assistant.io/docs/core/entity/siren/).

It would be nice and convinient in order to integrate other components from HomeAssistant like 'alarm_panel' or 'alarmo'

**Describe the solution you'd like**
I have implemented the basic stuff but, for unknown reasons, the entity doesn't seems to be added to hass. 
I'm filling this feature request hoping for help in this step. I have read and check code but I can't figure out why it doesn't work.

See: https://github.com/ldotlopez/HomeAssistant-Tapo-Control/tree/wip/siren

**Describe alternatives you've considered**
Buttons for start and stop Tapo alarm are already available and can be reused in the siren entity.

**Comment by JurajNyiri** [comment]
Thank you for your contribution! 

Please open PR draft instead, I can help you out there.
