### ISSUE TITLE
C200 home assistant not showing feed

### ISSUE THREAD

**Issue by willhaggan** [JurajNyiri/HomeAssistant-Tapo-Control#287]
### Description

Camera feed not updating, various resets and power down complete. Got feed to eventually show but not a live feed and not the right orientation .

### Reproduction Steps

Camera feed not updating, various resets and power down complete. Got feed to eventually show but not a live feed and not the right orientation .

### Expected behavior

Camera feed not updating, various resets and power down complete. Got feed to eventually show but not a live feed and not the right orientation .

### If applicable, add error logs.

Camera feed not updating, various resets and power down complete. Got feed to eventually show but not a live feed and not the right orientation .

### Device Firmware

Latest HACS

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Home assistant 

### Search for similar issues

Yes

### Additional information

Camera feed not updating, various resets and power down complete. Got feed to eventually show but not a live feed and not the right orientation .

**Comment by JurajNyiri** [comment]
Provide more information. There is a reason why there are different sections in the template.
