### ISSUE TITLE
Save preset service creates two identical presets instead of one

### ISSUE THREAD

**Issue by pohlond** [JurajNyiri/HomeAssistant-Tapo-Control#293]
### Description

Service tapo_control.save_preset creates two identical presets instead of one. Verified via tapo application. Running on HASS 2023.2.3.

### Reproduction Steps

1. call tapo_control.save_preset
2. presets attribute in camera state contains two identical presets

### Expected behavior

Only one preset is created

### Device Firmware

1.1.16 Build 211209 Rel.37726n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

docker

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
I was not able to replicate this. Could you please try with the latest beta release? What is the service call?

**Comment by pohlond** [comment]
ok, i will try with the latest beta release

**Comment by pohlond** [comment]
I am running the latest beta release now and it seems to be ok
