### ISSUE TITLE
Feature Request: Timelapse feature

### ISSUE THREAD

**Issue by evripidis** [JurajNyiri/HomeAssistant-Tapo-Control#296]
Is your feature request related to a problem? Please describe.
No problem.

Describe the solution you'd like
It would be great to have an integrated solution for a Timelapse, a feature that lacks from the official app too.
For example to be able to set time frame, periodically captures an image file and create a gif or video file.

Describe alternatives you've considered
MJPEG timelapse

**Comment by JurajNyiri** [comment]
Thank you for the suggestion.
You can write a custom script to do it, it is pretty simple and you can probably find something online. This is not something in scope of this integration.

**Comment by nicelight** [comment]
> You can write a custom script to do it, it is pretty simple
Can you help how to google for implement such script?

**Comment by JurajNyiri** [comment]
Look at results here https://www.google.com/search?client=firefox-b-d&q=rtsp+make+timelapse
