### ISSUE TITLE
Feature Request: Turn on or off the Tapo camera control notifications

### ISSUE THREAD

**Issue by nil-ghosh** [JurajNyiri/HomeAssistant-Tapo-Control#298]
**Is your feature request related to a problem? Please describe.**
Option to turn on or turn off Tapo camera notifications to phone from Home Assistant

**Describe the solution you'd like**
A service call to turn on/off notifications 

**Describe alternatives you've considered**
Using the Tapo phone app

**Additional context**
None

**Comment by JurajNyiri** [comment]
Where is this set in the app? Could you provide some screenshots?

**Comment by nil-ghosh** [comment]
Hi. Thanks for your reply. 

The option is available in Camera settings > Detection & Alerts > Activity Notifications 

You can turn it on and off and also set the timings. 

Attached are screenshots. Hope these help. 

![9FC383A1-5F76-4481-B9EF-078FB678EC1A](https://user-images.githubusercontent.com/33167744/225101780-9997e132-2e96-460c-a23c-3c5015f31c17.jpeg)
![F5C6EEF1-C3B6-4E51-B109-70A8100D1CC6](https://user-images.githubusercontent.com/33167744/225101785-3a7c12de-fc93-497a-890a-4e0a6872bfce.jpeg)
![C9E17815-6995-4A97-B5F4-E342108340A1](https://user-images.githubusercontent.com/33167744/225101787-2d771b39-78c3-48c2-91e7-a10e9cc41c95.jpeg)

**Comment by JurajNyiri** [comment]
Once someone discovers and documents the API calls I can add this.

**Comment by AndreiArdelean1** [comment]
##########
`{"method":"multipleRequest","params":{"requests":[{"method":"setMsgPushConfig","params":{"msg_push":{"chn1_msg_push_info":{"notification_enabled":"off","rich_notification_enabled":"off"}}}}]}}`

`{"result":{"responses":[{"method":"setMsgPushConfig","result":{},"error_code":0}]},"error_code":0}`
##########
`{"method":"multipleRequest","params":{"requests":[{"method":"setMsgPushPlan","params":{"msg_push_plan":{"chn1_msg_push_plan":{"enabled":"on","push_plan_1":"0800-2000,127"}}}}]}}`

`{"result":{"responses":[{"method":"setMsgPushPlan","result":{},"error_code":0}]},"error_code":0}`
##########
`{"method":"multipleRequest","params":{"requests":[{"method":"setMsgPushPlan","params":{"msg_push_plan":{"chn1_msg_push_plan":{"enabled":"off","push_plan_1":"0800-2000,127"}}}}]}}`

`{"result":{"responses":[{"method":"setMsgPushPlan","result":{},"error_code":0}]},"error_code":0}`
##########
`{"method":"multipleRequest","params":{"requests":[{"method":"getMsgPushEventList","params":{"msg_push":{"table":["msg_push_event"]}}}]}}`

`{"result":{"responses":[{"method":"getMsgPushEventList","result":{"msg_push":{"msg_push_event":[{"name":"people_detection","enabled":"on"},{"name":"vehicle_detection","enabled":"on"},{"name":"pet_detection","enabled":"on"},{"name":"sound_detection","enabled":"on"},{"name":"bark_detection","enabled":"on"},{"name":"meow_detection","enabled":"on"},{"name":"glass_detection","enabled":"on"},{"name":"alarm_detection","enabled":"on"},{"name":"motion_detection","enabled":"on"},{"name":"tamper_detection","enabled":"on"},{"name":"linecrossing_detection","enabled":"on"}]}},"error_code":0}]},"error_code":0}`
##########
`{"method":"multipleRequest","params":{"requests":[{"method":"setMsgPushEventList","params":{"msg_push":{"msg_push_event":[{"name":"pet_detection","enabled":"on"},{"name":"sound_detection","enabled":"off"},{"name":"linecrossing_detection","enabled":"off"},{"name":"people_detection","enabled":"on"},{"name":"meow_detection","enabled":"on"},{"name":"vehicle_detection","enabled":"on"},{"name":"glass_detection","enabled":"on"},{"name":"motion_detection","enabled":"on"},{"name":"tamper_detection","enabled":"on"},{"name":"bark_detection","enabled":"on"}]}}}]}}`

`{"result":{"responses":[{"method":"setMsgPushEventList","result":{},"error_code":0}]},"error_code":0}`
##########

**Comment by Tockerz** [comment]
The app has an "Away Mode" and "Home Mode" under the Camera tab that would do this with one click and would be super handy in HA. This allows you to define the notificaiton and detection settings for each camera for each "mode".
E.g. Home = no notificaitons, person detection only. Away = all detection on, notifications on.

**Comment by JurajNyiri** [comment]
You can replicate home / away mode via the HA script / automations. There is no way how to trigger the button as it calls all the functions manually. Marking as offtopic as it is not related to this discussion.

**Comment by antstyl** [comment]
Just as an update.. is there any possibility to be added in the future or not in your plans at all?
thanks

**Comment by JurajNyiri** [comment]
I do plan to add this.

**Comment by JurajNyiri** [comment]
Now available in [Beta 4.](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.3.0.beta.4).

**Comment by JurajNyiri** [comment]
Available in [5.3.0](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.3.0).

**Comment by nil-ghosh** [comment]
Great work!! Let me try it. Thanks
