### ISSUE TITLE
C210 controls and other settings not working

### ISSUE THREAD

**Issue by lordraiden** [JurajNyiri/HomeAssistant-Tapo-Control#305]
### Description

Many controls and configuration options are grayed out

![imagen](https://user-images.githubusercontent.com/17175395/230354040-2c0a738d-6d4e-4d19-b2f6-f88697f2ce6e.png)
![imagen](https://user-images.githubusercontent.com/17175395/230354099-21482fb6-c8ae-49eb-8d45-84319f77ea34.png)

Is this normal? I remember some of them where working in the past because I have configurations based on them? could this be due to a firmware upgrade?

### Reproduction Steps

.

### Expected behavior

.

### Device Firmware

1.3.0 Build 220830 Rel.69909n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Check and send logs. This is expected if camera is probably available or reachable by HA.
