### ISSUE TITLE
Recording Avalible After an Hour

### ISSUE THREAD

**Issue by AnzeSI** [JurajNyiri/HomeAssistant-Tapo-Control#317]
### Description

When the camera creates a recording it is visible in the media player, but cannot be downloaded for an hour after the recording stopped. The error "Recording in progress" is shown. After an hour elapses, the recording can be downloaded.

### Reproduction Steps

- Set up the camera so that it records videos on an SD card when the motion is detected.
- Connect the camera to the integration.
- Trigger motion detection on the camera.
- Wait for the camera to stop recording (about a minute).
- Go to the media player and try to download the recording that was just created.
- The error "Recording in progress" is shown
- Wait for an hour
- Try to download the recording again
- Recording downloads and is available to play.

### Expected behavior

The recording should be available for download immediately after the camera stops recording. 

### Device Firmware

1.3.0 Build 220830 Rel.74146n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

RP4

### Search for similar issues

Yes

### Additional information

Camera type: Tapo C320WS
Integration version: 5.1.1

**Comment by thomasramm** [comment]
Try to disable the time sync in Tapo Control:configuration.
see #307.
maybe your cam is internaly one hour in the future. 
If you disable time sync in HA you still have to set the correct time back on your cam.

**Comment by JurajNyiri** [comment]
This is not related to above, there is no need to disable time sync and it will probably not help, fix needs to happen in this integration.

**Comment by AnzeSI** [comment]
I tried with time sync off and there was no difference. The time on camera was correct before, so I did not change it. There is a timestamp in the upper left corner of the video and is always correct.

**Comment by Casadomoticap** [comment]
I have the same problem, someone know how to solve it? Or we need to wait for a new release of the integration?

**Comment by JurajNyiri** [comment]
It will require change both in pytapo to accept the current time and this intregration to calculate it properly (similarly to how it is calculated on listing recordings). It will be done when I get to it or someone creates a working PR.

**Comment by JurajNyiri** [comment]
Fixed in 5.2.4.

**Comment by whitty** [comment]
Sorry to dead-post here, but I think this is causing me issues at the moment with 5.4.12, I thought syncing was just "very slow", but now I think this explains some of my issues, (though it is hidden by occasional pauses in the syncing process where it stops syncing until I reload the integration).  I'm going to gather up logs and details and open a new issue when I have something more helpful to say.

PS - I'm in the southern hemisphere so the `dst` code is back in play.

**Comment by cbh** [comment]
This is still happening
