### ISSUE TITLE
Integration incompatible with latest HASS stable 2023.4.6

### ISSUE THREAD

**Issue by r33int** [JurajNyiri/HomeAssistant-Tapo-Control#324]
### Description

Hello,

I am trying to install this integration using HACS, but it requires minimum version 2023.5.0.

You are running Home Assistant version '2023.4.6', but this repository requires minimum version '2023.5.0' to be installed.

I see that 2023.5.0 is still in beta. Release 5.1.3 states that it is compatible with 2023.5.0, but is it expected to be a minimum requirement? Is there any way to install the latest version of the integration on 2023.4.6?

When I click download, it spins forever and nothing ever happens.

Thank you for your help!

### Reproduction Steps

- Go to HACS
- Look for Tapo intergration and try to install it
- Download takes forever and error message showing that integration is incompatible.

### Expected behavior

Integration being compatible and installing properly on latest stable version

### If applicable, add error logs.

You are running Home Assistant version '2023.4.6', but this repository requires minimum version '2023.5.0' to be installed.

### Device Firmware

1.3.3 Build 230228 Rel.79740n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Hass OS

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Yes that is correct. Use 5.1.2 with april release of HA.
