### ISSUE TITLE
Can't configure on HA 2023.5.0

### ISSUE THREAD

**Issue by andrenarchy** [JurajNyiri/HomeAssistant-Tapo-Control#329]
### Description

I updated HA to 2023.5.0 and then the tapo_control integration to 5.1.7. My existing configuration didn't work and removing didn't work immediately either but eventually it did. Now I'm trying to create a new configuration but I get the error `Config flow could not be loaded: {"message":"Invalid handler specified"}`:
![image](https://user-images.githubusercontent.com/1874116/236156888-c433e002-3646-425b-ad5c-e14482170562.png)

In the logs I see this:
```
2023-05-04 08:52:29.686 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration tapo_control: cannot import name 'NotificationManager' from 'onvif.client' (/config/deps/lib/python3.10/site-packages/onvif/client.py)
```

### Reproduction Steps

1. Go to Settings -> Integrations -> Add Integration -> Tapo: Cameras Control
2. Error

### Expected behavior

It should show the config screen.

### Device Firmware

1.1.21

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker in k8s

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Make sure to clear cache or try in incognito.

**Comment by andrenarchy** [comment]
I tried several times but it turns out that the dependencies of the integration were outdated. After uninstalling I ran
```
rm -rf ffmpeg* onvif* pytapo*
```
in `config/deps/lib/python3.10/site-packages` and reinstalled. Now it's working fine.
