### ISSUE TITLE
c320ws motion detection works after restart but stops getting events after 12-24h

### ISSUE THREAD

**Issue by allankosowan** [JurajNyiri/HomeAssistant-Tapo-Control#332]
### Description

I was previously having trouble with the camera detecting motion events since maybe March.  I believe it was the onvif subscription existing bug.  No amount of restarts of camera nor HA would resolve it.  But I upgraded to tapo integration 5.1.2 and motion detection worked again. 

But I have a new issue.  The camera does work for 12-24 hours with motion events triggering  recordings via automations,   but then stops triggering events.

### Reproduction Steps

1. Restat HA
2.observe motion detection events for several hours while also receiving phone notifications from tapo app
3. After a while. Detection events stop being recognized while tapo app continues receiving them.

### Expected behavior

Detection events should continue to be received in HA.

### If applicable, add error logs.

No related logs.  I enabled tapo integration debug logs and will add if anything shows up.

### Device Firmware

1.3.0

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

windows VM running HAOS

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Specify firmware, integration version and Home Assistant version please.

**Comment by JurajNyiri** [comment]
Issue is upstream, might be fixed by https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/pull/333#pullrequestreview-1415073531 .

**Comment by allankosowan** [comment]
> Specify firmware, integration version and Home Assistant version please.

Firmware 1.3.1
Tapo integration 5.1.2
HA 2023.4.6
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230411.1 - latest

**Comment by JurajNyiri** [comment]
Issue has now been fixed in [5.2.0](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.2.0).

**Comment by allankosowan** [comment]
So far so good.  Using version 5.2.1 and it survived overnight without dropping motion events.   🙏
