### ISSUE TITLE
Motion detection triggers on camera reboot if privacy mode is enabled

### ISSUE THREAD

**Issue by twisterss** [JurajNyiri/HomeAssistant-Tapo-Control#341]
### Description

On C200 camera reboot (whether manual or during a daily automatic reboot configured in the tapo app), if privacy mode was enabled, the motion detection sensor triggers and then remains "detected" until next Home Assistant reboot

### Reproduction Steps

1. Make sure the camera motion detection sensor exists (by triggering a first detection) and then wait for the sensor to go back to "not triggered"
2. Enable the "Privacy" option of the camera
3. Click on "Reboot" to reboot the camera
4. Wait until the camera is fully rebooted
5. The motion detection triggers and then remains triggered until next Homev Assistant reboot

### Expected behavior

The motion detection should not trigger on reboot.

### Device Firmware

1.3.4 Build 230424 Rel.76394n(4555)

### Using stream component

No

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

2023.5.2 Docker on Ubuntu

### Search for similar issues

Yes

### Additional information

This is new since a few days (I recently got updates for the cameras, for HASS and for the tapo integration)
This happens whatever the Motion Detection configuration value (tested off and normal)
I can make further tests if necessary.

(and thank you for this awesome integration :) )

**Comment by Write** [comment]
Can confirm. Personally it stays as detected until first actual motion is detected. Haven't tried an ha reboot yet.

**Comment by JurajNyiri** [comment]
Could you please verify if this behaviour happens with https://www.home-assistant.io/integrations/onvif/ ? It might need to be fixed upstream as this integration is using HA onvif for events.

**Comment by Dielee** [comment]
@JurajNyiri how can we verify this ? For me this happens, too.

**Comment by Write** [comment]
> Could you please verify if this behaviour happens with https://www.home-assistant.io/integrations/onvif/ ? It might need to be fixed upstream as this integration is using HA onvif for events.

Yes, same for ONVIF

**Comment by JurajNyiri** [comment]
In that case please open issue on home assistant Onvif. Once it is fixed there it will be fixed here.
