### ISSUE TITLE
Tapo camera entities are disabled automatically

### ISSUE THREAD

**Issue by ArchiRavi** [JurajNyiri/HomeAssistant-Tapo-Control#342]
### Description

Hello, I have followed the installation and even updated the Tapo controller to the latest version available. After adding the Tapo camera devices, the devices are going to a disabled state, I tried enabling but it did not work. any help here, please? 

### Reproduction Steps

Install Tapo Controller
Update to latest version
Connect Tapo camera C200, C210 and C100

### Expected behavior

They should be visible 

### Device Firmware

1.3.0

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Tapo App

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Check logs, it gets disabled when there is network issue.
