### ISSUE TITLE
Motion detection has stopped working with home assistant.

### ISSUE THREAD

**Issue by Fredrichl** [JurajNyiri/HomeAssistant-Tapo-Control#345]
### Description

The motion detection has stopped working on my tapo c200 after working flawlessly for some time.
I have updated the integration in hacs, i have restarted the camera, i have restarted Home assistant. I get detection notices in the tapo app, but they dont seem to get thru to HA.

### Reproduction Steps

It has stopped working alltogether.

### Expected behavior

I had it set up so it took photos and saved them, and sent via a telegram bot. This has been working since i bought the camera but stopped last week.

I can run the automations manually and they work, but it no longer functions automatically.

### Device Firmware

1.3.4 Build 230424 Rel.76394n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Hassio on raspberry pi 3b

### Search for similar issues

Yes

**Comment by Fredrichl** [comment]
When i looked into the motion detection there's a message:
"Denna enhet tillhandahålls inte längre av tapo_control -integrationen. Om enheten inte längre används, radera den i inställningarna."

Which translates to "This entity is no longer provided by the tapo_control integration. If the device is no longer in use, delete it in the settings."

**Comment by JurajNyiri** [comment]
Read [FAQ](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control#troubleshooting--faq).

Also https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/347, https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues?q=is%3Aissue+is%3Aclosed+motion .
