### ISSUE TITLE
Bug: Updated to OS v4.15 and lost motion entity

### ISSUE THREAD

**Issue by Taomyn** [JurajNyiri/HomeAssistant-Tapo-Control#35]
**Describe the bug**
I just upgraded from OS v4.14 to v4.15 and now HA reports that the motion entity is lost and orphaned.

Have tried HA restart and host reboot, and no change.

I cannot find anything logged anywhere so cannot give any extra info unless there is somewhere else to look.

![image](https://user-images.githubusercontent.com/4365929/96735201-9a17df80-13bb-11eb-9324-e647d156f2b3.png)

![image](https://user-images.githubusercontent.com/4365929/96735339-c3387000-13bb-11eb-9e33-df1588c56d0c.png)

**Comment by JurajNyiri** [comment]
I am not yet able to update to the newest OS. Are the sensors still missing after doing steps in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control#troubleshooting ? It might take some time for the sensor to appear.

**Comment by Taomyn** [comment]
Yes, none of that worked so I reported it here, but having left it alone overnight and also switched the camera from normal to detection-only a couple of times, it's back again.

I'll close this one as just something weird or bad timing, and thanks for help.
