### ISSUE TITLE
Feature Request: service for video download

### ISSUE THREAD

**Issue by Eyco1981** [JurajNyiri/HomeAssistant-Tapo-Control#353]
**Is your feature request related to a problem? Please describe.**
Downloads of video footages are only performed, if they are viewed in the media browser.

**Describe the solution you'd like**
A service to download footages would enable us to use automations for that. That way we could use HA as a kind of NVR.

**Describe alternatives you've considered**
I considered using NVR add-ons like motionEye or Frigate. But on a HA Yellow CPU usage would be too high or a Coral TPU isn't working reliably.

**Additional context**

**Comment by esistgut** [comment]
can this be done with some kind of work around?

**Comment by JurajNyiri** [comment]
https://github.com/JurajNyiri/pytapo#downloading-recordings

**Comment by JurajNyiri** [comment]
Media Sync is now available in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.3.0.beta.1 .
