### ISSUE TITLE
Errors after updating to version 5.2.3

### ISSUE THREAD

**Issue by Joralmo** [JurajNyiri/HomeAssistant-Tapo-Control#354]
### Description

I'm encountering a couple of errors after updating to version 5.2.3 of the integration. 

Here are the specific error messages I've been getting:

Error occurred loading flow for integration tapo_control: cannot import name 'Downloader' from 'pytapo.media_stream.downloader' (/usr/local/lib/python3.10/site-packages/pytapo/media_stream/downloader.py)
Timestamp: 14:43:20 – Error source: config_entries.py

Setup failed for custom integration tapo_control: Unable to import component: cannot import name 'Downloader' from 'pytapo.media_stream.downloader' (/usr/local/lib/python3.10/site-packages/pytapo/media_stream/downloader.py)
Timestamp: 14:37:50 – Error source: setup.py

These issues arose immediately following the update to the latest version of the integration. 

Any assistance in troubleshooting these issues would be greatly appreciated!

## System details:

- Integration version: 5.2.3
- Home Assistant 2023.5.4
- Python version: 3.10
- Operating System: Raspberry pi 3

Thank you in advance!

### Reproduction Steps

- Update the last version of integration
- Reboot

### Expected behavior

Can see the hd stream of cameras

### Device Firmware

1.3.4 Build 230424 Rel.76394n(5553)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Raspberry Pi 3

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Looks like incorrect dependencies, make sure to properly install this integration and pytapo dependency.

**Comment by Joralmo** [comment]
I have downloaded the latest version, 5.2.3, how do I check or update pytapo? according to the manifest.json I have the version that you mention :/

**Comment by JurajNyiri** [comment]
That depends on your environment. What OS are you running?

**Comment by Joralmo** [comment]
I am using the home assistant operating system installed on a raspberry pi 3
