### ISSUE TITLE
Error in logs" Updating tapo_control camera took longer than the scheduled update interval"

### ISSUE THREAD

**Issue by confuserated** [JurajNyiri/HomeAssistant-Tapo-Control#355]
### Description

Updating tapo_control camera took longer than the scheduled update interval 0:00:30
and
Update of camera.tapo_camera_7c0c_hd_stream is taking over 10 seconds
and 
Update of siren.tapo_camera_115c_siren is taking over 10 seconds
and more similar

These errors have many thousands of entries against my Tapolink TC70 cameras, is it something I should be concerned about or something that I can get rid of with a config change or similar?

### Reproduction Steps

No steps needed, it just occurs all the time

### Expected behavior

Hoping not to see so many errors

### Device Firmware

Firmware: 1.1.22 Build 220725 Rel.75119n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HASSIO

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
This happens if the camera takes longer to 10 seconds to respond. Check ping to camera and your network, if everything works it can be ignored.

**Comment by confuserated** [comment]
hi, thanks for the response, is it possible to increase the timeout in config?

**Comment by jrhansen** [comment]
I see these errors in the journal as well (2 lines every 30 seconds):

```
Apr 27 01:58:01 lhserver homeassistant[1097]: 2024-04-27 01:58:01.835 WARNING (MainThread) [homeassistant.components.sensor] Updating tapo_control sensor took longer than the scheduled update interval 0:>
Apr 27 01:58:01 lhserver homeassistant[1097]: 2024-04-27 01:58:01.833 WARNING (MainThread) [homeassistant.components.camera] Updating tapo_control camera took longer than the scheduled update interval 0:>
```

The network and the cameras (ping 3 ms) are fine not busy doing anything. I don't think log flooding should be ignored. Is there any way to turn off logging to the systemd journal, if these messages truly can be ignored?

Thanks in advance! :-)
