### ISSUE TITLE
2 Cameras C500 HD Stream failure

### ISSUE THREAD

**Issue by jruibarroso** [JurajNyiri/HomeAssistant-Tapo-Control#357]
### Description

I had installed at first one Tapo C500 on Home assistant and everything went ok. Next day, bought another C500 camera, add it to integration and also went ok.
Some hours later, first camera fails HD stream, only SD stream works. Removed it from integration, add it again, same problem.. 2nd camera working ok all this time.. Today, bought a 3rd camera, thinking 1st camera had some issue, add it to integration, 2 cameras streaming ok !! Great, i thought... some hours ago, this last camera bought today, fails HD Stream again :-( ... 

### Reproduction Steps

no errors

### Expected behavior

2 or more cameras streaming HD or SD without issues.

### If applicable, add error logs.

no logs - no errors

### Device Firmware

1.0.4

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Home Assistant 

### Search for similar issues

Yes

**Comment by jruibarroso** [comment]
if I reboot Home Assistant camera works ok again

**Comment by JurajNyiri** [comment]
Hi, all this integration does regarding cameras is informs Home Assistant about the rtsp stream address. I recommend looking into camera limitations (there is a maximum number of concurrent streams), verifying the stream works and looking into logs. Closing as not an issue of integration.
