### ISSUE TITLE
Cannot import Downloader 

### ISSUE THREAD

**Issue by giovannipinna1** [JurajNyiri/HomeAssistant-Tapo-Control#358]
### Description

After updating to home assistant OS 10.3 when initializing the integration this error appears.
The entities cannot be deleted and this prevents a reinstall of the integration. 

Logger: homeassistant.setup
Source: setup.py:215
First occurred: 10:28:03 AM (1 occurrences)
Last logged: 10:28:03 AM

Setup failed for custom integration tapo_control: Unable to import component: cannot import name 'Downloader' from 'pytapo.media_stream.downloader' (/usr/local/lib/python3.11/site-packages/pytapo/media_stream/downloader.py)

### Reproduction Steps

Update to theatest 10.3 home assistant os.
Reboot and the integration will look not_loaded with the error above in the logs as a cause.

### Expected behavior

This error shouldn't appear and the integration should load correctly

### If applicable, add error logs.

Logger: homeassistant.setup
Source: setup.py:215
First occurred: 10:28:03 AM (1 occurrences)
Last logged: 10:28:03 AM

Setup failed for custom integration tapo_control: Unable to import component: cannot import name 'Downloader' from 'pytapo.media_stream.downloader' (/usr/local/lib/python3.11/site-packages/pytapo/media_stream/downloader.py)

### Device Firmware

1.3.4 Build 230424 Rel.76394n(4555)

### Using stream component

No

### Does camera work via official integrations?

No

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Haos

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Your installation or environment is corrupted or incorrectly set up. make sure to install the latest version of both integration and pytapo. Reinstall might help.
