### ISSUE TITLE
This entity is no longer being provided by the tapo_control integration. If the entity is no longer in use, delete it in settings.

### ISSUE THREAD

**Issue by nunorios** [JurajNyiri/HomeAssistant-Tapo-Control#361]
### Description

Since two days ago, I'm getting this error on HomeAssistant - Tapo: Cameras Control "This entity is no longer being provided by the tapo_control integration. If the entity is no longer in use, delete it in settings." and the streaming is no longer available. can you help me to solve this?

I'm using C200 cameras, firmware version 1.3.6 and Home Assistant 2023.6.3 Supervisor 2023.06.2 Operating System 10.3 Frontend 20230608.0 - latest 

Thanks 

Nuno

### Reproduction Steps

N/A

### Expected behavior

stream available

### If applicable, add error logs.

Logger: custom_components.tapo_control
Source: custom_components/tapo_control/__init__.py:494
Integration: Tapo: Cameras Control ([documentation](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control), [issues](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues))
First occurred: 10:06:17 AM (44 occurrences)
Last logged: 10:15:36 AM

    Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.1.147', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5fe64cd0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
    Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.1.150', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5ff2bbd0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
    Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.1.149', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5ffaa010>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
    Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.1.148', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5f762b90>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
    Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.1.147', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f60cd7b50>: Failed to establish a new connection: [Errno 113] Host is unreachable'))

### Device Firmware

firmware version 1.3.6 

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Operating System 10.3

### Search for similar issues

Yes

**Comment by nunorios** [comment]
Although I reserved the ip's on the router, after an issue, Vodafone reset my router and the cameras tooked another ip

**Comment by Homeassistant60** [comment]
Bonjour j'ai le même problème,  mais mon adresse IP n'a pas changé.  
Que faire ?

**Comment by raespanha** [comment]
I'm facing the same issue since a couple of days ago. 
I have the same message and I can't configure the camera again (even after  I deleted the previous one). 
I already checked the router to see if my camera was in the same IP , and it is.
Everything remains the same
