### ISSUE TITLE
Offline device causes issues with other integrations

### ISSUE THREAD

**Issue by Eilivers** [JurajNyiri/HomeAssistant-Tapo-Control#366]
### Description

I have 3 P100 plugs added through Tapo Control integration, one of them is unplugged and offline. But the Tapo integration continuously tries to connect to the last one, and in the process making the communication with WLED API super slow/unstable.

### Reproduction Steps

1. Add a smart plug to HA
2. Take the plug offline
3. Look at the Supervisor logs for
`Failed to setup Error communication with API: Cannot connect to host <ip:port> ssl:default [Connect call failed ('<ip:port>)]
Failed to setup Error communication with API: Cannot connect to host <ip:port> ssl:default [Network unreachable]
`
4. Disable smart plug in integration, logs disappear and other integrations work fine again.

### Expected behavior

I want the Tapo integration to poll less if the device is not online.

### If applicable, add error logs.

[update_coordinator.txt](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/files/12027144/update_coordinator.txt)
[custom_components.tapo_control.__init__.txt](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/files/12027145/custom_components.tapo_control.__init__.txt)
[wled_logs.txt](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/files/12027163/wled_logs.txt)

### Device Firmware

1.1.5 Build 230324 Rel.143956

### Using stream component

No

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

No

### HASS Environment

N/A

### Search for similar issues

Yes

### Additional information

Added the logs i got for WLED until i disabled the offline Tapo plug in integration.

**Comment by JurajNyiri** [comment]
Wrong repo. This one is for cameras.
