### ISSUE TITLE
Motion sensor unavailable 

### ISSUE THREAD

**Issue by robkarpati** [JurajNyiri/HomeAssistant-Tapo-Control#369]
### Description

All of my sensors working fine, only the motion sensor is unavailable. I can setup at the configuration part but no sensor at the sensors part.
Is it possible to use the motion sensor of my camera in your integration anyhow? 
Thanks a lot!

### Reproduction Steps

checking in the integration

### Expected behavior

no motion sensor

### Device Firmware

1.3.6

### Using stream component

No

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

core

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Read FAQ.
