### ISSUE TITLE
Bug: Long delay

### ISSUE THREAD

**Issue by kolisko** [JurajNyiri/HomeAssistant-Tapo-Control#37]
**Describe the bug**
The live stream on dashboard has long delay, about 7 seconds.

**To Reproduce**
Using 'Camera control example' by Roman Kaporin in EXAMPLES_LOVELACE.md

**Expected behavior**
Shorter delay

**Log**
No errors

**Camera (please complete the following information):**
 - Device Model: C200
 - FW: 1.0.14

**Using stream component**
no

**Camera works through onvif component OR different cameras work in general**
- Another mjpeg camera works fast from HA
- Accessing c200 from vlc rtsp is OK, also using over ffmpeg from HA is OK

**Camera has all attributes filled out properly in developer tools**
[yes/no - provide more info]

**HASS Environment**
Docker

**Comment by JurajNyiri** [comment]
This affects many cameras on Home Assistant and is a known issue. 
This component uses the native stream / ffmpeg module provided by HASS so nothing I could do on a component side to improve the delay.

**Comment by MikaJaask** [comment]
Still way too delay on Tapo cameras control.
Please improve it.
