### ISSUE TITLE
Corrupted image with Snapshot service.

### ISSUE THREAD

**Issue by jasimancas** [JurajNyiri/HomeAssistant-Tapo-Control#370]
### Description

I have an automation, when a door opens a snapshot is made and then a video, with the video I have no problem, but randomly (6 out of 10) appear as the image below with the snapshot.

![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/15717847/d16fccae-0e92-43fc-a3f4-af3ab4cd12f2)

### Reproduction Steps

Start camera.snapshot service with the HD Camera Stram in the parameter.
Save picture in /www/picture.jpg

### Expected behavior

The image looks clear, I use the HD stream.

### Device Firmware

1.3.3 Build 230228 Rel.79740n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HassOS

### Search for similar issues

Yes

### Additional information

I have tried both HD and SD, and both native stream and HA stram, same result.

**Comment by JurajNyiri** [comment]
This is handled the same way as in ha. There is not much we can do here unless you find it working well with HA native integrations for camera streams.
