### ISSUE TITLE
Tapo C320WS. Siren does not work

### ISSUE THREAD

**Issue by plallana** [JurajNyiri/HomeAssistant-Tapo-Control#373]
### Description

I have two Tapo C320WS cameras integrated in my Home Assistant. 
Siren control does not work. Replies: 
   Failed to call service siren/turn_on. Error: Parameter to get/do does not exist, Response: {"error_code": -40106}
Manual alarm (start or stop) does not work either.
Other Tapo cameras (C110 and C310) work great with the siren integration.
HACS for TAPO is up to date.

### Reproduction Steps

1. Go to Settings. Devices & Services. Tapo cameras control.
2. Inside Control box, play on/off Siren. Does not work.

 
![Control](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/117858476/9b01e4a6-2299-424b-b65f-43ebf97068e8)

### Expected behavior

The Siren should sound. 

### Device Firmware

1.0.5 Build 230316 Rel.55457n

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Raspberry Pi

### Search for similar issues

Yes

**Comment by plallana** [comment]
Hi Juraj,
Thank you for answering so fast.
I don't understand the question.
Are you referring to the Tapo app on the cell phone?
I have the Tapo App installed in my cell (android), and there is not any
button related to noises, or sounds or something else.

Regards,
   Pedro

**Comment by JurajNyiri** [comment]
This function is not officially supported via the app, so it is possible this camera simply does not support it. We also cannot detect it without trying to use it automatically at start, which is of course something we cannot do.

**Comment by plallana** [comment]
Now I am experiencing the issue #362 (C320WS goes offline) in both C320WS cameras. It doesn't make sense to continue with this thread without first solving the issue #362. 
First of all I am going to remove this integration from Home Assistant and hope that the cameras will work again in their android native app. With Tapo C310, also connected via ethernet and also integrated into Home Assistant,  I have never had any problem.

**Comment by JurajNyiri** [comment]
Marking this as Wontfix. Unfortunately there is no way how to automatically detect the support for this functionality.

We could exclude the camera so that the entity does not appear at all, but if it is added in the future, or worked in older firmwares it would still stay excluded which is worse than current functionality. Feel free to disable the entity.
