### ISSUE TITLE
Bug: Services Enable/Disable Motion Detection inverted

### ISSUE THREAD

**Issue by rodrigogbs** [JurajNyiri/HomeAssistant-Tapo-Control#38]
**Describe the bug**
The services "camera.enable_motion_detection" and "camera.disable_motion_detection" are inverted, when calling "camera.enable_motion_detection" the motion detection turns OFF, and when calling "camera.disable_motion_detection" the motion detection turns ON.

**To Reproduce**
1. Go to 'Developer Tools -> Services'
2. Run service 'camera.enable_motion_detection' with parameters 'name of your camera'
3. See that motion_detection was turned OFF
4. Run service 'camera.disable_motion_detection' with parameters 'name of your camera'
5. See that motion_detection was turned ON

**Expected behavior**
When calling "camera.enable_motion_detection" the motion detection must turn ON, and when calling "camera.disable_motion_detection" the motion detection must turn OFF.

**Log**
Not applicable.

**Camera (please complete the following information):**
 - Device Model: Tapo C200
 - FW: 1.0.16 Build 200930 Rel.26253n(4555)

**Using stream component**
[no]

**Camera works through onvif component OR different cameras work in general**
[yes]

**Camera has all attributes filled out properly in developer tools**
[yes]

**HASS Environment**
[default HASSIO on a raspberry pi4]

**Additional context**
Not applicable.

**Comment by vks007** [comment]
yep, I too noticed this.

**Comment by JurajNyiri** [comment]
Thank you for the bug report, fixed in 2.2.2.

**Comment by vks007** [comment]
Thanks, it works fine now.

**Comment by rodrigogbs** [comment]
Now it’s working well, thanks!
