### ISSUE TITLE
Feature Request: Binary Sensor for night mode

### ISSUE THREAD

**Issue by joewashear007** [JurajNyiri/HomeAssistant-Tapo-Control#380]
**Is your feature request related to a problem? Please describe.**
I am wanting to measure the power used by my tapo camera, so it can be auto discovered by the power_calc home assistant custom component. I have measured the power, there is a very clear change in power when the night mode is active as can be seen below

![Screenshot_20230812-071704.png](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/3577785/db6ee0fb-ed6e-4295-a303-3852c5052f94)

**Describe the solution you'd like**
Is it possible to expose the night mode/infrared light on as a binary sensor? This way the power calculation could be reliable determined. 

**Describe alternatives you've considered**
N/A

**Additional context**

Linked Issue: https://github.com/bramstroker/homeassistant-powercalc/issues/1763#issuecomment-1675794391

**Comment by Nafania** [comment]
Plus one but the reason is completely different :) Im using frigate with tapo cameras. At night firgate hardly recognizes some things, but frigate has the option to improve the contrast of images. The thing here

**Comment by joaopedros2** [comment]
I come to ask but for different reasons.

When in night vision mode, it activates notifications when my kids are asleep.

The only way I managed to solve this was by using Node-RED + Snapshot to check whether the image is in color or not.

**Comment by JurajNyiri** [comment]
I looked into this, currently we have nothing in the data that would signify whether night vision (IR) is on or off from the camera itself.

Is this reported anywhere inside the app?

**Comment by Nafania** [comment]
No, there is no clear indicators in the app as well, I thought it might be reported somewhere in the api

**Comment by JurajNyiri** [comment]
Closing as this is impossible to implement because app does not support this.

**Comment by Aegeontis** [comment]
Hey, just wanted to offer a workaround solution. Create a (homeassistant or bash) script with the following steps:
1. Store a snapshot of the relevant camera as a file somewhere
2. Use this python script to determine whether the image is black-and-white or colored. You could also probably do the same with other tools such as ImageMagick: ```from PIL import Image; img = Image.open("<file_path>" ).convert("RGB"); print("on" if all(p[0] == p[1] == p[2] for p in img.getdata()) else "off")```
4. Store the output of that script (or modify to use the exit code, etc)
5. Use that to toggle an input_boolean in homeassistant
