### ISSUE TITLE
Feature Request: Change sort order of Tapo Recordings

### ISSUE THREAD

**Issue by fabermundi** [JurajNyiri/HomeAssistant-Tapo-Control#383]
**Is your feature request related to a problem? Please describe.**
Hello, the recordings the integration gets from my Tapo C200 in the media folder are sorted by date ascending (oldest folder first). Is it possible to reverse this order (or make it customizable) as I think the most common use case is to enter the newest folder and at the moment one has to scroll down through all the recording to get it.

**Describe the solution you'd like**
Change the sorting order of the recordings folder or make it cutomizable.

**Describe alternatives you've considered**
Scrolling through all the folders to get the newest one.

Thank you

**Comment by JurajNyiri** [comment]
Available now in [5.3.0.beta.10](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.3.0.beta.10).

**Comment by JurajNyiri** [comment]
<img width="380" alt="Screenshot 2023-08-19 at 11 57 35" src="https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/5785999/5935f411-434c-42fc-9cbf-f53951207793">

**Comment by JurajNyiri** [comment]
Available in [5.3.0](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.3.0).
