### ISSUE TITLE
Failed to call service Tapo_control/ptz. Service not found 

### ISSUE THREAD

**Issue by apnaf** [JurajNyiri/HomeAssistant-Tapo-Control#385]
### Description

I have the following picture glace card configuration:

camera_view: live
type: picture-glance
title: Entrada
entities:
  - entity: camera.patio_entrada_sd_stream
    icon: mdi:arrow-left-drop-circle-outline
    tap_action:
      action: call-service
      service: tapo_control.ptz
      service_data:
        entity_id: camera.patio_entrada_sd_stream
        pan: LEFT
  - entity: camera.patio_entrada_sd_stream
    icon: mdi:arrow-up-drop-circle-outline
    tap_action:
      action: call-service
      service: tapo_control.ptz
      service_data:
        entity_id: camera.patio_entrada_sd_stream
        tilt: UP
  - entity: camera.patio_entrada_sd_stream
    icon: mdi:arrow-down-drop-circle-outline
    tap_action:
      action: call-service
      service: tapo_control.ptz
      service_data:
        entity_id: camera.patio_entrada_sd_stream
        tilt: DOWN
  - entity: camera.patio_entrada_sd_stream
    icon: mdi:arrow-right-drop-circle-outline
    tap_action:
      action: call-service
      service: tapo_control.ptz
      service_data:
        entity_id: camera.patio_entrada_sd_stream
        pan: RIGHT
  - entity: camera.patio_entrada_sd_stream
    icon: mdi:eye-outline
    tap_action:
      action: call-service
      service: tapo_control.set_privacy_mode
      service_data:
        entity_id: camera.patio_entrada_sd_stream
        privacy_mode: 'off'
  - entity: camera.patio_entrada_sd_stream
    icon: mdi:eye-off-outline
    tap_action:
      action: call-service
      service: tapo_control.set_privacy_mode
      service_data:
        entity_id: camera.patio_entrada_sd_stream
        privacy_mode: 'on'
  - entity: camera.patio_entrada_sd_stream
    icon: mdi:power
    tap_action:
      action: call-service
      service: tapo_control.reboot
      service_data:
        entity_id: camera.patio_entrada_sd_stream
camera_image: camera.patio_entrada_sd_stream

When i press any icon for camera movement I get the error mentioned above.
Can you give me some guidance.
Thanks in advance

### Reproduction Steps

.

### Expected behavior

.

### Device Firmware

1.3.6

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Home Assistant 2023.8.2 Supervisor 2023.08.1 Operating System 10.4 Frontend 20230802.0 - latest

### Search for similar issues

Yes

### Additional information

Camera model is Tapo c200

**Comment by JurajNyiri** [comment]
Read readme.
