### ISSUE TITLE
Feature Request: Smart Detection Entities

### ISSUE THREAD

**Issue by talldrin** [JurajNyiri/HomeAssistant-Tapo-Control#386]
**Is your feature request related to a problem? Please describe.**
No problem just a potential feature.

**Describe the solution you'd like**
Sensors for smart detection entities for cameras that support it. ie. Person, Pet, or Vehicle Detected.

**Describe alternatives you've considered**
You can do this with Frigate via RTSP streams or natively through ONVIF on Reolink Cameras. Seems like this should be doable on Tapo cameras if they use ONVIF.

**Additional context**

**Comment by JurajNyiri** [comment]
Duplicate of https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/304
