### ISSUE TITLE
Wired Tapo TC65 'authentication error'

### ISSUE THREAD

**Issue by Bobber76** [JurajNyiri/HomeAssistant-Tapo-Control#389]
### Description

When try to add TC60 to integration, add IP, and credentials, it comes back with an authentication error. User and pass made in Tapo app, RTSP stream works with those credentials. No special characters.

### Reproduction Steps

Any try to add camera

### Expected behavior

Authentication error with wired connection. Before, with wireless it worked.

### Device Firmware

1.3.3 Build 221207 Rel.79642n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
If this happens on user credentials (not cloud password) camera is overloaded. Restart it and ensure you are not accessing it from too many sources. Use search function in issues there is a lot similar user issues like this.
