### ISSUE TITLE
cannot access local variable 'motion_detection_digital_sensitivity' 

### ISSUE THREAD

**Issue by Fruitsmart** [JurajNyiri/HomeAssistant-Tapo-Control#391]
### Description

Hello I got the following error since yesterday.

I have the C420 model, which I have previously controlled with the Home Assistant. Now it doesn't start anymore.

Greetings Michel

### Reproduction Steps

Download from HACS, follow setup instructions
Connect with account
Camera is Tapo C420 

### Expected behavior

The ability to control the camera. Especially the private mode.

### If applicable, add error logs.

Unable to connect to Tapo: Cameras Control controller: cannot access local variable 'motion_detection_digital_sensitivity' where it is not associated with a value
Unable to connect to Tapo: Cameras Control controller: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

### Device Firmware

1.2.11

### Using stream component

No

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

No

### HASS Environment

Docker on Unraid

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Fixed in [5.3.1](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.3.1).
