### ISSUE TITLE
5.3.3: Log flooded when camera is offline

### ISSUE THREAD

**Issue by buhito81** [JurajNyiri/HomeAssistant-Tapo-Control#394]
### Description

Log is being flooded when one of the camera's is physically offline:

![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/101875447/867a2fdb-d6ca-4355-afeb-d9a260be2352)

### Reproduction Steps

Switch one of the Deco camera's off
Check the log

### Expected behavior

Good question, but probably not this, wouldn't we want some check for the camera being online instead of the 'bool' object is not subscriptable error?

### Device Firmware

Unrelated to firmware

### Using stream component

No

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HAOS

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/382

Also, Use latest version.
