### ISSUE TITLE
HD Streams of C210 and C100 stopped working

### ISSUE THREAD

**Issue by SmartHomeFanatic** [JurajNyiri/HomeAssistant-Tapo-Control#398]
### Description

The HD streams of my C210 and C100 stopped working yesterday. I do not get an image, SD stream and changing settings is still working.
RTSP is also still working.

Looks like they got a firmware update.

### Reproduction Steps

Opening the camera does not show any picture. HD streams are also getting unavailable.

### Expected behavior

Being able to watch HD footage from the cameras.

### Device Firmware

1.3.6 Build 230426 Rel.48373n(4555) on C210 --- 1.3.4 Build 230613 Rel.39355n(4555) on C100

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HASS OS on generic hardware

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
No problem with integration, it just passes rtsp link to ha.
Make sure your authentication data is correct, you have not disabled camera entities, camera is not overloaded and try restarting it.
