### ISSUE TITLE
Debouncer call ignored as shutdown has been requested.

### ISSUE THREAD

**Issue by DarthSonic** [JurajNyiri/HomeAssistant-Tapo-Control#399]
### Description

```
Logger: custom_components.tapo_control
Source: helpers/debounce.py:67
Integration: Tapo: Kamerasteuerung (documentation, issues)
First occurred: 24. August 2023 um 20:26:46 (15328 occurrences)
Last logged: 09:28:40

Debouncer call ignored as shutdown has been requested.
```

### Reproduction Steps

none that I know of. only added camera and then this warning was shown.

### Expected behavior

-

### Device Firmware

1.3.5 Build 230717 Rel.47395n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Home Assistant OS

### Search for similar issues

Yes

### Additional information

Warning is logged even in privacy mode. I can stream eitherway.

**Comment by JurajNyiri** [comment]
This is expected if you are shutting down ha.

**Comment by DarthSonic** [comment]
But I did not shutdown and why "15328 occurrences"?

**Comment by DarthSonic** [comment]
Meanwhile its 15688 occurrences and HA is running for the last 12 hours.

**Comment by JurajNyiri** [comment]
Ha is in shutdown state for some reason unrelated to this integration.

**Comment by DarthSonic** [comment]
Still have that issue:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht
```

Logger: custom_components.tapo_control
Source: helpers/debounce.py:67
Integration: Tapo: Kamerasteuerung (documentation, issues)
First occurred: 22:01:25 (1 occurrences)
Last logged: 22:01:25

Debouncer call ignored as shutdown has been requested.

```
Right after restart of HA and all switches, select and other entities of the Tapo camera are unavailable.
