### ISSUE TITLE
Feature Request: Access Recordings on SD

### ISSUE THREAD

**Issue by giovanne123** [JurajNyiri/HomeAssistant-Tapo-Control#40]
First of all, thanks a lot for the great work. I have a C200 running in HA very well.

Is there a way to access, download the recordings on the SD card of the Tapo C200? (right after motion is/was detected)
Or alternatively and maybe better to start a recording on HA side if motion is detected?

Currently there is the lack of feature in C200 firmware to directly record to ftp, cloud, ... instead if only to the SD card. So the SD card can be stolen and every record is away :-(

I know this request is normally more a todo for TP-Link to add the possibility in their C200 firmware, but maybe there is also a way within your HA-Tapo-Control. There are lot's of requests in the TP-Link forum but no progress so far...

**Comment by JurajNyiri** [comment]
Hello, 

I would also love a way to get the videos out of SD card. It is possible to watch the videos via app so should be possible to do via API.

When someone discovers a way to download the videos by RE I will add it to Tapo library and then maybe also here when I figure a Home Assistant friendly implementation.

I am not doing RE myself to not break the TOS of Tapo.

Pytapo, library which I am using for this integration has a Feature Request opened here: https://github.com/JurajNyiri/pytapo/issues/4

**Comment by JurajNyiri** [comment]
In the mean time, you could record via Home Assistant instead, by using https://www.home-assistant.io/integrations/camera/ `record` service. Using automation trigger binary sensor, initiate recording.

**Comment by peslung** [comment]
> In the mean time, you could record via Home Assistant instead, by using https://www.home-assistant.io/integrations/camera/ `record` service. Using automation trigger binary sensor, initiate recording.

Using the motion trigger and automation myself.
Tip that worked for me is to enable  [Preload stream](https://www.home-assistant.io/integrations/camera/) on the camera
and define lookback in the recording. This will start the record xx seconds before the motion event started

```service: camera.record
data:  
  filename: '/media/movement_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'  
  duration: 10  
  lookback: 10  
entity_id: camera.camgar_mainstream

**Comment by JurajNyiri** [comment]
We are almost there and need help! More information at [pytapo feature request](https://github.com/JurajNyiri/pytapo/issues/4).

**Comment by alucard80** [comment]
This question is not about this topic, I wonder if this custom package works for the Tapo C100 cameras?, my doubt comes cuz in the description of this package don't said nothing about any exclusive Model type of Tapo cameras, and I like to know if someone have any experience with this Tapo model camera.

Thanks & I hope you can help me with this doubt

**Comment by RestOp** [comment]
> In the mean time, you could record via Home Assistant instead, by using https://www.home-assistant.io/integrations/camera/ `record` service. Using automation trigger binary sensor, initiate recording.

It do not work. Not it works, but the it freezes and give and continious error till HA restated. So this function us unuseful

**Comment by Electronlibre2012** [comment]
Hello!

First, big thank you to @JurajNyiri for this awesome integration!

it works with the sd or hd stream provide with the TAPO integration ```camera.yourcam_hd```, with the servoce camera.record of HA, i have video in .mp4 done, but i get this error in the log :
```Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 2304x1296): unspecified pixel format Consider increasing the value for the 'analyzeduration' (10000000) and 'probesize' (5000000) options```

Any idea please to solve this?

Thanks

**Comment by JurajNyiri** [comment]
@Electronlibre2012 there is an issue opened about this and its not this one. Please keep discussion on topic.

**Comment by dvelayos** [comment]
i'm checking the ts files in order to see if we can fix this... it seems that there are two streams, video and i suposse an audio stream, but my ffmpeg doesn't recognice the second stream codec...

```
[mpegts @ 0x5623237e0600] probed stream 1 failed
[mpegts @ 0x5623237e0600] Could not find codec parameters for stream 1 (Unknown: none ([144][0][0][0] / 0x0090)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mpegts, from '2021-12-10 13_21_05.ts':
  Duration: 00:00:41.66, start: 1.934333, bitrate: 809 kb/s
  Program 1 
    Stream #0:0[0x44]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuvj420p(pc, bt709, progressive), 1920x1080, 15 fps, 15 tbr, 90k tbn, 30 tbc
    Stream #0:1[0x45]: Unknown: none ([144][0][0][0] / 0x0090)
```

**Comment by leaskovski** [comment]
Chucking my thoughts on this in as well.  If this could open up recordings to be accessible via the "Media" interface in HA, similar to say how the reolink plugin works, that would be awesome!

**Comment by lucamir** [comment]
I recently buy a tapo c200 cam and i would like to write a python script that download the local SD recorded videos after the alarm was triggered. I see that the function getMediaSession use the cloud password that involve that i need a paid plan. 
So i just wanna ask you if there's any https request that for access to that local files and if there's any sort of webhook for trigger the event ?

**Comment by JurajNyiri** [comment]
> I see that the function getMediaSession use the cloud password that involve that i need a paid plan.
That is an incorrect assumption. Cloud password is not used for cloud, just a different type of account (fully local).

> So i just wanna ask you if there's any https request that for access to that local files and if there's any sort of webhook for trigger the event ?

No, check this thread and connected https://github.com/JurajNyiri/pytapo/issues/4 for more info.

**Comment by JurajNyiri** [comment]
This is now possible super easily via a script. 

https://github.com/JurajNyiri/pytapo#downloading-recordings

Home Assistant way coming in the future.

**Comment by JurajNyiri** [comment]
This is now available in beta releases.

**Comment by Bastiencc** [comment]
Awesome 👍 is there a way to download/synchronize those recording to local storage (on hassOs) ?

**Comment by JurajNyiri** [comment]
Not currently, you can play recordings on demand on the latest version 5.0.0. It will stay cached for 24 hours.

**Comment by Bastiencc** [comment]
ok thanks @JurajNyiri , do you think this will be something doable in the future?

**Comment by pdsakurai** [comment]
Hi @JurajNyiri! Thank you and your team for making Tapo cameras integrated very well in Hass.

May I know how I can use the Media Browser in Hass? I already tried re-adding my tapo cameras but I cannot fihure out how to access the media browser.

**Comment by pikajuicy** [comment]
Hi, thanks for making this available for everyone. Just wondering if it is possible to run this on a NAS. I have an Asustor AS5202T and hope to run this script on my NAS for retrieving recordings stored locally on my Tapo C110 and C320WS.

**Comment by JurajNyiri** [comment]
https://github.com/JurajNyiri/pytapo#downloading-recordings might be better for your use case @pikajuicy especially if you are not already running HA.

**Comment by Bastiencc** [comment]
> Yes I plan to implement it.

Hello, I come to the news, to know if you still think that it will be possible?

**Comment by JurajNyiri** [comment]
Hi, I've been busy and haven't gotten to it yet. I will try to find some time soon, or if anyone else wants to open pr it is welcomed.

**Comment by JurajNyiri** [comment]
Media Sync is now available in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.3.0.beta.1 .
