### ISSUE TITLE
Feature Request: Disable camera stream?

### ISSUE THREAD

**Issue by fjeddy** [JurajNyiri/HomeAssistant-Tapo-Control#400]
**Is your feature request related to a problem? Please describe.**
I am currently using Frigate to display, record and monitor the cameras. But as per most cameras, they don't allow unlimited streams.

**Describe the solution you'd like**
A possibility to disable the camera stream, only implement and use the controls part of the cameras.

**Describe alternatives you've considered**
.

**Additional context**
There might be a way around this that I havn't thought off. But I ultimately want the ability to control the camera at such a fine grained level that this module gives me, but at the same time I still want Frigate to handle the streams. Having this module and Frigate connect and try to fetch the stream, seems to add an unecessary load on the WiFi and cameras.

**Comment by JurajNyiri** [comment]
Disable camera entities or even better override stream URL in settings with the frigate restream.
