### ISSUE TITLE
Login Error with verified credentials

### ISSUE THREAD

**Issue by eprompc** [JurajNyiri/HomeAssistant-Tapo-Control#401]
### Description

TAPO C225 Login error 

### Reproduction Steps

I install the library from HACS 
I go in HomeAssistant to add new device 
I select TAPO Control Camera service 
It asks me the IP address
I add the IP address 
It asks me user and password 
I add user and password created with the TAPO app in Android, inside the advanced configuration of the camera 
Then it returns an error of credentials 
I have tested in VLC the same IP data with user and password, and it works perfectly.

### Expected behavior

Esperaba poder añadir el dispositivo pero no puedo. Se queda esperando usuario y contraseña válidos.
He probado rtsp://user:pass@IP:554/stream1 y funciona perfectamente, pero esas mismas credenciales no me funcionan al añadir el dispositivo en HomeAssistant.

Podríais ayudarme?

### Device Firmware

1.0.24

### Using stream component

No

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

No

### HASS Environment

Synology NAS Dsj213

### Search for similar issues

Yes

### Additional information

Thanks for your work

**Comment by eprompc** [comment]
In the Logs I found this error:

Home Assistant Core
Setup failed for stream: Requirements for stream not found: ['ha-av==10.1.0'].
11:41:35 – (ERROR) setup.py - el mensaje se produjo por primera vez a las 11:41:18 y aparece 2 veces
Unable to set up dependencies of default_config. Setup failed for dependencies: stream
11:41:35 – (ERROR) setup.py

**Comment by eprompc** [comment]
Unable to install package ha-av==10.1.0: error: subprocess-exited-with-error × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> [1 lines of output] pkg-config is required for building PyAV [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output. note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by JurajNyiri** [comment]
You will need to install dependencies on your env as stated in the error message. Not an integration issue.
