### ISSUE TITLE
Integration causing webhook UI to fail.

### ISSUE THREAD

**Issue by tomwrgriff** [JurajNyiri/HomeAssistant-Tapo-Control#403]
### Description

HA is inaccessible via port `8123` over local /external network using either URL or IP address. Ping of IP address is successful. Checking for open ports on IP address finds 8123 closed. Other ports, such as SSH 22 are open. Using SSH to run `ha core check` doesn't show any errors and automations are running successfully. Log entries show error message relating to `Tapo camera controller`. 

There doesn't seem to be any issues with the Tapo plugs controller at this time. Disabling the Tapo camera controller integration seems to make the system more stable but need to see if this is the case over a longer period of time.

### Reproduction Steps

1. Open HA app on device (tried android, ios, and windows).
2. UI fails to load.
3. Retry in 60 seconds dialogue continues with no success.
4. Updating URL settings has no success.

### Expected behavior

UI load normally.

### If applicable, add error logs.

```
This error originated from a custom integration.

Logger: custom_components.tapo.coordinators
Source: helpers/update_coordinator.py:229
Integration: TP-Link Tapo (documentation, issues)
First occurred: 12:06:13 (2 occurrences)
Last logged: 12:28:30

Error fetching tapo data: Unexpected exception:
```

//

```
This error originated from a custom integration.

Logger: custom_components.tapo_control
Source: custom_components/tapo_control/__init__.py:187
Integration: Tapo: Cameras Control (documentation, issues)
First occurred: 11:16:02 (1 occurrences)
Last logged: 11:16:02

Home Assistant is running on HTTPS or it was not able to detect base_url schema. Disabling webhooks.
```

### Device Firmware

1.3.1 Build 221218 Rel.73283n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Hass OS, Rpi 4 8gb, ssd boot.

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Wrong repo.

**Comment by tomwrgriff** [comment]
Thanks for letting me know @JurajNyiri
