### ISSUE TITLE
Feature Request: Add Support for TP-Link NC450 Camera

### ISSUE THREAD

**Issue by luixal** [JurajNyiri/HomeAssistant-Tapo-Control#405]
**Is your feature request related to a problem? Please describe.**
No, TP-Link NC450 is not a Tapo camera, but belongs to the same manufacturer. Indeed, it works with a different app.

**Describe the solution you'd like**
I would like support for NC450 cameras.

**Describe alternatives you've considered**
Creating my own integration for HA forking this one and removing features not supported by NC450. But it would be great to make a PR adding support using [this dep](https://github.com/TomAFrench/nc450-python-api) :)

**Comment by JurajNyiri** [comment]
Thank you for suggestion, this integration is only for Tapo cameras as they have common API.
