### ISSUE TITLE
Feature Request:Action in automation to take a picture based on a time trigger

### ISSUE THREAD

**Issue by CarstenDennis** [JurajNyiri/HomeAssistant-Tapo-Control#406]
**Is your feature request related to a problem? Please describe.**
Not a problem, but a feature request :-)

I would like to use this existing camera, that is overviewing our garden, to make a timelapse of the garden, with a few pictures per day at the same time each day.

**Describe the solution you'd like**
An additional action under devices to "Take picture and store to local memory"

**Describe alternatives you've considered**
Scripts use the same actions as far as I can see.

**Additional context**
Here you can see where I mean it would be nice with an action that just takes a picture:
![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/139639309/b4a41405-1df6-4f72-b3f3-5181da39dd41)

I can save a picture (also record video manually) via the offical Tapo app, that is stored on the device itself, but not via home assistant.

Great integration otherwise!

**Comment by JurajNyiri** [comment]
https://www.home-assistant.io/integrations/camera/
