### ISSUE TITLE
Feature Request: Baby Crying binary sensor

### ISSUE THREAD

**Issue by owanvik** [JurajNyiri/HomeAssistant-Tapo-Control#407]
**Is your feature request related to a problem? Please describe.**
Not related to a problem, just missing

**Describe the solution you'd like**
A binary sensor for the baby crying feature. As of now i can get a push notification from the Tapo app.

**Comment by JurajNyiri** [comment]
Duplicate of https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/304
