### ISSUE TITLE
Entities mixed up with each other for multiple cameras with same name in Tapo app

### ISSUE THREAD

**Issue by longer83** [JurajNyiri/HomeAssistant-Tapo-Control#409]
### Description

Entities mixed up with each other for multiple cameras with same name (not location) in Tapo app.

### Reproduction Steps

Simply add 2 or more cameras to HA with same name in Tapo app and restart HA.

### Expected behavior

Entities for each camera are grouped under device in integration.

### If applicable, add error logs.

Both cameras are named "kamera" in Tapo app and assigned to different locations / rooms.

Screenshot after adding garage camera:
![1](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/15156852/8ef10ae7-030e-4e08-b6c0-c9c442fdb398)

Screenshot of entities after adding garage camera:
![2](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/15156852/9787df09-7f22-4da2-9ddd-0a12eae69445)

Screenshot after adding living room camera:
![3](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/15156852/51b88a7a-782f-4eeb-b174-713397d09c6c)

Screenshot of entities after adding living room camera:
![4](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/15156852/fbce7c2b-1990-4a1f-a38e-6f7a2439cdbd)

Screenshots of logs after adding both cameras:
![5-1](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/15156852/77221235-f7f2-40e2-b687-0abfb07888e9)
![5-2](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/15156852/75a098e5-1736-4b43-a573-308772ac1353)
![5-3](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/15156852/02953075-d14f-4eaf-9f82-b20019bd1137)
![5-4](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/15156852/6426f1ac-fd7a-45c7-b26a-f0e6ea101212)
![5-5](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/15156852/5e9f9a94-6ae7-43d3-a399-6dda40dcdbc9)
![5-6](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/15156852/ce849a60-2f9f-476a-9a2b-6b35b9eaf2cd)
![5-7](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/15156852/08611ee1-3e8b-47b9-8643-3b6c25a8c0ea)
![5-8](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/15156852/9a4067a4-ae6f-4b33-b61f-2529bc9b0f9d)
![5-9](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/15156852/f3445d0c-2c53-4648-ba4c-a47f84bf83c3)

Screenshot of list of cameras after HA restart:
![6](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/15156852/5ebd87e6-2e48-47b4-84c1-79cd913d5077)

Screenshots of logs after HA restart:
![7-1](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/15156852/69362ed7-48b3-45fd-98b3-bf2356da3ac0)
![7-2](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/15156852/9cc4a4a1-41cd-429c-be74-1d3868bbd1da)
![7-3](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/15156852/4b051e26-2799-4668-bb7a-805d0d2cbf17)
![7-4](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/15156852/fb87e0a5-2a32-4e64-9b75-e6904ad7c52b)
![7-5](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/15156852/32f3d10f-db66-456a-924c-5eabc66579ef)
![7-6](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/15156852/b260216a-403d-4355-95d8-62c9d1a7788c)
![7-7](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/15156852/2dd99124-b946-45d3-97eb-b675db117c48)
![7-8](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/15156852/42c3dbfb-5d28-4ef4-add1-b9b2fa58fdae)

### Device Firmware

1.3.0 Build 220830 Rel.698880n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

No

### HASS Environment

HAOS

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Fixed in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.3.5.
