### ISSUE TITLE
Feature Request: Compatibility with Tapo C310

### ISSUE THREAD

**Issue by zino78** [JurajNyiri/HomeAssistant-Tapo-Control#41]
Dear Juraj,

Is possible to use this perfect component with Tapo C310 outdoor cam?
I want to use it, but when i try to add it on integrations it say "Invalid authentication data".
This version is fixed type, but it has motion detection.
I think all port are the same like on C200.
I try to find some usable logs on my HA.
With ffmpeg i can use it to see the stream with the standard tapo like rtsp url.

Thanks,
  Janos Bodor

**Comment by JurajNyiri** [comment]
Hello,

I do not own Tapo C310 so I am not sure what has changed. Someone will need to provide details about API similarly to how they did for C200.

Someone who owns C310 and knows basics of python could look into https://github.com/JurajNyiri/pytapo/ library and investigate in auth method what exactly is going wrong while authenticating.

**Comment by JurajNyiri** [comment]
In the mean time, you can use onvif component which provides video and motion detection binary sensor similarly to this component.

**Comment by zino78** [comment]
Dear Juraj,

Thank for your quick answer! I try onvif too, but that doesn't work too.
When i have some time, i try to understand your python library and
investigate the problem.
I'm not python programer, but before i wrote some perl and php scripts.

Best regards,
  Janos Bodor

Juraj Nyíri <notifications@github.com> ezt írta (időpont: 2020. nov. 24.,
K, 0:41):

**Comment by dp106** [comment]
Hi ya I have a very basic knowledge of python, emphasis on the word very!

Is it you want someone to download the library and then run the code to get back the basic info?

**Comment by JurajNyiri** [comment]
So the first step would be to see what the actual response from the camera authentication request is.

1. Download https://github.com/JurajNyiri/pytapo/tree/debug_sign_in
2. Extract, into root create tmp.py (modify according to your user, pass and ip)

```

from pytapo import Tapo

user = "user"  # user you set in Advanced Settings -> Camera Account
password = "password"  # password you set in Advanced Settings -> Camera Account
host = "192.168.1.52"  # ip of the camera, example: 192.168.1.52

tapo = Tapo(host, user, password)
print(tapo.getBasicInfo())

```

3. Run file with python3 tmp.py
4. Post results here

This might point us to a correct direction... That being said, authentication failing most probably means that TPLink changed the way API works so someone will probably need to find out and document how the new API works before I can add support for it here.

**Comment by dp106** [comment]
Unfortunately I just get the same error trying to run it:

`Traceback (most recent call last):
  File ".\tapo.py", line 7, in <module>
    tapo = Tapo(host, user, password)
  File "E:\Program Files\Python\lib\site-packages\pytapo\__init__.py", line 32, in __init__
    self.basicInfo = self.getBasicInfo()
  File "E:\Program Files\Python\lib\site-packages\pytapo\__init__.py", line 378, in getBasicInfo
    self.ensureAuthenticated()
  File "E:\Program Files\Python\lib\site-packages\pytapo\__init__.py", line 46, in ensureAuthenticated
    return self.refreshStok()
  File "E:\Program Files\Python\lib\site-packages\pytapo\__init__.py", line 65, in refreshStok
    raise Exception("Invalid authentication data.")
Exception: Invalid authentication data.`

**Comment by dp106** [comment]
Does this help:  https://www.tp-link.com/uk/support/faq/2748/

**Comment by JurajNyiri** [comment]
@dp106 that means you have downloaded invalid branch - master. You need to download branch debug_sign_in.

1. Open https://github.com/JurajNyiri/pytapo/tree/debug_sign_in
2. Click on Code, Download as Zip - or git clone and switch branch to debug_sign_in
3. Follow steps I have posted before from step 2

You should get some prints before the error stack.

The FAQ is instructions that every user should follow before using this integration, even for C200 or C100.

**Comment by Depau** [comment]
You can try using `admin` as username and the TP-Link password, see if that works.

**Comment by peslung** [comment]
This is the output from the C310 camera when I have tested this Python code

`eter@ubuntu-vm:~/ha_tapo/pytapo-debug_sign_in$ python3 tmp.py
https://10.10.99.133:443
{'method': 'login', 'params': {'hashed': True, 'password': 'xxxxxx', 'username': 'user'}}
<Response [200]>
{"error_code": -40401, "result" : { "data": {"code": -40411, "encrypt_type": ["1", "2"], "key": "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDYCTGjKCv1qWLAnO%2b2ushLzu3ZVfh8NPpAwwBKMKeLukb%2fTo1djupOFeX22oFaR%2bmYqh1NJlSTXIIfOp4qEkUyEyyO%2bLOnSADF9wzdF8oPbWNciC0BqHlRrgtxr8JCGDIieJ5g2wIDAQAB", "nonce": "ijRp25nC"}}}
Traceback (most recent call last):
  File "tmp.py", line 8, in <module>
    tapo = Tapo(host, user, password)
  File "/home/per/ha_tapo/pytapo-debug_sign_in/pytapo/__init__.py", line 32, in __init__
    self.basicInfo = self.getBasicInfo()
  File "/home/per/ha_tapo/pytapo-debug_sign_in/pytapo/__init__.py", line 382, in getBasicInfo
    self.ensureAuthenticated()
  File "/home/per/ha_tapo/pytapo-debug_sign_in/pytapo/__init__.py", line 46, in ensureAuthenticated
    return self.refreshStok()
  File "/home/per/ha_tapo/pytapo-debug_sign_in/pytapo/__init__.py", line 69, in refreshStok
    raise Exception("Invalid authentication data.")
Exception: Invalid authentication data.
`

This is the output when i tested the same code on my C200 camera

`https://10.10.99.111:443
{'method': 'login', 'params': {'hashed': True, 'password': 'xxxxx', 'username': 'user'}}
<Response [200]>
{"error_code": 0, "result" : { "stok": "933486b666ea8842aff38bb6bb62df2e", "user_group": "third_account"}}
{'device_info': {'basic_info': {'device_type': 'SMART.IPCAMERA', 'device_model': 'C200', 'device_name': 'C200 1.0', 'device_info': 'C200 1.0', 'hw_version': '0930 Rel.26253n(4555)', 'device_alias': 'HA-Garasjen', 'features': '3', 'barcode': '', 'mac': '74-DA-88-F6-FC-46', 'dev_id': '802146C912AE40192F97AA59050A7CBA7721DE92F5759839C2', 'hw_desc': '48574445534300000000000000000001'}}, 'error_code': 0}
`

**Comment by JurajNyiri** [comment]
Please confirm / try following:
1. Are you using your account created in the advanced settings trough the app in both cases AND is your password a simple one / same on in both cases?
2. Try using "admin" as username and your tplink password as a password for both

**Comment by peslung** [comment]
Np.

1. Yes, the same account and password is created in advanced settings on both cameras. Simple password. Both cameras is added successfully with the integration ONVIF.

2. More output with the tplink password

`C310
https://10.10.99.133:443
{'method': 'login', 'params': {'hashed': True, 'password': 'tp-link_pwd', 'username': 'admin'}}
<Response [200]>
{"error_code": 0, "result" : { "stok": "5b338e3187a92e77092beb6e913be25e", "user_group": "root"}}
https://10.10.99.133:443
{'method': 'login', 'params': {'hashed': True, 'password': 'tp-link_pwd', 'username': 'admin'}}
<Response [200]>
{"error_code": 0, "result" : { "stok": "5b338e3187a92e77092beb6e913be25e", "user_group": "root"}}
Traceback (most recent call last):
  File "tmp.py", line 8, in <module>
    tapo = Tapo(host, user, password)
  File "/home/per/ha_tapo/pytapo-debug_sign_in/pytapo/__init__.py", line 39, in __init__
    self.presets = self.getPresets()
  File "/home/per/ha_tapo/pytapo-debug_sign_in/pytapo/__init__.py", line 729, in getPresets
    return self.getPresets(True)
  File "/home/per/ha_tapo/pytapo-debug_sign_in/pytapo/__init__.py", line 725, in getPresets
    + json.dumps(data)
Exception: Error: Parameter to get/do does not exist Response:{"preset": {}, "error_code": -40106}`

`C200
https://10.10.99.111:443
{'method': 'login', 'params': {'hashed': True, 'password': 'tp-link_pwd', 'username': 'admin'}}
<Response [200]>
{"error_code": 0, "result" : { "stok": "1ee10a64f1924b290f3e2600ee04efb5", "user_group": "root"}}
{'device_info': {'basic_info': {'device_type': 'SMART.IPCAMERA', 'device_model': 'C200', 'device_name': 'C200 1.0', 'device_info': 'C200 1.0', 'hw_version': '1.0', 'sw_version': '1.0.16 Build 200930 Rel.26253n(4555)', 'device_alias': 'HA-Garasjen', 'features': '3', 'barcode': '', 'mac': '74-DA-88-F6-FC-46', 'dev_id': '802146C912AE40192F97AA59050A7CBA1C4FC165', 'oem_id': '8902D2F34FCE407721DE92F5759839C2', 'hw_desc': '48574445534300000000000000000001'}}, 'error_code': 0}`

**Comment by JurajNyiri** [comment]
Ok this is good!

Even though I am not sure why the custom account doesn't work, I can now get the camera working in the integration!

Beta version coming soon to try out.

**Comment by JurajNyiri** [comment]
New version has been released for testing on github.

Please proceed with [manual install instructions](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control#installation) as it has not yet been deployed on HACS until it is tested.

https://github.com/JurajNyiri/HomeAssistant-Tapo-Control

Use "admin" as username and your tplink password as a password when adding the camera to HASS.

@peslung @dp106 @zino78

**Comment by zino78** [comment]
Dear Juraj,

Thanks for your work!
I'm sorry, but my week is very overloaded...
I try this new version. I copy it, my custom components folder.
After it, I restart HA.
With admin username I can add it Tapco C310 camera to my HA, but when I add it to Lovelace, no stream is available.
After add the component, I have an SD and HD stream entity, but no motion sensor at yet. 
But I try to investigate, that I made some mistake, or no :)

Best regards,
  Janos

**Comment by zino78** [comment]
My error:

Stream connection failed: rtsp://admin:password@192.168.0.108:554/stream1

My stream usarname not te same, like my edited username. I try to renew my user to admin, ind I try it again!

**Comment by dp106** [comment]
Hey @zino78, I've just tested it and get the same error. At least we are consistent!

**Comment by zino78** [comment]
Hmmmm.... I can't use admin usernem on camera, because the tape app say me it should contain 6 to 32 characters..

**Comment by zino78** [comment]
I think, the admin username is correct to connect the camera, but with the stream we need not the admin username. Sorry my terrible english.....

**Comment by dp106** [comment]
Your english is very good @zino78. I did wonder if it should be the email I use to sign in to the app but I would have thought if there was an issue with using admin as the username we wouldn't be able to add the camera at all?  Will have to see what @JurajNyiri comes back with

**Comment by JurajNyiri** [comment]
Thank you for confirming adding the camera works. 

So here is the conclusion:
- The **stream** on **all** the cameras works **only via account** set up through advanced settings and not with admin username
- The **control** works via **admin** username **or** the **account** set up through advanced settings on **Tapo C100 and C200**
- The **control** works **only** via **admin** username on **Tapo C310**

I will need to think about how to approach this situation in a user friendly way and how to implement it properly.

No worries though, because we can get the C310 camera working right using following workaround:
- Use the current version of tapo-control from the master branch (the one mentioned above) for control (not the one on HACS)
- Use other home assistant component like onvif (use port 2020!) or generic component for RTSP stream

Not ideal, but for now the only solution that works with C310.

I have everything that I need to get it working nicely all in one integration, now its only a matter of time to make the updates.

**Comment by JurajNyiri** [comment]
In the mean time, could I ask you to test if all the other functionality (except the stream) and services work after adding the C310?

**Comment by JurajNyiri** [comment]
After giving some thoughts about implementing this I have made a decision.

TL&DR:
No changes for current cameras. Tapo C310 will have a slighly different setup flow requiring also cloud password. If there is a change in the future requiring cloud password, current cameras will need to be updated with cloud password via integration settings trough hass.

Here are the factors I considered:
- User shall not be needed to enter cloud password if his camera doesn't require it
- Adding the camera should be easy and user friendly
- Absolutely no breaking changes for current users
- Be camera model independent. Setup should still work if they change the behaviour on existing cameras, or release a new camera.

So here are the changes that will come in 2.3 regarding the setup of cameras.

**Initial setup:**

1. User will be required to create account in advanced settings just like today. He will be then prompted to enter this username and password. Integration will test these credentials in 2 ways - does rtsp stream work AND does control work?
2a. If control worked, setup is done.
2b. If control did not work, user is required to enter his cloud password - not email as that is not required.
3. Setup is finished

**Changing settings after setup:**

User is able to provide all the settings just like in initial setup. The check for rtsp stream and control is done similarly to above. If it is found that the cloud password is needed for control, user is required to enter it after seeing an error message.

Migration of cameras will be done automatically, with no action required from current users.

**Comment by zino78** [comment]
I try some services:

- privacy
- motion detection
- day-night mode

This services works well!
 
I don't have binary motion detection sensor at yet...
The sensor entity is generated during add integration or just when the first motion detected? 

A possible workaround for authenticaion: when user add tapo integration to HA, then when the user name and password doesn't work for authentication, the integration maybe try the admin username and the given password to authenticate the camera. If it is ok, that mean this is a C310 camera (or any not C100 or C200 model). When it is C310, then the SD and HD stream entity can use the given username and password, and the services can use the admin username and given password. Just an idea :)

**Comment by JurajNyiri** [comment]
![image](https://user-images.githubusercontent.com/5785999/100557284-755f3380-32a8-11eb-9c9e-bfef6ee8f0e8.png)
![image](https://user-images.githubusercontent.com/5785999/100557287-77c18d80-32a8-11eb-96dd-38f9230e48fe.png)
![image](https://user-images.githubusercontent.com/5785999/100557294-814af580-32a8-11eb-8581-f38e85940183.png)
![image](https://user-images.githubusercontent.com/5785999/100557298-8740d680-32a8-11eb-88d6-24154056fbfb.png)

Some progress on the new config flow. 2nd picture will not appear if its not needed.

**Comment by JurajNyiri** [comment]
@peslung @dp106 @zino78

Please try the latest version on master branch on github just like before.

If you have added camera, remove it first and add again just to be sure everything works.

Should work flawlessly 🤞

**Comment by JurajNyiri** [comment]
@peslung @dp106 @zino78

Please try the latest version on master branch on github just like before.

If you have added camera, remove it first and add again just to be sure everything works.

Follow instructions during the flow, it will verify everything along the way to make sure everything works once added.

Should work flawlessly 🤞

**Comment by zino78** [comment]
I try it! I remove the old integration from HA, then overwrite the tapo_control directory the new one in  custom_components directory. Restart HA, and add the new tapo integration witn my c310 camera. The integration add procedure work well, in my case, the integration ask for my cloud password. I write my cloud password (it is the same like the camera password... my mistake... :) )
After it, the camera is added into HA, with 2 entity. The SD and HD stream. I try the privacy mode on and off. That works well too!
In the HA, the motion detection binary sensor is added too. I haven't much time in my work, but on evening, i try thet the motion sensor is working or not. But i think, it works well ;)
Perfect work, and many-many thanks for your work and time!

**Comment by JurajNyiri** [comment]
@zino78 thank you for the verification! Release 2.3 has now been released.

**Comment by Phyks** [comment]
For whoever coming across this thread, I had very similar issue with Tapo C210. It works perfectly fine by using username `admin` and password of the TP-Link cloud account in `pytapo`. Note that this works in a purely local way (no need to actually have an internet connection to the camera to use these credentials). Thanks for pytapo library!

**Comment by sawh** [comment]
> For whoever coming across this thread, I had very similar issue with Tapo C210. It works perfectly fine by using username `admin` and password of the TP-Link cloud account in `pytapo`. Note that this works in a purely local way (no need to actually have an internet connection to the camera to use these credentials). Thanks for pytapo library!

The current C210 hardware version 1.0 and firmware 1.1.21 no longer works with the username 'admin' or the username selected in "Advanced Settings". The video stream works perfectly.
