### ISSUE TITLE
Cell Motion Detection sensor's Entity ID changed

### ISSUE THREAD

**Issue by jmsantos86** [JurajNyiri/HomeAssistant-Tapo-Control#413]
### Description

Just noticed that the Entity ID of Cell Motion Detection sensor for Tapo C210 changed from **binary_sensor.<_camera_label_>_cell_motion_detection** to **binary_sensor.<_camera_label_>_cell_motion_detection_2** unexpectedly.

### Reproduction Steps

1. Add Tapo C210 Camera
2. Enable Motion Detection
3. Wait for binary_sensor.<_camera_label_>_cell_motion_detection to show once motion is detected
4. Leave it for a while and check if the Cell Motion Detection sensor's Entity ID change

### Expected behavior

Entity ID should not change

### Device Firmware

1.3.7 Build 230823 Rel.55314n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker on Synology NAS

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
This is ok on update, just delete the old entity and rename the new one, it should not happen regurarely.
