### ISSUE TITLE
Motion detection not avaliable in automation

### ISSUE THREAD

**Issue by froniusMW** [JurajNyiri/HomeAssistant-Tapo-Control#415]
### Description

After latest update, the motion and cellmotion etinity are not visible for use as an trigger in automation(C310). My C310WS are working fine. The etinity shows in the list but not when I want to use it as an trigger in automation.

### Reproduction Steps

1. Automation
2. Event device action
3.  Motion detection

### Expected behavior

Before latest update, I could use motion detection as an trigger in my automations, not working now.
The entinity shows for my C310WS

### Device Firmware

1.3.7

### Using stream component

No

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HAOS on dedicated NUC

### Search for similar issues

Yes

**Comment by Electronlibre2012** [comment]
hello, for me no more motion sensors on my 3 tapo cam, c200, c310 and c320w after update today  :(

**Comment by JurajNyiri** [comment]
Read faq and get back once you try all the steps. Nothing was changed in latest version for motion detection.
