### ISSUE TITLE
Feature Request: Add Sensor for person detection

### ISSUE THREAD

**Issue by indyanafr** [JurajNyiri/HomeAssistant-Tapo-Control#416]
**Is your feature request related to a problem? Please describe.**
Need to differentiate simple motion detection of a person detection in Home Assistant

**Describe the solution you'd like**
Add a sensor for Person detection in the same way as Motion sensor. The goal is to run automatizations/scripts in HA using the camera algorithm.

If you could please consider this, that would be great!

I can test Integration on C500 and C210 cams if needed.

Thanks in advance!

**Comment by JurajNyiri** [comment]
https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/304

**Comment by d4get** [comment]
Also interested in the integration of a person sensor, I have the tapo 520ws, if you need me to do any tests, tell me.
