### ISSUE TITLE
Feature Request: Modify microphone level

### ISSUE THREAD

**Issue by Charles-HL** [JurajNyiri/HomeAssistant-Tapo-Control#417]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
The Tapo app gives the ability to modify the microphone level of the camera.
It would be nice to be able to modify it through home assistant too.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by JurajNyiri** [comment]
Where is this done in the app? Could you please post pictures?

**Comment by Gabba-63** [comment]
![Tapo mic](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/121426799/a1752c84-e823-4bc5-942e-e09fcb979a95)

**Comment by JurajNyiri** [comment]
Someone will need to find the correct call that happens from phone to camera once this is adjusted and then we can implement this.

**Comment by kobrata0912** [comment]
@JurajNyiri I've played around for a few days with pytapo and read through the documentation that helped create it, and I've come up with a solution that was working for me to change the microphone level and disable the Privacy mode locally. Here it is below. I hope it helps you, and you can implement it!

**from pytapo import Tapo
user = USERNAME
password = PASSWORD
host = HOST_IP
tapo_one = Tapo(host, user, password)
tapo_one.setPrivacyMode(False)
tapo_one.executeFunction('setMicrophoneVolume', {'method':'set', 'audio_config': {'microphone': {'volume': '100'}}})**

**Comment by kobrata0912** [comment]
This will help you find all settings for the microphone.

tapo.executeFunction('getAudioConfig', {'method':'get', 'audio_config': {'name':'microphone'}})

**Comment by JurajNyiri** [comment]
Implemented in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.4.2
