### ISSUE TITLE
Feature Request: Documenation on how to construct media paths to recordings.

### ISSUE THREAD

**Issue by tlamadon** [JurajNyiri/HomeAssistant-Tapo-Control#418]
**Is your feature request related to a problem? Please describe.**

This is a documentation request. The issue is that I can't construct the media path to the recordings. I would like to expose the recordings of my cameras (which I can see in the media folder) in a gallery card:
https://github.com/TarheelGrad1998/gallery-card

I tried many different paths, but none worked successfully. I also don't know where I can try out some of these paths in home assistant, so I can't say for sure if the issue is coming from the gallery card of the Topo extension.

**Describe the solution you'd like**
Only thing I would like is a documentation on the media path to the recordings.

**Describe alternatives you've considered**
There are other plugins that create media paths from filesystem. But it seems like an overkill since the recordings are already available as media. I also considered running a separate web server, but that also seems a bit much.

**Additional context**
Thank you for your help, you have done a terrific job! I love the extension!

**Comment by JurajNyiri** [comment]
Hi,

Media paths in www folder are randomly generated and the files are deleted after a short period on purpose - to protect the privacy of users because the www folder is not password or Auth protected at all.

Files are stored in cold storage that is not accessible to browser in .storage folder using the entry_id of configured device as a folder name.

**Comment by BrianZ96** [comment]
Hi developer, I'm trying to add a cold storage path to my network storage (a synology NAS) to remove the TF card on the camera. But I have an issue of constructing that cold storage path.

Now I have added the network storage using CIFS, let's say the name is **storage_1**, and the remote share is **folder\recordings**, and the server is **192.168.x.xxx**, what should be the format of that cold storage path? I have tried:
- \\storage_1\folder\recordings
- 192.168.x.xxx:folder\recordings
- storage_1
None of these can download videos to my NAS, instead, a new folder named with the same string as all my above tested name occurs in the path: **/homeassistant**

Can anyone help me with this problem?

**Comment by JurajNyiri** [comment]
You will need to mount the folder via HA first and then provide the path from ha. 
Recordings are saved to SD card first, if you remove it there will be nothing to sync.

**Comment by BrianZ96** [comment]
Hi Juraj, thank you for the reply! Yes, as you mentioned, I have mounted my NAS folder to the HA, and it has the following configurations:
- **Name**: storage_1
- **Server**: 192.168.x.xxx
- **Protocol**: CIFS
- **Remote share**: folder\recordings

My confusion comes at the 
> then provide the path from ha

part. What would be the path under such circumstance? I'll be greatly appreciated your generous help! Thank you!

**Comment by JurajNyiri** [comment]
Hi, see https://www.home-assistant.io/common-tasks/os/#network-storage .

My path is for example `/share/InsideCameras/Bedroom`.
