### ISSUE TITLE
motion detection sensor not available

### ISSUE THREAD

**Issue by Matt7C2** [JurajNyiri/HomeAssistant-Tapo-Control#420]
### Description

Hi, i have a TP-Link Tapo C100 Model.
Firmware: 1.3.6 Build 230512 Rel.47982n(4555)
Hardware: 2.0

Until a few months ago the motion detection sensor (on/off) worked.
However, with the latest updates it stopped working.
If I check in the integration properties, i see theese:
- binary_sensor.telecamera_cell_motion_detection: non available
- binary_sensor.telecamera_motion: not available

Is it possible to solve this problem or alternatively tell me what I can do please?
I was currently using them on some automations.
Thank

### Reproduction Steps

Go to Tapo integration properties and check the entities.
If you click on the "state button" on the right, the popup says:
"This entity is no longer provided by the tapo_control integration. If the entity is no longer used, delete it in settings."

### Expected behavior

I appreciate if you can fix and rehabilitate entities that are no longer functional

### Device Firmware

1.3.6 Build 230512 Rel.47982n(4555)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Raspberry pi4

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Read faq or many duplicates where I said the same.
