### ISSUE TITLE
Request to add motion detection binary sensor

### ISSUE THREAD

**Issue by seocg** [JurajNyiri/HomeAssistant-Tapo-Control#421]
**Is your feature request related to a problem? Please describe.**
A clear and concise explanation of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
tapo - Request to add motion detection function for c510w

**Describe alternatives you've considered**
With the noise detection function, if the window is open when going out, external noise is detected and it is detected that you are in the room.

**Additional context**

**Comment by JurajNyiri** [comment]
It is there, read readme, especially FAQ. For battery cameras: https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/273

**Comment by seocg** [comment]
What is a battery camera? c510w is a wireless ipcctv for outdoor use. The document you mentioned does not match my problem situation.
Does this mean that the motion detection function cannot be used with onvif?

It is very disappointing that the c510w is not supported even though it is a higher model than the c210.

**Comment by seocg** [comment]
What is a battery camera? c510w is a wireless ipcctv for outdoor use. The document you mentioned does not match my problem situation.
Does this mean that the motion detection function cannot be used with onvif?

It is very disappointing that the c510w is not supported even though it is a higher model than the c210.

**Comment by JurajNyiri** [comment]
Battery camera is a camera which has a battery. 
C510W is fully supported. Please list steps you have tried from FAQ as instructed, in detail.

**Comment by seocg** [comment]
Currently, my Synology server is at my parents' house.

tapo's c510w is installed in my room in another area.

At the router level, communication is allowed only with the IP of the c510w and the server, and communication with all other IPs is blocked, so camera control is not possible with the tapo app.

Of course, all detection functions were turned on before blocking communication.

Install your component and enter the IP number as xxx.xxx.xxx.xxx. Streaming is also fully supported. (There is some buffering, but it is not a major problem as it mainly uses Synology NAS’s surveillance)

However, it supports noise detection but not motion detection.

In the comment section, you are disappointed that the c510w does not support motion detection. This is not a disappointment with your component, but with tapo, so I hope you do not view it negatively.

**Comment by seocg** [comment]
![Uploading 202310141697268777.jpg…]()

**Comment by JurajNyiri** [comment]
I repeat, again, it is supported. Read readme, faq section your questions are answered there. Once you do, please list steps you have tried from FAQ as instructed, and what was the result in detail.

**Comment by seocg** [comment]
![202310141697274914](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/97216612/549b679e-0ec6-4638-91a7-115478206586)
It is said that it is said that it is said that it is said that it is said that it is said that it is said that!!!!!
What other parts should I look into?

Should I try editing yaml directly? It's not even in the disabled items and there's just no entity there.

**Comment by seocg** [comment]
Are there any photos of your work that I haven't done or uploaded in the faq?
What do emojis mean?
Please post a comment.

**Comment by JurajNyiri** [comment]
You posted screenshot with Chinese and which is not related to this integration, it's some random part of ha. And you were super rude, that is why I put in disappointed smiley face.

Here is the faq and that's the last help you get with this attitude. Thousands before you were able to find it and get it to work or were able to ask about it nicely.
https://github.com/JurajNyiri/HomeAssistant-Tapo-Control#troubleshooting--faq
