### ISSUE TITLE
Feature Request: Additional binary sensors

### ISSUE THREAD

**Issue by samdorrity** [JurajNyiri/HomeAssistant-Tapo-Control#424]
**Is your feature request related to a problem? Please describe.**

The binary motion sensor picks up everything including rain.

**Describe the solution you'd like**

Can we request a binary sensor for other sensors such as person, vehicle and animal binary sensors.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by JurajNyiri** [comment]
https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/304
