### ISSUE TITLE
Tapo C200 HW 1.0 motion sensor still stuck in detected after some time

### ISSUE THREAD

**Issue by eldi0s** [JurajNyiri/HomeAssistant-Tapo-Control#430]
### Description

Hi, I tried everything that I read about this issue here, but nothing resolved it for me. The issue is always coming back after some detections. I'm triggering recordings within HA with the sensor and this is now just flooding my HDD on the server. My other Tapo C310 on 1.3.7 Firmware works as expected.

Things I tried:
- Removed integration completely and reinstalled everything
- Check if instance is reachable via http
- remove cameras
- tried  with webhooks
- tried with pullpoint
- activated debug on this integration and onvif but nothing to see there

### Reproduction Steps

Sometimes within minutes after restart sometimes within hours or even days.

### Expected behavior

Sensor going back to normal after no detection

### Device Firmware

C200 HW 1.0 Firmware 1.3.6

### Using stream component

No

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HA Core 2023.9.3

### Search for similar issues

Yes

### Additional information

Tapo Control 5.3.9

**Comment by JurajNyiri** [comment]
Wait for new firmware, 1.3.6 is buggy firmware. 

This integration reuses onvif official integration for detecting the motion, if there is anything to fix, it will need to be fixed there. Try with that integration for a few days and see if it happens there as well.
