### ISSUE TITLE
Siren switch is not working for C420

### ISSUE THREAD

**Issue by Exelord** [JurajNyiri/HomeAssistant-Tapo-Control#431]
### Description

Hi, 

First of all, I really appreciate your work on this integration! 🙇‍♂️

I want to report a bug with Siren entity and C420 cameras. I know they are battery powered which might be a reason why it's  not possible to use them. However I found this issue after 2 months of usage and I didn't realize they are not working until they alarm went off. I was relaying on this switch to trigger my home alarm as these cameras also don't support motion sensors. 

BTW. Are you aware of any other sensor that could be used to know when alarm has been triggered on cameras?

### Reproduction Steps

1. Switch sirens for C420 cameras.
2. No effect

### Expected behavior

I would be great if the sirens would not be present at all (if they are not supported) to not mislead the users.

### Device Firmware

1.2.14 Build 20230829 rel.65193

### Using stream component

No

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HA OS

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
There is unfortunately no way how to detect whether siren is supported or not.
