### ISSUE TITLE
Feature Request: Motion Dectection for new Cameras with AI-Feature (Persons, Cars, Pets) eg. C225, C325WS

### ISSUE THREAD

**Issue by nafets2** [JurajNyiri/HomeAssistant-Tapo-Control#434]
**Is your feature request related to a problem? Please describe.**
No, It´s not a problem. It a extension to an existing feature

**Describe the solution you'd like**
At the moment it is only possible that the generic Motion Detection can be used in HA. 
My TP-LinkTapo C225 and C325WB Cameras have additional Motion Detection alerts for persons, cars and pets. But this AI alerts do not trigger an alert in HA. It would very useful if all Motion Detections will trigger an HA alarm.
This feature would be very nice, if you can integrate this?

**Describe alternatives you've considered**
I think, there is no alternative possible

**Additional context**
At the moment I have no useful screenshot.

If my request is unclear, or if you need more infos, please contact me.

Thanks,
Stephan

**Comment by nafets2** [comment]
Hello, sorry I Think there are already Feature Requests for the AI Detections. E.g.: #304

Should I Install the onviv extention or, do you add this enhancements in future releases?
Thanks,

Stephan

**Comment by JurajNyiri** [comment]
https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/304
