### ISSUE TITLE
Bug: random strong password does not authenticate

### ISSUE THREAD

**Issue by jwaes** [JurajNyiri/HomeAssistant-Tapo-Control#44]
I created a camera account in the Tapo android app, with a strong randomly generated password 
`?=ml=slOnqg?w?u*`

The account, username and password work, as i can connect to the stream using vlc with that username and password.
However i cannot register the camera using the integration, when i give in the credentials and the ip, i get an authentication error.

When i changed the password of the camera account in the app back to something simple, like 'password123', i could add the camera using the integration.

My guess would be an issue with escaping that password string containing _difficult_ characters.

**Comment by JurajNyiri** [comment]
Hey, thank you for the report! This is most likely an encoding issue as you mentioned. I will take a look at it in upcoming days.

For now you can use a strong password including uppercase, lowercase and numbers. That should work fine.

**Comment by JurajNyiri** [comment]
Fixed in [2.3.1](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/2.3.1).
