### ISSUE TITLE
move_to_preset shows as unknown instead of being disabled

### ISSUE THREAD

**Issue by codyc1515** [JurajNyiri/HomeAssistant-Tapo-Control#445]
### Description

The value of the move_to_preset selection is empty (`unknown`).

![2023-11-08 09_08_04-Clipboard](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/50791984/569f15f0-db59-40dc-8cb1-b2a0dcddab41)
![2023-11-08 09_12_28-Clipboard](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/50791984/99e63eec-dd90-4c80-870f-8f87aec1e830)

### Reproduction Steps

I do not have any preset's set-up.

### Expected behavior

The dropdown should be disabled automatically in that case.

### Device Firmware

1.3.6 Build 230424 Rel.77225n(4555)

### Integration Version

5.4.2

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

OS

### Search for similar issues

Yes

### Additional information

```
access_token: xxx
model_name: C200
brand: TP-Link
motion_detection: on
frontend_stream_type: hls
device_type: SMART.IPCAMERA
device_model: C200
device_name: C200 1.0
device_info: C200 1.0 IPC
hw_version: 1.0
sw_version: 1.3.6 Build 230424 Rel.77225n(4555)
device_alias: Dining Room Camera
avatar: camera c212
longitude: 0
latitude: 0
has_set_location_info: 0
features: 3
barcode: 
mac: 28-EE-52-93-E9-D3
dev_id: 80215ACBBFF1B116E989BD4366B7BBF31E273DDA
oem_id: 8902D2F34FCE407721DE92F5759839C2
hw_desc: 48574445534300000000000000000001
alarm: off
user: homeassistant
presets: 
{}

record_plan: 
sunday: '["0000-2400:2"]'
monday: '["0000-2400:2"]'
tuesday: '["0000-2400:2"]'
wednesday: '["0000-2400:2"]'
thursday: '["0000-2400:2"]'
friday: '["0000-2400:2"]'
saturday: '["0000-2400:2"]'

entity_picture: /api/camera_proxy/camera.dining_room?token=xxx
icon: mdi:webcam
friendly_name: Dining Room Camera
supported_features: 3
```

**Comment by JurajNyiri** [comment]
Correct, camera does not report current state. Not a bug.
