### ISSUE TITLE
Feature Request: In my setup for my Tapo C510W I’m using a 512gb sd card which of course does not require a cloud connection when I try to connect my camera via Tapo: Camera Control it asks for my cloud password which of course I don’t have. Is there a way around this? Currently I’m using the home automation ONVIF Integration to view my camera.

### ISSUE THREAD

**Issue by Baz-ace** [JurajNyiri/HomeAssistant-Tapo-Control#454]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JurajNyiri** [comment]
Do not write everything in title, that is why description exists.

Read the description in integration, it is telling you it is the password you have on your tp link account.

**Comment by Baz-ace** [comment]
Thank you for your help JurajNyiri I’m very grateful for your help
