### ISSUE TITLE
Upgraded Firmware 1.3.9 on Tapo C200 and get Check tapo tag failed when trying to connect

### ISSUE THREAD

**Issue by grunkands** [JurajNyiri/HomeAssistant-Tapo-Control#456]
### Description

Home Assistant version: 2023.10.2
Tapo Cameras Control: 5.4.4
Camera: Topa C200
Camera Firmware that breaks the config  1.3.9
(I have another camera with FW 1.3.6 that works)

After upgrading fw to  1.3.9 on Tapo C200 it will no longer work. Get errors in the logs. 

```
This error originated from a custom integration.

Logger: custom_components.tapo_control
Source: custom_components/tapo_control/config_flow.py:770
Integration: Tapo: Cameras Control (documentation, issues)
First occurred: 16:57:43 (4 occurrences)
Last logged: 17:02:13

Error: -1, Response: {"result": {"responses": [{"msg": "Check tapo tag failed", "error_code": -1}]}, "error_code": -1}

```

I even tried to remove one camera from the configuration and add it again with now luck. Get an error message `Unknown error`

### Reproduction Steps

1. Upgrade camera FW to 1.3.9
2. Restart 
3. Broken in HA (works in the Tapo app so the cameas are working)

### Expected behavior

That camera works and send stream to HA after firmware upgrade. 

### Device Firmware

1.3.9 Build 231019 Rel.38052n(4555)

### Integration Version

5.4.4

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Home Assistant Core

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
I received the update today and my C200 v3.0 works flawlessly.

I will need access to your camera in order to debug this issue further. Please port forward it and share details via juraj.nyiri@gmail.com.

**Comment by grunkands** [comment]
I have version 2.0 if that make any difference. 
I understand it would help to get access to my cameras. But I do not feel comfortable with giving you access to them. 
I can always downgrade to 1.3.6 that seems to work.

**Comment by JurajNyiri** [comment]
That is completely understandable. We will need to wait for someone else to come with the some issue then or maybe it starts happening to me as well. 
You can try using https://github.com/JurajNyiri/pytapo and see if you can replicate the issue there as well. Use "admin" account together with your cloud password. You can also try using 3rd party account with your 3rd party acc and see if that works, each camera is a little bit different in what it accepts.

**Comment by ndrsfr** [comment]
Hi, had the same issue after the firmware update of my C200 to 1.3.9 today.
Was able to solve it by adding my cloud password to the camera config of the integration.

**Comment by JurajNyiri** [comment]
@grunkands does this work for you?

**Comment by jdndm** [comment]
I am also experiencing a similar issue to @grunkands.

Attempting to add a C200 camera to my setup, but getting the error message `Unknown Error`.

![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/20547747/85f9eec2-9501-4d44-b7c4-a650226780e5)

Model: C2000 V2.0
Camera FW: 1.3.9
Tapo Cameras Control: 5.4.4

**Comment by grunkands** [comment]
I do not use the cloud service for my cameras. I have even blocked all internet traffic for them. You can call me paranoid if you like. 😅

I can also try to do some more digging on my side to try to understand what is going on.

**Comment by bysimba** [comment]
Hello yesterday i have the same problem so, i remove the tapo component restart Home Assistant, add again the tapo integration and is ok now Tapo C200

**Comment by JurajNyiri** [comment]
Using cloud service has nothing to do with using the admin account on camera.

As I described above, to move this issue further, try using https://github.com/JurajNyiri/pytapo and see if you can replicate the issue there as well. Use "admin" account together with your cloud password. You can also try using 3rd party account with your 3rd party acc and see if that works, each camera is a little bit different in what it accepts. Post results here.

**Comment by kksligh** [comment]
I have 2 of the exact same cameras:

C211 - Firmware: 1.3.9 Build 231019 Rel.31045n(5553) (**HAS ISSUES BELOW**)
C211 - Firmware: 1.3.7 Build 230823 Rel.55314n(5553) (**NO ISSUES**)

I'm having an issue where sporadically after a restart HA, it will require a re-authentication - which that on its own isn't bad, but the issue is, after I re-authenticate, the functions of the camera do not work.  It throws the following error...

![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/83232851/851df83a-8119-4e06-879d-77f6b65716cb)

Logs are as follows....

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:230
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 9:14:28 AM (1 occurrences)
Last logged: 9:14:28 AM

[140016802176832] Padding is incorrect.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 230, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2035, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2072, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 580, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/tapo_control/light.py", line 76, in async_turn_on
    result = await self._hass.async_add_executor_job(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytapo/__init__.py", line 819, in reverseWhitelampStatus
    return self.executeFunction(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytapo/__init__.py", line 331, in executeFunction
    data = self.performRequest(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytapo/__init__.py", line 420, in performRequest
    responseJSON = json.loads(self.decryptResponse(encryptedResponse))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytapo/__init__.py", line 367, in decryptResponse
    return unpad(pt, AES.block_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/Crypto/Util/Padding.py", line 92, in unpad
    raise ValueError("Padding is incorrect.")
ValueError: Padding is incorrect.



Additional Logs:

Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 9:14:15 AM (10 occurrences)
Last logged: 9:14:15 AM

Error setting up entry 172.16.0.XX for select
Error setting up entry 172.16.0.XX for siren
Error setting up entry 172.16.0.XX for update
Error setting up entry 172.16.0.XX for binary_sensor
Error setting up entry 172.16.0.XX for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 440, in async_setup_entry
    return await component.async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!

**Comment by JurajNyiri** [comment]
@kksligh completely remove the camera, including all references to tapo_control in .storage. then try to add the camera again and document step by step what happened in detail (including whether it asks for cloud PW).

**Comment by kksligh** [comment]
Will do - I’ll get back with you on the results.

Thanks,

Kale Sligh
________________________________

**Comment by Frazou1** [comment]
I have the same issue as well. Try the same step of [bysimba] and doesnt work

**Comment by iwebsource** [comment]
I'm trying to figure this out as well. Just updated the FW on one of my C200 (HWRev.3) to 1.3.9. Now I can no longer pass the third step when adding the Cam (Cloud Password step). Will report back if I can get this working.

**Comment by maroliar** [comment]
Camera Info:
C200 FW1.3.9 Hardware Version: 1.0 Build: 231019 Rel.37378n(4555)

>>> print(tapo.getBasicInfo())
{'device_info': {'basic_info': {'device_type': 'SMART.IPCAMERA', 'device_model': 'C200', 'device_name': 'C200 1.0', 'device_info': 'C200 1.0 IPC', 'hw_version': '1.0', 'sw_ve rsion': '1.3.9 Build 231019 Rel.37378n (4555)', 'device_alias': 'Casa', 'avatar': 'Living room', 'longitude': 0, 'latitude': 0, 'has_set_location_info': 0, 'features': 3', 'barcode': 'mac': '5C-A6-E6-75-3A-6A', 'dev_id': '8021B44D704C54509622286B3E2B6D3C1F395945', 'oem_id': '8902D2F34FCE407721DE92F5759839C2', 'hw_desc': '485744455343000
00000000000000001'}}}

**Comment by boheme61** [comment]
Questions: As i intend to make some tests, but i would like some "background" info
* Which of you guys updated through HA, VS through the Tapo-phone app ?
* Did you have ALL entities enabled in HA ?
* Does any of you guys have HW 1.0 ... or is i just me sitting on "pre-historical devices" ? :)

**Comment by JurajNyiri** [comment]
@maroliar That means it is working. You did not post before, what behaviour are you seeing in HA?

**Comment by maroliar** [comment]
Hi @JurajNyiri, it's exactly the same behavior of @jdndm said. I tried with my 3rd party account and after I tried with this admin.

With my account:

>>> tapo =
Tapo("192.168.1.18", "marcelo", "xxxxxxxxxxx")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/marcelo/.local/lib/python3.9/site-packages/pytapo/__init__.py", line 67, in
self.basicInfo = self.getBasicInfo()
____init____
File "/home/marcelo/.local/lib/python3.9/site-packages/pytapo/__init__.py", line 825, in getBasicInfo return self.executeFunction(
File "/home/marcelo/.local/lib/python3.9/site-packages/pytapo/__init__.py", line 332, in executeFunction data = self.performRequest(
File "/home/marcelo/.local/lib/python3.9/site-packages/pytapo/__init__.py", line 436, in performRequest return self.performRequest(requestData, loginRetryCount + 1)
File "/home/marcelo/.local/lib/python3.9/site-packages/pytapo/__init__.py", line 436, in performRequest return self.performRequest(requestData, loginRetryCount + 1)
File "/home/marcelo/.local/lib/python3.9/site-packages/pytapo/__init__.py", line 438, in performRequest raise Exception(
Exception: Error: -1, Response: {"result": {"responses": [{"msg": "Check tapo tag failed", "error_code": -1}]}, "error_code": -1}

**Comment by yiskang** [comment]
It reports the same error as Marollar does, but switching to admin account with cloud password works.


```python
from pytapo import Tapo

user = "cameraAccountUser" # user you set in Advanced Settings -> Camera Account
password = "cameraAccountPass" # password you set in Advanced Settings -> Camera Account
host = "192.168.xx.xx" # ip of the camera, example: 192.168.1.52

tapo = Tapo(host, user, password)

print(tapo.getBasicInfo())

## Exception: Error: -1, Response: {"result": {"responses": [{"msg": "Check tapo tag failed", "error_code": -1}]}, "error_code": -1}
```

This one works:
```python
from pytapo import Tapo

user = "admin" # user you set in Advanced Settings -> Camera Account
password = "tplinkCloudAccountPass" # password you set in Advanced Settings -> Camera Account
host = "192.168.xx.xx" # ip of the camera, example: 192.168.1.52

tapo = Tapo(host, user, password)

print(tapo.getBasicInfo())
```

**Comment by boheme61** [comment]
FWIW:
I Just updated 1 cam

C200
HW: 1.0
FW: 1.3.9 Build 231019 Rel.37378n(4555)
Tapo Control version: 5.3.9

Working, in 2 different Ha-installs , i could try to update 1 to Tapo Control version: 5.4.4

**Comment by JurajNyiri** [comment]
Thank you @yiskang this is very helpful. I tried it with my 3.0 on the newest firmware but unfortunately that one does not accept 3rd party credentials at all.

One more step needed; Please update to pytapo 3.3.8 `pip install pytapo==3.3.8`.

Then initiate the script like so:

```
from pytapo import Tapo

user = "cameraAccountUser" # user you set in Advanced Settings -> Camera Account
password = "cameraAccountPass" # password you set in Advanced Settings -> Camera Account
host = "192.168.xx.xx" # ip of the camera, example: 192.168.1.52

tapo = Tapo(host, user, password, printDebugInformation=True)

print(tapo.getBasicInfo())
```

Output should have all the confidential data already redacted, please post it here and we will know where exactly the communication fails with 3rd party acc credentials.

**Comment by yiskang** [comment]
Hi @JurajNyiri,

Here is the debug log following your instructions. I truncated some strings in the payloads of requests or responses that I'm unsure if they include confidential info. 

```bash
New request:
{'data': {'method': 'login', 'params': {'encrypt_type': '3', 'username': 'cameraAccountUser'}}, 'headers': {'Host': 'REDACTED', 'Referer': 'REDACTED', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8'}, 'verify': False}
200
{'error_code': -40413, 'result': {'data': {'code': -40401, 'encrypt_type': ['3'], 'key': 'REDACTED', 'nonce': 'REDACTED', 'device_confirm': 'REDACTED'}}}
New request:
{'data': {'method': 'login', 'params': {'cnonce': 'REDACTED', 'encrypt_type': '3', 'username': 'cameraAccountUser'}}, 'headers': {'Host': 'REDACTED', 'Referer': 'REDACTED', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8'}, 'verify': False}
200
{'error_code': -40413, 'result': {'data': {'code': -40401, 'encrypt_type': ['3'], 'key': 'REDACTED', 'nonce': 'REDACTED', 'device_confirm': 'REDACTED'}}}
New request:
{'data': {'method': 'login', 'params': {'cnonce': 'REDACTED', 'encrypt_type': '3', 'digest_passwd': 'REDACTED', 'username': 'cameraAccountUser'}}, 'headers': {'Host': 'REDACTED', 'Referer': 'REDACTED', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8'}, 'verify': False}
200
{'error_code': 0, 'result': {'stok': 'REDACTED', 'user_group': 'third_account', 'start_seq': 739}}
New request:
{'data': {'method': 'securePassthrough', 'params': {'request': 'aqJP...fA'}}, 'headers': {'Host': 'REDACTED', 'Referer': 'REDACTED', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8', 'Seq': '739', 'Tapo_tag': 'REDACTED'}, 'verify': False}
500
{'error_code': 0, 'seq': 739, 'result': {'response': 'Es9...VM6p'}}
New request:
{'data': {'method': 'login', 'params': {'cnonce': 'REDACTED', 'encrypt_type': '3', 'username': 'cameraAccountUser'}}, 'headers': {'Host': 'REDACTED', 'Referer': 'REDACTED', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8', 'Seq': '739', 'Tapo_tag': 'REDACTED'}, 'verify': False}
200
{'error_code': -40413, 'result': {'data': {'code': -40401, 'encrypt_type': ['3'], 'key': 'REDACTED', 'nonce': 'REDACTED', 'device_confirm': 'REDACTED'}}}
New request:
{'data': {'method': 'login', 'params': {'cnonce': 'REDACTED', 'encrypt_type': '3', 'digest_passwd': 'REDACTED', 'username': 'cameraAccountUser'}}, 'headers': {'Host': 'REDACTED', 'Referer': 'REDACTED', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8', 'Seq': '739', 'Tapo_tag': 'REDACTED'}, 'verify': False}
200
{'error_code': 0, 'result': {'stok': 'REDACTED', 'user_group': 'third_account', 'start_seq': 559}}
New request:
{'data': {'method': 'securePassthrough', 'params': {'request': 'DE7Zf...b0Dv0'}}, 'headers': {'Host': 'REDACTED', 'Referer': 'REDACTED', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8', 'Seq': '559', 'Tapo_tag': 'REDACTED'}, 'verify': False}
500
{'error_code': 0, 'seq': 559, 'result': {'response': '1DsffKNKzy...TQgu4'}}
New request:
{'data': {'method': 'login', 'params': {'cnonce': 'REDACTED', 'encrypt_type': '3', 'username': 'cameraAccountUser'}}, 'headers': {'Host': 'REDACTED', 'Referer': 'REDACTED', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8', 'Seq': '559', 'Tapo_tag': 'REDACTED'}, 'verify': False}
200
{'error_code': -40413, 'result': {'data': {'code': -40401, 'encrypt_type': ['3'], 'key': 'REDACTED', 'nonce': 'REDACTED', 'device_confirm': 'REDACTED'}}}
New request:
{'data': {'method': 'login', 'params': {'cnonce': 'REDACTED', 'encrypt_type': '3', 'digest_passwd': 'REDACTED', 'username': 'cameraAccountUser'}}, 'headers': {'Host': 'REDACTED', 'Referer': 'REDACTED', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8', 'Seq': '559', 'Tapo_tag': 'REDACTED'}, 'verify': False}
200
{'error_code': 0, 'result': {'stok': 'REDACTED', 'user_group': 'third_account', 'start_seq': 506}}
New request:
{'data': {'method': 'securePassthrough', 'params': {'request': '32ocm...AsG'}}, 'headers': {'Host': 'REDACTED', 'Referer': 'REDACTED', 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Tapo CameraClient Android', 'Connection': 'close', 'requestByApp': 'true', 'Content-Type': 'application/json; charset=UTF-8', 'Seq': '506', 'Tapo_tag': 'REDACTED'}, 'verify': False}
500
{'error_code': 0, 'seq': 506, 'result': {'response': 'gS...Rz'}}
```

Exception log when using 3.3.8
```python
Traceback (most recent call last):
  File "/Users/kang/Desktop/tapo/tapo.py", line 7, in <module>
    tapo = Tapo(host, user, password, printDebugInformation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytapo/__init__.py", line 77, in __init__
    self.basicInfo = self.getBasicInfo()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytapo/__init__.py", line 906, in getBasicInfo
    return self.executeFunction(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytapo/__init__.py", line 413, in executeFunction
    data = self.performRequest(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytapo/__init__.py", line 517, in performRequest
    return self.performRequest(requestData, loginRetryCount + 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytapo/__init__.py", line 517, in performRequest
    return self.performRequest(requestData, loginRetryCount + 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytapo/__init__.py", line 519, in performRequest
    raise Exception(
Exception: Error: -1, Response: {"result": {"responses": [{"msg": "Check tapo tag failed", "error_code": -1}]}, "error_code": -1}
```

**Comment by JurajNyiri** [comment]
@yiskang @maroliar @iwebsource @Frazou1 @bysimba @grunkands @jdndm @ndrsfr 
Please test with https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.4.6 .

In case of problem still persisting:

Add following to configuration.yaml:
```
logger:
  logs:
    custom_components.tapo_control: debug
```

Post full log in case of an error.

If you see `Incorrect pytapo version installed` error on start, fix your environment.

**Comment by Frazou1** [comment]
Newbi question but i cant find the new update? Or maybe i dont look at the right place


Alexandre Fraser
418-208-6556
***@***.***

Le 15 nov. 2023 à 07:51, Juraj Nyíri ***@***.***> a écrit :

﻿

@yiskang<https://github.com/yiskang> @maroliar<https://github.com/maroliar> @iwebsource<https://github.com/iwebsource> @Frazou1<https://github.com/Frazou1> @bysimba<https://github.com/bysimba> @grunkands<https://github.com/grunkands> @jdndm<https://github.com/jdndm> @ndrsfr<https://github.com/ndrsfr>
Please test with https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.4.6 and confirm the fix working.

In case of problem still persisting:

Add following to configuration.yaml:

logger:
  logs:
    custom_components.tapo_control: debug


Post full log in case of an error.

If you see Incorrect pytapo version installed error on start, fix your environment.

**Comment by JurajNyiri** [comment]
It is linked in the post you are posting reply to. If you are using HACS it should show up soon or you can force the install by going to `/hacs/repository/300358676` in your HA instance clicking 3 dots and selecting Redownload.
If you are not using hacs, just install manually as you did before. (You should be using HACS though.).

**Comment by yiskang** [comment]
@JurajNyiri Thanks a ton for your prompt help! I confirmed that [5.4.6](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.4.6) works and fixes the issue on my side. 

My devices:
- Device: C200
- Hardware: 2.0 & 3.0
- Fireware: 1.3.9 Build 231019 Rel.38052n(5553)

**Comment by grunkands** [comment]
@JurajNyiri Thank you so much for the quick solution to this problem! ⭐️

**Comment by Frazou1** [comment]
Work great !! Wonderful and quick fix that why i choose tapo and Ha ! Thansk you very much


Alexandre Fraser
418-208-6556
***@***.***

Le 15 nov. 2023 à 08:17, Juraj Nyíri ***@***.***> a écrit :

﻿

It is linked in the post you are posting reply to. If you are using HACS it should show up soon or you can force the install by going to /hacs/repository/300358676 in your HA instance clicking 3 dots and selecting Redownload.
If you are not using hacs, just install manually as you did before. (You should be using HACS though.).

**Comment by brianjmurrell** [comment]
> I do not use the cloud service for my cameras. I have even blocked all internet traffic for them. You can call me paranoid if you like. 😅
> 
> I can also try to do some more digging on my side to try to understand what is going on.

This is my general feeling about IoT devices, and in particular cameras.  But then how do you do firmware updates?  We all know that out-of-date firmwares are one of the bigger vectors to cracking these kinds of devices.
