### ISSUE TITLE
Reach cameras outside local network with custom port mappings

### ISSUE THREAD

**Issue by Ontrackx** [JurajNyiri/HomeAssistant-Tapo-Control#459]
### Description

As described or some other advanced networking, make sure ports 443, 554 and 2020 are opened for camera.
But for my instances there are serveral cameras on the remote site. And need hav to port forward each camera with unique port.
Camera 1 :  
Port 2020-mapped to 1985
Port 554-mapped to 555
Port 443-not mapped

Camera 2 :  
Port 2020-mapped to 1986
Port 554-mapped to 556
Port 443-not mapped

This works to fetch the cameras with my NVR but not in the addon.

Is this possible?

### Reproduction Steps

adding  remote camera

### Expected behavior

adding  remote camera with custom port map like ip:port number

### Device Firmware

we

### Integration Version

latest

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/375
