### ISSUE TITLE
Bug: No Home Assistant Integration Entry

### ISSUE THREAD

**Issue by jcbagtas** [JurajNyiri/HomeAssistant-Tapo-Control#46]
**Describe the bug**
After Installing via HACS and Manually,
There is no "Tapo" entry in the Configuration>Integration-UI Dropdown

![image](https://user-images.githubusercontent.com/17738997/101261539-12bbdb00-3773-11eb-8ecd-f672651574c8.png)

**To Reproduce**
1. Follow the Installation from [HomeAssistant-Tapo-Control](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/blob/main/README.md)
2. Restart Home Assistant Service
3. Go to Configuration>Integrations
4. Try to find "Tapo" in the choices

**Expected behavior**
There is a "Tapo" integration.

**Log**
No Error logs, just warning

```
2020-12-06 03:15:16 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for tapo_control which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
```

**Camera (please complete the following information):**
 - Device Model: TP Link Tapo C200

**Using stream component**
The Camera has a Stream out of the box but not in HA

**Camera works through onvif component OR different cameras work in general**
The Camera Works out of the box but not in HA

**Camera has all attributes filled out properly in developer tools**
Not sure where I can find this

**HASS Environment**

|Key|Value|
|--|--|
|Raspberry Pi 4|Model B 8GB RAM|
|Version | 0.118.5|
|Installation Type | Home Assistant OS|
|Development | false|
|Supervisor | true|
|Docker | true|
|Virtual Environment | false|
|Python Version | 3.8.6|
|Operating System Family | Linux|
|Operating System Version | 4.19.127-v8|
|CPU Architecture | aarch64|
|Host Operating System | HassOS 4.17|
|Update Channel | stable|
|Supervisor Version | 2020.12.6|
|Docker Version | 19.03.12|
|Disk Total | 28.6 GB|
|Disk Used | 3.9 GB|
|Healthy | true|
|Supported | true|
|Board | rpi4-64|
|Supervisor API | ok|
|Version API | ok|

**Additional context**
There was no error upon installation. There is just now Tapo entry as stated in the documentation.

> Add cameras via Integrations (search for Tapo) in Home Assistant UI.

**Comment by JurajNyiri** [comment]
1.) Restart Home Assistant after installing integration
2.) Hard refresh your browser (clear cache)

**Comment by KonTiki1957** [comment]
good evening to everyone, same issue here even after having reinstalled, restarted many times and cleared the cache. what else can be done?
