### ISSUE TITLE
It is no longer possible to stream audio to the camera

### ISSUE THREAD

**Issue by thespainfluencer** [JurajNyiri/HomeAssistant-Tapo-Control#461]
### Description

On Home Assistant I have always played audio using the Media Extractor service and now, after updating the firmware, it stopped working.

### Reproduction Steps

Try streaming audio to the cameras through Home Assistant.

### Expected behavior

I would like to be able to stream audio to the cameras like we did before the update.

### Device Firmware

1.3.9 Built 231019 Rel.31045n(4555)

### Integration Version

5.4.6

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

RaspberryPi 4

### Search for similar issues

Yes

**Comment by thespainfluencer** [comment]
Logger: homeassistant.core
Source: core.py:2051
First occurred: 21:56:01 (5 occurrences)
Last logged: 22:13:21

Error executing service: <ServiceCall media_player.play_media (c:01HFCYPNRP0K060RM9QDD8BDJD): extra=, entity_id=['media_player.tapo_soggiorno_2'], media_type=MUSIC, media_id=http://homeassistant.local:8123/local/audio/campanello.mp3>
Error executing service: <ServiceCall media_player.play_media (c:01HFCYPY94EM0EHMFYRXYDR92Z): extra=, entity_id=['media_player.tapo_cucina'], media_type=MUSIC, media_id=http://homeassistant.local:8123/local/audio/campanello.mp3>
Error executing service: <ServiceCall media_player.play_media (c:01HFCYTP4SVS5FBJBVQJZ0NK18): extra=, entity_id=['media_player.tapo_soggiorno_2'], media_type=MUSIC, media_id=http://homeassistant.local:8123/local/audio/campanello.mp3>
Error executing service: <ServiceCall media_player.play_media (c:01HFCZE6GC8V3MFBE0VHD0A1DX): extra=, entity_id=['media_player.tapo_soggiorno_2'], media_type=MUSIC, media_id=http://homeassistant.local:8123/local/audio/portaingressoaperta.mp3>
Error executing service: <ServiceCall media_player.play_media (c:01HFCZPD1T3272SCZ39DH73H05): extra=, entity_id=['media_player.tapo_cucina'], media_type=MUSIC, media_id=http://homeassistant.local:8123/local/audio/campanello.mp3>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2051, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2072, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/webrtc/media_player.py", line 74, in async_play_media
    assert r.ok
AssertionError

**Comment by JurajNyiri** [comment]
It was never possible through this integration.
