### ISSUE TITLE
C310 - entity "Cell Motion Detection" not available

### ISSUE THREAD

**Issue by MartinGoX** [JurajNyiri/HomeAssistant-Tapo-Control#468]
### Description

Hello.
After an TAPO integration update (or as well sometimes after HA update/restart) the "Cell Motion Detection" entity is not available.
I know that it is created dynamic and I have already tried all the things listed in the 'Trouble shooting / FAQ' section of your description - but it doesn't help at all.
In the past it did a "self-repair", so the entity appears after a while without any help from me. Sometimes it was available after several restarts of the TAPO integration, sometimes after switching privacy mode off/on. But now it remains for already 16 hours in the state 'not available'. Here is the original German message:
Diese Entität wird nicht mehr von der Integration tapo_control bereitgestellt. Wenn die Entität nicht mehr verwendet wird, lösche sie in den Einstellungen.
I have a second camera, model C510. Here the problem doesn't occur.

### Reproduction Steps

As already explained above the problem occurs
- after an update of TAPO integration in HACS
- after a restart of HA

### Expected behavior

Immediate availability of entity "Cell Motion Detection" after update and/or restart.
Better: do not dynamically create this entity but create it always/static.

### Device Firmware

1.3.9 b231024 r62920n (4555)

### Integration Version

5.4.10

### Using stream component

No

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HACS

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Read faq. Try with onvif integration instead.

**Comment by MartinGoX** [comment]
Hi Juraj,

I've installed the ONVIF integration and set up the C310 (where I had 
the problem with). The 'Cell Motion Detection' sensor is working!

Before the above I removed the C310 from your TAPO integration (my C510 
still remained) and afterwards I added the C310 again. Now I have a 
mixture of both integrations for the C310 which seems to work. To be 
more sure I disabled all entities except 'Cell Motion Detection' inside 
ONVIF.

Do you see any problems withh that?

Best regards
Martin


------ Originalnachricht ------
Von "Juraj Nyíri" ***@***.***>
An "JurajNyiri/HomeAssistant-Tapo-Control" 
***@***.***>
Cc "MartinGoX" ***@***.***>; "Author" 
***@***.***>
Datum 20.11.2023 10:08:26
Betreff Re: [JurajNyiri/HomeAssistant-Tapo-Control] C310 - entity "Cell 
Motion Detection" not available (Issue #468)

**Comment by JurajNyiri** [comment]
Glad to hear you got it working! You should have only 1 integration (this one) for the camera, otherwise you overload it unnecessarily.

**Comment by MartinGoX** [comment]
Hi.
I think with "this one" you mean your integration. But this one doesn't 
provide the cell motion entity any more - but the ONVIF integration.
That's the reason why I have both integrations in use but everything 
disabled in ONVIF except cell motion. All other information I fetch from 
yours integration.

Best regards
Martin


------ Originalnachricht ------
Von "Juraj Nyíri" ***@***.***>
An "JurajNyiri/HomeAssistant-Tapo-Control" 
***@***.***>
Cc "MartinGoX" ***@***.***>; "Author" 
***@***.***>
Datum 21.11.2023 14:04:23
Betreff Re: [JurajNyiri/HomeAssistant-Tapo-Control] C310 - entity "Cell 
Motion Detection" not available (Issue #468)

**Comment by JurajNyiri** [comment]
Yes that should be ok.

**Comment by reloadxero** [comment]
C310 cell motion not appearing, neither on onvif nor on TCC
I'm on version 5.4.12 for Tapo: Cameras Control and Firmware 1.3.11 Build 231116.

Sorry don't know what other info to provide, just wanted to put it out here if anyone else is experiencing the same issue.
