### ISSUE TITLE
Cloud Authentification ?

### ISSUE THREAD

**Issue by Shinichi76** [JurajNyiri/HomeAssistant-Tapo-Control#469]
### Description

Until today, camera control was available with a tapo account only. Now, it requires cloud credentials ? Is it a new feature, or a bug ? My account is a free one, without cloud access... I would like to know if I must create one.
Thx

### Reproduction Steps

No stream
No Control
No Detection

### Expected behavior

Authentification with account credentials only

### Device Firmware

1.3.9 Build 231019 Rel.38052n(4555)

### Integration Version

5.4.10

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

rPi4

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
New firmware requires TPLink cloud password in order to control camera locally.
