### ISSUE TITLE
Information on RTSP & 1.3.9

### ISSUE THREAD

**Issue by strickersuk** [JurajNyiri/HomeAssistant-Tapo-Control#473]
### Description

Apologies, this isn't a bug but there seems to be lots of issues with RTSP and ONVIF not working on C100/C200 cameras after the latest update. The ports are open and we can ping the cameras but can't connect. If anyone is having trouble like me then head over to the TP-LINK Smart Home Community forums. I haven't found a fix yet.

### Reproduction Steps

C100 with integration.

### Expected behavior

Prior to 1.3.9

### Device Firmware

1.3.9

### Integration Version

5.4.12

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HAOS

### Search for similar issues

Yes

**Comment by Shinichi76** [comment]
Same here, SDStream and HDStream are unavailable...

**Comment by JurajNyiri** [comment]
Read FAQ, closing due to this not being an integration issue.
