### ISSUE TITLE
Feature Request:  to many options

### ISSUE THREAD

**Issue by ewonais** [JurajNyiri/HomeAssistant-Tapo-Control#474]
**Is your feature request related to a problem? Please describe.**
vhen making automations in the gui there is a crapton (mutch mor then the image show) of options, most are redundent, hard and timeconsuming to find the right one.

**Describe the solution you'd like**
remove redundent opotions and split the rest as suboptions if possible

**Additional context**
![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/86527854/6caf0637-e444-48a5-aa5e-2833779c2379)
![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/86527854/e7890e9f-73aa-4f68-ad1a-89f8596feba6)

**Comment by JurajNyiri** [comment]
This is controlled by HA. Choose a correct service first and then an entity and it's super easy to set up.
