### ISSUE TITLE
C500 missing State Recording

### ISSUE THREAD

**Issue by Frazou1** [JurajNyiri/HomeAssistant-Tapo-Control#476]
### Description

I have a Tapo C500 and look like they missing the state recording.

### Reproduction Steps

I look into developper mode and no recording state or entity exist

### Expected behavior

Does they missing something ?

### Device Firmware

1.39

### Integration Version

5.4.12

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

No

### HASS Environment

Appliance Linux

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
What do you mean by "state recording"?

Please edit the description and if it is valid we will reopen.

**Comment by Frazou1** [comment]
My other Tapo Camera have this state and im using to stream in lovelance :  
![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/89617565/84d7736c-5fa6-4f11-863b-f5c5bbb629f8)

**Comment by JurajNyiri** [comment]
There is no recording state for cameras in this integration. Please open new feature request what you would like to see, why and when.
