### ISSUE TITLE
Error: Home Assistant is running on HTTPS or it was not able to detect base_url schema. Disabling webhooks. 

### ISSUE THREAD

**Issue by dankocrnkovic** [JurajNyiri/HomeAssistant-Tapo-Control#479]
### Description

HA is only awailable on HTTPS. External and internal urls are https
On HA Boot logs message:
Logger: custom_components.tapo_control
Source: custom_components/tapo_control/__init__.py:313
Integration: Tapo: Cameras Control ([documentation](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control), [issues](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues))
First occurred: 17:24:14 (1 occurrences)
Last logged: 17:24:14

Home Assistant is running on HTTPS or it was not able to detect base_url schema. Disabling webhooks. 

base_url is depriciated.

As it seams integration is working but I dont know it is degrades in any way.

### Reproduction Steps

Set HA external and internal urls to https
Reboot HA
Find log message:
Logger: custom_components.tapo_control
Source: custom_components/tapo_control/__init__.py:313
Integration: Tapo: Cameras Control ([documentation](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control), [issues](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues))
First occurred: 17:24:14 (1 occurrences)
Last logged: 17:24:14

### Expected behavior

No errors in log

### Device Firmware

1.3.9 Build 231024 Rel.73362n(4555)

### Integration Version

5.4.12

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

VM on Synology NAS

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Works as expected. Motion events might not work because of the setup. Read readme faq.

**Comment by TCB13** [comment]
So, you can't have HA running on HTTPs and expect to have working motion detection? Is that it?
