### ISSUE TITLE
Cloud Authentication is declared as needed but it is not (or at least not always).

### ISSUE THREAD

**Issue by distante** [JurajNyiri/HomeAssistant-Tapo-Control#485]
### Description

As per https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/469#issuecomment-1819248030
> New firmware requires TPLink account password in order to control camera locally. You already have one which you used for official app.

I have several Tapo C200 cameras with firmware `1.3.9 (Build 231019 Rel.37378n(4555)` and C210 with firmware `1.39 (Build 231019 Rel.31045n(4555)` and I can control them using the [TinyCam app on Android ](https://play.google.com/store/apps/details?id=com.alexvas.dvr&hl=en) without the need to put any cloud password.

Why would it be different for HA control?

### Reproduction Steps

1. Try to add a camera
2. Put local password

### Expected behavior

Cloud auth should be optional if needed for some special cameras.

### Device Firmware

1.3.9 (Build 231019 Rel.37378n(4555)

### Integration Version

5.4.12

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

VM in Proxmox

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
It is needed.

**Comment by distante** [comment]
> It is needed.

My I ask, why exactly?

**Comment by JurajNyiri** [comment]
See edit.

**Comment by distante** [comment]
Understood
