### ISSUE TITLE
Feature Request: activate Marked Positions

### ISSUE THREAD

**Issue by stloewen** [JurajNyiri/HomeAssistant-Tapo-Control#49]
Hi,

Thanks for the integration.
Would it be possible to activate marked positions from inside Home Assistant? I would like to turn the camera to certain marked positions at certain times. 

Camera Model: C200

**Comment by JurajNyiri** [comment]
Yes, use ptz with preset property. Read readme

**Comment by stloewen** [comment]
Oh. Didn't see that. I'm sorry!
