### ISSUE TITLE
Feature Request: Allow alternative Port options for Home assistant Login Details 

### ISSUE THREAD

**Issue by maz199312** [JurajNyiri/HomeAssistant-Tapo-Control#490]
**Is your feature request related to a problem? Please describe.*yes*
I have 2 cameras setup at another location and both need to be port forwarded to access but of course only one can have the port 554 as the unique Port , the other camera has to have a * Public * Facing port E.g 5544 which internally forwards to 554 at the other cameras ip address  and of course the login details on the HA setup will only look for port 554 by default so i would liking to see if we could add an option to change the port under an advanced menu option when popping in credentials because when i pop in the address with :5544 at the end the link shows cant connect yet it works and i have tested this working as the camera works normally in the rtsp stream on HA i just cant setup the functions to access the reboot commands and such via HA because of the port limitation with login details 

**Describe the solution you'd like**
Potentially add / change for an option to change the Port upon login authentication entry screen 

**Describe alternatives you've considered**
any way where we can set the facing port to another port while it still retains the 554 in the background

**Comment by JurajNyiri** [comment]
https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/375

**Comment by JurajNyiri** [comment]
Port forwarding the camera is also a terrible idea and you will get hacked eventually.
