### ISSUE TITLE
Service not found (tap action switch.privacy)

### ISSUE THREAD

**Issue by ciclocaffe** [JurajNyiri/HomeAssistant-Tapo-Control#491]
### Description

Hi, I get a "service not found error" when I try to execture tap_action to switch privacy on/off. The code is copied from "custom stack in card lovelace examples .

### Reproduction Steps

Full lovelace stack in card code

`type: custom:stack-in-card
cards:
  - type: picture-entity
    entity: camera.camera3_hd_stream
  - type: horizontal-stack
    cards:
      - type: button
        icon: mdi:arrow-left-drop-circle-outline
        tap_action:
          action: call-service
          service: button.press
          service_data:
            entity_id: button.camera3_move_left
        entity_id: camera.camera3_hd_stream
      - type: button
        icon: mdi:arrow-up-drop-circle-outline
        tap_action:
          action: call-service
          service: button.press
          service_data:
            entity_id: button.camera3_move_up
        entity_id: camera.camera3_hd_stream
      - type: button
        icon: mdi:arrow-down-drop-circle-outline
        tap_action:
          action: call-service
          service: button.press
          service_data:
            entity_id: button.camera3_move_down
        entity_id: camera.camera3_hd_stream
      - type: button
        icon: mdi:arrow-right-drop-circle-outline
        tap_action:
          action: call-service
          service: button.press
          service_data:
            entity_id: button.camera3_move_right
        entity_id: camera.camera3_hd_stream
      - type: button
        icon: mdi:eye-off-outline
        tap_action:
          action: call-service
          service: switch.camera3_privacy
        entity_id: camera.camera3_hd_stream
`

### Expected behavior

privacy should turn on or off when switch is pressed

### Device Firmware

1.3.11 Build 231117 

### Integration Version

latest

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Rpi4

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
You have entity_id there twice, that is not the way how it is in the docs. Docs work.

**Comment by ciclocaffe** [comment]
Hi, sorry I don't understand then., In your examples you are using scripts which I'm not using. In the integration I found the entity switch.camera3_privacy and I just need to trigger that on tap_action. I don't see an example using that and I'm not understanding where the mistake is..?
thanks

**Comment by JurajNyiri** [comment]
<img width="370" alt="Screenshot 2024-01-04 at 14 21 23" src="https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/5785999/0b354acb-88da-42cf-8c20-777b84586553">

You have entity_id there twice which is incorrect, there is no button.press service on camera entity. 

As for switch services, see https://www.home-assistant.io/integrations/switch/ .

**Comment by ciclocaffe** [comment]
I see that's the same in the card stack in example:

`type: custom:stack-in-card
cards:
  - type: custom:webrtc-camera
    entity: camera.bedroom_sd
  - type: horizontal-stack
    cards:
      - type: button
        icon: mdi:arrow-left-drop-circle-outline
        tap_action:
          action: call-service
          service: button.press
          service_data:
            entity_id: button.bedroom_move_left
        entity_id: camera.bedroom_sd`

also these buttons are working fine. I managed to get the switch working somehow:

`      - type: button
        icon: mdi:eye-off-outline
        tap_action:
          action: call-service
          service: switch.toggle
          service_data:
            entity_id: switch.camera3_privacy
        entity_id: camera.camera3_hd_stream`

thanks

**Comment by JurajNyiri** [comment]
[You see wrong,](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/blob/main/examples/EXAMPLES_LOVELACE.md#camera-control-example-with-webrtc-and-scripts-using-stack-in-card) there is only 1 entity there and the full example works.

**Comment by JurajNyiri** [comment]
There are 2 entities [there](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/blob/main/examples/EXAMPLES_LOVELACE.md#camera-control-example-with-webrtc-and-scripts-using-stack-in-card) but the padding matters, it got lost in your code since it was not formatted properly.


Glad you got it working!
