### ISSUE TITLE
Home Assistant 2014.01 deprecates camera services

### ISSUE THREAD

**Issue by sca075** [JurajNyiri/HomeAssistant-Tapo-Control#494]
### Description

I am developing / maintaining a camera too and I use this integration. It is just to give you an head up.
The services for the cameras are now redesigned in home assistant and since version 2024.01 this could cause a brake down of this integration, please check the camera example on the core GitHub for the details.

### Reproduction Steps

Installing the beta version of Home Assistant, it was reported from one of my users, I do not know if you already implemented the required changes.

### Expected behavior

No Deprecation Warnings at 2014.01 release.

### Device Firmware

Not relevant 

### Integration Version

Last

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker on Debian Server 

### Search for similar issues

No

### Additional information

Of course this is intended just as an head up, thanks for considering it

**Comment by JurajNyiri** [comment]
https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/492
