### ISSUE TITLE
Feature Request: Service for Night Vision selection

### ISSUE THREAD

**Issue by Hood-fr** [JurajNyiri/HomeAssistant-Tapo-Control#495]
In some light context, the auto mode for night vision selection keeps on coming and going every minute, which is annoying. I know there is a select.night_vision entity to show on a card, but cannot find how to activate it through an automation

I would like to be able to force it depending on external trigger, sunset/ sunrise, light setting  & stuff

Would it be possible to have a tapo_control service that allows to force the night vision mode ? (and all other select.* entities by the way)

Thanks in advance

**Comment by JurajNyiri** [comment]
Use the select services from ha in automation. Google doc.

**Comment by Hood-fr** [comment]
This is the only two service I see are these two 
<img width="286" alt="image" src="https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/36336734/da36807f-ca4c-46e5-8e6c-81b64d8ef278">

**Comment by Hood-fr** [comment]
OK i understood my mistake, sorry for the bother
