### ISSUE TITLE
Bug: Home Assistant Core 2020.12.0 breaks integration

### ISSUE THREAD

**Issue by tescophil** [JurajNyiri/HomeAssistant-Tapo-Control#50]
**Describe the bug**
The latest release of home assistant breaks the integration, all devices become unavailable. Nothing in my logs, and when I remove and re-add a camera the UI just says "Unknown Error" This could be the same as the issue titled "Incompatible with 1.0.0(b0)", but I don't recognise that version number system for HA.

**To Reproduce**
Install HA release 2020.12.0

**Expected behavior**
Not to break

**Log**
No logs on my system

**Camera (please complete the following information):**
 - C200, HW version 1.0, Firmware 1.0.17

**Using stream component**
[yes

**Camera works through onvif component OR different cameras work in general**
unknown

**Camera has all attributes filled out properly in developer tools**
no, entity disabled

**HASS Environment**
Home Assistant OS 5.8 on Raspberry Pi 3B+

**Additional context**

**Comment by JurajNyiri** [comment]
It's most probably the same as https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/43

There should be logs in your system. 

Did you update to the **latest** version 2.3.3?

**Comment by tescophil** [comment]
Updated to the latest version, then upgraded to 2020.12.0 again and all is well

Perfect, thanks.

**Comment by tescophil** [comment]
Job done
