### ISSUE TITLE
Invalid Cloud Password Error

### ISSUE THREAD

**Issue by kiwii25** [JurajNyiri/HomeAssistant-Tapo-Control#501]
### Description

Upon creating/ linking the cameras to HA via the intergation, it says my cloud password is invalid.

I am 1000% sure it is the correct password.

Tapo C320 

### Reproduction Steps

<img width="603" alt="Screenshot 2024-01-14 at 18 21 30" src="https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/129169050/113a9775-4b9e-46f6-9e89-765a7f1129e8">

### Expected behavior

Accept the password and load the integration for the first time/ a working camera stream.

### Device Firmware

1.3.9 Build 231024 Rel.7332n(4555)

### Integration Version

n/a

### Using stream component

Yes

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HA OS on Proxmox VE

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
> Integration Version
> n/a
First, make sure to use the latest version.

1. Reset your password
2. Make sure your camera can access the internet
3. Reboot it a few times
4. Remove the camera from account
5. Factory reset
6. Add it back, with internet access
7. Add to this integration, it will work if you are entering correct password.

**Comment by aritzvinagre** [comment]
> > Versión de integración 
> > n/a
> 
> Primero, asegúrese de utilizar la última versión.
> 
> 1. Restablecer su contraseña
> 2. Asegúrese de que su cámara pueda acceder a Internet
> 3. Reinícialo varias veces
> 4. Quitar la cámara de la cuenta
> 5. Restablecimiento de fábrica
> 6. Agréguelo nuevamente, con acceso a Internet
> 7. Agregue a esta integración, funcionará si ingresa la contraseña correcta.



Esto sigue funcionando? Imposible vincular unantapp c212 nueva....

**Comment by RealCommerzpunk** [comment]
I just got a new Tapo C225 V2.x
Firmware is 1.0.7
Integration Version is 5.4.18

Camera is in the network, has internet access and is visible and controllable in the Tapo app.

I did all the steps above a hundred times, I am 100% sure to use the correct camera account credentials and a different password for my cloud account.

Finally, it does still reject the cloud password and i have no more ideas what to try.

Any help or ideas?

**Comment by JurajNyiri** [comment]
Yes see pinned issue.

**Comment by RealCommerzpunk** [comment]
OK, sorry, I did see that of course, but it is not clear at the first look, it's **this** issue. The whole process feels like I am doing a mistake or mixing up my setup.

Just a very little and friendly hint: Maybe you change 2 little things to get less messages from idiots like me ;)

1. Integrate the words "Invalid cloud password" in the pinned topics headline to make it more clear that's the error. For me, the statement "makes the integration stop working" was a different kind of issue then my experience being unable to set it up for the first time.

2. The FAQ / Troubleshooting for "Invalid cloud password" in the integrations' description sound like a general and just normal procedure. Maybe you can add a more clear warning there, that there is a explicit issue there right now, that can not be solved by following the steps.

Thanks for your work, your last info updates from today sounds promising, so i will just wait a few days or weeks for the new "official" method.

Thanks, have a nice day!

**Comment by JurajNyiri** [comment]
Thank you for the feedback @RealCommerzpunk . You’re right I will update the docs and the issue soon to make it clearer.

**Comment by JurajNyiri** [comment]
Updated both, @RealCommerzpunk hopefully this is now more apparent.

**Comment by onkeloki** [comment]
same here, with all my tapo devices:
c100 +  c200
message: Invalid cloud password. Make sure you are entering the password for your cloud account and NOT the password which you created via the camera settings (unless they are the same). You need to enter password which you used with your email when signing into the Tapo app.

thinks i have done:
factory reset
change passwords
disable 2fa

without luck

**Comment by FlyingFinn11** [comment]
I can confirm I'm having the same problem. Restarted, reset etc still run into invalid cloud password.
