### ISSUE TITLE
Feature Request:Monitor WiFi signal strength for Tapo cameras

### ISSUE THREAD

**Issue by steviebug** [JurajNyiri/HomeAssistant-Tapo-Control#502]
**Is your feature request related to a problem? Please describe.**
I need to investigate WiFi signal strength related to my Tapo cameras. I suspect one of them is too far from the AP.

**Describe the solution you'd like**
I see from Tapo app that signal strenght is visible and can be visually checked. I would like to have this information stored by HA, so that I could check a graph to undestand if during the day the WiFi signal strenght decreases too much.

**Describe alternatives you've considered**
I have tried monitoring from OpenWrt router, but HA integration does not contain a sensor with signal strength for connected devices.

**Comment by JurajNyiri** [comment]
Now available in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.4.14 .
