### ISSUE TITLE
Invalid authentication data

### ISSUE THREAD

**Issue by TraipZe** [JurajNyiri/HomeAssistant-Tapo-Control#503]
### Description

When i try to add the camera in home assistant ill get Invalid authentication data

### Reproduction Steps

i have added the addon in HACS
Then i go to integrations

search for tapo
then tapo camera control comes up
then i fill in ip adress press next
then it ask for username & pass
ill write in the account info i have added in the tapo app

then ill get this nvalid authentication data. Make sure you have created your 3rd party account via Tapo app. You can also test if these credentials work via rtsp stream, for example VLC using link rtsp://username:password@IP Address:554/stream1

### Expected behavior

I did expect i could login wih the 3th part account in tapo app

### If applicable, add error logs.

-

### Device Firmware

1.1.7 build 231122 rel.55299

### Integration Version

 5.4.14

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

homeass OS on Nuc

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Read faq.

**Comment by danktankk** [comment]
same problem all this time later. this does not seem to have any rhyme or reason. Now I cant get it to add the camera back at all. why are so many people having such an issue with IP/user/pass? this cant be on us for every post

**Comment by JurajNyiri** [comment]
The issue you are searching for:

    Is pinned under issues
    Has a section in main readme file with big title right at the top
    Has 3 red exclamations marks in the title
    Contains a workaround both for accounts still working and the ones affected.

And a warning was sent a month ago as an update via HACS.

You can find it at https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/551.

Please do not post me too comments or any other comment that does not provide any value to the discussion as everyone monitoring it gets notified. If the comments with no value continue maintainer will be forced to lock the issue to contributors only.
