### ISSUE TITLE
Move to preset unavailable 

### ISSUE THREAD

**Issue by roisec** [JurajNyiri/HomeAssistant-Tapo-Control#508]
### Description

Hi 
Thanks for this project.
I have the move to preset is unavailable?
any idea why?

The camera is C200
by TP-Link

<img width="1252" alt="image" src="https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/68992144/1daa0053-c684-4c1d-b70d-7be61adff28a">

### Reproduction Steps

See the move to preset is unavailable

### Expected behavior

The entity will be available.

### Device Firmware

Firmware: 1.3.11 Build 231115 Rel.85400n(4555)

### Integration Version

latest

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker on Raspberry pi

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
You might not have any presets.
The camera might be unavailable.
Or the privacy mode is on.

**Comment by KostaMadorsky** [comment]
Sometimes it takes a long time to update the state and get the preset available after Privacy Mode was disabled.
The icon of the Privacy mode also changes, and it also takes a long time from time to time.

I have C200 and TC71. The later usually gets the preset available sooner after Privacy Mode is disabled.
