### ISSUE TITLE
Invalid authentication data

### ISSUE THREAD

**Issue by briberolles** [JurajNyiri/HomeAssistant-Tapo-Control#510]
### Description

I can't registered my Tapo Camaras... C320WS
Camara account created in the Tapo App for the camara
Good User/pwd but no access by RTSP (by VLC neither)
Ports 443 & 554 OPENED
Port 2020 CLOSED

### Reproduction Steps

adding a new TAPO camara...

### Expected behavior

I want to register my TAPO camaras in Home assistant
Actually i don't have any TAPO camaras regsitered with this integration

### Device Firmware

1.1.7

### Integration Version

5.4.14

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Home Assistant Green / Tapo APP

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Read FAQ.

**Comment by briberolles** [comment]
> Read FAQ.

Yes i've read FAQs but i can't register my TAPO camaras...
You are sure that we can do it with this firmware ?
Perhaps a config on camaras or TAPO App because i can't access by VLC neither...
Thanks
Bruno

**Comment by JurajNyiri** [comment]
You are hitting the limit of maximum concurrent streams like described in faq or haven't created the account for RTSP or are entering incorrect password.

**Comment by danktankk** [comment]
same problem all this time later. this does not seem to have any rhyme or reason. Now I cant get it to add the camera back at all. why are so many people having such an issue with IP/user/pass? this cant be on us for every post

**Comment by JurajNyiri** [comment]
The issue you are searching for:

    Is pinned under issues
    Has a section in main readme file with big title right at the top
    Has 3 red exclamations marks in the title
    Contains a workaround both for accounts still working and the ones affected.

And a warning was sent a month ago as an update via HACS.

You can find it at https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/551.

Please do not post me too comments or any other comment that does not provide any value to the discussion as everyone monitoring it gets notified. If the comments with no value continue maintainer will be forced to lock the issue to contributors only.
