### ISSUE TITLE
No image on Home Assistant

### ISSUE THREAD

**Issue by catalane41** [JurajNyiri/HomeAssistant-Tapo-Control#515]
### Description

Hi,
Things were working perfectly untill monday and suddenly (update of core HA and update of TAPO control) I don't get any image on HA where I have all images on TAPO app on my phone. Please help
Best regards
Edouard

### Reproduction Steps

Connect to HA as in the past

### Expected behavior

To get clear images

### If applicable, add error logs.

Logger: custom_components.tapo_control
Source: helpers/update_coordinator.py:300
Integration: Tapo: Cameras Control ([documentation](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control), [issues](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues))
First occurred: 14:47:12 (1 occurrences)
Last logged: 14:47:12
Unexpected error fetching Tapo resource status data: 'bool' object is not subscriptable

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 256, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/tapo_control/__init__.py", line 482, in async_update_data
    entity["entity"].updateTapo(
  File "/config/custom_components/tapo_control/sensor.py", line 183, in updateTapo
    self._attr_state = camData["connectionInformation"]["ssid"]
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
TypeError: 'bool' object is not subscriptable

### Device Firmware

1.3.9 Build 231024 Rel 62920n (4555)

### Integration Version

5.4.14

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HACS

### Search for similar issues

Yes

### Additional information

_No response_

**Comment by addboy58** [comment]
I have the same issue.

**Comment by JurajNyiri** [comment]
See FAQ regarding multiple rtsp stream limitation.

Regarding error ssid, this is a duplicate: https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/506
