### ISSUE TITLE
Moving camera unavailable

### ISSUE THREAD

**Issue by hkavsc** [JurajNyiri/HomeAssistant-Tapo-Control#518]
**Is your feature request related to a problem? Please describe.**
I don't know if it is a problem, or just can't be done on tapo c200. With app of tapo it works fine.

**Describe the solution you'd like**
I would like to have available moving of camera

**Comment by JurajNyiri** [comment]
If a camera is unavailable it cannot be controlled. It can be unavailable due to network or privacy mode being on.

**Comment by JurajNyiri** [comment]
Ptz and presets are supported on all cameras.
