### ISSUE TITLE
Password is shown in log

### ISSUE THREAD

**Issue by yujinlin0224** [JurajNyiri/HomeAssistant-Tapo-Control#519]
### Description

![圖片](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/11353779/0b078920-f47d-4dc9-a104-f0ecbe2642e8)

Camera is using Tapo C125.

### Reproduction Steps

After I cannot see the stream of camera in Home Assistant, I open the log to see what happened, I noticed camera reported 400 error and then I saw my password in my log.

### Expected behavior

All passwords should be hiden in log.

### Device Firmware

1.1.7 Build 231222 Rel. 64156n

### Integration Version

5.4.14

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker with WSL2 backend in Windows 11

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
RTSP requires password, in order to pass the stream to HA it needs to pass password as well.

These logs are not coming from this integration.

**Comment by JurajNyiri** [comment]
Also the blur you used can be reversed. I recommend changing password and using solid color next time.

**Comment by yujinlin0224** [comment]
OK, I will edit the post to remove the image and reopen the issue to HA.
