### ISSUE TITLE
Supported device list

### ISSUE THREAD

**Issue by KamilDzierbicki** [JurajNyiri/HomeAssistant-Tapo-Control#52]
Hi 👋  Is there any list somewhere of supported Tapo devices? I have Tapo c200 camera and it doesn't work for some reason(Invalid authentication data error)

**Comment by JurajNyiri** [comment]
Hey. Supported devices are c100, c200 and c310.

Make sure to follow instructions in config flow to put in correct credentials.

**Comment by KamilDzierbicki** [comment]
@JurajNyiri Thanks for this list! I tried to connect via homeassistant->integrations->tapo but still the same error. I did some tests from my local machine by using `pytapo` from the python console and I see some basic info about the camera :/ So now I know I put the correct data into the integration form. Any other things need to be checked? homeassistant is in 'host' network in docker.

**Comment by JurajNyiri** [comment]
Hey, does your rtsp stream via vlc work with the same credentials as you are putting into the integration?

**Comment by KamilDzierbicki** [comment]
via VLC - yes... even MotionEye integrated in HomeAssistant works good(link: rtsp://192.168.1.16/stream1) :/

**Comment by JurajNyiri** [comment]
Hmmm, that is really weird, I am not sure what could be causing this. Can you test the rtsp stream from the same docker just to double check? And I am sure you did, but make absolutely sure the username and password you are entering are correct.

**Comment by KamilDzierbicki** [comment]
uff, the easiest solution helped :D (upgrade software of the tapo camera with hard reset) thanks @JurajNyiri
