### ISSUE TITLE
Cannot take control with cloud password

### ISSUE THREAD

**Issue by apfffr** [JurajNyiri/HomeAssistant-Tapo-Control#520]
### Description

I changed camera IP and reconfigured it. Everything works except I get this message as notification in HA:

"Camera requires your cloud password for control.
This is the password which you used with your email when signing into the Tapo app.
Tapo Care paid subscription is not required.
Unless you used the same password for cloud as for your Camera account, this password is not the same.
Email is not needed and all communication is still fully local."

When I put in the password it says:
"Invalid cloud password. Make sure you are entering the password for your cloud account and NOT the password which you created via the camera settings (unless they are the same). You need to enter password which you used with your email when signing into the Tapo app."

The password is 100% corret. I did reset it and used it to login the Tapo app several times now to verify. Also restarted the cam a bunch of times and also HA. Cam control with the app works no problem.

I now removed the camera and can't even add it again without the cloud password

### Reproduction Steps

1. Go to devices.
2. Click 3 buttons on Tapo camera control
3. Click configure
4. select configure device
5. enter user, password, cloud password etc.
6. Click send
7.  Error: "Invalid cloud password. Make sure you are entering the password for your cloud account and NOT the password which you created via the camera settings (unless they are the same). You need to enter password which you used with your email when signing into the Tapo app."

### Expected behavior

It works and no error

### Device Firmware

1.3.9

### Integration Version

newest from HACS, where would I see this?

### Using stream component

No

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Home Assistant OS

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
1. Remove camera from the app
2. Enable camera to reach internet
3. Factory reset camera
4. Add camera to the app
5. It will work

**Comment by gloumy68** [comment]
Hi, I have the same problem today with a tapo C220.

First I've success to add the camera the first time. 
And after some hours, I have to reconfigure and now I always have the cloud password error.

I already try to reset to factory settings multiple time. Remove camera from app. Reset password... I think I try everything.
But impossible to add again the camera. And I have temporary suspension...

Can you help me ?

**Comment by JurajNyiri** [comment]
@gloumy68 https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/551

**Comment by javierugarte** [comment]
Hi, I'm writing here because the other thread is locked.

I have a question: do we really need authorization from Tapo to use those services that can be viewed publicly? If they haven't responded by now, I don't think they will.

Other third-party integrations have the brand's approval (LG, Samsung...) I don't think it's necessary.

I understand that you don't want to release a version and expose yourself to a potential claim, but could you share the code with interested people so we can take responsibility for implementing it in our HA?

Thank you very much for everything.

**Comment by OldGuyDevGithub** [comment]
Same error here with all my tapo cameras (C310, C510W, C210)

Cloud passwoird triple checked and 100% correct..

**Comment by figariglio** [comment]
is there an official  Solution? 
I've the same problem

**Comment by JurajNyiri** [comment]
@figariglio  https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/551

**Comment by darcab** [comment]
"Invalid cloud password. Make sure you are entering the password for your cloud account and NOT the password which you created via the camera settings (unless they are the same). You need to enter password which you used with your email when signing into the Tapo app."
Same problem for me...

**Comment by all3kcis** [comment]
Same here, no solution ?
