### ISSUE TITLE
cell_motion_detection and motion_alarm are not found (Tapo C110)

### ISSUE THREAD

**Issue by moritzmaier84** [JurajNyiri/HomeAssistant-Tapo-Control#524]
### Description

As the headline says.

The two (important) sensors are unknown and HA says something like "This entity is no longer provided by the Tapo Control integration. If the entity is no longer in use, delete it in the settings."

Strange thing is: It already worked... Then it went off, back again and not it's off for several days.

The sensors ARE working in the Tapo App.

Solutions? Thx!

### Reproduction Steps

Constant error

### Expected behavior

cell_motion_detection and motion_alarm are not found

### If applicable, add error logs.

none

### Device Firmware

1.0.13

### Integration Version

newest

### Using stream component

No

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HASS OS

### Search for similar issues

Yes

### Additional information

none

**Comment by JurajNyiri** [comment]
Read faq in readme.

**Comment by RoninMurat** [comment]
Hello, this is how it worked for me.


![1](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/115777672/ba6b8bc4-f122-4df7-83be-815c0765d9f3)
![2](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/115777672/a6d32023-1295-4d54-b7d7-e7fcc9e0f87e)
![3](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/115777672/44a3d8bc-aaf7-4bc6-b793-04eaad6fcf52)

**Comment by moritzmaier84** [comment]
I did and checked everything. Webhooks is disabled in my case...

Only thing I did not really get is this point:

Make sure you have correct IP set for Home Assistant. Turn on Advanced Mode under /profile. Go to /config/network and under Network Adapter verify correct IP is shown for the device. If it is not correct, under Home Assistant URL uncheck Automatic next to Local Network and set it to http://<some IP address>:8123. DO NOT USE HTTPS.


Where are those options? /profile and stuff?

**Comment by JurajNyiri** [comment]
If it worked before and you haven't updated the camera firmware yes. Some cameras have pull point broken and you will need to get webhooks working for motion detection or wait until they fix it.

**Comment by moritzmaier84** [comment]
Yeah, worked and did not update.
Strange.

Thank you for your quick responses. It's frustrating because I wanna use the motion trigger for recording commands.

**Comment by moritzmaier84** [comment]
(Now it's working again. I don't get it.)

**Comment by M4ndaL0re** [comment]
Same problem here with C325WB Camera
Was working before last HA Update and this integration error message see from above come up.
Deleted all cameras and re-installed and then Entity is gone.
Moved Kameras in same vlan but still no help.
