### ISSUE TITLE
Unknown error when trying to access files from a camera that's offline in the Media library

### ISSUE THREAD

**Issue by vaihelvette** [JurajNyiri/HomeAssistant-Tapo-Control#527]
### Description

I get "Unknown error" when i try to access files from a camera that's offline in the Media library. I have "enabled media synchronisation". I have 2 cameras with media sync enabled and just one camera down at the moment. I can access the files with in the media library with no problem from the camera that is online.
I have the files locally on the home assistant. I can ses the files from both cameras locally when i list them in a ssh terminal.

### Reproduction Steps

Turn off one camera 
Go to the offline camera in the Media library in home assistant.

### Expected behavior

View the recordings that is synced.

### If applicable, add error logs.

![fel_home](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/95184027/9fdcac21-5aca-4151-83d9-075711de6a74)

### Device Firmware

1.3.11

### Integration Version

5.4.14

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Generic x86-64

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
What is the error in the logs?

**Comment by JurajNyiri** [comment]
Recordings do not work when camera is offline by design. If you would like, please open new feature request, no promises on when it will be done though as by design, this is a sync, not a copy, so it always uses the latest information from camera and would require major rewrite.
