### ISSUE TITLE
In HA 2024.3.* integration is stopped working.

### ISSUE THREAD

**Issue by alexanderznamensky** [JurajNyiri/HomeAssistant-Tapo-Control#528]
### Description

In beta HA 2024.3.0b1 integration is not working.
Rolling back to 2024.2.5 returns the integration to a working state.

### Reproduction Steps

Instalation of HA 2024.3.0b1

### Expected behavior

working integarion in 2024.3.*

### If applicable, add error logs.

Регистратор: homeassistant.config_entries
Источник: config_entries.py:504
Первое сообщение: 09:51:11 (5 сообщений)
Последнее сообщение: 10:05:49

Error setting up entry Tapo C210 for tapo_control
Error setting up entry Tapo C310 for tapo_control
Error setting up entry Tapo C110 for tapo_control
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo_control/__init__.py", line 318, in async_setup_entry
    entry.unique_id = DOMAIN + host
    ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in __setattr__
    raise AttributeError(
AttributeError: unique_id cannot be changed directly, use async_update_entry instead

### Device Firmware

Tapo C110, Tapo C210, Tapo C310

### Integration Version

5.4.13

### Using stream component

No

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker

### Search for similar issues

No

### Additional information

Core 2024.2.5
Supervisor 2024.02.1
Operating System Debian GNU/Linux 12 (bookworm)
Docker 24.0.7
UI 20240207.1

**Comment by gateriderz** [comment]
Similar issue after upgrading:

HA Core: 2024.03.0b1
Integration: 5.4.14
Cameras: C100

Thanks

**Comment by JurajNyiri** [comment]
Looking into this now.

**Comment by alexanderznamensky** [comment]
awesome! many thanks!

**Comment by imadjamil** [comment]
I am seeing the same problem with 2024.10.2. 

`AttributeError: unique_id cannot be changed directly, use async_update_entry instead`
