### ISSUE TITLE
Mx retries exceeded

### ISSUE THREAD

**Issue by ciclocaffe** [JurajNyiri/HomeAssistant-Tapo-Control#529]
### Description

Hi, I very often get this erro in the Core system log.

```
HTTPSConnectionPool(host='192.168.1.43', port=443): Max retries exceeded with url: /stok=5565857b18cbc67234f659504f5b4aa1/ds (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f36cc61e0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
HTTPSConnectionPool(host='192.168.1.41', port=443): Max retries exceeded with url: /stok=4cfe6f0d10376eac6494c965d2cec8b9/ds (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f36cc7cb0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
HTTPSConnectionPool(host='192.168.1.41', port=443): Max retries exceeded with url: /stok=4cfe6f0d10376eac6494c965d2cec8b9/ds (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000)')))
```

### Reproduction Steps

restart home assistant and check Core logs
or wait randomly for the error to appear in the log

### Expected behavior

There shouldn't be errors

### If applicable, add error logs.

This error originated from a custom integration.

Logger: custom_components.tapo_control
Source: custom_components/tapo_control/__init__.py:464
Integration: Tapo: Cameras Control (documentation, issues)
First occurred: 03:47:18 (3 occurrences)
Last logged: 11:59:13

HTTPSConnectionPool(host='192.168.1.43', port=443): Max retries exceeded with url: /stok=5565857b18cbc67234f659504f5b4aa1/ds (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f36cc61e0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
HTTPSConnectionPool(host='192.168.1.41', port=443): Max retries exceeded with url: /stok=4cfe6f0d10376eac6494c965d2cec8b9/ds (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f36cc7cb0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
HTTPSConnectionPool(host='192.168.1.41', port=443): Max retries exceeded with url: /stok=4cfe6f0d10376eac6494c965d2cec8b9/ds (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000)')))

### Device Firmware

.3.11 Build 231115 Rel.85400n(4555) Hardware: 3.0 

### Integration Version

5.4.15

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Rpi4

### Search for similar issues

Yes

**Comment by juangiler** [comment]
I have the same issue, trying to find some circuit breaker method so it doesnt crash the HASS
