### ISSUE TITLE
Bug: "__init__() got an unexpected keyword argument 'loop'" on Device Setup 

### ISSUE THREAD

**Issue by nervous-inhuman** [JurajNyiri/HomeAssistant-Tapo-Control#53]
**Describe the bug**
When trying to add a new device through the HASS (Python 3.9), the component throws an error.

![image](https://user-images.githubusercontent.com/8982584/103374094-f6dbf880-4ad6-11eb-84df-297aee64e679.png)

**To Reproduce**
1. Go to HASS Integrations
2. Add Tapo integration
3. Enter the required data (IP, Credentials) and submit

**Expected behavior**
To successfully add the device.
 
**Log**

When trying to add the device:
```
Logger: custom_components.tapo_control
Source: custom_components/tapo_control/config_flow.py:129
Integration: Tapo: Cameras Control (documentation, issues)
First occurred: 19:19:37 (5 occurrences)
Last logged: 19:39:42

__init__() got an unexpected keyword argument 'loop'
```

I can see the following line in my logs as well, however it's not an error:
```
Dec 30 19:40:18 panopticon hass[667953]: 2020-12-30 19:40:18 DEBUG (MainThread) [custom_components.tapo_control] Finished fetching Tapo resource status data in 0.632 seconds
```

**Camera (please complete the following information):**
 - Device Model: C200 and C100
 - FW: See additional info below

**Using stream component**
N/A

**Camera works through onvif component OR different cameras work in general**
N/A

**Camera has all attributes filled out properly in developer tools**
N/A

**HASS Environment**
`community/home-assistant 2020.12.1-1` on Arch Linux with Python 3.9.1

**Additional info:** 
When using the pytapo module directly from Python, it seems to work?

```
In [2]: tapo = Tapo(C100_IP, USER, PASS)
In [3]: tapo.getBasicInfo()
Out[3]: {'device_info': {'basic_info': {'device_type': 'SMART.IPCAMERA',
   'device_model': 'C100',
   'device_name': 'C100 1.0',
   'device_info': 'C100 1.0',
   'hw_version': '1.0',
   'sw_version': '1.0.10 Build 200519 Rel.66820n(4555)',
   'device_alias': 'C100',
   'features': '3',
   'barcode': '',
   'mac': '60-32-B1-AF-A0-5D',
   'dev_id': '802109312465D4F1ECE95C3F46DD39861D71C2AA',
   'oem_id': 'EDCF1D37890C9D554B594B8F567946D2',
   'hw_desc': '48574445534300000000000000000001'}},
 'error_code': 0}
```

```
In [2]: tapo = Tapo(C200_IP, USER, PASS)
In [3]: tapo.getBasicInfo()
Out[3]:
{'device_info': {'basic_info': {'device_type': 'SMART.IPCAMERA',
   'device_model': 'C200',
   'device_name': 'C200 1.0',
   'device_info': 'C200 1.0',
   'hw_version': '1.0',
   'sw_version': '1.0.17 Build 201111 Rel.74534n(4555)',
   'device_alias': 'C200',
   'features': '3',
   'barcode': '',
   'mac': '84-D8-1B-5B-53-D7',
   'dev_id': '802100EDFEC558C14D50DAF15D2225161D885874',
   'oem_id': '8902D2F34FCE407721DE92F5759839C2',
   'hw_desc': '48574445534300000000000000000001'}},
 'error_code': 0}```

**Comment by JurajNyiri** [comment]
Hello, update to the latest version of this integration.

If issue persists after that we can reopen this.

**Comment by vaidyasr** [comment]
I am getting the exact same error. I am using Tapo integration 3.1.1 and HA 2021.2.2

**Comment by JurajNyiri** [comment]
Make sure that you are updated. Function loop has not been used for a long while now. If you are getting the error you are not updated.

**Comment by vaidyasr** [comment]
I just installed the tapo from HACS today which is latest I think. 3.1.1

**Comment by JurajNyiri** [comment]
Please post your error log.

**Comment by vaidyasr** [comment]
Same error as above. Whenever I enter credetials, I got the error in log.
`2021-03-02 17:00:13 ERROR (MainThread) [custom_components.tapo_control] __init__() missing 1 required positional argument: 'loop'`

**Comment by vaidyasr** [comment]
Is that something to do with Python 3.9.1?

**Comment by JurajNyiri** [comment]
That looks like something with your python environment / dependencies is not correct. Home Assistant removed this parameter in the first 2021 release.

**Comment by vaidyasr** [comment]
ok, will try to re-configure the environment and post the update here.

**Comment by vaidyasr** [comment]
Tried on a fresh install with Python 3.9.2, same error. Will try on Python 3.8.9

**Comment by vaidyasr** [comment]
same error for Python 3.8.8. I am using venv and not docker.

**Comment by vaidyasr** [comment]
![image](https://user-images.githubusercontent.com/5370937/109686439-48bcff80-7ba8-11eb-8ac5-e8f78987e46a.png)
any help? am using the latest version of HASS too.

**Comment by vaidyasr** [comment]
opened new issue.
