### ISSUE TITLE
Feature Request: Allow HD/SD video streams to be disabled

### ISSUE THREAD

**Issue by gcardy** [JurajNyiri/HomeAssistant-Tapo-Control#532]
**Is your feature request related to a problem? Please describe.**
Not necessarily, but it is possible.

**Describe the solution you'd like**
I would like the option to disable the integration from creating the HD/SD video streams. I find all of the configuration options for the cameras useful, but not the video feeds.

**Describe alternatives you've considered**

**Additional context**
I have all of my camera feeds ingested into Frigate, so the HD/SD streams being available directly via the plugin is unnecessary for my configuration. The additional streams open on the camera from Home Assistant use up resources that I would like to free up.

**Comment by JurajNyiri** [comment]
Disable the camera entities in Home Assistant.
