### ISSUE TITLE
Tapo Cameras Control does not wwork anymore

### ISSUE THREAD

**Issue by Sonarufy** [JurajNyiri/HomeAssistant-Tapo-Control#534]
### Description

after my last system update, my Tapo Cameras stopped working,
and it was working fine for 2 weeks since first integration (streaming and recording)
 Core 2024.3.1 
 Supervisor 2024.03.0
 Operating System 12.1 
camera tapo C200
when i deleted the integration and tried to add it again it doesn't work (Connection failed)

### Reproduction Steps

opening old integration entities
or adding new integration

### Expected behavior

showing stream and camera controls

### Device Firmware

1.3.11 Build 231115 Rel85400n(4555)

### Integration Version

5.4.17

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Home assistant os on raspberry pi

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Post logs. Connection failed means ha cannot reach cameras.
