### ISSUE TITLE
Tapo C200, all move are anaivalaible

### ISSUE THREAD

**Issue by pinkfloydFR** [JurajNyiri/HomeAssistant-Tapo-Control#536]
### Description

Camera model : C200

Hi,

Don't know since when, but all move related function are unavailable ( worked very well for a long time )
![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/49475899/73d8d4c4-bb9e-4ae7-8212-ed42e41adb88)

### Reproduction Steps

Cannot access to move command of the camera

### Expected behavior

Have access to move command of the camera

### Device Firmware

1.3.9 Build 231019 Rel.37378n(4555)

### Integration Version

5.4.17

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HA OS raspberry

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Hi post logs and proper version in template.

**Comment by pinkfloydFR** [comment]
Oh so strange !

For giving you debug log, tested more...   and : 

- movement ( like left / right, up and down, despite unavailable, are working
- movement for goind to position, ARE NOT
- nothing about my C200 camera in the log ( searched for name, firmware version and type name )  ( log are full of message of my another camera, a C310, a static one )

So not sure what can i post you :(

**Comment by JurajNyiri** [comment]
Please disable your other camera and then enable debug logs for this integration and post that when you see this issue.

Integration version is still incorrect.

I will reopen this once the above is sent.

**Comment by pinkfloydFR** [comment]
Intégration 5.4.17

Here is the log with only one camera :

[debug.log](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/files/14693983/debug.log)

**Comment by JurajNyiri** [comment]
Thank you could you please post screenshots of all the entities? I  see “_2” in the entities. Maybe these are duplicate and there are other for movement ?

**Comment by pinkfloydFR** [comment]
Sure, here are the screen shot, as i said, all was working before, surely a recent update ( HA or extension ? ) broke this...

( first capture is reseaching 'mov' )

![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/49475899/9753ea4a-1a2f-417d-ad2d-3f733d20f9df)

![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/49475899/e131ee4e-1011-443e-a1f8-296994fda376)
![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/49475899/56ffd9b3-0d85-40f0-bafa-139a569b3a8e)
![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/49475899/eeb0c5e1-e70b-434f-a585-c540bb3b9133)
![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/49475899/06a57873-9148-4a53-9822-fdf7ef39dc0d)

**Comment by JurajNyiri** [comment]
Thank you.

As the next steps:

1. Please try to remove camera, restart, and add it again
2. If you are still experiencing the issue, please post full debug logs from the start of HA (the last ones you posted are just a small section while it was running).

**Comment by pinkfloydFR** [comment]
ok will do this ! thanks for helping !

**Comment by pinkfloydFR** [comment]
So, deleted all, restard HA, reconfigure the camera and strangely all entity are ok this time ( name without _2 of course )

All is ok, so no better information in log to understand what was the problem.

Thanks for your time btw.
