### ISSUE TITLE
C310 Cam Setup Error

### ISSUE THREAD

**Issue by MWagnerOE5AOO** [JurajNyiri/HomeAssistant-Tapo-Control#538]
### Description

Try to connect a C310. The TAPO APP is working. No Firewalls between HASS and CAM. After step by step config at the end occurs the message "Fehler beim Einrichten" means "setup error" The Integrations works a long time. Since the update around 2024 01 don't work any more.  All systems  have the latest versions. Try to cange the stream from tcp to other protokolls. No effekt.

### Reproduction Steps

Eintrag hinzufügen, Add IP, Add CAM Account Data, Add  Tapo Password, in the nextstep leave all on default, and finished with send. ->Setup Error

### Expected behavior

After send the configuraiton the cam should work 

### Device Firmware

1.3.11 Build 231117 Rel:38282n(4555

### Integration Version

5.4.12

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

No

### HASS Environment

HASS on Proxmox

### Search for similar issues

Yes

### Additional information

Please conntact me for furter informaitons

**Comment by MWagnerOE5AOO** [comment]
After delete and reinstall the integration will work again. Reinstllation with 5.4.17

**Comment by JurajNyiri** [comment]
Post error logs.

**Comment by MWagnerOE5AOO** [comment]
Thx fort he quick responce. Where i can find the logs?

Von: Juraj Nyíri ***@***.***>
Gesendet: Sonntag, 24. März 2024 10:02
An: JurajNyiri/HomeAssistant-Tapo-Control ***@***.***>
Cc: Wagner Michael (Lehrer) ***@***.***>; Author ***@***.***>
Betreff: Re: [JurajNyiri/HomeAssistant-Tapo-Control] C310 Cam Setup Error (Issue #538)


Post error logs.
