### ISSUE TITLE
D130 Doorbell Settings not available

### ISSUE THREAD

**Issue by adamzeis** [JurajNyiri/HomeAssistant-Tapo-Control#540]
### Description

I've just fired up a D130 using the integration. It adds easily and the camera feed works great, however the controls and configuration options don't appear to be functioning. Not sure if this is a known issue since it's a doorbell vs a camera, but I wasn't able to find much else about the D130 here or elsewhere. 

### Reproduction Steps

Within device settings in HA. Camera is up and running but configuration toggles and options aren't made available, though they are listed on the device page. Disk status etc. all shows as unavailable, but the camera feed (SD and HD) are working.

### Expected behavior

I have other cameras that work just fine with all options available. 

<img width="350" alt="Screen Shot 2024-03-26 at 6 44 18 AM" src="https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/39461983/7fcf5c64-db9d-4d9b-b476-63dcfdf27a91">

### Device Firmware

1.0.16 Build 230829 Rel.56497n

### Integration Version

5.0.1

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

No

### HASS Environment

HA Yellow

### Search for similar issues

Yes

**Comment by cadavre** [comment]
Any chance that D130 would get a "doorbell button press" sensor? That would be a game-changer for me to switch away from EZVIZ (crap).
