### ISSUE TITLE
Invalid cloud password. Make sure you are entering the password for your cloud account and NOT the password which you created via the camera settings (unless they are the same). You need to enter password which you used with your email when signing into the Tapo app.

### ISSUE THREAD

**Issue by emartinskan** [JurajNyiri/HomeAssistant-Tapo-Control#542]
### Description

Does not matter what, always come this error during setup. Cloud password has been check multiple times.

### Reproduction Steps

Add integration, all good until cloud password does not match

### Expected behavior

Add integration , but it fails on cloud password

### Device Firmware

1.3.11 build 231117 Rel.36789n(4555)

### Integration Version

5.4.17

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Raspeberry pi

### Search for similar issues

Yes

### Additional information

none

**Comment by uptothedog** [comment]
I'm having the same issue. Had a problem with my camera feed not showing up, and upon removing and trying to reconnect the camera, it just wouldn't take my credentials. I double-checked everything multiple times.

**Comment by bulentbaskan** [comment]
Bende aynı sorunu yaşıyorum v5.8.7
