### ISSUE TITLE
Siren entity won't trigger the siren (Tapo C420).

### ISSUE THREAD

**Issue by Pippo1989** [JurajNyiri/HomeAssistant-Tapo-Control#545]
### Description

![Siren entity](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/98611451/ef34b4e4-d393-4c6f-a2a7-3d1443636a05)
One of the entities shown by the integration is "siren", represented as a switch, which I believe should turn the sound alarm on or off. However, it has no effect on the camera alarm.

### Reproduction Steps

1. Open the integration
2. Select the entity "siren.XXXX_siren"
3. Turn on/off the siren like a switch

### Expected behavior

The entity should turn the sound alarm on or off.
In addition, you should be given the option to choose the volume (low/medium/high) and the siren type (siren/emergency/red alarm), just like in the application.

### If applicable, add error logs.

[home-assistant_tapo_control_2024-04-07T21-16-22.705Z.log](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/files/14899002/home-assistant_tapo_control_2024-04-07T21-16-22.705Z.log)

### Device Firmware

1.2.17 Build 20240305 rel.75572

### Integration Version

5.4.17

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HassOs on Raspberry Pi 4

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Hi, thank you for the report. 
- How does it work via an app? 
- Can you launch siren manually via an app?
- What happens when you trigger it via HA?

If the answer to above is you can launch it via an app, someone will need to document the HTTP(s) calls, and then I can add the functionality, ideally if we can also get the state of the siren (on/off).

**Comment by Pippo1989** [comment]
![2](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/98611451/99a5780f-632c-4fd9-acb5-4b02fef9e663)
![3](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/98611451/e7327a8d-5863-42d3-8f74-dba968406249)
![1](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/98611451/b77ac458-4b01-4280-84f6-c44fc841fe53)

I've analyzed better the entities provided by the integration and the different configurations of the Tapo application, so I should make a clarification.
As you can see from the attached photos, in the menu of each camera, by selecting the "alarm" option, you can choose whether this should be active at the time of detection or not. If so, you can choose the type of alarm (light, sound or both: this option is already included in the integration) and the type of sound. In this last configuration, it is then possible to choose the volume (low, medium or high) and the type of sound (siren, emergency or red alarm).
Here, **what triggers the siren is the "play" button next to each melody**.
Ultimately, I imagine that the "alarm" sensor simply serves to activate/deactivate the possibility of sounding the alarm if the camera detects movement.
**However, it would be desirable, in addition to being able to select the volume and type of sound, to be able to manually activate the siren.** This possibility, in fact, would open up several useful automation scenarios.

**Comment by JurajNyiri** [comment]
The siren currently triggers the camera to sound the siren. If that is supported in the app someone will need to document the call along with the call to get state (whether it’s sounding or not) for this ticket. 

For the missing features please open new feature request and the calls will need to be documented there by community as well in order to implement the new features.

**Comment by JurajNyiri** [comment]
ability to change the siren plan is already implemented via the select box - automatic alarm. Where it can be set to off, light, sound or both.

**Comment by JurajNyiri** [comment]
Duplicate
