### ISSUE TITLE
Issue: The IP address does not belong to any supported Tapo device

### ISSUE THREAD

**Issue by flobo1990** [JurajNyiri/HomeAssistant-Tapo-Control#547]
### Description

Recently, the integration with my Tapo C225 no longer works.
I think there was a new firmware update.
Error message: "The IP address does not belong to any supported Tapo device"

![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/61708287/f79a82c7-92c5-4cdc-94b7-7a48784e7fb6)

### Reproduction Steps

Add camera via UI

### Expected behavior

Add camera in HA

### Device Firmware

1.0.28 Build 240408 Rel.64223n

### Integration Version

5.4.17

### Using stream component

No

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

No

### HASS Environment

VM Proxmox

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
First a control question - are you sure the camera IP is correct and did not change? 
I will need access to the camera in order to debug this further if yes. If you have public ip and can port forward and willing to share the camera with me reach out to me on discord.

**Comment by kei81131** [comment]
> ### Description
> Recently, the integration with my Tapo C225 no longer works. I think there was a new firmware update. Error message: "The IP address does not belong to any supported Tapo device"
> 
> ![image](https://private-user-images.githubusercontent.com/61708287/321299044-f79a82c7-92c5-4cdc-94b7-7a48784e7fb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3OTg2MDYsIm5iZiI6MTcxMjc5ODMwNiwicGF0aCI6Ii82MTcwODI4Ny8zMjEyOTkwNDQtZjc5YTgyYzctOTJjNS00Y2RjLTk0YjctN2E0ODc4NGU3ZmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDAxMTgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzYjQyMTY4MmY2ZjMwYzhmN2UxNTk0ZDY5YzhkYTk5OWMyZGFhZGM0YWE3ZmRlYmExMzgxYTY2ZDA5M2E2YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fDQjVvDWhTbaPeiKD5aSDAfYXLpk5dDZyfb19TB41kg)
> 
> ### Reproduction Steps
> Add camera via UI
> 
> ### Expected behavior
> Add camera in HA
> 
> ### If applicable, add error logs.
> _No response_
> 
> ### Device Firmware
> 1.0.28 Build 240408 Rel.64223n
> 
> ### Integration Version
> 5.4.17
> 
> ### Using stream component
> No
> 
> ### Does camera work via official integrations?
> N/A
> 
> ### Camera has all attributes filled out in developer tools
> No
> 
> ### HASS Environment
> VM Proxmox
> 
> ### Search for similar issues
> Yes
> 
> ### Additional information
> _No response_

My C225 also have this issue last month after update firmware 1.0.28
My workaround is downgrade firmware to 1.0.27

Below is 1.0.27 firmware I asked from tp-link cs, with instruction inside
hopes it can help you.
https://static.tp-link.com/upload/beta/2024/202404/20240402/C225%201.0.27.zip

**Comment by JurajNyiri** [comment]
While downgrading works we should work on supporting the new firmwares in the integration if possible.
