### ISSUE TITLE
Invalid cloud password

### ISSUE THREAD

**Issue by tomtpcz** [JurajNyiri/HomeAssistant-Tapo-Control#549]
### Description

![Výstřižek](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/24278255/2a8abaf5-9850-4fad-9384-5b41047b36d7)

The integration with three cameras worked perfectly fine for 2 months. Now it keeps saying cloud password is required. The password is correct and valid, also verified in the mobile application. The firmware was not updated for either camera.

### Reproduction Steps

see error

### Expected behavior

N/A

### Device Firmware

1.3.11 Build 23117 Rel.47346n(4555)

### Integration Version

 5.4.17

### Using stream component

Yes

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HAOS Rpi5

### Search for similar issues

Yes

### Additional information

Home assistant:
Core 2024.3.3
Supervisor 2024.04.0
Operating System 12.1
Frontend 20240307.0

**Comment by JurajNyiri** [comment]
Read FAQ.
