### ISSUE TITLE
No Home Assistant Integration Entry Bug:

### ISSUE THREAD

**Issue by erikatl** [JurajNyiri/HomeAssistant-Tapo-Control#55]
**Describe the bug**
Same issue as described by jcbagtas in bug report #46. Restart of HA and cleared browser cache does not solve the problem. A late comment in #46  from KonTiki1957 suggests he/she has the same problem too.

**To Reproduce**
Same as #46.

**Expected behavior**
Same as #46.

**Log**

**Camera (please complete the following information):**
 Device Model: TP Link Tapo C200

**Using stream component**
N/A

**Camera works through onvif component OR different cameras work in general**
N/A

**Camera has all attributes filled out properly in developer tools**
N/A

**HASS Environment**
## System Health

version | 2021.1.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.79-v7l
arch | armv7l
timezone | Europe/Stockholm

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.9.0
Stage | running
Available Repositories | 712
Installed Repositories | 20

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.10
-- | --
update_channel | stable
supervisor_version | 2020.12.7
docker_version | 19.03.13
disk_total | 28.6 GB
disk_used | 6.9 GB
healthy | true
supported | true
board | rpi4
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.3.0), Terminal & SSH (8.10.0), Dropbox Sync (1.3.0), Duck DNS (1.12.4), motionEye (0.10.2), AdGuard Home (2.6.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
mode | storage
views | 16
resources | 16

</details>

**Additional context**
N/A

**Comment by JurajNyiri** [comment]
I am sorry but if you do not see the integration in the Home Assistant you installed it incorrectly.

Try installing via HACS, restart, clear browser cache (or use incognito) and it will be there 100%.

Follow manual installation steps correctly and restart etc and it will be there 100%.

For example, following paths should be valid:
/config/custom_components/tapo_control/manifest.json
/config/custom_components/tapo_control/translations/en.json
/config/configuration.yaml

**Comment by erikatl** [comment]
"Try installing via HACS, restart, clear browser cache (or use incognito) and it will be there 100%."
That is exactly what I have done, I installed via HACS (I even reinstalled), I restarted HA, I cleared the browser cache. I have tried with Brave, Chromium and Firefox. Same result every time, no Tapo integration.

**Comment by JurajNyiri** [comment]
@erikatl did you verify the paths I listed above?

**Comment by erikatl** [comment]
All the paths above exist.

**Comment by erikatl** [comment]
```
custom_components $ cd tapo_control/
tapo_control $ ls -l
total 68
-rw-r--r--    1 root     root          5209 Jan 10 10:38 __init__.py
-rw-r--r--    1 root     root          2762 Jan 10 10:38 binary_sensor.py
-rw-r--r--    1 root     root         15000 Jan 10 10:38 camera.py
-rw-r--r--    1 root     root          9704 Jan 10 10:38 config_flow.py
-rw-r--r--    1 root     root          2690 Jan 10 10:38 const.py
-rw-r--r--    1 root     root           479 Jan 10 10:38 manifest.json
-rw-r--r--    1 root     root          3663 Jan 10 10:38 services.yaml
-rw-r--r--    1 root     root           987 Jan 10 10:38 strings.json
drwxr-xr-x    2 root     root          4096 Jan 10 10:38 translations
-rw-r--r--    1 root     root          6761 Jan 10 10:38 utils.py
tapo_control $ ls -l translations/
total 4
-rw-r--r--    1 root     root          1736 Jan 10 10:38 en.json

```

**Comment by JurajNyiri** [comment]
Is there anything in the log? Are the permissions the same as for configuration.yaml for Home Assistant?

**Comment by erikatl** [comment]
One item in the log:
```
2021-01-11 20:30:27 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for tapo_control which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
```
Permission for configuration.yaml:
```
config $ ls -l configuration.yaml 
-rwxr--r--    1 root     root          1500 Jan 10 08:49 configuration.yaml
```
All other custom integrations (of those that I use) work fine.

**Comment by JurajNyiri** [comment]
The log means integration loaded successfully.

You should be able to see it in Configuration -> Integrations -> Add Integration

![image](https://user-images.githubusercontent.com/5785999/104445412-5f2bdf00-5599-11eb-86dc-b6dfec22d3f1.png)

If not, it is a bug of Home Assistant or/and you need to clear your cache and hard refresh browser.

**Comment by erikatl** [comment]
Now I feel stupid! I was looking for Tapo in the list of integrations. I didn't notice the "Add integration" button. Of course it was there. So sorry for taking up your time. Closing...
