### ISSUE TITLE
intergration rejects camera account credentials

### ISSUE THREAD

**Issue by MrSilkworm** [JurajNyiri/HomeAssistant-Tapo-Control#552]
### Description

After installing the HACS intergration, through settins in HAthe IP is inputed correctly and then it will not accept the cameras userid and password that where created throuh the official app. 
Camera worka correctly through the app and the rtsp has veed tested on VLC.

### Reproduction Steps

1. Install HACS ibtergratuon
2. Got to settings
3. Add 8ntergration
4. Run intergration
5. Input IP
6. Input usename and password
7. Error "Invalid authentication data. Make sure you have created your 3rd party account via Tapo app. You can also test if these credentials work via rtsp stream, for example VLC using link rtsp://username:password@IP Address:554/stream1"
8.

### Expected behavior

The username and password are corect and tested. Itrrgration should run

### Device Firmware

TapoC200 1.3.13

### Integration Version

5.4.17PSA

### Using stream component

No

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Home assistant on mini pc

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Read faq.
