### ISSUE TITLE
It is not possible to integrate new cameras. Cloud password is returned as incorrect.

### ISSUE THREAD

**Issue by FragForward** [JurajNyiri/HomeAssistant-Tapo-Control#553]
### Description

I cannot add a new camera. Every time I try to do this, I get an error telling me to enter the correct password. I have already changed this several times to make sure that I enter the correct one.![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/27769630/5859d84c-8aa8-446f-8eaf-0faaa139bc7d)

### Reproduction Steps

After the person recognition did not work, I deleted the camera and wanted to add it again. 

### Expected behavior

That I see the camera again

### Device Firmware

1.3.11

### Integration Version

1.3.9

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Homeassistan Core

### Search for similar issues

Yes

### Additional information

Core
2024.4.2
Supervisor
2024.04.0
Operating System
12.2
Frontend
20240404.1

**Comment by JurajNyiri** [comment]
https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/551
