### ISSUE TITLE
reload_config_entry ends with unknown error

### ISSUE THREAD

**Issue by scetu** [JurajNyiri/HomeAssistant-Tapo-Control#555]
### Description

After calling homeassistant.reload_config_entry it fails (I must say that config_entry comes from custom component https://github.com/JurajNyiri/HomeAssistant-Tapo-Control)

```
service: homeassistant.reload_config_entry
data: {}
target:
  device_id:
    - 88e356383b63391290aa1b3539239906
```

fails with
```
Translation Error: The intl string context variable "reason" was not provided to the string "Stopped because of unknown reason {reason} at {time} (runtime: {executiontime} seconds)"
```

![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/30218362/638033d1-9bf1-447f-b1c7-f54f92e40ab2)

Referenced in Core as issue, but repoted integration Bosch Smarthome has fixed it within integration itself - https://github.com/home-assistant/core/issues/115060

### Reproduction Steps

```
service: homeassistant.reload_config_entry
data: {}
target:
  device_id:
    - 88e356383b63391290aa1b3539239906
```

### Expected behavior

Entitty/Device is reloaded without error.

### Device Firmware

1.3.11

### Integration Version

5.4.17

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HAOS

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
I just tried this with the latest version - 5.4.25 on HA 2024.07.0 and it works as expected.

```
service: homeassistant.reload_config_entry
data: {}
target:
  device_id: 806300c7c7b2d7e03fa04045cbd6a67c
```

@scetu if you are still encountering error please post which language you are using in HA, version of HA and integration version and we can reopen.
