### ISSUE TITLE
Feature Request:  manually activate the alarm and select its type and volume.

### ISSUE THREAD

**Issue by Pippo1989** [JurajNyiri/HomeAssistant-Tapo-Control#556]
**Is your feature request related to a problem? Please describe.**
This feature request is related to issue #545.

Using TAPO C420 cameras, the integration, unlike the application, does not allow you to manually activate the alarm or select its type and volume.

**Describe the solution you'd like**
In addition to what is described in issue #545, it would be extremely useful to add to the integration what is already provided by the TAPO application. Namely, you should be given the option to :
- manually activate the siren;
- choose the volume (low/medium/high) and the siren type (siren/emergency/red alarm).

**Describe alternatives you've considered**
What I described above represents the arrival point for the ideal functioning of the integration.

**Additional context**
![1 (2)](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/98611451/6e841241-53c8-4f78-a4a7-0f9f41ebef67)
![2 (2)](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/98611451/2cbdc87c-2d10-41ba-81f8-af259e5c4d57)
![3](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/98611451/0c2cdc1b-0816-48fc-8ca2-fd91296a9579)

**Comment by lazmo88** [comment]
+1 related to this, replicating the Home and Away modes from Tapo app (alert/alarm presets for all selected cameras) would be very useful.

**Comment by JurajNyiri** [comment]
This should now be supported in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.4.33 . 

Let me know if there are any issues since I do not own these cameras.
