### ISSUE TITLE
Feature Request: control the volume, type and duration of the Tapo Hub 4A97 alarm (Tapo C420 cameras).

### ISSUE THREAD

**Issue by Pippo1989** [JurajNyiri/HomeAssistant-Tapo-Control#558]
**Is your feature request related to a problem? Please describe.**
Differently from the Tapo app, the integration does not allow you to control the volume, type and duration of the Tapo Hub 7A97 alarm, which manages the Tapo C420 cameras.

The problem is probably related to the issue #557. 

**Describe the solution you'd like**
It would be very useful to be able to control:
- the volume of the alarm (from 1 to 10);
- its type (there are many different ones);
- its duration (5 seconds, 10 seconds, 30 seconds, 1 minute, 5 minutes, 10 minutes or - more important - custom duration).

**Describe alternatives you've considered**
What I described above represents the arrival point for the ideal functioning of the integration.

**Additional context**
![HUB 1](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/98611451/1bab6127-d020-4aa2-bbb6-d0830ddfff9c)
![HUB 2](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/98611451/cec2794a-1449-4184-bc52-f704f7387a12)

**Comment by JurajNyiri** [comment]
Implemented in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.4.31
