### ISSUE TITLE
Cloud password is required for control

### ISSUE THREAD

**Issue by f-f** [JurajNyiri/HomeAssistant-Tapo-Control#563]
The integration requires the cloud password for "control of the camera". The password is marked as "optional" but it really isn't - it won't let me save the configuration if the password is not there. I would like this to be truly optional, and forego controlling the camera if no cloud password is there.

**Comment by f-f** [comment]
That's a little harsh - I hope a human reads this and can answer/reopen. I'm happy to fix the issue myself if given pointers where to look.

**Comment by JurajNyiri** [comment]
Some cameras require cloud password and there is nothing to do about it.

**Comment by JurajNyiri** [comment]
If you wish to just use the stream use official ha integration for rtsp or onvif.

**Comment by f-f** [comment]
Sounds good, I'll move to these - thanks!
