### ISSUE TITLE
Unavailble streams

### ISSUE THREAD

**Issue by andre1808** [JurajNyiri/HomeAssistant-Tapo-Control#565]
### Description

Hi there,

during the past days/weeks I've an worsening issue with my TC70 camera (which I believe is the same model as C200?).
It always starts with the HD stream not being available in Home Assistant anymore. When this happens, the SD stream usually is still available and when I check the Tapo app, the stream there seems to be HD still.
Later during the day, the SD stream also cuts off and is unavailable within HA. Sometimes the Tapo app is still working, but it also happened twice to me now, that even the Tapo app says, that I have "reached the device limit for playing this video". It's asking me to tap to retry, but this doesn't help either.

When this happens, the only fix is to reboot the camera.
What I mean by worsening is, that the HD stream did cut off like once a week, but the SD stream always stayed alive.
During the past week, both streams cut off **once a day**. So I am rebooting the camera every day.

I have the feeling that HA / your integration continuously pulls from the server which may be identified as a new device, or something.

Any idea how to fix this?

Thanks
André

PS: Maybe one more "hint": I've set the Stream identity on my dashboard to "live" rather than auto. For testing purpose I've just changed this to auto - which doesn't show me the stream on my Dashboard now anymore and instead just a grey error image, but maybe this helps.

### Reproduction Steps

I have pretty much explained everything in the description.
Over time the streams just cut off, nothing special needs to be done from my end.

### Expected behavior

No stream cuts :)

### Device Firmware

1.3.11 Build 231121 Rel.39429n(4555)

### Integration Version

5.4.13

### Using stream component

Yes

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HA VM under Proxmox

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Check faq there is a limit of concurrent streams on camera you are hitting. App does not use rtsp stream.
