### ISSUE TITLE
Tapo C510W with new Firmware stop integration

### ISSUE THREAD

**Issue by nevada750club** [JurajNyiri/HomeAssistant-Tapo-Control#567]
### Description

Today my Camera was updated (Firmware: 1.1.2 Build 231213 Rel.36199n).
Now I can't see Camera in HA and all his Entities.
With Tapo software all work good.

### Reproduction Steps

No streaming video

### Expected behavior

Fix integration

### If applicable, add error logs.

No Logs because integration not working

### Device Firmware

Firmware: 1.1.2 Build 231213 Rel.36199n

### Integration Version

5.4.17PSA

### Using stream component

Yes

### Does camera work via official integrations?

No

### Camera has all attributes filled out in developer tools

No

### HASS Environment

Virtual Machine Manager on Synology NAS

### Search for similar issues

Yes

### Additional information

C510W
from TP-Link
Firmware: 1.1.2 Build 231213 Rel.36199n
Hardware: 1.0

**Comment by sholvatealc** [comment]
The same Problem as @nevada750club

**Comment by JurajNyiri** [comment]
> Search for similar issues
> Yes

https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/551
