### ISSUE TITLE
IP address is not a supported Tapo device

### ISSUE THREAD

**Issue by RadeSojic** [JurajNyiri/HomeAssistant-Tapo-Control#568]
### Description

Hi Developer & Community

I want to connect my Tapo C510W but get the error "IP address is not a supported Tapo device". Unfortunately there is also no usable information in the homeassistant log: 
![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/165903368/64d5289d-6c2a-494c-8737-748112083c17)

I couldn't find a log file in the tapo control folder - so I don't know what to do more here. I've restarted my HomeAssistant couple times and also my cam - nothing changed. Can someone help me here? 

The Cam and the HASS are in the same Network (LAN). I checked also the tcp ports (80, 443, 554, 2020) on the cam from a pc in the same network - the ports are open and also respond to requests. 

Thanks in advance =)

Best regards 

### Reproduction Steps

Start Setup Wizard
Put in IP Address
Click on submit
ERROR

### Expected behavior

Start Setup Wizard
Put in IP Address
Click on submit
go on with the configuration part...

### Device Firmware

1.2.1 Build 240401 Rel.61067n

### Integration Version

5.4.17PSA

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

No

### HASS Environment

Docker

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Verify you are putting in correct ip address. If yes, try with pytapo directly and enable debug output.

**Comment by RadeSojic** [comment]
IP Address verified - everything ok. I did also the trace with pytapo -> the same error "SSL handshake failure". What could that be? I updated the firmware of the cam 2 days ago and the problem occured yesterday - really strange... And ideas? =)

[Trace Tapo Cam.txt](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/files/15260203/Trace.Tapo.Cam.txt)

**Comment by JurajNyiri** [comment]
What python version are you executing the script with? Do you have a way how to port forward the camera for me to test it? If so, contact me on discord and I can investigate.

**Comment by Lord2666** [comment]
Same problem generated from the last update of my tapo c510w cameras. The last updated firmware was yesterday in my case, version 1.2.1 build 240401 ref 61067n.

**Comment by Perquins** [comment]
> ### Descripción
> Hola desarrollador y comunidad
> 
> Quiero conectar mi Tapo C510W pero aparece el error "La dirección IP no es un dispositivo Tapo compatible". Lamentablemente, tampoco hay información útil en el registro de Homeassistant: ![imagen](https://private-user-images.githubusercontent.com/165903368/329044081-64d5289d-6c2a-494c-8737-748112083c17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNzU3MjEsIm5iZiI6MTcxNTI3NTQyMSwicGF0aCI6Ii8xNjU5MDMzNjgvMzI5MDQ0MDgxLTY0ZDUyODlkLTZjMmEtNDk0Yy04NzM3LTc0ODExMjA4M2MxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxNzIzNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNWJkNDQyN2RmNzY4ZDBmN2MxZTVmMmU5NGJhOTM1ZWVhOTlhMGNhZTY0MmNkNGM5ZWZkNGZhYWFiMTZhMGUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Rg7ifx5QJxrW4ih7L0Cx3AY6ANIgBkcDDNn1GJOuhSA)
> 
> No pude encontrar un archivo de registro en la carpeta de control de tapo, así que no sé qué hacer más aquí. Reinicié mi HomeAssistant un par de veces y también mi cámara; nada cambió. ¿Puede alguien ayudarme aquí?
> 
> La Cam y el HASS están en la misma red (LAN). También verifiqué los puertos tcp (80, 443, 554, 2020) en la cámara desde una PC en la misma red: los puertos están abiertos y también responden a las solicitudes.
> 
> Gracias de antemano =)
> 
> Atentamente
> 
> ### Pasos de reproducción
> Inicie el asistente de configuración Ingrese la dirección IP Haga clic en enviar ERROR
> 
> ### Comportamiento esperado
> Inicie el asistente de configuración Ingrese la dirección IP Haga clic en enviar y continúe con la parte de configuración...
> 
> ### Si corresponde, agregue registros de errores.
> _Ninguna respuesta_
> 
> ### Firmware del dispositivo
> 1.2.1 Compilación 240401 versión 61067n
> 
> ### Versión de integración
> 5.4.17PSA
> 
> ### Usando el componente de flujo
> Sí
> 
> ### ¿La cámara funciona a través de integraciones oficiales?
> Sí
> 
> ### La cámara tiene todos los atributos completados en las herramientas de desarrollo.
> No
> 
> ### Medio ambiente HASS
> Estibador
> 
> ### Buscar problemas similares
> Sí
> 
> ### Información adicional
> _Ninguna respuesta_

Me ocurre lo mismo.

**Comment by Perquins** [comment]
tengo también el mismo problema. supongo que tendremos que restablecer la cámara a estado de fabrica y no actualizar hasta que este resuelto el problema.

**Comment by RadeSojic** [comment]
Thanks for that hint. Python 3.9.2 was installed on my raspi -> updated that now to 3.9.19. But still the same error when I want to add the cam. It has to do something with the firmware update... 

I've opened also an issue on the tp-link website. For the people with the same error -> please comment there https://community.tp-link.com/en/smart-home/forum/topic/666994?replyId=1357126&utm_source=Subscription&utm_medium=email. 

Thanks =)

**Comment by JurajNyiri** [comment]
Fix incoming.

**Comment by JurajNyiri** [comment]
Fixed in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.4.18.

**Comment by RadeSojic** [comment]
Thank you very much Juraj :)

**Comment by harmanjosan94** [comment]
Hi, I am having the same issue with the Tapo C560WS 360 camera. The error under Tapo: Cameras Control says "IP address is not a supported Tapo device".

**Comment by GaryParr** [comment]
> ... says "IP address is not a supported Tapo device".

Weirdly, I just had the same issue, but with a different camera model. 4 other cameras connected fine. A simple reboot of the problem camera fixed it for me.
