### ISSUE TITLE
Error when changing motion detection mode, automation stopped

### ISSUE THREAD

**Issue by jpizquierdo** [JurajNyiri/HomeAssistant-Tapo-Control#569]
### Description

I have an automation which enable and disable the camera alarm by proximity. The automation was triggered but when I tried to change the motion detection selector to “off” the error ocurred:

Error: 'utf-8' codec can't decode byte 0xa7 in position 0: invalid start byte
Resultado:
params:
  domain: select
  service: select_option
  service_data:
    option: 'off'
    entity_id:
      - select.cam_salon_motion_detection
  target:
    entity_id:
      - select.cam_salon_motion_detection
running_script: false

### Reproduction Steps

Change motion detection mode by automation

### Expected behavior

Continue with the rest of automation or try again in a few seconds if error

### If applicable, add error logs.

Error: 'utf-8' codec can't decode byte 0xa7 in position 0: invalid start byte
Resultado:
params:
  domain: select
  service: select_option
  service_data:
    option: 'off'
    entity_id:
      - select.cam_salon_motion_detection
  target:
    entity_id:
      - select.cam_salon_motion_detection
running_script: false

### Device Firmware

1.3.11 Build 231121 Rel.39429n(4555)

### Integration Version

5.4.17

### Using stream component

No

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
https://www.home-assistant.io/docs/scripts/#continuing-on-error

> Error: 'utf-8' codec can't decode byte 0xa7 in position 0: invalid start byte

This error sometimes happens when camera is responding incorrectly, or when overloaded. Not much we can do, there are already retries built in to eliminate this as much as possible.
