### ISSUE TITLE
home assistant error configuration

### ISSUE THREAD

**Issue by matteos1** [JurajNyiri/HomeAssistant-Tapo-Control#570]
### Description

Tapo: Cameras Control
Camera requires your cloud password for control.
This is the password which you used with your email when signing into the Tapo app.
Tapo Care paid subscription is not required.
Unless you used the same password for cloud as for your Camera account, this password is not the same.
Email is not needed and all communication is still fully local.

### Reproduction Steps

new autentification

### Expected behavior

credential not work

### Device Firmware

1.3.9

### Integration Version

5.4.13

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

docker

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
> Search for similar issues
> Yes

Search again it is highlighted enough.
