### ISSUE TITLE
C100 camera - does not accept cloud password

### ISSUE THREAD

**Issue by HWiese1980** [JurajNyiri/HomeAssistant-Tapo-Control#573]
### Description

When I try to log in to my C100 cams, they accept the local camera account passwords, but the second password, the cloud password is never accepted. I am 100% sure the password I am using is correct and it is the cloud password. 

![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/743912/4bef79b2-0a3b-4c75-98cb-81c176285bd4)

### Reproduction Steps

1. Try to set up a C100 camera in the integration
2. enter cloud password
3. see error message

### Expected behavior

Well, it should accept the password

### Device Firmware

1.3.9 Build 231019 Rel. 40264n(4555)

### Integration Version

5.4.18

### Using stream component

Yes

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

No

### HASS Environment

HA Supervisor on Raspberry Pi

### Search for similar issues

Yes

### Additional information

The cameras work like a charm in the official Tapo app.

**Comment by blastik** [comment]
since this afternoon this is also happening to me with all my tapp cameras . I believe tapi has done chnages un their side and it broke this extension

**Comment by JurajNyiri** [comment]
> Search for similar issues
> Yes

it is literally pinned, in main readme and with huge 3 exclamation marks.

**Comment by HWiese1980** [comment]
> > Search for similar issues
> > Yes
> 
> The issue you are searching for:
> 
> * Is pinned under issues
> * Has a section in main readme file with big title right at the top
> * Has 3 red exclamations marks in the title
> * Contains a workaround both for accounts still working and the ones affected.
> 
> And a warning was sent a month ago as an update via HACS.

Sometimes things are placed TOO prominently...

**Comment by ruimgoncalves** [comment]
Like @HWiese1980 I was also surprised today to have all my cameras with that error. 

Even though I am aware of the issue mentioned in the README and the workaround, and since the issue occurred to several of us at almost the same time, that can indicate server side changes, I wonder if any of you guys already  tried the steps and if it fixed the issue.

PS: @JurajNyiri congrats for this integration, it's top notch
