### ISSUE TITLE
Feature Request: Use the luminosity sensor of the camera to create automations

### ISSUE THREAD

**Issue by rodrigogbs** [JurajNyiri/HomeAssistant-Tapo-Control#59]
**Is your feature request related to a problem? Please describe.**
This suggestion is not related to a problem, but related to an opportunity of creating more intelligent automations based on the luminosity of the environment.

**Describe the solution you'd like**
Create and control attributes related to luminosity sensor of the camera in Home Assistant, allowing to be used on automations, for example: If the luminosity_sensor is below of 300 lux, turn on the lights, or allow another sensors to turn on the lights.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by JurajNyiri** [comment]
Is this sensor exposed somewhere in the app?

**Comment by rodrigogbs** [comment]
Hello @JurajNyiri, I didn’t find it explicit in the app, but I believe that this parameter exists, because it is necessary to change the day/night mode on the camera. My suggestion is to analyze the viability of implementing this sensor, I really don’t know more about the technical components. Thanks for your availability on this topic.

**Comment by Cicicok** [comment]
Are you sure, that the camera has luminosity sensor? I think they just analyze the image and if it's too dark the camera goes into night mode.

if you look into user manual, there is nothing about light/luminosity sensor.
![c100](https://user-images.githubusercontent.com/38496829/107353656-95dc1300-6acd-11eb-8693-28810f1dc025.jpg)
![c200](https://user-images.githubusercontent.com/38496829/107353667-983e6d00-6acd-11eb-8082-00d6fc200857.jpg)

**Comment by rodrigogbs** [comment]
Hello my friend.

You are right, probably the software analyses the luminosity and turn on/off night mode, there is nothing about a sensor in the product description.

Unfortunately, I couldn’t find a smart luminosity sensor compatible with HA, this is why I am looking for alternatives for it...

Thanks.

Rodrigo Garcia
E-mail: rodrigogbs@gmail.com
Mobile: +55 (11) 99287-9747

Sent from my iPad
________________________________

**Comment by Cicicok** [comment]
@rodrigogbs you can try Shelly Door/Window 2 it has luminosity sensor and much more.

**Comment by JurajNyiri** [comment]
Closing this FR as camera does not have a sensor like this.

@rodrigogbs another solution would be for example Hue motion sensor, which also exposes lux into HASS.

**Comment by rodrigogbs** [comment]
Thanks for the tips, just you to know, I solved this with a CC2531 dongle flashed with zigbee2mqtt and a Xiaomi Mijia Light Sensor, now I can put more intelligence to my automations, turning the lights on/off depending on the lux situation.

Obrigado.

Rodrigo Garcia
E-mail: ***@***.***
Mobile: +55 (11) 99287-9747

Sent from my iPhone
________________________________
