### ISSUE TITLE
Issue with Cloud password gone, now problem with RTSP credentials

### ISSUE THREAD

**Issue by andreyl9** [JurajNyiri/HomeAssistant-Tapo-Control#602]
### Description

Hi, update HA and plugins and lost camera video, check issue, probe to downgrade and reset and have some another error, wrong login and password to RTSP, check them into VLC, all be ok... 
<img width="691" alt="tapo" src="https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/82682122/9858536c-a0af-4702-97e0-2a6b2c3f2414">

### Reproduction Steps

tapo c210 hw.v1, fw 1.3.11 b2311117 rel.36789n(455)
1. reset camera
2. configure again credentials in tapo app
3. delete camera from tapo control
4. add new camera
5. enter login/pass from step 2
6. receive error
7. check in VLC my string for rtsp - all be ok

### Expected behavior

may be some problem in tapo control..

### Device Firmware

1.3.11 b2311117

### Integration Version

5.4.13

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

docker

### Search for similar issues

Yes

### Additional information

may problem in auth method in tapo control

**Comment by JurajNyiri** [comment]
Follow steps in faq.

**Comment by andreyl9** [comment]
I think I find way with this issue, if make credentials in tapo app for rtsp like as login and password in tapo cloud all works,
login = email
pass = pass for cloud
after it use cloud pass for nex step and in my config all worked

**Comment by andreyl9** [comment]
I mean [❗❗❗Invalid cloud password on firmware build 230921 and higher](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/551) topic

if in camera create login and password for RTSP like login (email) and password for cloud all works
