### ISSUE TITLE
Find some way to fix cloud pass problem

### ISSUE THREAD

**Issue by andreyl9** [JurajNyiri/HomeAssistant-Tapo-Control#603]
### Description

I trying to reset camera and add RTSP login as login to tapo cloud (email), and password to tapo cloud as password, after delete camera in Tapo Control and add it as new, with login and password for tapo cloud (as RTSP login), and in next step enter password for Tapo cloud, all be ok on my config - try...

### Reproduction Steps

1. delete camera from tapo control in HA
2. reset tapo camera
3. pair with tp link app with camera
4. add login and pass in additional setting for RTSP stream (must be equal as login and pass to tapo cloud)
5. add new camera to tapo control in HA
6. enter login and password for tapo cloud (equal rtsp stream in camera)
7. enter on next step cloud password (password for tapo cloud, equal password rrtsp stream)

### Expected behavior

all be ok on my system and tapo control reauth.

### Device Firmware

1.3.11 build 211117

### Integration Version

5.4.13

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

docker

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
That’s not related at all. You experienced issue with rtsp of max concurrent streams as documented in faq which is not related at all.

**Comment by andreyl9** [comment]
This is related because I started experimenting because of this problem with the password for the cloud

**Comment by JurajNyiri** [comment]
No it is not. Rtsp stream started working because you are not overloading it anymore because of the rtsp password change.

**Comment by andreyl9** [comment]
try it! It's not about the RTSP stream! I also got cloud password problem! I accidentally found a solution to the problem by replacing the account and password for the stream with the same login and password for the cloud!

**Comment by andreyl9** [comment]
yes, and pass for cloud, and for next step put pass from cloud again, it's seems works
