### ISSUE TITLE
"message"."Invalid handler specified"

### ISSUE THREAD

**Issue by macoca28021** [JurajNyiri/HomeAssistant-Tapo-Control#605]
### Description

Cuando añado la integración de Tapo Camara integración obtengo el mensaje de "message"."Invalid handler specified"

### Reproduction Steps

1. Añado la integración de Tapo en Hacs, resultado OK
2. Voy a ajustes->Dispositivos y Servicios->Añadir Integración->Tapo camara control
3. Obtengo el mensaje "message"."Invalid handler specified"

### Expected behavior

Que  tapo camara control se integrase correctamente
![Tapo error](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/82387245/bf671e9d-7817-4f06-b53e-ad5fc251dfed)
![Tapo](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/82387245/def74ce4-63be-41b6-b081-79d0c91f8795)

### Device Firmware

N/P

### Integration Version

5.4.18

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Home Assistant OS

### Search for similar issues

Yes

**Comment by macoca28021** [comment]
Registrador: homeassistant.util.package
Fuente: util/package.py:123
Ocurrió por primera vez: 10:36:54 (3 ocurrencias)
Último inicio de sesión: 10:50:26

Unable to install package pytapo==3.3.21: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=60.0)")': /packages/12/75/5fb687d91a633e7489a81de96f913f355cecf8633cd586500e4bf0ac2fbf/pytapo-3.3.21-py3-none-any.whl.metadata WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=60.0)")': /packages/12/75/5fb687d91a633e7489a81de96f913f355cecf8633cd586500e4bf0ac2fbf/pytapo-3.3.21-py3-none-any.whl.metadata WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=60.0)")': /packages/12/75/5fb687d91a633e7489a81de96f913f355cecf8633cd586500e4bf0ac2fbf/pytapo-3.3.21-py3-none-any.whl.metadata WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=60.0)")': /packages/12/75/5fb687d91a633e7489a81de96f913f355cecf8633cd586500e4bf0ac2fbf/pytapo-3.3.21-py3-none-any.whl.metadata WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=60.0)")': /packages/12/75/5fb687d91a633e7489a81de96f913f355cecf8633cd586500e4bf0ac2fbf/pytapo-3.3.21-py3-none-any.whl.metadata ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/12/75/5fb687d91a633e7489a81de96f913f355cecf8633cd586500e4bf0ac2fbf/pytapo-3.3.21-py3-none-any.whl.metadata (Caused by ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=60.0)"))

**Comment by macoca28021** [comment]
Registrador: homeassistant.config_entries
Fuente: config_entries.py:2757
Ocurrió por primera vez: 10:52:09 (1 ocurrencias)
Último inicio de sesión: 10:52:09

Error occurred loading flow for integration tapo_control: No module named 'pytapo'

**Comment by JurajNyiri** [comment]
Reinstall integration.

**Comment by macoca28021** [comment]
![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/82387245/e0443f01-89c6-4a91-841b-7edc6f8c04e0)

**Comment by macoca28021** [comment]
> Reinstall integration.

Ya lo hice y obtengo el mismo resultado
