### ISSUE TITLE
Feature Request: Recording Sync configuration via sensor

### ISSUE THREAD

**Issue by Spamfast** [JurajNyiri/HomeAssistant-Tapo-Control#606]
**Is your feature request related to a problem? Please describe.**

I would like to be able to determine the media sync configuration of a device. This would allow me to omit devices that are not being synced from auto-entities cards showing download status.

**Describe the solution you'd like**

The integration could expose a per-device binary sensor entity giving the enabled state of the media sync feature.

Alternatively, the existing sensor could have a 'disabled' state as well as an 'idle' state to distinguish the two cases.

Either way, attributes matching the sync duration, storage destination and optionally the two time direction fields would also be useful for status display panels and automation tasks.

**Describe alternatives you've considered**

At present, I'm manually having to include/exclude and maintain a list of enabled devices which is a bit frustrating given the information is in the configuration.

**Additional context**

N/A

**Comment by JurajNyiri** [comment]
Implemented in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.4.21.

<img width="996" alt="Screenshot 2024-07-04 at 16 37 14" src="https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/5785999/feb9fec1-764d-4738-9c5b-661658bc9f86">

It will be off even if enabled but the number of hours is set to "" - reflecting the logic inside the sync.
