### ISSUE TITLE
Build 240223 (>230921) works well but with workaround to solve the cloud auth issue for TP-Link Tapo C220 

### ISSUE THREAD

**Issue by alexeyrv** [JurajNyiri/HomeAssistant-Tapo-Control#608]
### Description

Hello it works finally for Tapo C220 camera with HA Core 2024.6.2 Frontend 20240610.0
But I have the issue with Cloud Auth today 12.06.24.
After reading forums on Github also I have tried to solve the authentication issue.
My Firmware Build version is 240223 and it is higher than the version in the warning "**does not work temporarily on firmware build 230921 and higher**" https://github.com/JurajNyiri/HomeAssistant-Tapo-Control?tab=readme-ov-file

Hardware: by TP-Link
Firmware: 1.1.9 Build 240223 Rel.56143n
Hardware: 1.0

Follow the rules: only ascii lowercase letters and numbers.
1. Created a useless account on https://tplinkcloud.com/
In my case I can use google email without a "dot" and it works.
2. Change account settings in the mobile app (in my case it is Android)
In this case, the password contains special symbols and upper cases but username follows the rule.

It was added to HA successfully, managed by "buttons" to the available functions in C220.
Streaming SD and HD video.

Thank you for the nice work.
BR, Alex

 

### Reproduction Steps

1. Install Docker on win10 WSL
2. Install stable HA 
3. Install [HomeAssistant-Tapo-Control](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control)
4. Add device with IP
5. Auth to camera account 
6. Auth to TP-Link Cloud 

### Expected behavior

Cloud auth accepts any combination of letters, numbers and special characters in password, email or account.

### Device Firmware

1.1.9 Build 240223 Rel.56143n

### Integration Version

HA  Core 2024.6.2 Frontend 20240610.0

### Using stream component

Yes

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker on Win10 WSL from homeassistant/home-assistant:stable image

### Search for similar issues

Yes

**Comment by alexeyrv** [comment]
BTW, it is a bug, a working state report and a workaround simultaneously. I have no idea how to post it correctly. Any recommendations how to do it are welcome.
Thanks in advance for your tolerance.

**Comment by JurajNyiri** [comment]
Sorry to dissapoint, but it gets rolled out to accounts in green blue, it was not rolled out to this new account  yet, this is not a long term solution.

If you have it working now, block internet access so it does not receive the update.

**Comment by JurajNyiri** [comment]
Link: https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/551
