### ISSUE TITLE
Motion detector sensor not available

### ISSUE THREAD

**Issue by vdiogo** [JurajNyiri/HomeAssistant-Tapo-Control#61]
I have two Tapo cameras which have stopped reporting motion detection since 1 day. They are still streaming in SD and HD though.

This is what I get in the log:
```
Logger: custom_components.tapo_control
Source: helpers/update_coordinator.py:153
Integration: Tapo: Cameras Control (documentation, issues)
First occurred: 6:27:34 (1 occurrences)
Last logged: 6:27:34

Error requesting Tapo resource status data: HTTPSConnectionPool(host='192.168.86.70', port=443): Max retries exceeded with url: /stok=6584d86b23f6a7c9b25e324ffa3daf3c/ds (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x9813f640>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
```
Any suggestion/ help please?

**Comment by JurajNyiri** [comment]
The log message suggests your camera is offline.

For motion sensor not available check troubleshooting section in readme.

**Comment by vdiogo** [comment]
![image](https://user-images.githubusercontent.com/24878195/105844648-7a531180-5fd1-11eb-993e-1a7c2977934e.png)
Yes, all those steps were checked.

**Comment by JurajNyiri** [comment]
Try setting motion detection sensitivity to high setting.

If it still doesn't work after reboot, and there are no other errors there is nothing we can do in code. The camera sometimes refuses to publish events through onvif.

You can let it be and see if it starts working after a few hours, maybe days. Some users reported success that way.

You can also try using onvif camera component, which creates motion sensors the same way (before that, remove camera from this integration to reduce stress on camera). It will show the same behaviour.

Keeping this closed as unfortunately this is an camera issue and not this integration issue as stated previously in other issues or comments on hass community.
