### ISSUE TITLE
Kamera Tapo C225

### ISSUE THREAD

**Issue by hermann-geekom** [JurajNyiri/HomeAssistant-Tapo-Control#613]
### Description

Meine Kamera Tapo C225 möchte ich in Home Assistant einbinden. Die Tapo App funktioniert einbahnfrei. Wenn ich in Hacs die Tapo: Cameras Control Intregration starte, wird die IP und vom Kamera Konto der Benutzername, das Kamera Passwort abgefragt. Dann kommt die Frage nach dem Acount Passwort. Obwohl ich sicher bin das meine Eingabe richtig ist wird dieses nicht akzeptiert.

### Reproduction Steps

1. Home Assistant starten
2. HACS wählen
3. In der Suche nach Tapo: Cameras Control suchen
4. Tapo: Cameras Control auswählen
5. ADD INTEGRATION TO MY Home Assistant wählen
6. Open Link wählen
7. Möchtest du Tapo: Cameras Control einrichten? mit ok bestätigen.
8. Die IP Adresse der Kamera eingeben, und Weiter
9. Benutzername der Kamera eingeben und weiter
10. Passwort der Kamera eingeben und weiter
11. Passwort der Tapo Cloud eingeben und weiter. (Dieses ist nach mehrfacher Überprüfung auf jeden fall richtig.)
12. Es erscheint die Meldung das Passwort sei falsch. (Ist es aber nicht.)

### Expected behavior

Ich möchte meine Kamera Tapo C225 in Home Assistant einbinden.
Sollte ich Fehler machen benennen Sie diese bitte.
Sollten in Tapo: Cameras Control Fehler sein, bereinigen Sie diese bitte.

![Screenshot 2024-06-21 073045](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/138379730/bd8670b1-7847-49a8-b50b-96e08f42fb07)

### If applicable, add error logs.

Ein Fehlerprotokoll wird nicht erzeugt, vorher abgebrochen?

### Device Firmware

1.0.28 Build 231214 Rel. 69164n

### Integration Version

12.4

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Betriebssystem Homeassistant

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
We use English for communication. 

https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/551
