### ISSUE TITLE
TP-Link is playing around - release what you have working :)

### ISSUE THREAD

**Issue by TCB13** [JurajNyiri/HomeAssistant-Tapo-Control#619]
Hello,

> all the work (weeks) I spent working on it is now not going to be able to be used and released for everyone here, which makes me sad, but I learned a lot in the process.
https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/551#issuecomment-2137323663

According to your last comment on that issue TP-Link seems to be "playing chicken" with us. So, may I ask you, why can't you release all that good work you've done? Eventually they'll make their API endpoint ready and we switch to that.

Thank you.

**Comment by TCB13** [comment]
@JurajNyiri ... can you re-open this?

**Comment by JurajNyiri** [comment]
See https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/551#issuecomment-2111341474 your questions are answered there.
