### ISSUE TITLE
Motion detector sensor not available (continue from #61)

### ISSUE THREAD

**Issue by vdiogo** [JurajNyiri/HomeAssistant-Tapo-Control#62]
![image](https://user-images.githubusercontent.com/24878195/105844648-7a531180-5fd1-11eb-993e-1a7c2977934e.png)
Yes, all those steps were checked.

_Originally posted by @vdiogo in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/61#issuecomment-767509290_

**Comment by JurajNyiri** [comment]
Please do not open new tickets and keep the conversation in the old one.
