### ISSUE TITLE
Loading time is too long

### ISSUE THREAD

**Issue by vsimanin** [JurajNyiri/HomeAssistant-Tapo-Control#620]
### Description

Integration takes a long time to load after recent changes:
![Screenshot_2024-07-07-10-10-22-39_c3a231c25ed346e59462e84656a70e50](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/9263449/9754a7c7-e4c9-4002-a5b6-9d4d32ddc6d1)

### Reproduction Steps

1.Update 5.4.18 to last active version

### Expected behavior

-

### If applicable, add error logs.

-

### Device Firmware

1.3.9 Build 231019 Rel.40264n(4555)

### Integration Version

5.4.26

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
It now reports this correctly. This depends on the camera response time, some cameras are slower to initialize. Nothing to fix here.
