### ISSUE TITLE
The integration does not load (TAPO C420).

### ISSUE THREAD

**Issue by Pippo1989** [JurajNyiri/HomeAssistant-Tapo-Control#621]
### Description

When Home Assistant starts, the integration struggles to load, showing "initializing" for a certain period of time (indefinitely long).

Also, if the startup is successful, you can see that many camera and hub entities are no longer available.

![Cameras 1](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/98611451/9b832bd6-afa8-4c12-9708-07c8806278c8)

![Hub](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/98611451/efb00a98-ba79-405f-af0c-7205700f0a18)

### Reproduction Steps

=/=

### Expected behavior

=/=

### If applicable, add error logs.

[home-assistant_tapo_control_2024-07-07T15-09-15.196Z.log](https://github.com/user-attachments/files/16119776/home-assistant_tapo_control_2024-07-07T15-09-15.196Z.log)

### Device Firmware

1.2.17 Build 20240305 rel.75572 (cameras) - 1.3.3 Build 20240604 rel.61598 (hub)

### Integration Version

5.4.26

### Using stream component

No

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

No

### HASS Environment

Hassio on Raspberry Pi4

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Did this start happening after an update? If so, which one? I do not have these hub cameras so I cannot verify them myself.

**Comment by Pippo1989** [comment]
> Did this start happening after an update? If so, which one? I do not have these hub cameras so I cannot verify them myself.

Yes, it most likely happened after the latest core and supervisor updates.

![Latest updates](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/98611451/55321854-2822-475d-becf-3f7a90c6b5ae)

**Comment by JurajNyiri** [comment]
Did it happen after integration version update? Could you rollback and note down the versions where it worked?

**Comment by harobertocpf** [comment]
Podemos volver a la versión anterior 5.4.25?

Gracias

**Comment by JurajNyiri** [comment]
Could you please manually remove following parts from your code on the latest version one by one and after each time see if it helps:

https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/compare/5.4.25...5.4.26

First remove this green part in switch.py

<img width="1179" alt="Screenshot 2024-07-15 at 13 11 31" src="https://github.com/user-attachments/assets/713ad500-d2bd-4bdb-af32-975ad505cfc0">

Then remove these:

<img width="1178" alt="Screenshot 2024-07-15 at 13 11 57" src="https://github.com/user-attachments/assets/9b9d606b-f132-4c2c-ab85-37e395d2927b">

Finally if it still does not work, replace these greens with red:

<img width="1178" alt="Screenshot 2024-07-15 at 13 12 23" src="https://github.com/user-attachments/assets/6e17a2b9-4023-487b-b629-e0b7731b4593">

**Comment by JurajNyiri** [comment]
Fixed in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.4.27
