### ISSUE TITLE
Downgrading Process of TAPO Cams

### ISSUE THREAD

**Issue by RestOp** [JurajNyiri/HomeAssistant-Tapo-Control#623]
### Description

Hi to all downgraders,

I have just combined all the infos to one post to make it easier for newbies.
I would like opt post this post in the right Thread, but is was blocked https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/551
@JurajNyiri  If you find it usable, just add my post in it.

Firts of all - very good news first of all!!! 

I have just downgraded all my 3 different Tapo Cams: C100 V1, C200 V1 and C210 V1
It is very easy, took about 15 mins for all of 3 cams...

Here are the working firmware for this cams:
C100 v1: /Tapo_C100v1_en_1.3.6_Build_230512_Rel.47642n_up_boot-signed_1689123454635.bin
C200 v1: /Tapo_C200v1_en_1.3.6_Build_230424_Rel.77225n_up_boot-signed_1682511249340.bin
C210 v1: /Tapo_C210v1_en_1.3.7_Build_230823_Rel.55528n_up_boot-signed_1697005413481.bin

To download one just put the at the start of link - https://download.tplinkcloud.com/firmware

For all other cams you can find the firmware here https://github.com/tapo-firmware/Directory/blob/main/all_keys.txt

Instruction of formatting of SD Card is here https://github.com/DrmnSamoLiu/Downgrading-Tapo-Cams/tree/main?tab=readme-ov-file#solution

Here is the list of commands, you can just copy paste them:

- list disk

- select disk 6

- clean

- convert gpt

- create partition primary

- format quick FS=FAT32

A litle bit more infos to understand downgrade process is here https://github.com/nervous-inhuman/tplink-tapo-c200-re/issues/4#issuecomment-1030056785

As for me i noticed the following steps of flashing
1. About 15 sec after the power on - red light blinks
2. About 50 sec after the power on - green light blinks
3. Then  led lights green - It seems to be the downgrade process is fiunished, but i have waited 3 minutes as suggested in manual.

Then restart cam without SD Card, delete firmware from SD Card on PC and put SD Card in cam.
Great that the cam authorisation and all the settings in APP remain, you have just to initialise SD Card in APP again and thats all! 

Good Luck!

### Reproduction Steps

See above

### Expected behavior

See above

### If applicable, add error logs.

See above

### Device Firmware

1.1.1.1.1

### Integration Version

5.01

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Hass

### Search for similar issues

Yes

**Comment by krasatos** [comment]
Thank you for this!
I have a bunch of C320ws.
Has anyone gone through the process on Tapo C320ws and can confirm it went smoothly?
Which firmware should I go for?

**Comment by andyjduncan** [comment]
I've commented on the other downgrade thread, but I'll add this here:

I found I couldn't downgrade my C210 v2 devices directly to firmware 1.3.7, but it did work downgrading to 1.3.8 first.

**Comment by bellario89** [comment]
Does anyone know the firmware I should use for TC73? It's the HomeKit PTZ one, I couldn't figure it out from the list.

**Comment by TeDeVPrime** [comment]
i am guessing that we haven't heard any news from TP-Link about this issue yet eh?

**Comment by JurajNyiri** [comment]
Thank you @RestOp linked this in issue and readme as well, once you move into discussion I will change the link.

**Comment by RestOp** [comment]
> The last update is always inside [#551 (comment)](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/551#issuecomment-2230580891). I just posted a new update today.
> 
> @RestOp I have enabled discussions for this repository. Could you please move this in there? https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/discussions Once done, I will link it in the issue above.

Done https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/discussions/625

**Comment by JurajNyiri** [comment]
TY, updated all.

**Comment by mitchelltornquist** [comment]
Has anyone here had success downgrading a C200v3? Seen lots of posts about success on v1 and v2, but can't find much info on v3. Have been trying to downgrade mine with no success.

**Comment by dindi999** [comment]
Tapo C310(US)_V2.8_1.5.1 Build 251011 ? 🙏
