### ISSUE TITLE
Tapo cam c100 stops working when using HA Tapo control

### ISSUE THREAD

**Issue by neutrongenious** [JurajNyiri/HomeAssistant-Tapo-Control#64]
I have experienced a problem when i connect my tapo cam with HA. camera became unresponsive and no feed is shown.
I have opened issue with Tapo but as per their developers, it seems to be issue with Tapo control or HA (I don't agree with them).
have you experienced this?

I have a tapo c100 cam purchased recently.

**Comment by JurajNyiri** [comment]
Hello, 

where does camera become unresponsive? App, rtsp stream or Home Assistant? Or all? Which parts are unresponsive? Does it respond to ping?
Does this happen when you have it in home assistant and start to control it via app?
What are you exactly doing with the camera when this issue happens?

Could you please link the issue you opened?

AFAIK noone experienced this before and so far I don't see anything that could be changed to fix this from Home Assistant side. Tapo control uses https API which is used by App on phone and onvif/rtsp stream which is exposed by camera.

Please reopen this by filling the bug template along with all the information I asked above.
