### ISSUE TITLE
Tapo C500 Cell Motion Detection not working properly

### ISSUE THREAD

**Issue by PhilipHei** [JurajNyiri/HomeAssistant-Tapo-Control#645]
### Description

The entity binary_sensor.tapo_c500_cell_motion_detection is not available some times or doesn’t show the correct state. Motion was detected from camera and I receive notification from Tapo app, but no state changes in homeassistant. 

### Reproduction Steps

Listed in description. 

### Expected behavior

Entity always available and correct state

### Device Firmware

1.1.4 Build 240506 Rel.39487n

### Integration Version

5.5.4

### Using stream component

Yes

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Intel Nuc

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Read faq. Nothing else can be done on integration side.
