### ISSUE TITLE
Feature Request:  To make motion binary_sensors unknown instead of unavailable

### ISSUE THREAD

**Issue by alexanderznamensky** [JurajNyiri/HomeAssistant-Tapo-Control#648]
After each HA restart or Tapo-Control integration reload
binary_sensor.tapo_c***_motion_alarm
binary_sensor.tapo_c***_cell_motion_detection
bacome to status "unavailable". We have to wait until motion is detected in front of each camera or change status manually.

I think it would be more logical to use "unknown" status instead.
What do you think?

**Comment by JurajNyiri** [comment]
Integration reuses funtionality from official onvif component, thats how it works there.
