### ISSUE TITLE
 Feature Request: Tapo C520WS ver 1.0

### ISSUE THREAD

**Issue by mauricederden** [JurajNyiri/HomeAssistant-Tapo-Control#649]
Any progress on de Tapo cams? I have bought 2 camera's  C520WS ver1.0
I can't find a way to migrated it in home assistant and also it doens't find it
Adding the ip adress manually didn't bring any result.
Would be great if this would be possible since all other unifi camera's work already
![image](https://github.com/user-attachments/assets/9824b997-5567-4d44-a3d4-3908c5772989)

**Comment by JurajNyiri** [comment]
You need to first install the integration, you are adding the incorrect integration. Follow readme.
