### ISSUE TITLE
Tapo C200 stream doesn't work

### ISSUE THREAD

**Issue by stj101** [JurajNyiri/HomeAssistant-Tapo-Control#650]
### Description

I purchased tapo care and stream doesn't work

![Screenshot_4](https://github.com/user-attachments/assets/7eb8c0f9-c9bd-41d3-b742-9724bf012275)

### Reproduction Steps

![Screenshot_2](https://github.com/user-attachments/assets/f8105c46-8ee9-4e50-a24a-e126378eabd9)
![Screenshot_3](https://github.com/user-attachments/assets/a0ee8c5d-118e-40a9-b070-527b082c7dda)
![Screenshot_4](https://github.com/user-attachments/assets/dfcae961-f556-4bc9-b0f1-1a5089a5c0e6)

### Expected behavior

Since I have purchased tapo care I can't see the cameras in home assistant. Before I could see them and even record with motionEye, but now I can't. Is there a solution?

### If applicable, add error logs.

2024-08-04 23:04:53.299 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.entrance_sd_stream] Error from stream worker: Error opening stream (HTTP_OTHER_4XX, Server returned 4XX Client Error, but not one of 40{0,1,3,4}, rtsp://****:****@xxxxxxxxx:554/stream2)

### Device Firmware

1.3.9 Build 231019

### Integration Version

5.6.0

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Raspberry Pi 4

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Expected, read FAQ in this repo, or Tapo website.
