### ISSUE TITLE
C320WS flickering green picture

### ISSUE THREAD

**Issue by 1bieber** [JurajNyiri/HomeAssistant-Tapo-Control#651]
### Description

Some weeks ago my tapo c320ws camera started flickering in HA. I integrated the camera with the home assistant tapo control plugin. The SD as well as the HD stream are flickering. Additionally the picture is green.
The RTSP stream using VLC or the stream in the tapo app are working fine.
I'm using the newest Firmware (1.1.5). I also did a camera reset.
![Screenshot 2024-08-07 094125](https://github.com/user-attachments/assets/d5c972d8-9d1a-411d-97f7-76da1562f889)

### Reproduction Steps

1. Open Home Assistant
2. Go to integration
3. Go to Tapo Camera Control
4. Go to device
5. Open stream
6. Same problem with picture card

### Expected behavior

Working video stream

### Device Firmware

1.1.15 build 240605 Rel.49436n

### Integration Version

5.5.4

### Using stream component

Yes

### Does camera work via official integrations?

No

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Core

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Integration passes the stream url to HA which handles it.  Try using webrtc card and try to find out what changed and see if there are any errors in the logs. 

Closing as this is not an integration issue.

**Comment by Gjuju** [comment]
Hello.

I had the same problem, just disabled : "Use Stream from Home Assistant (restart required)"

and it went fine

**Comment by Junikiewicz** [comment]
I had a similar problem - changing the RTSP transport mechanism from TCP to UDP solved the problem.

**Comment by isabellaalstrom** [comment]
> Hello.
> 
> I had the same problem, just disabled : "Use Stream from Home Assistant (restart required)"
> 
> and it went fine

Where did you do this? I have the same problem.

**Comment by h8hr1pzdo3rmiqv5** [comment]
> Where did you do this? I have the same problem.

Integrations > Tapo > your camera > Options > Configure device
It worked for me too.
