### ISSUE TITLE
Device is Deactivated by configuration

### ISSUE THREAD

**Issue by erasor2010** [JurajNyiri/HomeAssistant-Tapo-Control#652]
### Description

I installed my Tapo C200 today, but it is shown as deactivated by configuration entry but i cant find anything
![Screenshot 2024-08-10 224138](https://github.com/user-attachments/assets/eb14ba81-9e7f-4f58-af70-abf6c6d2ac1d)

### Reproduction Steps

Add Camera to Integration after blocking Internet access

### Expected behavior

a working Device

### Device Firmware

 1.3.14 Build 240513

### Integration Version

5.6.0

### Using stream component

No

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HassOS

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
You will need to reenable it. Search on google for "reenable config entry home assistant".

**Comment by erasor2010** [comment]
hi, i tried that but without any success, all tapo entrys in the files are labled deactivated_by: null
