### ISSUE TITLE
No sensor for Motion Detection on C100

### ISSUE THREAD

**Issue by msshnl** [JurajNyiri/HomeAssistant-Tapo-Control#653]
### Description

I have a C100 and when motion detection is used there is no sensor available to get feedback whether there is motion.

### Reproduction Steps

Turn on Motion detection to normal
See the sensor not there

### Expected behavior

Seeing the snesor there

### Device Firmware

1.3.7 Build 230918 Rel.67333n(4555)

### Integration Version

5.6.0

### Using stream component

No

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HAOS

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
This is answered in far and many different duplicate issues. Make sure to follow steps and document what happened before opening issue or following up please.

**Comment by msshnl** [comment]
My apologisies, wrong search terms where used.
