### ISSUE TITLE
Feature Request: Separate binary sensors for Person, Pet and Vehicle

### ISSUE THREAD

**Issue by rverstappen** [JurajNyiri/HomeAssistant-Tapo-Control#657]
**Is your feature request related to a problem? Please describe.**
Many of the Tapo cameras automatically distinguish Motion detection from more specific detection, such as "Person Detection", "Pet Detection" and "Vehicle Detection". I would find these incredibly useful, especially for outside situations. Even distinguishing between a person and a car is useful by itself. Other people might also well be interested in "Line-Crossing", "Baby Crying", "Glass Break", "Dog Barks", "Cat Meows" but I don't know if Tapo marks recorded snippets with those tags.

**Describe the solution you'd like**
Rather than a single "Cell Motion Detection" binary sensor, it would be great to have separate binary sensors for each enabled feature. Somehow, Tapo can figure this out and mark each recorded detection with a tag.  

**Describe alternatives you've considered**
A template binary sensor could help filter out noise such as leaves and bugs but I can't think of a way to distinguish these specific disparate event types, and Tapo seems to be able to do it for us.  

**Additional context**
The image shows that Tapo can recognize and categorize detection events differently. 
![Uploading Screenshot_20240812-162239.png…]()

**Comment by JurajNyiri** [comment]
https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/304
