### ISSUE TITLE
Upgrading to OS 13.0 breaks integration. : Failed to establish a new connection: [Errno 113] Host is unreachable

### ISSUE THREAD

**Issue by andonevris** [JurajNyiri/HomeAssistant-Tapo-Control#659]
### Description

After upgrading to OS 13.0 on a VMware install the Tapo integration fails to start with error message

Failed setup, will retry: HTTPSConnectionPool(host='192.168.xxx.xxx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f290522d880>: Failed to establish a new connection: [Errno 113] Host is unreachable'))

The camera is reachable via IP ping from the console.  

Reverting to OS 12.4 restores functionality

### Reproduction Steps

Update to OS 13.0
On reboot integration won't start

### Expected behavior

Integration should start as normal

### If applicable, add error logs.

Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='192.168.107.89', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2908daaab0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))

### Device Firmware

1.3.14

### Integration Version

5.6.1

### Using stream component

Yes

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

No

### HASS Environment

Vmware

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
<img width="592" alt="Screenshot 2024-08-14 at 16 56 44" src="https://github.com/user-attachments/assets/c835a761-b69e-417e-9c20-e4e9d3e1b060">

I am running HA OS 13 and all works well. Make sure HA can reach your camera after the update. SSH into it, see if you can ping it, try rebooting etc.
