### ISSUE TITLE
TC85 doesn't work with new update

### ISSUE THREAD

**Issue by minhkhoiii1997** [JurajNyiri/HomeAssistant-Tapo-Control#660]
### Description

Hello,

I tried to view the live camera of TC85 on Home Assistant but it says that Unavailable. On another note, I have a doorbell D130, and I can view the live on HA. 

I'm still new with the HA environment so any suggestion would help.

Thanks!

### Reproduction Steps

In Sensor section, click on HD Stream or SD Stream => Status changed from Idle to Unavailable.

### Expected behavior

Would be able to view the live stream.

### Device Firmware

1.2.18 Build 240430 Rel.67495n

### Integration Version

5.6.1

### Using stream component

Yes

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Windows VM

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Hi, stream is not supported on battery powered cameras as documented in the readme. This is a limitation of the camera, it does not offer RTSP stream.
