### ISSUE TITLE
Sensor alarm sounding

### ISSUE THREAD

**Issue by danieleproietti** [JurajNyiri/HomeAssistant-Tapo-Control#664]
Hi, and thank you very much for this fantastic integration! Is there a sensor that indicates when the camera alarm is sounding? It would be very useful to associate other devices through an automation, like an external siren, for example.

**Comment by JurajNyiri** [comment]
Hi, no at the moment there is not. You could use motion sensor along with alarm enabled or not select to achieve this in theory.

**Comment by danieleproietti** [comment]
Unfortunately I can't see the motion sensor in home assistant for the C410 camera 🥹
