### ISSUE TITLE
Feature Request: Add binary sensors for motion and person  detection

### ISSUE THREAD

**Issue by saaubry** [JurajNyiri/HomeAssistant-Tapo-Control#668]
**Is your feature request related to a problem? Please describe.**
I can't use motion/person detection in Alarmo.

**Describe the solution you'd like**
We can select which level of sensitivity for motion or person detection but it doesn't exist any reporting of this detection.
I would like to have on binary sensor for motion detection and one for person detection.

**Describe alternatives you've considered**
I don't see any workaround.

**Additional context**
I have two TAPO C210 with Hardware v2.1

Thank you

**Comment by JurajNyiri** [comment]
Binary sensor for motion is available. If it isn’t for you check faq for steps. 

For special events see https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/304

**Comment by johndoe0815** [comment]
For my tapo C100, the problem was the newest firmware. I downgraded to the previous one, afterwards the motion sensor appeared again.

**Comment by saaubry** [comment]
Thanks Juraj
I forget this details in your tuto.
I managed to get the sensor back after following the process.
Thanks again for this ingration in HA.
Next camera will certainly be reolink for outdoor.

Le mer. 25 sept. 2024, 20:51, johndoe0815 ***@***.***> a
écrit :
