### ISSUE TITLE
RSSI sensor creates issues on log

### ISSUE THREAD

**Issue by WorldOfGZ** [JurajNyiri/HomeAssistant-Tapo-Control#674]
### Description

Hello.
I use this integration for 2 cam TAPO, with last version.
It seems sometimes when the rssi sensor goes to unavailable, that create an entry on the log.
Everything other works, I downgrade firmware since long time.

Not a big issue, but maybe something to check when some times.

### Reproduction Steps

Just check the log, probably there is the error.

### Expected behavior

No error on log

### If applicable, add error logs.

```
Enregistreur: homeassistant
Source: components/sensor/__init__.py:664
S'est produit pour la première fois: 03:14:35 (4 occurrences)
Dernier enregistrement: 10:21:44

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 662, in state
    numerical_value = float(value)  # type:ignore[arg-type]
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'unavailable'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 960, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1011, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 664, in state
    raise ValueError(
ValueError: Sensor sensor.tapo_cam_1_rssi has device class 'None', state class 'measurement' unit 'dBm' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'unavailable' (<class 'str'>)
```

### Device Firmware

1.3.7 Build 230920 Rel.60220n(4555)

### Integration Version

5.6.1

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Proxmox

### Search for similar issues

Yes

**Comment by susanacf90** [comment]
Having the same issue.

**Comment by rct** [comment]
A few bits of information in case it helps.

* Only one of my two C120's has this error
* The error was being logged roughly every 30 seconds.I
* when I looked at the entity in Dev tools it had a numeric value.  It didn't change to unavailable even though the error message was still being periodically logged.

Workaround to stop the excessive logging, disable the rssi entity.

**Comment by JurajNyiri** [comment]
Fixed in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.7.1
