### ISSUE TITLE
Motion Detection Stuck after restart C125/C120

### ISSUE THREAD

**Issue by loganbrooks25** [JurajNyiri/HomeAssistant-Tapo-Control#680]
### Description

Motion Detection for both Camera’s C120 and C125 does not report correctly when they are also being broadcast to Scrypted. After start up, either will be stuck in ‘Unavailable’ or work for the first few seconds then either stuck in ‘Detected’ or ‘Clear’.  When I remove the camera’s from Scrypted, motion detection resumes in HA permanently after a restart. 
I also have 2 C110 models and they both work excellent when being used for Scrypted and HA (both report motion correctly). Considering the C110’s work as expected, I suspect the bug is on the HA side?  
Have all the same settings for the camera’s on Scrypted side and HA side. 

### Reproduction Steps

1. Load HA
2. Check Motion detection. 
3. State stuck

### Expected behavior

Home Assistant to report motion correctly when triggered. 

### Device Firmware

1.1.12 Build 240604 Rel.64460n

### Integration Version

5.6.1

### Using stream component

No

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/677
