### ISSUE TITLE
Feature Request: Support for doorbell Tapo D235

### ISSUE THREAD

**Issue by phil-schneider** [JurajNyiri/HomeAssistant-Tapo-Control#682]
**Is your feature request related to a problem? Please describe.**
Are there any plans for the new D235 door bell?
https://www.tp-link.com/en/home-networking/cloud-camera/tapo-d235/
I set this one up with the tapo app incl. "always on mode" with DC wiring power.
I was able to add the camera.

**Describe the solution you'd like**
But the SD and HD stream are not working.
Should there be a sensor for the door bell?

**Describe alternatives you've considered**
No Alternatives

**Additional context**
Can I provide any debug messages are something?
I will test the doorbell for like 10 days. If I dont get it working, I will return it, because I need the HA integration

**Comment by JurajNyiri** [comment]
Hi, see https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/397

Streams are only supported if device supports trap currently.

**Comment by phil-schneider** [comment]
Thanks a lot.
I think for stream there could be a solution with a beta firmware
https://community.tp-link.com/en/smart-home/forum/topic/683314

@JurajNyiri Do you know how I might be able to get the "press Ring" Event into home assistant?

**Comment by phil-schneider** [comment]
I can confirm, that the video stream incl. motion detection is working.

**Comment by Thekinghim** [comment]
Hey are you able to stream the doorbell on home assistant?

**Comment by Gh0st556** [comment]
I have the sensors but no video
how can i get the video stream in HA

**Comment by rizzification** [comment]
Adding here - would love to integrate within HA. Anyone been able to do so?

**Comment by phil-schneider** [comment]
I returned it and bought a reolink door bell

**Comment by krystof-k** [comment]
It should be possible since `Tapo D235(EU)_V1_1.1.14 Build 240929` (October 22, 2024) firmware:

> Modifications and Bug Fixes:
> 1. Added support for RTSP/ONVIF in Always-on mode.
> …

Can anyone confirm whether it is working?
