### ISSUE TITLE
Feature Request: Doorbell D235 - ring button pressed - event

### ISSUE THREAD

**Issue by phil-schneider** [JurajNyiri/HomeAssistant-Tapo-Control#685]
**Is your feature request related to a problem? Please describe.**
I have a D235 door bell.
https://www.tp-link.com/en/home-networking/cloud-camera/tapo-d235/

The video is working with a special firmware version:
https://community.tp-link.com/en/smart-home/forum/topic/683314

What am I currently (actually the only thing) missing is an event when the door bell button is pressed.
Am I missing something? What am I doing wrong?

**Describe the solution you'd like**
An entity or event that can be used in automations when the physical button is pressed

**Describe alternatives you've considered**
Dont know any

**Additional context**
Thanks for your work

**Comment by JurajNyiri** [comment]
See https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/397

**Comment by phil-schneider** [comment]
In my opinion its not the same issue.
This camera can also be cable powered be and then its always one.
The camera function is working on this with a special firmway.

Anyway, I sent the model back and bought a reolink door bell

Thanks a lot for this integration (which I also use on cameras).
Thanks for your free time and free work.

I think its a shame from Tapo!! 
They should at least, send you each model for free and if you get it fully integrated in your "plugin" you should receice a money bonus from them.
