### ISSUE TITLE
Feature Request: Set / refresh timezone setting

### ISSUE THREAD

**Issue by Fettkeewl** [JurajNyiri/HomeAssistant-Tapo-Control#687]
**Is your feature request related to a problem? Please describe.**
Tapo C520WS currently forgets to apply timezone setting after reboot, leaving the camera timestamp +1h ahead until I apply the TZ setting manually from tapo app. 

**Describe the solution you'd like**
A button to refresh TZ setting forcing it to reapply current setting/an input select to control TZ setting

**Describe alternatives you've considered**
Reapply TZ when using the sync time feature 

**Additional context**
N/a

**Comment by JurajNyiri** [comment]
Available in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.6.3
