### ISSUE TITLE
Couldn't turn on siren on C510W

### ISSUE THREAD

**Issue by MartinGoX** [JurajNyiri/HomeAssistant-Tapo-Control#690]
### Description

Hi Juraj
I'm using C310 and C510W models and want to switch on the siren. This works for the C310 models but when trying it with C510W I get the following message:
"Die Aktion siren/turn_on konnte nicht ausgeführt werden. argument of type 'bool' is not iterable."
Same happens for turn_off.
Same happens when pressing the button in the entity properties and also from inside an automation action.

Is this something the integration doesn't support for this model?

Best regards
Martin

### Reproduction Steps

See above.

### Expected behavior

Switching siren should work also for C510W models.

### Device Firmware

1.2.2 Build 240517 Rel.42283n

### Integration Version

5.6.1

### Using stream component

Yes

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker (maybe?)

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Upgrade to 5.6.3.

**Comment by bernfp** [comment]
> Upgrade to 5.6.3.

Hello, I already updated to this version but C510W still not available. Same error message.
Thanks in advance for your huge work with this integration.
