### ISSUE TITLE
Cell motion detection missing 

### ISSUE THREAD

**Issue by Firefox1986** [JurajNyiri/HomeAssistant-Tapo-Control#696]
### Description

Entities Cell Motion Detection is not provided by Tapo-Control anymore after updating to 5.7.2.
Integration-Overview is showing Versionnumber 5.6.3 after updating and restarting HASS...

### Reproduction Steps

Update to 5.7.2, check your entities from Tapo-Control, Entities Cell Motion is marked as not provided anymore

### Expected behavior

Entities Cell Motion Detection should be available, or at least another binary-sensor, so that we could react on motion.

### Device Firmware

1.2.8 Build 240606 Rel.39146n

### Integration Version

5.7.2

### Using stream component

No

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

No

### HASS Environment

VM on Synology NAS

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Read FAQ. Nothing changed regarding this between updates.
