### ISSUE TITLE
Person/motion detection not working 

### ISSUE THREAD

**Issue by sickkick** [JurajNyiri/HomeAssistant-Tapo-Control#699]
### Description

Person detection not working. I have tried to set up automations with person detection and they are never triggered. Also the Logbook and logs don't show anything with person detection.

### Reproduction Steps

Set Up an automation with person detection and test the doorbell.  Person detection. is not triggered.

### Expected behavior

Person detection should trigger when person is detected from door bell. 

### Device Firmware

1.1.14 Build 240929 Rel.63130n

### Integration Version

5.8.0

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Proxmox

### Search for similar issues

Yes

### Additional information

Tp link D225 door bell

**Comment by JurajNyiri** [comment]
Read faq in readme
