### ISSUE TITLE
The tapo* services are not showing

### ISSUE THREAD

**Issue by 1endell** [JurajNyiri/HomeAssistant-Tapo-Control#70]
Hello! I've installed the integration from HACS, restarted and created a card just like the examples, witth the buttons for PTZ. I'm using a C200 camera. When i click on any button, the lovelace tells me that the tapo's services are unavailable. They really are not shown in the developer tools also.

![image](https://user-images.githubusercontent.com/4711579/108097380-d1905300-7060-11eb-8fc0-492b3c4592be.png)

**Comment by JurajNyiri** [comment]
Hey,

Do they show up here? 
![Screenshot_20210216_190855_io homeassistant companion android](https://user-images.githubusercontent.com/5785999/108103628-7ecb9100-708a-11eb-92f5-4963695799df.jpg)

**Comment by 1endell** [comment]
No. It doesn't. I'm using homeassistant in a docker container. Here's the folder, where the files are.
![image](https://user-images.githubusercontent.com/4711579/108201210-45346d80-70fe-11eb-9c72-625e0d0e6f00.png)

**Comment by JurajNyiri** [comment]
Please fill in the bug report template properly for more details.

**Comment by 1endell** [comment]
Great news: It worked!

I followed all the steps for installation until this point: https://github.com/JurajNyiri/HomeAssistant-Tapo-Control#usage
After it, the integration never have showed to me (even disconnecting and re-connecting the power supply cable from the camera). What i did was to exclude the camera mac from the DHCP server and let it get another IP when re-connected. The Tapo notification showed up, i typed the credentials and is working smoothly now. Sorry for this. Great integration. I'm running most of the resources in my C200, with the new firmware from tp-link

**Comment by JurajNyiri** [comment]
Glad that it worked for you.

Integration shows up after you click the plus sign on integrations page in home assistant.

Without clicking the plus sign, it lists integrations you are currently using or discovered devices.
