### ISSUE TITLE
Could not setup dependencies: Incorrect pytapo version installed: 3.3.30. Required: 3.3.32.

### ISSUE THREAD

**Issue by perosb** [JurajNyiri/HomeAssistant-Tapo-Control#702]
### Description

pyTapo dependency version is not correct and the integration fails to load.

### Reproduction Steps

Lock at logs when reloading or starting tapo.

### Expected behavior

Success

### If applicable, add error logs.

```python
2024-11-10 11:24:49.226 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry C200_xxXXxx for tapo_control
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo_control/__init__.py", line 325, in async_setup_entry
    # Delete all media stored in hot storage for entity
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant.exceptions.DependencyError: Could not setup dependencies: Incorrect pytapo version installed: 3.3.30. Required: 3.3.32.
```

### Device Firmware

1.3.15

### Integration Version

5.8.0

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker

### Search for similar issues

Yes

### Additional information

hass 2024.11.1

**Comment by martinohmann** [comment]
Just in case somebody else runs into this weird issue, here's a potential fix that worked for me at least: https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/684#issuecomment-2495981990
