### ISSUE TITLE
Feature Request: Timed motion response

### ISSUE THREAD

**Issue by jimmyz5150** [JurajNyiri/HomeAssistant-Tapo-Control#709]
**Is your feature request related to a problem? Please describe.**
TAPO C310
Motion detection is very short while displaying feed when a card has conditional trigger (dashboard card only visible when triggered)
Is it possible to extend motion trigger length when motion is detected. 
Real example: When motion is activated it will trigger several times during 1 event. Condition card pops for only 3 seconds multiple times.

**Describe the solution you'd like**
Is it possible to create a timed length slider bar entity that gives say 5 sec to 30 sec ( like the Microphone Volume slide entity) to keep feed stream active and alive. 
Or
maybe jpeg still shots?

**Describe alternatives you've considered**
Possibility of a condition template, haven't figured out.

**Comment by JurajNyiri** [comment]
There is a discussion on this github if you would like to discuss, or get help creating an automation - https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/discussions

By native onvif, I mean https://www.home-assistant.io/integrations/onvif/ . This integration reuses that part to get motion data information. Data that camera reports is reflected inside HA 1:1.

If you would like to do anything more with it, for example, build in a delay, you can very easily do via helper entity and an automation, as previously described.

**Comment by jimmyz5150** [comment]
Thank you for elaborating on it. Appreciate it
    On Monday, November 18, 2024 at 12:54:27 PM EST, Juraj Nyíri ***@***.***> wrote:  
 
 


There is a discussion on this github if you would like to discuss, or get help creating an automation - https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/discussions

By native onvif, I mean https://www.home-assistant.io/integrations/onvif/ . This integration reuses that part to get motion data information. Data that camera reports is reflected inside HA 1:1.

If you would like to do anything more with it, for example, build in a delay, you can very easily do via helper entity and an automation, as previously described.
