### ISSUE TITLE
Feature Request: Noise Sensor

### ISSUE THREAD

**Issue by JaviCepa** [JurajNyiri/HomeAssistant-Tapo-Control#71]
First of all: thanks for such an amazing integration! Works flawlessly :D

It'd be really awesome to include a noise sensor related to each camera like the ffmpeg noise one -> https://www.home-assistant.io/integrations/ffmpeg_noise/

I've used the ffmpeg integration in the configuration.yaml file, but I'm afraid this creates a double connection to the stream that doesn't work properly.

I'm using this to monitor my baby when she wakes up and I barely hear her :)

**Comment by JurajNyiri** [comment]
Hey thank you for the suggestion!

Before I start working on this, have you verified its working properly with just ffmpeg integration?

**Comment by JaviCepa** [comment]
Yes! Only ffmpeg worked correctly, but when I added the tapo cams it went off.

**Comment by JaviCepa** [comment]
Thanks! :D

**Comment by forast3r** [comment]
Does this noise detection also activate the motion sensor?

**Comment by Dielee** [comment]
I'm intrested how this works, too. noise_detected entity is not showing up. Where I can find this sensor ?

**Comment by Dielee** [comment]
Ahh, you will get a new attribute in both camera.* entites.
Template sensor for this case: `{{ state_attr('camera.kellercam_sd', 'noise_detected') }}`

**Comment by forast3r** [comment]
Thanks, will prepare a template sensor for this
