### ISSUE TITLE
Tapo C720 Smart Floodlight Camera Fully Functional

### ISSUE THREAD

**Issue by RobDehnert** [JurajNyiri/HomeAssistant-Tapo-Control#710]
I am pleased to report that the Tapo C720 Smart Floodlight Camera is fully functional via this integration in HA.  This includes SD and HD camera feeds and control of the dual head floodlight.  A total of 74 new entities were created for the camera.

The floodlight control is timed based on a separate timer entity.  The timer entity can be set for 5, 10, 15 or 30 minutes.  My one wish would be a way to override the timer to keep the floodlight illuminated indefinitely.

My new C720 camera arrived with firmware: 1.2.2 Build 240717 Rel.73927n.  The Tapo app and this integration are both reporting that a firmware update (1.2.3 Build 240823 Rel.40327n) is available.  I have blocked the firmware update until the cloud password issue is resolved.

**Comment by JurajNyiri** [comment]
@RobDehnert ignore the mean bot ^, sometimes it doesn't understand well what the ticket is about, "cloud password" triggered it. :-)

Thank you for the report, I have updated readme.

As for the `keep the floodlight illuminated indefinitely.` part, it depends whether its possible via the official app, if it is please open feature request. If not, what you can do is make an automation, when the light turns off, it turns it back on... or maybe sets it every couple of minutes to on or something similar.
