### ISSUE TITLE
5.8.2 some hub/doorbell entities unavailable (OK on 5.8.1)

### ISSUE THREAD

**Issue by RedNo7** [JurajNyiri/HomeAssistant-Tapo-Control#719]
### Description

After updating to 5.8.2, the following entities became unavailable (all hub related).
```
select.doorbell_timezone,
select.tapo_doorbell_motion_detection,
select.tapo_doorbell_person_detection,
select.tapo_doorbell_vehicle_detection,
sensor.tapo_doorbell_disk_1_status
sensor.hub_disk_1_status,
select.hub_timezone,
```
- The problem survives a restart of both the hub and HA.
- Downgrading to 5.8.1 resolved the issue.
- Upgrading back to 5.8.2, and only 3 of the doorbell `select.xxx` were still unavailable (the hub itself was fine).
```
select.tapo_doorbell_motion_detection,
select.tapo_doorbell_person_detection,
select.tapo_doorbell_vehicle_detection,
```
- Downgrading to 5.8.1 resolved the issue again.
- Upgrading back to 5.8.2, and the same 3 doorbell `select`s  remained unavailable (hub still OK).
```
select.tapo_doorbell_motion_detection,
select.tapo_doorbell_person_detection,
select.tapo_doorbell_vehicle_detection,
```

### Reproduction Steps

upgrade to 5.8.2

### Expected behavior

I expect all (enabled) entities to be available (except buttons which are always 'unavailabe').

### Device Firmware

1.1.16 Build 20240617 rel.65780

### Integration Version

5.8.2

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker on RPi

### Search for similar issues

Yes

### Additional information

Note the hub and camera are fine for several sensors (i.e. it is working).

I have a bunch of doorbell entities disabled so not sure whether they would also have been problem.  I am happy to re-enable if it helps diagnose the issue.

my dashboard with 5.8.1
![Screenshot 2024-11-29 at 08 16 11](https://github.com/user-attachments/assets/ff4a53f1-77ed-48ac-97a9-633726fee6e7)

my dashboard with 5.8.2
![Screenshot 2024-11-29 at 08 18 42](https://github.com/user-attachments/assets/d42d7f78-047b-4a92-a951-da6539414f88)

**Comment by JurajNyiri** [comment]
Please add error logs.

**Comment by RedNo7** [comment]
Sorry, here you go.

[home-assistant.log](https://github.com/user-attachments/files/17959511/home-assistant.log)

**Comment by JurajNyiri** [comment]
In order to fix this I will need debug logs as well as previously requested. Please enable them and post full log here.

**Comment by JurajNyiri** [comment]
When you will be posting debug logs, please post both from 5.8.1 and 5.8.2

**Comment by RedNo7** [comment]
I'm in the UK (was asleep) so only just got your email.

Sorry about the previous logs - I read your request to mean you wanted debug logs only if there were no error in the logs (and I thought there were).

I got you reply by email this morning, did the work but can now see there was a 2nd message (that I didn't get by email overnight) and so will post the 5.8.3 logs now and downgrade back to 5.8.1 to get those logs in a few mins.

**5.8.3 logs:**
[home-assistant.log](https://github.com/user-attachments/files/17964982/home-assistant.log)

**Comment by JurajNyiri** [comment]
Fixed in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.8.4.

**Comment by RedNo7** [comment]
awesome - thanks for the quick turnaround!
