### ISSUE TITLE
Feature Request: Tapo C310

### ISSUE THREAD

**Issue by Jack123uk** [JurajNyiri/HomeAssistant-Tapo-Control#72]
Hi, is there anyway of updating the component for the Tapo C310? It has 3 settings for resolution 720p / 1080p / 3MP , when adding the camera to the component within home assistant it shows HD and SD. Im not quite sure whether the HD setting is 1080p or the 3MP one, if its not the 3MP one can that be added?
Lastly just want to say thank you for doing this integration it works great within home assistant.

**Comment by JurajNyiri** [comment]
Hey,

What are the resolutions for rtsp and could you please provide links for them?

If there is a new endpoint I can add it.

**Comment by Jack123uk** [comment]
Hi, sorry for the delayed reply, I have been waiting on an email from tp-link, there is no rtsp url for the 3MP stream, you use the 1080p stream and set the app to 3MP, to view 3MP over rtsp. So it’s all good! Thanks
