### ISSUE TITLE
version remained 5.8.2

### ISSUE THREAD

**Issue by ssersh** [JurajNyiri/HomeAssistant-Tapo-Control#722]
### Description

After updating to version 5.8.3 the version in home assistant remained 5.8.2

### Reproduction Steps

1. update
2. go in settings

### Expected behavior

want to see version 5.8.3

### Device Firmware

1.1.4 Build 230922 Rel.57957n

### Integration Version

5.8.3

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

vm in unraid

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
I forgot to bump it, it’s still 5.8.3, I can change it on the next release.

**Comment by JurajNyiri** [comment]
Fixed in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.8.4.
