### ISSUE TITLE
C720 Camera -- no spotlight control

### ISSUE THREAD

**Issue by tpascaru** [JurajNyiri/HomeAssistant-Tapo-Control#729]
### Description

Hi -- I just added my 3rd Tapo to this integration! It's a C720. Following the instructions to isolate the network from the public internet worked in adding the integration. The  only thing I don't see is a switch to enable the spotlight. I see a previous thread that it sems to work. 

### Reproduction Steps

Go to the control setting, and see there is no switch for the spotlight as there is on the other tapo camera I have.
![Screenshot 2024-12-08 122436](https://github.com/user-attachments/assets/acb196e8-0545-4052-ab0b-2f674077f771)

### Expected behavior

Be able to turn the spotlight on/off

### Device Firmware

Firmware: 1.2.3 Build 240823 Rel.40327n

### Integration Version

5.8.5

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Bare metal 

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
There is ongoing work on https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/715 which is also for C720. New methods have been discovered that will solve this issue. 

The reason why even the timed one doesnt show up is possibly a firmware difference, they probably removed that method in your new firmware.

Closing this as a duplicate, please continue discussion there.

**Comment by tpascaru** [comment]
Thank you! Great that it's being worked, and appreciate the integration --
it's very useful!

**Comment by PetePeter** [comment]
hey when i setup my c720 initially the switch for the light was not there.
i then turned the light on via tapo, and then did a reload on the integration, and the switch appeared.

or something like that.

can you check if it appears?

**Comment by JurajNyiri** [comment]
Available in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.8.6 .

**Comment by tpascaru** [comment]
Thank you -- I updated the integration and can confirm that I see the
buttons for both floodlight and timed floodlight and they work! There is
some weird behavior if you turn them both on, then it becomes hard to turn
it off. I'll check it out later and give more feedback, but it's likely a
race condition of some sort between the two methods.

I also verified that the dimmer works: there's a "brightness" and an
"intensity" setting, of which the brightness one does the trick (with
intensity failing). -- I am going to try and make a combined switch to make
the floodlight look like a dimmer in HASS.

Regards

**Comment by tpascaru** [comment]
Of course -- I didn't want to seem presumptuous :)

**Comment by JurajNyiri** [comment]
@tpascaru if you are around, could you please contact me on [discord](https://discord.gg/pa54QyK) so that we can test this before release?

**Comment by JurajNyiri** [comment]
Released in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.8.7 .

**Comment by tpascaru** [comment]
Wow -- that was fast! How would the brightness scale be presented to the
user? (I'm not seeing any changes on the control page)
[image: image.png]

Regards!

**Comment by JurajNyiri** [comment]
Just click on the light entity there is a brightness slider inside it. Not the timed one but the normal one.

**Comment by tpascaru** [comment]
Hi -- I confirmed it works (I can dim using the slider), but there is a
weird interaction that I cannot yet fully repeat where the "timed" version
of the switch turns on when i turn off the "untimed" version of the switch,
and the light actually stays on.

**Comment by kvanbiesen** [comment]
> Hi -- I confirmed it works (I can dim using the slider), but there is a
> weird interaction that I cannot yet fully repeat where the "timed" version
> of the switch turns on when i turn off the "untimed" version of the switch,
> and the light actually stays on.
> […](#)

i had the same issue, for now i just disabled the timed trigger in HA, and then it works. Dunno what cause it. Maybe file a new PR for it seem fairly fix
