### ISSUE TITLE
can we have a component also to activate the notification

### ISSUE THREAD

**Issue by Sadoo-MH** [JurajNyiri/HomeAssistant-Tapo-Control#73]
Hi,
thank you so much for this wonderful integration, can we also have kind of script to activate the notification when the motion detected, i know i can use HA for this, but i like the notification from the camera also if it's not a huge job it will be nice to have it :)

many thanks
all the best!

**Comment by JurajNyiri** [comment]
Hey,

yes you can. Use automation trigger with binary sensor and [notification](https://www.home-assistant.io/integrations/notify/) from Home Assistant! :)
