### ISSUE TITLE
Feature Request: Turn the floodlight switch into a dimmer switch 

### ISSUE THREAD

**Issue by tpascaru** [JurajNyiri/HomeAssistant-Tapo-Control#734]
The floodlight or spotlight on Tapo cameras have an independent setting to  set the brightness/intensity level of the light. The feature request would be to present the LED switch to the user in HASS as a dimmer that would combine on/off functionality along with setting the brightness level.

It seems that different models have different "ranges" of brightness/intensity which would have to be accounted for. Also, there seems to be different settings from "brightness" vs "intensity" which may need to be disambiguated for this to work.

Thank you!

**Comment by JurajNyiri** [comment]
Reopening, will be added soon.

**Comment by JurajNyiri** [comment]
Added in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.8.7
