### ISSUE TITLE
Motion Sensors disappeared in HomeAssistant

### ISSUE THREAD

**Issue by domerich** [JurajNyiri/HomeAssistant-Tapo-Control#740]
### Description

I used to have sensors for motion and person detection but they are no longer available in home assistant as of today. I the Tapo app they still exist. Now I can only see SD and HD camera feed.

![image](https://github.com/user-attachments/assets/295c651c-f854-40b8-8c8e-ff5f3e379257)

### Reproduction Steps

check in the entities 

### Expected behavior

I used to have motion sensors

### Device Firmware

1.3.14 Build 240513 Rel.43631n(4555)

### Integration Version

5.8.7

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Runs on a NUC

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Check FAQ regarding motion detection.
