### ISSUE TITLE
Can't add model C120 - IP Address is not a supported Tapo device

### ISSUE THREAD

**Issue by adamzeis** [JurajNyiri/HomeAssistant-Tapo-Control#747]
### Description

I've enabled Third-Party compatibility and have my C100s and D130 working, however I have 4 C120 that I'm not able to add to the integration. When I enter the IP address I get the error **IP Address is not a supported Tapo device**.  All cameras have a static IP.

If I try multiple times, I also often get a Connection Failed error. 

So far I've tried rebooting the camera, restarting Home Assistant and factory resetting the camera, same result. 

### Reproduction Steps

1. Add Device
2. Enter IP of C120 camera
3. Error - IP Address is not a supported Tapo device

### Expected behavior

I've successfully added back my C100 cameras that are all set up in the same manner on my network with static IPs. The C120 camera do not get further than attempting to enter the IP address.

<img width="573" alt="395580455-a63bd982-cfcd-4243-bf76-e14829d616cb" src="https://github.com/user-attachments/assets/0a9edd9e-c8b2-40e7-84ab-33c25871945b" />

### Device Firmware

1.2.2 Build 240905

### Integration Version

5.4.13

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

No

### HASS Environment

HASS Yellow

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Post debug logs please.

**Comment by JurajNyiri** [comment]
5.4.18 for example was fixing exactly this.
