### ISSUE TITLE
Tapo-App Version 3.8.103 Not aviable on Android

### ISSUE THREAD

**Issue by Stoony1** [JurajNyiri/HomeAssistant-Tapo-Control#750]
### Description

Hi Tapo-App Version 3.8.103 is not abiable on Andoid Play Story the only current Version is 3.7.811.
Pls help i dont have a Button to unlock the Thierd Party.

### Reproduction Steps

Install the App on Android 

### Expected behavior

Install the App o. Android and follow the Patch note staps 

### Device Firmware

1.3.14 Build 240513 Rel.43692n (4555)

### Integration Version

5.6.1

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Haos 

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Wait until it is released. Not an integration issue.

**Comment by rverstappen** [comment]
> Wait until it is released. Not an integration issue.

Maybe mention this in the release note? I also spent some time trying to figure this out and I imagine many others on Android will too.

**Comment by JurajNyiri** [comment]
![Screenshot 2024-12-13 222854](https://github.com/user-attachments/assets/e8e9d131-454b-4b91-8a1d-425b1803b463)

**Comment by Stoony1** [comment]
> ![Screenshot 2024-12-13 222854](https://private-user-images.githubusercontent.com/5785999/395703389-e8e9d131-454b-4b91-8a1d-425b1803b463.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxNDczNDgsIm5iZiI6MTczNDE0NzA0OCwicGF0aCI6Ii81Nzg1OTk5LzM5NTcwMzM4OS1lOGU5ZDEzMS00NTRiLTRiOTEtOGExZC00MjViMTgwM2I0NjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTRUMDMzMDQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTBlNzU1YTFlNDM4YTE1NDhhMzJkOGNkNDI1NTI1MjZhY2QzZTA2NGExMjExZTE0NDEzMDE1NDYyOWU5MzhjZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.7Udz0D77o5UpzSzCApHQyrmclPOdEmVrL96__-3psIM)




Not work Now!

**Comment by JurajNyiri** [comment]
https://github.com/JurajNyiri/HomeAssistant-Tapo-Control?tab=readme-ov-file#third-party-compatibility

<img width="837" alt="Screenshot 2024-12-15 at 02 33 38" src="https://github.com/user-attachments/assets/2a86865a-376d-46b9-a781-dca42824fced" />

### You need version 3.8.103 or newer.

**Comment by iz8mbw** [comment]
New version of Tapo app for Android just released on Play Store.
All works well.

**Comment by Stoony1** [comment]
> New version of Tapo app for Android just released on Play Store. All works well.

I'm looking for the new version but can't find it. I'm from Germany.

My Playstore Version its the Old... he havent change it.
