### ISSUE TITLE
Problems with Live Views limits in Tapo app after 6.0.0 update

### ISSUE THREAD

**Issue by rgjertsen** [JurajNyiri/HomeAssistant-Tapo-Control#751]
### Description

After updating to 6.0.0 I started having issues with reaching a Live View limit on one of my cameras in the Tapo app. I have never had this issue before updating this evening, but after the update both me and my wife had the same issue.
I did some searching and found some info that there is a 3 device limit for Live Viewing on a single camera. Has there been any changes here after the local communication so that HA counts as two devices because of the two separate streams per camera?

I will add that the issue is not there anymore, but I will still ask the question if anything changed since it was likely this issue was due to the update.

### Reproduction Steps

I updated to 6.0.0 and one of my cameras hit the limit right after. I did nothing else.
The other camera we have does not have the same issue after the update.

### Expected behavior

Since this was not an issue before the update, I guess I expect my Tapo app to work normally even though I have the cameras connected to HA.

### Device Firmware

1.3.9 Build 231019 Rel.37378n(4555)

### Integration Version

6.0.0

### Using stream component

Yes

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HAOS on Raspberry Pi 4

### Search for similar issues

No

**Comment by JurajNyiri** [comment]
There has been no functionality changes between 6.0.0 and 5.8.7 apart from instructions when adding the camera. 
RTSP streaming functionality has not changed since basically this integration has been created. 


There is a limit of concurrent rtsp streams as described in FAQ here, or Tapo.
