### ISSUE TITLE
Latest version of app doesn't seem to be available for everyone

### ISSUE THREAD

**Issue by easaw** [JurajNyiri/HomeAssistant-Tapo-Control#753]
### Description

As per the 6.0.0 update 'Victory for Local Control' (congratulations by the way), we've regained access.

However (and I realise it's only 14th December) version '3.8.103' is not available, even for beta testers in every country.

As you have _some_ communications with TP-Link, could you possibly ask them _very_ nicely to update it for Europe?

### Reproduction Steps

Install in Europe? (Android)

### Expected behavior

Version '3.8.103'

### Device Firmware

1.3.14

### Integration Version

?

### Using stream component

No

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Proxmox

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Thank you!
Personally I expect a staged rollout. It should come out soon in next few days or a week or two, if not, I will consider reaching out.

Alternative is using iOS device (temporarily) to switch the setting if you cannot wait.

Please continue discussion at https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/discussions/752 .

**Comment by easaw** [comment]
Okay so Version 3.8.103 seems to be iOS: https://apps.apple.com/us/app/tp-link-tapo/id1472718009

**Comment by easaw** [comment]
> Thank you! Personally I expect a staged rollout. It should come out soon in next few days or a week or two, if not, I will consider reaching out.
> 
> Alternative is using iOS device (temporarily) to switch the setting if you cannot wait.
> 
> Please continue discussion at #752 .

Will do!
