### ISSUE TITLE
Error: Invalid Handler Specified

### ISSUE THREAD

**Issue by Hatsune-Cthulhu** [JurajNyiri/HomeAssistant-Tapo-Control#754]
### Description

I get the following error when trying to add a new integration with a freshly installed copy of the plugin, I've already tried re-installing multiple times, is this a compatibility issue with the plugin and docker installs of home assistant?

Config flow could not be loaded: {"message":"Invalid handler specified"}

### Reproduction Steps

Install the plugin in HA docker and try to add a new integration

### Expected behavior

Don't receive the provided error

### If applicable, add error logs.

```
Logger: homeassistant.config_entries
Source: config_entries.py:3249
First occurred: 06:33:01 (2 occurrences)
Last logged: 06:33:46

Error occurred loading flow for integration tapo_control: No module named 'pytapo'
```

### Device Firmware

N/A

### Integration Version

6.0.0

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

The camera isn't in an environment, I'm not sure what you're meaning by this

### Search for similar issues

Yes

### Additional information

You have an old closed issue marked invalid with this same problem, but no resolution was added to the issue

I'm also not sure what the question about using the stream component is meaning, as far as I can tell the stream component is enabled by default in HA now

**Comment by Hatsune-Cthulhu** [comment]
pytapo does appear in the config/deps directory after installing
![Screenshot_20241214-071228](https://github.com/user-attachments/assets/e3ae25d1-1442-4267-beae-0145ee1d8b0b)

**Comment by Hatsune-Cthulhu** [comment]
Also tried 5.7.2 and have the same issue

**Comment by Hatsune-Cthulhu** [comment]
Pytapo appears to have not been installed under /usr/local/lib/python3.12/site-packages/ as part of the HACS install
![Screenshot_20241214-073841](https://github.com/user-attachments/assets/ba55d60b-691f-4679-8b18-989a4dcbdab8)

**Comment by JurajNyiri** [comment]
New HA uses python3.13 make sure it is installed under there if HA did not install it automatically for you (it should) closing as this is not an integration issue but an environment issue.

**Comment by Hatsune-Cthulhu** [comment]
But surely this should install pytapo in whatever python version the environment has

**Comment by JurajNyiri** [comment]
If you use supported installation method HA installs the dependencies for you as they are correctly specified in manifest file.

**Comment by JonnyHaystack** [comment]
I'm running Home Assistant in Docker and I'm hitting this same issue. Does this integration not support Docker installations then..? Seems quite odd to me that it would be trying to install packages system wide at all, rather than in its own virtual env.

**Comment by JonnyHaystack** [comment]
Aha, managed to fix it by adding env var `PYTHONPATH=/config/deps` to the container config. I guess this is an upstream bug in HA/the container. It is weird though, that other things install dependencies to `/config/deps` and work fine, but it was only a problem for this specific integration.

**Comment by Hatsune-Cthulhu** [comment]
> Aha, managed to fix it by adding env var `PYTHONPATH=/config/deps` to the container config. I guess this is an upstream bug in HA/the container. It is weird though, that other things install dependencies to `/config/deps` and work fine, but it was only a problem for this specific integration.

That was my point, this dev seems very eager to point blame elsewhere though from what I can see, I ended up just creating a mount point in /usr/local/etc.../site-packages and called it a day. This plugin very definitely doesn't support HA container out of the box, but I figured if the dev wants to ignore that then so beit. ¯\_(ツ)_/¯

**Comment by JurajNyiri** [comment]
@Hatsune-Cthulhu

https://developers.home-assistant.io/docs/creating_integration_manifest/#requirements

https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/blob/main/custom_components/tapo_control/manifest.json#L11

Both HA and this integration is an open source project. If you believe both me and the docs are incorrect, feel free to open PR.

Or... configure docker env correctly. :)

**Comment by R-Nabil** [comment]
> Aha, managed to fix it by adding env var `PYTHONPATH=/config/deps` to the container config. I guess this is an upstream bug in HA/the container. It is weird though, that other things install dependencies to `/config/deps` and work fine, but it was only a problem for this specific integration.

This solved it for me. Thanks !

**Comment by squimito** [comment]
I know this is an old thread, but do you know how to do this in Home Assistant OS?

**Comment by WinFinn** [comment]
I know this is closed. But sins I also ended up here with the same issue I though I should add a comment as the `PYTHONPATH=/config/deps` also fixed it for me. 
RasPi 4B 4GB.
HA docker: 2025.9.1 with Python 3.13.7  (ghcr.io/home-assistant/home-assistant:stable)
Tapo: Camers Control v7.0.0
