### ISSUE TITLE
Still invalid PW

### ISSUE THREAD

**Issue by moritzmaier84** [JurajNyiri/HomeAssistant-Tapo-Control#755]
### Description

I did everything, updates, toggle in the app, right password.

Still this (see picture). 

![IMG_4049](https://github.com/user-attachments/assets/e34bbdfa-69bd-4a18-8a81-f1e768162c4f)

### Reproduction Steps

yes

### Expected behavior

…

### If applicable, add error logs.

see picture

### Device Firmware

latest

### Integration Version

6

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

No

### HASS Environment

hassio

### Search for similar issues

Yes

### Additional information

none

**Comment by agnarvold** [comment]
Same here, worked yesterday, but broken for now.

**Comment by silfax** [comment]
Same here. Worked for about one hour for a couple of cameras then asked again for authentication and it fails. I wasn't able to add three other cameras, authentication failed from the very beginning.

**Comment by jq-yeraz** [comment]
Same here

**Comment by JurajNyiri** [comment]
Follow FAQ in readme for ‘Invalid cloud password’. It took my cameras a few hours to catch up without doing the steps listed in FAQ. Ensure cameras can reach internet as well at least while they switch the password.

**Comment by agnarvold** [comment]
I deleted the cams/integration setup, set a new cloud account password in the tapo app, and then added cameras again in HA and now it is working again (but it also worked from yesterday until today without password reset).
