### ISSUE TITLE
Motion sensor freezes after motion detected

### ISSUE THREAD

**Issue by agnarvold** [JurajNyiri/HomeAssistant-Tapo-Control#756]
### Description

I have two C200 and one C100 that registers motion and clears the sensor shortly after. My C120 however stays on motion registered forever until I reload the integration. Is there some workaround for this, or is it the firmware on the C120 that is incompatible with the integration? It also works as it should with motion detection in scrypted and homekit with the c120, but not in this integration.

### Reproduction Steps

Create motion in front of Tapo C120, motion is detected, sensor never clears out again - not with new motion either.

### Expected behavior

Motion sensor should clear out after motion like on C100 and C200.

### Device Firmware

1.2.2 Build 240905 Rel.41780n

### Integration Version

6.0.0

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HA Green

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
This will need to be fixed upstream in Home Assistant. For motion events this integration reuses [onvif ](https://www.home-assistant.io/integrations/onvif/) integration functionality.
