### ISSUE TITLE
 'FlowHandler' object has no attribute 'tapoHost'

### ISSUE THREAD

**Issue by RoSulek1** [JurajNyiri/HomeAssistant-Tapo-Control#757]
### Description

v. 6.0.0. - Cannot add previosly deleted camera.
after Third Party Compatibility turned on in the official Tapo app i cannot add camera (C520WS) which previously worked correctly. I tried to remove the component, install it again, unfortunately the effect is the same every time.
Moreover, despite restarts, the component still requires a password to the cloud service and does not allow the next step
via ONVIF camera working fine in HA

### Reproduction Steps

1/  go to ha, 
2/ add new, add new entry in Tapo Component
3/ input host IP and port (443)
4/ error

### Expected behavior

run without error

### If applicable, add error logs.

Ten błąd pochodzi z niestandardowej integracji.

Rejestrator: custom_components.tapo_control
Źródło: custom_components/tapo_control/config_flow.py:638
integracja: Tapo: Cameras Control (dokumentacja, Problemy)
Pierwsze zdarzenie: 18:11:50 (3 zdarzenia)
Ostatnio zalogowany: 18:22:50

'FlowHandler' object has no attribute 'tapoHost'

### Device Firmware

1.2.8 b. 240606 rel. 39146n

### Integration Version

6.0.0

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HA Yellow

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Please post full error.

**Comment by RoSulek1** [comment]
This is full error.
the system does not report anything more.

**Comment by JurajNyiri** [comment]
That is not correct, there is an error in the logs in HA.

Anyways, fixed in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/6.0.1 .
