### ISSUE TITLE
Binary motion sensor missing since 6.x

### ISSUE THREAD

**Issue by morpheus2939** [JurajNyiri/HomeAssistant-Tapo-Control#761]
### Description

Hi, I can not find the binary motion sensor any more on the latest version, is there a way to reintegrate it ?

### Reproduction Steps

Not listed in identities any more 

### Expected behavior

Was existing before 

### Device Firmware

1.1.5

### Integration Version

6.0.1

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Pi 5

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Read `I see error `Invalid authentication data. Make sure you have created your 3rd party account via Tapo app. You can also test if these credentials work via rtsp stream, for example VLC using link rtsp://username:password@IP Address:554/stream1` when I enter correct password` under Readme FAQ.

**Comment by morpheus2939** [comment]
Hi,

Sorry, sensor is present after first detection.

I should have rtfm.

My fault .

Regards
Daniel





Daniel Komorowski
SSI
An der Flurstadt 22
63589 Linsengericht
Tel. +49 (0) 1570 3516772
Fax. +49 (40) 38017-860352
VOIP. +49 (0) 15678 431473

________________________________
Von: Juraj Nyíri ***@***.***>
Gesendet: Sunday, December 15, 2024 9:50:54 AM
An: JurajNyiri/HomeAssistant-Tapo-Control ***@***.***>
Cc: morpheus2939 ***@***.***>; Author ***@***.***>
Betreff: Re: [JurajNyiri/HomeAssistant-Tapo-Control] Binary motion sensor missing since 6.x (Issue #761)


Read

I see error Invalid authentication data. Make sure you have created your 3rd party account via Tapo app. You can also test if these credentials work via rtsp stream, for example VLC using link ***@***.*** Address:554/stream1 when I enter correct password

under Readme FAQ.
