### ISSUE TITLE
binary_sensor.door_cell_motion_detection not available in version 6.0.1

### ISSUE THREAD

**Issue by Jesus-M** [JurajNyiri/HomeAssistant-Tapo-Control#762]
### Description

The entity `binary_sensor.door_cell_motion_detection` is no longer available in version 6.0.1. It was in 6.0.0

### Reproduction Steps

1. In a previously configured camera, go to the entity lists
2. look for `binary_sensor.door_cell_motion_detection` one and open the details
3. the message **_This entity is no longer being provided by the tapo_control integration. If the entity is no longer in use, delete it in settings._** is shown and the entity is disabled.

### Expected behavior

The entity should be available (or replaced by a new one)

### Device Firmware

1.3.9 Build 231019 Rel.37378n(4555)

### Integration Version

6.0.1

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HAOS on dedicated x86 device

### Search for similar issues

Yes

### Additional information

Similar case to #761 but it is not that the sensor is not working, the issue here is that the entity is shown 'unavailable' and the message saying it is no longer in use.

I, anyway, followed the steps in the Readme FAQ section, with no success.

The sensor is working properly with other integration (Amazon's Alexa) and the vendor App (Tapo).

**Comment by JurajNyiri** [comment]
Read 

> Binary sensor for motion doesn't show up or work

under Readme FAQ.


> Search for similar issues
> Yes
<img width="623" alt="Screenshot 2024-12-15 at 13 23 35" src="https://github.com/user-attachments/assets/6b7934c9-c81b-4b97-a336-15faf6c969b2" />

**Comment by Jesus-M** [comment]
thanks, but ... did you read the additional information section?

I saw the issue you mention and I don't think it's the same issue.

**Comment by JurajNyiri** [comment]
I see you mentioned the ticket in Additional information, I skipped through that initially when writing above comment.

6.0.1 vs 6.0.0 has changed nothing about this, this functionality hasnt been changed in months, possibly years, just keep trying, it will come up.

**Comment by JurajNyiri** [comment]
FYI;

"unavailable" with message that it is no longer provided is the exact same case as if it isn't there at all. On the first, HA just remembers that it used to be there and no longer is now.

**Comment by Jesus-M** [comment]
Will keep trying, but it was the only change. Indeed, you can see it was working until around 9:00 today, when I updated the integration from 6.0.0 to 6.0.1
![Screenshot_20241215_122730](https://github.com/user-attachments/assets/cfc90adc-5ff7-486d-9fd4-72ac6d08b903)

**Comment by JurajNyiri** [comment]
Every time you restart HA even without integration update it will dissapear, that is normal and expected.

See https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/discussions/748#discussioncomment-11571536 where I explained it a bit more.

**Comment by idenchev** [comment]
I faced the same issue today. My HASS was shutdown for a few hours and after turning it on again 'Cell Motion Detection' entity is no longer provided by your integration. You mentioned above that it is normal and expected to disappear after HASS restart. Does this mean that after the first detected motion it will re-appear (I am not on site to check it by myself) and will function normally in automations?
