### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by JordiBetting** [JurajNyiri/HomeAssistant-Tapo-Control#765]
**Is your feature request related to a problem? Please describe.**
I try to automate my daily manual actions with the cameras but it not all functions seem supported 

**Describe the solution you'd like**
I would like to be able to toggle the "privacy mode" vfrom home assistant. This mode is controllable via official tapo android app. 

**Describe alternatives you've considered**
I have not found any alternatives 

**Additional context**
![Screenshot_20241216_092519_Tapo](https://github.com/user-attachments/assets/7cb433e9-1ff0-483f-beea-defae13ed39b)
![Screenshot_20241216_092547_Tapo](https://github.com/user-attachments/assets/a212f6b7-1cdf-47e9-8081-bbb3b4b7fe06)

**Comment by JordiBetting** [comment]
I found the switch in your integration. I really had a good look before and didn't see it. Could it appear late after adding a camera?

Anyway, no new feature needed. Thank you for this integration, you made my day now that it works!!

**Comment by JordiBetting** [comment]
Indeed. More sensors and controls are showing much later than when the camera was added. I also got motion detection sensor now, which I surely didnt have when adding. I installed the integration about 30 minutes ago

**Comment by JurajNyiri** [comment]
Use the correct integration, you are using core one. Follow instructions in readme in Usage.
