### ISSUE TITLE
 Lightspot Always on for Tapo C510W

### ISSUE THREAD

**Issue by Mattia495** [JurajNyiri/HomeAssistant-Tapo-Control#768]
### Description

In tapo camera C500 this action works well, but in tapo C510W Lightspot action Is reverse: when I turn on the CAM light Is already powered on so if I turn this One off Will be disable for 5 minutes. Only removing the device the official application works well.

### Reproduction Steps

Add device to tapo camera plugin
See for turn on/off Lightspot (timed).
Try to set night mode on official tapo camera

[

### Expected behavior

Tapo light Will be already on so only pushing light button you Will be able to turn on night mode.

### If applicable, add error logs.

[Uploading error_log-3.zip…]()

### Device Firmware

1.0.5

### Integration Version

6.0.1

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Haos core

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
I dont really understand, can you please describe better even with pictures if possible?

**Comment by Mattia495** [comment]
Sorry about that, my english is not the best... I found that I didn't
install the latest apk version, now It works well.
Thank you for your immediate support I really appreciate that.

Il lun 16 dic 2024, 20:48 Juraj Nyíri ***@***.***> ha scritto:
