### ISSUE TITLE
Still receiving "Invalid cloud password" after newest update in coorp. with tp link

### ISSUE THREAD

**Issue by WxrthlessLiquid** [JurajNyiri/HomeAssistant-Tapo-Control#775]
### Description

After the famous update which should be the man in the camera-van (i don't know), I do still receive the error message which we all received before making the update. But, now there is some more text:
Invalid cloud password. Make sure you are entering the password for your cloud account and NOT the password which you created via the camera settings (unless they are the same). You need to enter password which you used with your email when signing into the Tapo app. Ensure you have Third-Party compatibility turned on in Tapo App (Me -> Tapo Lab -> Third-Party Compatibility - On).

What is causing the integration to still not work? After making the update of the integration i resarted home assistant. I delted it from HACS, then reinstalled it and tried again. Still no luck.

Thanks in advance. :-)

### Reproduction Steps

When adding a Camera via Integration I get the error.

### Expected behavior

Normally, it should accept my password, as I checked it multiple times by logging out from the tp link app, tp link website, trying to log in, the password must be right and so not the problem

### If applicable, add error logs.

![Screenshot 2024-12-17 130009](https://github.com/user-attachments/assets/20154486-4ced-40e4-adba-38948a6035ef)

### Device Firmware

1.1.15

### Integration Version

6.0.0

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HASSIO on Raspi

### Search for similar issues

Yes

### Additional information

![image](https://github.com/user-attachments/assets/9512827a-3606-4530-b06d-e5520463d4e2)

**Comment by WxrthlessLiquid** [comment]
So, I - in fact - didn't read the FAQs. I just needed to change the password, which now causes the integration to work again. :-)

**Comment by WxrthlessLiquid** [comment]
...ok, I was wrong. It helped at first. But then I remembered that the password I had chosen was breached, so I decided to change it again.

Thinking back, I realized: Wait, I initially set up the integration using the password I just switched to. Could that be why it’s working again now? But as I mentioned earlier, I still want to change it. However, the integration now refuses to accept the new password. When I switch back to the breached password, it works again.

This seems very odd. Are there any known issues related to password handling?

**Comment by JurajNyiri** [comment]
As noted above, FAQ exists for a reason. Follow all steps in faq and your issue will be solved. There is nothing wrong with integration, but camera is not getting updates for your password.

**Comment by JurajNyiri** [comment]
If you do not want to force it just use whatever works for your camera right now. Camera will eventually get the new password (if it is connected to internet) and integration will ask for new password.

**Comment by WxrthlessLiquid** [comment]
> If you do not want to force it just use whatever works for your camera right now. Camera will eventually get the new password (if it is connected to internet) and integration will ask for new password.

This is the problem. I only can get the camera set up to work, when having set the password which was breached. But it needs to be both entered while set up process in home assistant and also set up as password for tp link account.

Or do you mean, I should set it up like mentioned above, then, when everything is setten up, I should change the password and I should wait for the integration to give a warning or a command for re-setup/reconfiguration? I also already started to restart the camera, didn't help.

**Comment by JurajNyiri** [comment]
Set your new password for tplink account. Add camera with whatever works, done. 
When eventually camera gets password update integration will ask for it. 

Or follow FAQ - completely.
