### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by zyi840449** [JurajNyiri/HomeAssistant-Tapo-Control#780]
The current program can only store video files anywhere in /homeassistant/, but this folder will be saved by the system's backup function, which will cause the backup file to be abnormally large.

if set the backup path to /media/, it will show that the folder does not exist. Maybe it is a permissions issue?

hope that the backup path can be set to /midea to help reduce the size of the backup file.

**Comment by JurajNyiri** [comment]
You can define path in integration settings.
