### ISSUE TITLE
Can't connect to TAPO C520WS with Firmware 1.2.9

### ISSUE THREAD

**Issue by SteffKirch** [JurajNyiri/HomeAssistant-Tapo-Control#789]
### Description

I have 4 TAPO C520WS, 3 of them with Firmware 1.2.8 and one allready updated to 1.2.9 - the 3 with 1.2.8 work fine, but when I try to add the 1.2.9 TAPO camera, I got an error "Invalid authentication data. Make sure you have created your 3rd party account via Tapo app. You can also test if these credentials work via rtsp stream, for example VLC using link rtsp://username:password@IP Adresse:554/stream1" - BUT: I can connect to the stream with VLC, so the credentials are correct.
Any idea`?

### Reproduction Steps

1. go to TAPO camera control integration
2. click "Add entry"
3. insert the IP or hostename
4. insert credentials (username and password of the camera account)
5. error - "Invalid authentication data...."

### Expected behavior

The Camera is added

### Device Firmware

1.2.9 Build 240723 Rel. 58746n

### Integration Version

6.0.1

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Home Assistant Yellow

### Search for similar issues

Yes

**Comment by chsull** [comment]
I am having the same issue. From the discussion here:
[](https://www.reddit.com/r/homeassistant/comments/1h021kp/can_no_longer_access_camera_streams_after_update/url)
It seems to be a problem with using special characters in the password not being recognized by an underlying library. I am holding off changing my passwords in the hope that it can be resolved.

**Comment by SteffKirch** [comment]
> I am having the same issue. From the discussion here: https://www.reddit.com/r/homeassistant/comments/1h021kp/can_no_longer_access_camera_streams_after_update/url
> 
> It seems to be a problem with using special characters in the password not being recognized by an underlying library. I am holding off changing my passwords in the hope that it can be resolved.

Thanks chsull!
After setting the password to a simple/stupid one, I can add the Tapo-Camera.but I hope, that somebody fix it (because using a simple password does not feel good),

**Comment by JurajNyiri** [comment]
What was the password format? So that i can try and replicate this

**Comment by fett1979** [comment]
Same problem :(
Invalid authentication data. Make sure you have created your 3rd party account via Tapo app. You can also test if these credentials work via rtsp stream, for example VLC using link rtsp://username:password@IP Address:554/stream1

**Comment by fett1979** [comment]
My bad.. the wireless signal was to low..

**Comment by SteffKirch** [comment]
> What was the password format? So that i can try and replicate this

I used only letters and underscores as a password

**Comment by SteffKirch** [comment]
Tapo has released a new firmware 1.2.10 – everything works again, even with complex passwords

**Comment by mgiamberardino** [comment]
@JurajNyiri I just confirmed that this still happens in C320WS. There is no firmware update for those cameras yet. Not sure if this is an issue on the camera or in the integration.

I had to also remove dashes from the username:
username: domo-cameras
password: some-random-dash-separated-words
