### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by fbarberis** [JurajNyiri/HomeAssistant-Tapo-Control#79]
**Describe the bug**
Invalid config after uninstalling the component. The component no longer appears in HACS for reinstallation.

**Log**

```
Logger: homeassistant.setup
Source: setup.py:138
First occurred: 9:12:21 AM (1 occurrences)
Last logged: 9:12:21 AM

Setup failed for tapo_control: Integration not found.


Setup failed for tapo_control: Integration not found.
9:12:21 AM – setup.py (ERROR)

**Comment by JurajNyiri** [comment]
User error.

Integration is available in HACS for installing/uninstalling.

Integration also does not require you to edit config.yaml for a long time now.
