### ISSUE TITLE
"HomeAssistant - Tapo: Cameras Control" stopped working after updating HomeAssistant to a newer version

### ISSUE THREAD

**Issue by LaKaros7** [JurajNyiri/HomeAssistant-Tapo-Control#792]
### Description

I do not know what exactly happened. This HACS integration stopped working after updating Home Assistant to the latest version.

### Reproduction Steps

I would like to provide steps to reproduce this issue, but I do not know what exactly happened. This HACS integration stopped working after updating Home Assistant to the latest version.

But I have the some logs see bellow.

### Expected behavior

This integration will be possible to use.

### If applicable, add error logs.

Logger: homeassistant.setup
Source: setup.py:269
First occurred: December 20, 2024 at 8:43:24 PM (2 occurrences)
Last logged: December 20, 2024 at 8:43:36 PM

Setup failed for custom integration 'tapo': Requirements for tapo not found: ['plugp100==5.1.3'].
Setup failed for custom integration 'tapo_control': Requirements for tapo_control not found: ['pytapo==3.3.37'].

Logger: homeassistant.util.package
Source: util/package.py:152
First occurred: December 20, 2024 at 8:43:19 PM (6 occurrences)
Last logged: December 20, 2024 at 8:43:36 PM

Unable to install package plugp100==5.1.3: error: Failed to fetch: `https://files.pythonhosted.org/packages/b8/d9/470b26f24f67f32c488596d557371f935166994391601af160a8b0cfdbb6/plugp100-5.1.3-py3-none-any.whl.metadata` Caused by: Could not connect, are you offline? Caused by: Request failed after 3 retries Caused by: error sending request for url (https://files.pythonhosted.org/packages/b8/d9/470b26f24f67f32c488596d557371f935166994391601af160a8b0cfdbb6/plugp100-5.1.3-py3-none-any.whl.metadata) Caused by: client error (Connect) Caused by: dns error: failed to lookup address information: Name does not resolve Caused by: failed to lookup address information: Name does not resolve
Unable to install package pytapo==3.3.37: error: Failed to fetch: `https://files.pythonhosted.org/packages/e5/28/003d06f082e6c8baa011da42824ed5ef889afb5c18b5390a4e65d0e11d7c/pytapo-3.3.37-py3-none-any.whl.metadata` Caused by: Could not connect, are you offline? Caused by: Request failed after 3 retries Caused by: error sending request for url (https://files.pythonhosted.org/packages/e5/28/003d06f082e6c8baa011da42824ed5ef889afb5c18b5390a4e65d0e11d7c/pytapo-3.3.37-py3-none-any.whl.metadata) Caused by: client error (Connect) Caused by: dns error: failed to lookup address information: Name does not resolve Caused by: failed to lookup address information: Name does not resolve

### Device Firmware

1.2.2 Build 240914 Rel.55174n

### Integration Version

6.0.1

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Home Assistant - HACS

### Search for similar issues

Yes

### Additional information

I do not know how to fix it.

**Comment by JurajNyiri** [comment]
HA instance is not able to fetch dependencies for your custom integration as seen in logs. It might be due to connection issues on your side or the provider. Try restarting. 

Closing as this is not an integration issue.

**Comment by denishessberger** [comment]
I doubt that it is an error in dns resolution or a connection issue. I have the same issue and neither restarting nor reinstalling helps.

**Comment by JurajNyiri** [comment]
> I doubt that it is an error in dns resolution or a connection issue.

> Failed to fetch: https://files.pythonhosted.org/packages/b8/d9/470b26f24f67f32c488596d557371f935166994391601af160a8b0cfdbb6/plugp100-5.1.3-py3-none-any.whl.metadata Caused by: **Could not connect, are you offline?** Caused by: Request failed after 3 retries Caused by: error sending request for url ... Caused by: client error (Connect) Caused by: dns error: **failed to lookup address information**: Name does not resolve Caused by: failed to lookup address information: **Name does not resolve**

As described above, this is not an integration issue.

**Comment by JurajNyiri** [comment]
https://github.com/home-assistant/core/issues/133537
