### ISSUE TITLE
Connection lost with Tapo via NabuCasa HA Cloud

### ISSUE THREAD

**Issue by SebastianCismar** [JurajNyiri/HomeAssistant-Tapo-Control#795]
### Description

Hello everyone, every time I control my Tapo cameras in Home Assistant. Rotating, panning, etc. breaks the connection via the HA Cloud and shows me “Connection lost”. It's in the app and completely normal via the browser. Does anyone have experience with this. I have no problems using local IP on HA with webbrowser.

### Reproduction Steps

Control the camera via the Tapo integration, then immediately disconnect from the cloud

### Expected behavior

No lost connection

### Device Firmware

2024.12.5

### Integration Version

14.1

### Using stream component

No

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Lenovo MP93

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Integration has no connection / interactions with the HA cloud. Closing as this is not an integration issue.
