### ISSUE TITLE
Feature Request: C403 Control(O) Streaming(X)

### ISSUE THREAD

**Issue by vapury** [JurajNyiri/HomeAssistant-Tapo-Control#799]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

C403 battery cam control works great
But no video streaming

**Comment by JurajNyiri** [comment]
This is expected as listed in FAQ. Streaming is possible via go2rtc and has a very low priority to be implemented here by myself, but I welcome any PRs.
