### ISSUE TITLE
Bug: Issue Not being able to use the Motion Sensor on C100

### ISSUE THREAD

**Issue by soundslikeluke** [JurajNyiri/HomeAssistant-Tapo-Control#81]
I am having issues with the C100 camera not being able to get the sensor Entity to appear. I have deleted the cameras and re-added the camera and still the same with no entities. I have disabled and reenabled the motion detector on the camera and still no luck.

Camera 
 - Device Model: C100
 - FW: [e.g. 1.0.17 Build 201112 Rel.29622n (4555)

**Using stream component**
yes

**Camera has all attributes filled out properly in developer tools**
yes

**HASS Environment**
Running On a VM 

It was working perfectly but now I cant make them show up.

**Comment by JurajNyiri** [comment]
Follow instructions in troubleshooting and see other duplicates of this.
