### ISSUE TITLE
Model TC60 works

### ISSUE THREAD

**Issue by mvlperera** [JurajNyiri/HomeAssistant-Tapo-Control#82]
I am currently using the TC60 model - which seems to work fine with out any problems. 

Question - the noise detection attribute is set of "off" - how can I enable it?

**Comment by JurajNyiri** [comment]
Thank you for the feedback, I will add it to readme.

Information regarding sound sensor are here: https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/3.3.0 

I will need to add those to readme too.

**Comment by JurajNyiri** [comment]
Readme has been updated.
