### ISSUE TITLE
Poder enviar mensajes por el parlante de la camara

### ISSUE THREAD

**Issue by SergioEpstein** [JurajNyiri/HomeAssistant-Tapo-Control#85]
Buenos días a todos, impresionante el trabajo que viene haciendo para integrar esta cámara.

La propuesta que seria muy buena incorporar, es poder enviar mensajes para que lo reproduzca el parlante de la Cámara, así poder hacer una automatización que salude o que anuncie algún mensaje.

Muchas gracias por sus aportes

**Comment by JurajNyiri** [comment]
Hello, 

Information regarding how to make a tts / media request is not yet known / discovered and unfortunately cannot be implemented because of that.
