### ISSUE TITLE
Bug: Time synchronization still in winter time

### ISSUE THREAD

**Issue by forast3r** [JurajNyiri/HomeAssistant-Tapo-Control#87]
**Describe the bug**
The time synchronization option sets the date, but the time is 1h late since summer time (end of march)

**To Reproduce**
Mark the option "Automatically synchronise time", wait for summer time (DST?), check data printed on the video stream.

**Expected behavior**
Camera time and system time should be the same.

For example, system time is now 21:10, while cameras show 20:10. During winter time both were in sync.

**Log**
n/a

**Camera (please complete the following information):**
 - Device Model: C100, C200
 - FW: n/a
 
**Using stream component**
no

**Camera works through onvif component OR different cameras work in general**
yes

**Camera has all attributes filled out properly in developer tools**
yes

**HASS Environment**
Home Assistant OS

**Additional context**

**Comment by JurajNyiri** [comment]
Tapo cameras use UTC timezones which don't have daylight saving.

What is interesting, is that half of my cameras show a correct time and the other half don't.
The timezone in the app is set to UTC-1 in all the cameras.

However, the half which correctly displays time reports timezone as 'UTC-01:00DST-02:00,M3.5.0/02:00:00,M10.5.0/03:00:00' and the other half with incorrect time just 'UTC-01:00'. 

All of them have the same time synchronized.

In all the cases its following:
```
{
    'DateTimeType': 'NTP',
    'DaylightSavings': True,
    'TimeZone': {
        'TZ': 'see above'
    },
    'UTCDateTime': {
        'Time': {
            'Hour': 22,
            'Minute': 11,
            'Second': 18
        },
        'Date': {
            'Year': 2021,
            'Month': 5,
            'Day': 6
        }
    },
    'LocalDateTime': {
        'Time': {
            'Hour': 0,
            'Minute': 11,
            'Second': 18
        },
        'Date': {
            'Year': 2021,
            'Month': 5,
            'Day': 7
        }
    },
    'Extension': None,
    '_attr_1': None
}
```

Integration is setting UTC time, camera has to then apply your correct timezone AND daylight saving settings.

Not sure currently how to fix this, but it must be some setting hidden in the app. Try to have a look around?

**Comment by JurajNyiri** [comment]
Fixed in [3.3.2](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/3.3.2).

**Comment by forast3r** [comment]
Great! It is working fine with 3.3.2

**Comment by JurajNyiri** [comment]
@forast3r thank you for confirming! Make sure to update to 3.3.3 which was released shortly after 3.3.2, 3.3.2 broke winter time. 3.3.3 should have them both correct, we will see in the winter.

**Comment by forast3r** [comment]
Thanks for the quick response!
Strange... after upgrading to 3.3.3 the cameras went back to system time -1
Can't access the cams right now, will check again during the weekend and reopen this issue if the error persists.

**Comment by JurajNyiri** [comment]
That was happening to me too until I blocked them in firewall!

I think they are getting time from the internet if they have access and will get an incorrect one as they don't seem to support timezones? If they did, they should've actually **added** an hour.

If you are allowing them to access the internet, do not use this feature as cameras sync time automatically. If the time is incorrect in that case, make sure you have correct timezone selected and reach out to tplink for additional support.

**Comment by forast3r** [comment]
Thanks for your replay and clarification.The cams were isolated from the internet.
It is working perfect again after a home-assistant reboot (reloading only the component didn't do the trick).

**Comment by forast3r** [comment]
I uptate the tests done:
I checked the cameras, all are in the same timezone.

Having the cams isolated from the internet, when there is a restart (in HA or reloading the complement) the time sync is done right.

After an hour (couldn't check during this interval) the C100 keeps the right time, while the C200 is 1 hour delayed again.

I guess it is the same behaviour that you mentioned in a previous message @JurajNyiri anyway thank you for your efforts fixing this and such a great component!

BTW I saw a firmware upgrade for C200. Is this the one that places the tapo watermark on screen? Will stick to the factory firmware for now.

**Comment by JurajNyiri** [comment]
Yeah that's the one. Code does work for all my cameras now and if you look at changes it just adds +1 hour so that makes no sense 🤔 you can try and modify code and add +2 instead of 1 and see if that fixes it for you, imo it will go back to - 1 again if +1 didn't do the trick.
