### ISSUE TITLE
Bug: camera not responding after updating to 1.1.8

### ISSUE THREAD

**Issue by GuruPG** [JurajNyiri/HomeAssistant-Tapo-Control#89]
**Describe the bug**
I had installed and working fpr last few weeks.
Camera Firmware has updated to 1.1.8 this morning.
now it can't connect to camera.
I removed the integration and re-added.
The setup process starts with asking for the IP address as first step:

I enter the correct IP but it comes back as connection failed so can not continue with setup of integration.

Only change is camera firmware update this morning.

**Comment by JurajNyiri** [comment]
Hello, check if rtsp stresm via vlc still works.

**Comment by JurajNyiri** [comment]
Camera works on 1.1.8, I just tested.
Make sure that your camera is online on the IP you are entering, for example by testing rtsp stream via vlc.
