### ISSUE TITLE
Bug: Can't add C310 camera

### ISSUE THREAD

**Issue by pinkfloydFR** [JurajNyiri/HomeAssistant-Tapo-Control#91]
**Describe the bug**
Integration ask a cloud password, but C310 does'nt support cloud

**To Reproduce**
Try to add a c310 cam, last step ask cloud password

Test the tpcamera ( for tplink cloud ) it only support NCxxx cam.

**Comment by JurajNyiri** [comment]
Add it via official tapo app first, then follow instructions in integration.

**Comment by pinkfloydFR** [comment]
This is exactly what i done. First installed on my android phone in the official app, and after tested to integrate...

I am sure about the passord...

**Comment by JurajNyiri** [comment]
What are you getting when you enter cloud password?

**Comment by pinkfloydFR** [comment]
Password error, something like that, i can test again tomorrow to be more precise, it's late in france ^^

**Comment by JurajNyiri** [comment]
Make sure to follow all the steps. You need to create an account for rtsp stream. Then use that username and password in the integration **along** with the password of your tapo cloud account.
