### ISSUE TITLE
Model C110

### ISSUE THREAD

**Issue by louulouu** [JurajNyiri/HomeAssistant-Tapo-Control#92]
I am currently using the C110 and can confirm that it works well. I'll update if i do run into any issues, but so far it works the same as my C200. 

For anyone having issues while setting up, and asking for the "Cloud Password", just input your password for your official Tapo Account. 

Thank you so much for making this work @JurajNyiri!

**Comment by JurajNyiri** [comment]
Thanks for the report! I will add this to readme!

**Comment by JurajNyiri** [comment]
Added.

![image](https://user-images.githubusercontent.com/5785999/121521586-8b3a7780-c9f4-11eb-94d9-768afabc35c3.png)
