### ISSUE TITLE
Feature Request: Support for new Tapo C310 detection features since FW v1.1.7

### ISSUE THREAD

**Issue by ahochsteger** [JurajNyiri/HomeAssistant-Tapo-Control#93]
**Is your feature request related to a problem? Please describe.**
Recently my Tapo C310 HW v2.0 (not yet for HW v1.0 cameras) got a firmware update with some new detection features:
* Line-crossing detection
* Area intrusion detection
* Camera tampering
 
**Describe the solution you'd like**
Events from the new detection types should be made available as separate binary sensors.

**Comment by ahochsteger** [comment]
@JurajNyiri, if you could give me some pointers on how to get started for implementing such a feature, I'd be willing to try it myself.

**Comment by JurajNyiri** [comment]
Hello @ahochsteger this will not be possible until someone reverse engineers the functionality (I will not do this as per disclaimer). It might not be possible at all, depending on how it exposes the events to application. For example, motion detection events are published through onvif only. 

In any case, change will first need to happen in https://github.com/JurajNyiri/pytapo/tree/main/pytapo .
