### ISSUE TITLE
Feature Request: ability to find the camera via hostname, not only via IP

### ISSUE THREAD

**Issue by mariomare22** [JurajNyiri/HomeAssistant-Tapo-Control#94]
**Is your feature request related to a problem? Please describe.**
I would like to configure the integration with the hostname and not via IP

**Describe alternatives you've considered**
DHCP reservation on mac address

**Additional context**
is it something implementable?

**Comment by JurajNyiri** [comment]
Hello,

this is indirectly already supported. Just enter hostname instead of IP.

**Comment by mariomare22** [comment]
and it's not working, I tried.
