### ISSUE TITLE
Feature Request: Get brightness value from IR sensor - possible?

### ISSUE THREAD

**Issue by alexw1982** [JurajNyiri/HomeAssistant-Tapo-Control#96]
**Is your feature request related to a problem? Please describe.**
Using motion detection plus a brightness value from the IR sensor (or brightness sensor?) could be used to automate lighting in a room. There has to be some kind of brightness measurement inside the tapos for toggling IR/night vision - if we could get that value it would be awesome but I have not seen anything in that direction on the web...

**Comment by JurajNyiri** [comment]
Brightness value is not exposed by camera AFAIK. If someone discovers it, it can be added via PR into [pytapo](https://github.com/JurajNyiri/pytapo).
